### ISSUE TITLE
Up-N-Atom Management menu

### ISSUE THREAD

**Issue by BaelyTV** [fkk-cz/noire-public#1003]
currently unable to deposit or withdraw society funds, upon confirming the amount for either and clicking accept nothing happens and the balance doesnt change, tried with evens, odds, single dollars etc. tried relogging, clocking out and clocking in, no success.

**Comment by fkk-cz** [comment]
Which job grade do you hold? Assistant manager or manager?

**Comment by BaelyTV** [comment]
> Which job grade do you hold? Assistant manager or manager?

Manager

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/9f53a717b4fd7a30c23163af1c1d75db23616ac0.
