### ISSUE TITLE
i won at the casino and won no money 

### ISSUE THREAD

**Issue by Barry546363** [fkk-cz/noire-public#1004]
https://medal.tv/games/gta-v/clips/r7HrLYb6DJcbW/d1337ythjLGJ?invite=cr-MSxMTXAsNzc0OTYzODgs
there is the clip my in city name is Max Lockton

**Comment by PsychoticCore** [comment]
I've had this same issue happen...

**Comment by Competent1** [comment]
Nice Discord call you're in.... smh

**Comment by fkk-cz** [comment]
GitHub issues are required to be actionable and specific enough to identify and fix the stated issue. A video showing you 'lose' at the casino does not fall under this category.
