### ISSUE TITLE
Disable F3

### ISSUE THREAD

**Issue by GoldBlockGames** [fkk-cz/noire-public#1007]
F3 for ID should be disabled as people use it to see through walls and powergame.

**Comment by tythetanman** [comment]
For proper reporting purposes, that’s why it’s still there. 

How else would you be able to identify someone in a video to match the logs of a possible issue that happened?

**Comment by teresgrunt4555** [comment]
It is also used to com serve people that need to do some cleaning at beach.

**Comment by fkk-cz** [comment]
This cannot be disabled unless people start following all the rules and we no longer need to accept player reports.
