### ISSUE TITLE
Loans

### ISSUE THREAD

**Issue by AndyMurray123** [fkk-cz/noire-public#1029]
Maybe would be a cool addition where you can take loans out with repayments are interests rates, it could be accessed through the finance and insurance building and if not payed can lead to warrants for arrest. Just think would add another layer to that building and making it more realistic server.

**Comment by Fallinglol** [comment]
this makes me think back to over a year ago when you could finance cars and nobody would actually intend to pay for the vehicle. Great idea, I just think people would deliberately not pay the loan back.

**Comment by ix1ali** [comment]
People arent paying? Np
Make their bank accounts negative 

Just like how fees are when they are forced, Let them be down -200k
And have a warrant for their arrest, plus 300+ com serve

**Comment by Client7** [comment]
This isn’t what coms are for, also the whole make there account negative doesn’t solve the issue

**Comment by dukerzzz** [comment]
I think there are pros and cons to this. If they haven't made a payment, have DOT repo the car until it's caught up in payments. If they can't use their car until they get the payments caught up, then maybe that can be an initiative for them to pay it on time. Basically, once the player is in the city and the car is "out and about", DOT will get a "REPO MISSION". And it will be like car auto theft. It gives the name and year of the car and gives a general area of the location. Once DOT impounds the car. The only way to get it back is to catch up on the payments, and then pay a fee at DOT to get it back.

**Comment by xFooliee** [comment]
I think this would be a good idea for car payments. If you miss a payment or refuse to pay, the car gets repo’d with a fee as such. Just an idea but definitely would be a good idea for cars idk about for jail though.

**Comment by fkk-cz** [comment]
> People arent paying? Np
Make their bank accounts negative

This is no longer possible, for multiple reasons that I've already explained in Discord.

> If they haven't made a payment, have DOT repo the car until it's caught up in payments. If they can't use their car until they get the payments caught up, then maybe that can be an initiative for them to pay it on time. Basically, once the player is in the city and the car is "out and about", DOT will get a "REPO MISSION". And it will be like car auto theft. It gives the name and year of the car and gives a general area of the location. Once DOT impounds the car. The only way to get it back is to catch up on the payments, and then pay a fee at DOT to get it back.

How would DOT be responsible for enforcing a lien/repossession order on a vehicle owned by a bank? Putting aside the fact that DOT's activity is spotty at best -- not to mention comprised completely of gang members which would lead to accusations of bias and COI -- I don't see how this wouldn't be abused by people on both sides. Players who are late on payments will either never drive the vehicle or pull it out of a garage, anyone tasked with enforcement will do anything it takes to reclaim the vehicle.

If we're currently having issues of individuals not paying their criminal charges, what makes people think this won't be even worse when it comes to _loans_ or financed vehicles? Keep in mind obtaining a loan in the real world requires a credit/background check, talking to a loan officer (in this case, a car dealership employee), and a drawn out approval process. There is no way this will work with an automated approval system.

**Comment by dukerzzz** [comment]
Good point. I didn't think too far about the gang stuff! I'll keep that in mind for future comments and post.
