### ISSUE TITLE
Mining saying full inventory when it’s not 

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1031]
Sometimes,. the game says i’m full, and i can’t mine anymore, when i’m clearly not. Like just not i had 1 steel, 8 iron, and 3 copper, and it said i was full. it only adds up for 120 storage. i had nothing in my inventory besides that

**Comment by fkk-cz** [comment]
GitHub is for reporting bugs with **actionable** information. This doesn't seem like either.
