### ISSUE TITLE
New Ways for Bank Cards

### ISSUE THREAD

**Issue by YouTrippinShordy** [fkk-cz/noire-public#1033]
Coming from both Crim/LEO sides i think we want to see more Fleeca Banks being robbed. I think there needs to be different ways of getting bank cards. I imagined another way to get cards other than hitting an armored truck is dumpster diving. With this addition you can get variety of things from Garbage/Junk, to a random varying amount of cash, Jewelry that you can sell to the pawn shop, and make it a very slim chance to get bank cards. Coming from the LEO side. We enjoy responding to Bank Robberies it also spices things up .

**Comment by xFooliee** [comment]
Plus as a LEO myself I’ve never really heard or seen anyone do an actual bank robbery

**Comment by jeanndabeann** [comment]
i like this idea a lot, brings more things for crims and civs to do! ill totally go dumpster diving for fun

**Comment by STKstyx** [comment]
There's rarely ever any bank heist because there's never enough LEO'S too do them nor is there very many bank cards even in the city to my understanding

**Comment by Client7** [comment]
How would you find a bank card in the garbage  that’s highly implausible

**Comment by STKstyx** [comment]
> implausible

I agree. Don't disagree with the dumpster diving but definitely agree about the bank cards just somewhere else other then dumpster diving

**Comment by Client7** [comment]
Yea that’s true or maybe increase the amount of armor trucks that spawn like maybe having it back in a accessible spot like before, but thing with this people choose not to take the risk of retrieving them

**Comment by YouTrippinShordy** [comment]
I'm just tossing ideas out there for more ways. At the end of the day we are trying to have fun so i think something where its Luck based aswell. and for the plausibility Cops don't go on 200+ chases with Ferrari's and stuff. We are here to have fun. SO its ok to bend the plausibility a tad bit. It's just a thought to get more Banks going.

**Comment by BreezyEZ** [comment]
I agree, I think making it "easier" to be able to obtain bank cards would be nice. In my 9 months as LEO, I've only encountered less than ten Bank Robberies. Another potential option to make the bank more accessible is to make the vault or whatever door hackable whether be the default hacking method or through finding specific codes throughout the city like other cities do. Of course having the set codes, they would need to be changed daily if this method is used.

**Comment by YeagerGTA** [comment]
Joey Sammich was 30 seconds from making a getaway on a bank truck,  by himself :)  A truck can be done. If you look at the other thread about the trucks, fkk has been working and adjusting it to get it faster, and more doable. They are not easy, but can be done with a plan with focus from people. These are NOT rob at a whim missions. 

The only current issue is respawn after a failure that I am aware of and that is being looked at.

**Comment by tythetanman** [comment]
Joey is also the Jesus of crime lol.  Yeager is right.

**Comment by fkk-cz** [comment]
At this point, there are no plans to increase the number of bank cards in circulation, nor are there plans to make the process to obtain one significantly easier. We do not want bank robberies to be occurring every day, or even on a regular basis. If the cards were easier to obtain, players would powergame and repeatedly grind the banks that will pay the most/have the highest probability of getting away.

There should probably be a reduction in the number of cops required to commit crimes now that the LSSD has been added.

**Comment by cxerq** [comment]
Maybe instead of easier bank cards an overhul to the crim side, not for gang members or drugs just for robberies and other stuff that people can do cause right now its pretty much pointless to rob stores cause its the same thing all the time i understand its up to us crims at making them fun but we need more! Ill write up some ideas I have later!
