### ISSUE TITLE
AMR Distress Pings

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire-public#1035]
Over the last few days we have begun to receive distress pings from people inside the Morgue at 140. This should not be possible and was never a problem before.

Also you previously discussed disabling pings for places like Prison and Comserv since we are unable to get those as well. We constantly get pings from comserv at 811 right on the beach. It worked for a few days and then seemed to have broke as well. 

Thank you for all the hard work

**Comment by ix1ali** [comment]
a nice addition would be like a message/notification that is letting you know if a medic is on the way to come get you, Should pop up when they accept your distress signal [just like taxis]

**Comment by fkk-cz** [comment]
Players in community service or in the morgue will no longer be able to send distress signals, as originally intended.

> a nice addition would be like a message/notification that is letting you know if a medic is on the way to come get you, Should pop up when they accept your distress signal [just like taxis]

Added in https://github.com/fkk-cz/noire/commit/d62ecb44fda899d528396fc3b9dc2e06f515ccc4.

> I think adding a delay of 30 seconds before a ping can be sent could help with the problem of body’s flopping into different spots.

Agreed, should resolve most phantom movement issues. Added in https://github.com/fkk-cz/noire/commit/999ad83f14660c35c0f8897b36750987a0b2820d.
