### ISSUE TITLE
Roulette not paying out

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#1036]
Have now had 2 separate occasions where I hit 2500 on a number on roulette and it doesn’t pay out the winnings. Just wanted to bring this up as it’s a real buzzkill to see you won then not see the money come from it and I have seen this happen to others too

**Comment by Mynameisnotlenny** [comment]
https://medal.tv/games/gta-v/clips/srJl65oC9oPCb/d1337j1rNIoL?invite=cr-MSxrVUwsNjE3MjgzNjMs

**Comment by Mynameisnotlenny** [comment]
Also curious how I can go about receiving compensation for the $175,000 total that I would’ve won had it paid out correctly.

**Comment by fkk-cz** [comment]
See the updated restitution rules. https://github.com/fkk-cz/noire-public/discussions/985#discussioncomment-3218041
