### ISSUE TITLE
Burgershot new desserts issue

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#1037]
Just bringing this here, even though it is currently in the chat for Burgershot.

Just a simple issue, the desserts they show up where they're supposed to show up, but whenever you try to pull one out and put it in your inventory, it does not show up on yourself.

Preventing having possession of the product and being able to sell both items.

**Comment by tythetanman** [comment]
Thank you for the products. Only adjustment that is needed. Is the hunger, not being just one for both products it’s 1 food per item.

**Comment by fkk-cz** [comment]
Forgot to add a zero on the end. Fixed for next restart.
