### ISSUE TITLE
Off-road Park

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1039]
I think an awesome addition on the map would be an off-road park with tons of steep trails and mud pits and stuff to do with various off road cars. This would make a fun thing to do when you run bored in the city.

**Comment by CasperBoiRL** [comment]
https://www.gta5-mods.com/maps/san-andreas-off-road-park-ymap

**Comment by fkk-cz** [comment]
What about the redwoods light track?

**Comment by CasperBoiRL** [comment]
nah, it’s not the same. this is just way cooler, and would be amazing

**Comment by CasperBoiRL** [comment]
thats just a track, while the one i sent is a bunch of various trails and more

**Comment by okxeon** [comment]
This replaces a large part of the map. As of right now a majority of the map (with exceptions from building interiors) is mostly from the vanilla game. It does look nice though.

**Comment by CasperBoiRL** [comment]
it does, but it leaves a lot threes too. there’s nothing that is going on at this spot of the map though.
