### ISSUE TITLE
Despawning right in front of me

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1043]
Fix this dumbass shit bruh. This has gotta be the dumbest thing i’ve seen. there is absolutely no reason for this https://medal.tv/games/gta-v/clips/sKjvOo3pQ7PSz

**Comment by DeJayRambo** [comment]
bruh that happened to me the day as well. only one of my trucks despawned though i was able to recover it, but that looks painful when more than 1 despawns

**Comment by CasperBoiRL** [comment]
yeah, and if it’s the trailer it’s really bad. happened to me at the mine and i was so mad

**Comment by Jakebeastt** [comment]
This happened to me too pls considering fixing this it really annoying
mining for two hours and this shit disappears!!

**Comment by fkk-cz** [comment]
GitHub issues are for reporting bugs with **actionable** information with repro steps. Complaining without providing any further information is unhelpful.

**Comment by CasperBoiRL** [comment]
What do you mean? So this is just gonna go unfixed forever?
