### ISSUE TITLE
Best Buds untrimmed cannabis sales

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#1044]
Just wanted to bring up that the best buds is slightly broken, no matter what you’re not able to sell untrimmed cannabis to the PED behind the counter. Believe it may have unintentionally been specified in the code as the untrimmed weed you used to find when searching cars was a feature. However could be due to something else, just wanted to bring this up as it has been like this since the ability to process weed at that location was removed.

**Comment by fkk-cz** [comment]
Best Buds was supposed to be removed a while ago. I'd like to change weed to a DIY grow-anywhere system, instead of having static processing locations.
