### ISSUE TITLE
DOT Gates are being buggy

### ISSUE THREAD

**Issue by dukerzzz** [fkk-cz/noire-public#1049]
Clocked into work today and all of the gates are doubled after the update. They were working fine last night on 07/18/2022. I have a clip as well of all of the gates. Some of them work others don't. It's a hit in miss too. I can leave for 10 minutes come back and the gates change up to where some open and some just don't open. I have tried fly in and out of the city. I restarted my computer multiple times. I could try erasing the cache, but I doubt that is the issue.

https://medal.tv/games/gta-v/clips/t0l2iDMdlv_yv/d1337PLJRqKc?invite=cr-MSw4Q3EsNzcxMDkwMjEs

**Comment by No-Yes1** [comment]
Think it's time for DOT to relocate at this point.

**Comment by dukerzzz** [comment]
Have any ideas? You thinking a pre-existing area or a brand-new addition?

**Comment by fkk-cz** [comment]
DOT impound has been moved to a temporary new location until a better replacement can be found. The gate issues were caused by duplicate .ymaps in different stream folders.
