### ISSUE TITLE
Jet Ski trailer 

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1050]
We should have some sort of option to get a jet ski trailer, and hook it up to any car eligible for a small trailer. This would be amazing, and would allow for tons of fun, taking our jet skis anywhere. There’s already one that spawns at the jet ski rental, but you can’t drive ped jet skis.

**Comment by fkk-cz** [comment]
This would be nice, do you have a trailer model that would work? Something like the vanilla `boattrailer`.

**Comment by CasperBoiRL** [comment]
Yeah, we’ll there’s already a vanilla jet ski and trailer that spawns at the Whitewater rental. I say you just spawn the trailer at a garage and drive it to a public dock, and spawn your jetski. Load it up and take off. I figured you could do the same with boats.

**Comment by fkk-cz** [comment]
No, the issue lies in the fact the current trailer system will only allow vehicle attachement if the desired vehicle is stationary. Jetskis (and all boats, for that matter) will always move around in the water.

**Comment by CasperBoiRL** [comment]
https://www.gta5-mods.com/vehicles/jetski-trailer

**Comment by CasperBoiRL** [comment]
Taht one looks nice

**Comment by CasperBoiRL** [comment]
nvm, didn’t read description

**Comment by CasperBoiRL** [comment]
https://www.gta5-mods.com/vehicles/portuguese-public-security-police-jetski-trailer-addon

**Comment by CasperBoiRL** [comment]
that one is good, it just doesn’t have to be used for police.

**Comment by fkk-cz** [comment]
Did you completely ignore my post above? Stop posting random links to trailer models you're finding, it **won't work** given the fact the target vehicle will never be completely still in the water. If jetski trailers are added, the entire attach/detach system needs to be reworked.
