### ISSUE TITLE
Logitech G29/G920 Wheel Support

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1051]
I know there are scripts out there that allow players to use wheels while driving. Is there any chance we can get one of these in here?

**Comment by fkk-cz** [comment]
I don't have a steering wheel to test such 'scripts' out -- I'll tentatively add this to the list though.

**Comment by CasperBoiRL** [comment]
i feel that this would create some amazing immersion for those that do possess a wheel.

**Comment by CasperBoiRL** [comment]
any word?
