### ISSUE TITLE
Money wash

### ISSUE THREAD

**Issue by Krazij** [fkk-cz/noire-public#1054]
I know we spoke about this a few days ago but I Wanted to formally suggest bringing back money wash . A lot us want to rp that real trap life . And not have to turn to legals every time we want money. We love the challenge we face of having to sell drugs at a high risk and we want to actually tell people that this is the only way we Make money. People are making 100 of thousands of dollars Doing mining and that ok. But we you are trying to rp like a real gangsta money wash is the tool we need .

**Comment by teresgrunt4555** [comment]
There are ways to wash the money with out washing it. You sell it to gang members because they will buy it or you can sell guns to gang members to turn dirty to clean

**Comment by tythetanman** [comment]
Having an option like a new shell corporation (like a laundry mat, or a random business) where you would lose maybe 10 to 20% of the total for it being cleaned would be an option as well. That would be smart to add.


It would be an alternative to the sale of dirty money and guns, which is doubling your money, and sometimes even more than that.

**Comment by Krazij** [comment]
> There are ways to wash the money with out washing it. You sell it to gang members because they will buy it or you can sell guns to gang members to turn dirty to clean

been there done that. It’s not consistent. And for people who don’t really have time to play all week all day should have a money wash available to them.  I’m looking at it as another job.

**Comment by Krazij** [comment]
> Having an option like a new shell corporation (like a laundry mat, or a random business) where you would lose maybe 10 to 20% of the total for it being cleaned would be an option as well. That would be smart to add.
> 
> It would be an alternative to the sale of dirty money and guns, which is doubling your money, and sometimes even more than that.

Thank you bro.

**Comment by Krazij** [comment]
Also some of us ain’t looking to just be buying guns with dirty because we not really into just shooting. I’m not in a gang anymore and not looking to rejoin either. I’ve noticed that I’ve gotten better rp not wearing a flag.

**Comment by somedudenamedrush** [comment]
TBH it should just give u clean 
dirty isnt a thing irl forget the money wash 
think we need to look at the reasons why dirty should be scrapped

**Comment by Krazij** [comment]
> In reality yeah. But not for fivem servers. It’s really what you need so people actually want to sell drugs so they can get automatic guns. I just want the old money wash back . It was never hurting anybody being there .

**Comment by somedudenamedrush** [comment]
i feel that 
in a perfect world i think the back market guns should be something crims are able to craft from gun parts and other mats/get from other sources bobcat trucks/drops
