### ISSUE TITLE
in the 2 weeks of playing ive never had a single admin answer my /assist

### ISSUE THREAD

**Issue by classyz** [fkk-cz/noire-public#1055]
I've been rdmed multiple times many by players under the age of 14 and I am never able to get into contact with an admin. i dont understand if its something im doing wrong

**Comment by okxeon** [comment]
An admin will respond if one is available. Keep in mind without a clip 9 times out of 10 nothing can be done. Set up some sort of clipping software to capture at least 30 seconds to show what happened. As for your assist reason make it detailed enough and mention you have a clip. Phrases like "rdm", "help", or "I need an admin" won't get a response. Hope this helps.
