### ISSUE TITLE
Add Dispatch Back

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1058]
Dispatch used to be an an amazing addition, and would be great for call ins for robbery’s and fights. I don’t know why it was removed, but if it was added back, i would do the job, and i’m sure many others would want to also

**Comment by Bountyrogger** [comment]
See Discussion #942

**Comment by CasperBoiRL** [comment]
nothing has happened in that in forever

**Comment by Bountyrogger** [comment]
well staff are legit gonna just close this one and tell you legit what I said.

**Comment by okxeon** [comment]
> See Discussion #942

refer to this.
