### ISSUE TITLE
DoorDash WL job

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1063]
This would be very easy to implement. You don’t have to add any new cars, since people use there own. You can use the taxi system to notify someone if there order is on the way. The only part that would be hard would be how to communicate what the person wants to order. This could be done by a phone call i guess, or it could be done by an app on the phone

**Comment by Stagonium** [comment]
This does not need a whitelisted job behind it, you can easily acquire a business license through the DOJ, and run your own ads on twitter/marketplace and communicate with customers to bring them food/drink/repair kits or whatever.

**Comment by No-Yes1** [comment]
Not really, Twitter/Marketplace is free and works well.
