### ISSUE TITLE
DOJ access to old impound lot

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire-public#1068]
I know Sheriff's department has DOT's old parking lot, but after speaking to some of the members of the Sheriff's department, they said it would be ok with them if DOJ uses the half of the lot closest to the corner of the street. This would be super helpful since we had a DOJ parking lot at the old courthouse. Since moving, we have had to park in the open-access parking garage connected to the courthouse, which has led to many DOJ employees' cars being stolen/damaged

**Comment by tythetanman** [comment]
Ohhhhh I need… yassssss

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire/commit/e9b6b4a53bfce014d27f03794da2b9d34b59e192. DOJ will have access the old impound area only.
