### ISSUE TITLE
PDM Menu Organization Idea (Supporter Category)

### ISSUE THREAD

**Issue by dukerzzz** [fkk-cz/noire-public#1070]
Anyway to organize the Supporter category by make? Basically when you first go into the menu it's organized by Make.  That's great because its easy to navigate and its less cluttered, but when you go into the supporter section it's organized by date and alphabetically, which is a cluttered mess and takes time going through the vehicles.

I'm hoping to see something to where when you go to the supporter category it's organized into sub categories by Make, then inside those "Make" categories its organized alphabetically and by year.

It would make the process of finding/testing out cars easier and more efficient.

**Comment by CasperBoiRL** [comment]
oh hell yeah we need this

**Comment by dukerzzz** [comment]
> oh hell yeah we need this 

I also should've mentioned that we should see the trunk space. I notice sometimes we see a "No trunk space available". What about having a total number of trunk space in the stats? It would help new players out in deciding what car to get since you won't know until you buy it.

**Comment by CasperBoiRL** [comment]
i think that would be hard to do. you can see the class, which tells you how much space it has

**Comment by fkk-cz** [comment]
This has been on the list for a while. A new interface that prominently displays newly added vehicles is one of the main priorities. https://github.com/fkk-cz/noire-public/issues/508
