### ISSUE TITLE
Illegal Drug Transporting Job

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1076]
Have missions like the car theft, but much more common to get. You pick up the package and put it in your trunk, drive to the destination, drop it off, and you get your money. Like that movie The Transporter. Dirty Money Obviously

**Comment by fkk-cz** [comment]
> Have missions like the car theft, but much more common to get.

In other words:
> I'm greedy and want more ways to make dirty money with less risk and higher reward!!!!!! I want to be able to grind out dirty money!!!!!!!!!!!!!!!!!!!!!!!!!

Yeah, that's not happening, sorry.

**Comment by PeanutTheCop** [comment]
I could go for this, and i wouldn’t care if it even payed well or not
