### ISSUE TITLE
New Coke Tables Problem

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire-public#1077]
if someone flys out while they are on the gathering table 
the table cant be used till the next reset same thing used to happen at meth and was fixed figured id bring it up to be fixed

**Comment by fkk-cz** [comment]
Are you _sure_ this is an issue? A quick check shows a `playerDropped` handler is already in place to fix this, although the player ID comparison could have been bad.

**Comment by somedudenamedrush** [comment]
watched a guy fly in as he saw us come inside flew out while on the table and the table was broken by saying "someone is using this table already"

**Comment by fkk-cz** [comment]
Unless more people start reporting this issue and can provide repro steps, I'm going to assume this was either fixed or an isolated incident.
