### ISSUE TITLE
Ability to disable trucking CB radio

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#1078]
### Discussed in https://github.com/fkk-cz/noire-public/discussions/1075

<div type='discussions-op-text'>

<sup>Originally posted by **rawranevilpanda** July 27, 2022</sup>
I think players should be given the option to turn off the radio, there are times when people are just straight up trolling/making loud noises/saying racial slurs and they do it because theres no way to stop them or see who is doing it. If we aren't able to turn it off then at least make it so we see a callsign or something to identify a person when they're talking on the radio.</div>

**Comment by Bountyrogger** [comment]
I would honestly like a return to callsigns. I think I can speak to PD and HP when there are times you are trying to look for someone specific and you aren't sure if they are on radio or off radio or in another channel (As PD HP and AMR use at least 1 second channel. Prob wont make a return but I liked having the callsigns

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/b6da31f4afff3d653593a13a95a6cb0e42796745 fixes this issue.

> I would honestly like a return to show callsigns. I think I can speak to PD and HP when there are times you are trying to look for someone specific and you aren't sure if they are on radio or off radio or in another channel (As PD HP and AMR use at least 1 second channel. Prob wont make a return but I liked having it show callsigns

This will not be making a return. The number of active officers/AMR/DOT on at one given point makes this unfeasible to display on your screen, and is just unrealistic/unneeded.
