### ISSUE TITLE
More Co-Op-Able jobs 

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1082]
I really enjoy running around with a friend doing trash, but i wish there was another job that was Co-Op. If it was possible, landscaping could be made where we both did the job and we split the money.

**Comment by fkk-cz** [comment]
Why does it seem like the majority of your interactions with this repo are these generalized ill-considered suggestions that have been repeatedly asked & answered in the past? Or, for example, submitting these [nonsensical requests](https://github.com/fkk-cz/noire_vehicles/issues/1287) such as changing a vehicle class for the sole purpose of maximizing your trunk capacity?
