### ISSUE TITLE
Autotheft mission not completing/paying out

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire-public#1083]
Did an auto theft mission and it never despawned the car once the vehicle was delivered and I never got paid for doing the job either... The vehicle was in A1 condition and everything
Yellow circle where you're supposed to deliver the car disappeared and everything but car stayed there and I didn't receive the payout from the job

Video: https://streamable.com/0oyij5

**Comment by fkk-cz** [comment]
These appear to be isolated incidents and relatively infrequent, when compared to the total number of missions attempted. Unless repro steps are provided, this won't be fixed.
