### ISSUE TITLE
My guns are not the correct mags 

### ISSUE THREAD

**Issue by blap1** [fkk-cz/noire-public#1086]
I keep buying pistols which in default have 12 bullets in the mag like beretta and Springfield but i get 7 all the time how can i fix it?

**Comment by blap1** [comment]
![FiveM® by Cfx re -  24  🎲 L A  Noire RP _ discord gg_noirerp _ Custom Cars   Handling   Sounds _ Active PD   EMS   DOT 8_1_2022 3_38_02 AM](https://user-images.githubusercontent.com/109044532/182050074-0d0db3e4-46e2-4059-8234-0e454ca95c51.png)

**Comment by blap1** [comment]
????

**Comment by fkk-cz** [comment]
Duplicate of #1092.
