### ISSUE TITLE
Add a way to view total playtime

### ISSUE THREAD

**Issue by dukerzzz** [fkk-cz/noire-public#1087]
Anyway to add a total playtime on your ID card or maybe have a way to where if you go to the DMV and select "show total playtime" it then displays your total playtime?

**Comment by tythetanman** [comment]
Great… a detailed menu of more reasons of why I need to touch grass… yay… *headed back to court*

**Comment by dukerzzz** [comment]
> Great… a detailed menu of more reasons of why I need to touch grass… yay… _headed back to court_

😆 I just keep seeing people asking "how many hours do I have? Could save admins the time of checking.

**Comment by fkk-cz** [comment]
Playtime has no valid context or relevance in roleplay and shouldn't really be brought up, or used as any sort of comparison. This will not be added.
