### ISSUE TITLE
A person is connecting to my trailer even when its locked

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire-public#1089]
im mining and all i know is my trailer is gone and someone is driving away even tho its locked its so annoiyng

**Comment by fkk-cz** [comment]
Your truck was most likely marked for an auto theft mission. Vehicles marked for an active mission can be locked anywhere, regardless of any safezone. This is another reason why mining is fundamentally flawed and will ultimately need to be replaced.
