### ISSUE TITLE
issue with download ?

### ISSUE THREAD

**Issue by Jakebeastt** [fkk-cz/noire-public#1090]
this is what i got 

[CodeWalker] Unpacking RPF...
[Worker] Inflating 343439\cache\rpfunpack\carcols.meta
[Error] An error occoured during execution, stacktrace has been logged to /logs/latest.log, please submit to GitHub Issues page.

**Comment by fkk-cz** [comment]
GitHub is for reporting bugs with detailed actionable information. For vehicle requests, please ask in Discord.
