### ISSUE TITLE
Can't sell cars with unpaid fines but don't have any outstanding fines

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#1091]
Noticed this bug that doesn't allow you to sell cars because you have unpaid fines, but when the court checks, you don't have any outstanding charges.

**Comment by IIBurntLuisII** [comment]
same here

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/7c51339d275ce27adc4caac7d6804969a3015185.
