### ISSUE TITLE
The amount of bullets in each mag is incorrect

### ISSUE THREAD

**Issue by blap1** [fkk-cz/noire-public#1092]
My beretta and Springfield are supposed to have 12 bullets per mag but for me, I have 7 I've been trying to get help but no one responds.
![FiveM® by Cfx re -  24  🎲 L A  Noire RP _ discord gg_noirerp _ Custom Cars   Handling   Sounds _ Active PD   EMS   DOT 8_1_2022 3_38_02 AM](https://user-images.githubusercontent.com/109044532/182657790-10d586dc-f5b2-4c05-8522-3cf7cb38dd00.png)

**Comment by GoldBlockGames** [comment]
It is the right ammo bruh

**Comment by blap1** [comment]
all my friends have 12 whatchu mean

**Comment by GoldBlockGames** [comment]
Oh mb

**Comment by blap1** [comment]
?

**Comment by fkk-cz** [comment]
The amount of ammo given is determined by GET_WEAPON_CLIP_SIZE. This is not a bug, and works fine for everyone else.

Also what's with the black sky? 🤔
