### ISSUE TITLE
Auto-Theft mission

### ISSUE THREAD

**Issue by D4LPebble** [fkk-cz/noire-public#1095]
can we turn auto thefts back into PED cars. almost every time the only cars we get are people in mining, or people selling mining materials. and if theyve had the vehicle out or repair'd it multiple times it still counts as it having damage. either get 0-100$ dirty. so its just not worth it at all to do. in the sense of fun and risk/reward

**Comment by noyeahsure** [comment]
ped cars or maybe just somehow adjust it to only account for damage done after youve gotten in, just did one, stole the dudes bronco, drove it perfectly to the dropoff. $300 i got from it, lost 3400 profit

**Comment by PsychoticCore** [comment]
The mining trucks and shit are fine, the bad things about these missions being player vehicles is when they're in a locked parking lot for example like at the court house, ive gotten so much of those and just to cancel it and get rid of the mission you have to hop the fence and destroy the car by running it into walls. A real pain in the ass

**Comment by D4LPebble** [comment]
i will restate my statement. it is not okay, hence if the car has been out for hours, it has been repaird multiple times.. meaning youre going to get 0-100$ in dirty for the mission. i do agree with a lot of cars being behind locked gates/getting cars under water still

**Comment by fkk-cz** [comment]
Auto thefts will not revert back to non-player vehicles.

> almost every time the only cars we get are people in mining, or people selling mining materials.

https://github.com/fkk-cz/noire/commit/e6db18014c619605d97dc50f9d32545d55cd4c50 might help with this, all vehicles that are parked in safezones will no longer be eligible for missions.

> and if theyve had the vehicle out or repair'd it multiple times it still counts as it having damage

Probably should use the initial vehicle damage as a baseline value to compare when turning the vehicle in. Increasing the minimum vehicle health for mission eligibility would also help.

> the bad things about these missions being player vehicles is when they're in a locked parking lot for example like at the court house

There is no way to determine whether a vehicle is in a locked area or in water on the server. As a result, these vehicles cannot be excluded from missions. Maybe a mission time requirement would solve this?

**Comment by D4LPebble** [comment]
maybe like, a way to cancel the mission if anything happens. can go back to the same customs shop and 3rd eye the auto theft dealer and force cancel a mission if the car is for whatever reason bugged

**Comment by fkk-cz** [comment]
> maybe like, a way to cancel the mission if anything happens. can go back to the same customs shop and 3rd eye the auto theft dealer and force cancel a mission if the car is for whatever reason bugged

Added in https://github.com/fkk-cz/noire/commit/0f9f05d51ddb4b6b81d03b21ba5b8a42733338fc. There will be no further adjustments to these missions for the time being.
