### ISSUE TITLE
LSDS Garbage pick up point issue

### ISSUE THREAD

**Issue by Deathetron** [fkk-cz/noire-public#1096]
whenever we go and pickup garbage theres a chance that the red circle doesn't appear around the garbage can/bin so we can't pick up trash and get paid. Im unsure why this happens but im guessing maybe the script needs to be redownloaded woth the newest version or something im unsure like i said. Also i can't specify the locations, happens everywhere for me.

**Comment by Stagonium** [comment]
Certain locations have multiple trash cans that may have the trash in them, not all of them allow you to back the truck straight up to the can and just mash E. Look around a bit

**Comment by Deathetron** [comment]
alright so likd trial and error, and if you dont see the red circle and cant find the garbage?
