### ISSUE TITLE
Sheriff department

### ISSUE THREAD

**Issue by Baker187** [fkk-cz/noire-public#1097]
Hello, some stuff we need.
We need the ability to combatlog people who decide to fly out on arrest.

Also deputy 3+ needs tear gas if working proper

Discord roles for deputy 3 for deputy 3 channel so they can use it for training and what not.

**Comment by ChugThis** [comment]
-Helicopter access for sgt+ 
-EUP creator until new EUPs
-cuffing animation scuffed for hard cuffs 
-fence for the Davis station fixed

**Comment by ChugThis** [comment]
- EUP access, think you may have fixed it but LSSO still does not have access to the EUP menu or to save EUPs
- door to the roof of the Davis station 
- VOIP tutorial abilities/comserv 
- A way for the court to notify on duty LSSO they are needed

**Comment by tythetanman** [comment]
We have L.S County Sheriff (Non-Priority) button. Not sure if it’s possible to have more options for request service, but we do have that in the MDT at the moment.
