### ISSUE TITLE
Glitch with Dodge Charger Hellcat

### ISSUE THREAD

**Issue by Planegorgon** [fkk-cz/noire-public#1100]
Made a recent purchase of a dodge charger 2020 for 268k, whenever around the vehicle or driving I get black flickering lines on my screen and everything glitches. What can be done to fix this?

**Comment by TheBottomFragger** [comment]
Think this is one of the cars that needs to be removed/recalled

**Comment by Scubaaaaa** [comment]
This is the wrong section of the github. Make a new issue in https://github.com/fkk-cz/noire_vehicles
