### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by DarkHourEnt** [fkk-cz/noire-public#1111]
I’ve used over 300+ bait , mostly catching other items . The idea is to implement a promotion system. It currently always says amateur , getting higher rank with increased catch rate would be nice and rewarding . Or even encourage fishers to utilize boats going deeper in the ocean to catch better fish .

**Comment by Bountyrogger** [comment]
FKK has already stated multiple times I believe now that he is not reworking fishing

**Comment by fkk-cz** [comment]
Fishing will not be reworked. There are not a lot of [relevant ped models](https://docs.fivem.net/docs/game-references/ped-models/#animals) that would make sense to catch, and the job doesn't require players to actually move around and do anything, similar to mining.
