### ISSUE TITLE
Ladders 

### ISSUE THREAD

**Issue by Proudcat1** [fkk-cz/noire-public#1112]
Why where most of the ladders removed from around the hood?

**Comment by noyeahsure** [comment]
also confused about this...

**Comment by zoiczombie** [comment]
It was said in lobby that they were removed for KOS from the roofs. As Marlo's pointed out, we still have a red question mark at 122 luring new people to the area. With gangs constantly fighting for control of the area, the removal of ladders will not end the KOS in the area. I believe the question mark should have been removed before removing the ladders.

**Comment by AngelMff** [comment]
Kos from roofs from who specifically? Gangs agreed blocks would be kos so rather the question mark was there or not it will still be kos when gangs come to the blocks or when randoms come to the block it would be ros so what does kos have anything to do with being on roofs ?

**Comment by AngelMff** [comment]
Only thing I can think of why they were taking off is cause cops didn’t stand a chance in fights when we had control over our own block so took them out so when we do fight they get easy high ground to a roof no one can access

**Comment by KyleM49** [comment]
I think if they removed them to prevent KOS and force more interactions. tThat would mean a gang would have to literally sit in front of it and tell people to get lost instead of KOSing on a roof without any interaction.

**Comment by noyeahsure** [comment]
you obviously don't know what goes on there because we dont just "kos" there unless its a flagged gang. randoms we interact with.

**Comment by fkk-cz** [comment]
The ladders were originally removed by request of numerous players who pointed out the amount of shooting going on from the rooftops. Nothing to do with police, not sure why people are speculating and falsely assuming that. Restored them as people seem to be so angry & hostile about it.
