### ISSUE TITLE
Trailers at 402 Gas

### ISSUE THREAD

**Issue by residentalyeti1** [fkk-cz/noire-public#1114]
The past couple days I've noticed a heap of trailers dumped at 402 gas. They are the trailers for the ammunation trucking run. I was speaking with someone there and he told me that recently some have been despawning and others haven't been. Below is a clip of just the trailers i saw today before i cardelled them all.

https://medal.tv/games/gta-v/clips/wsrrsf5PFEXPu/d1337AvitqHJ?invite=cr-MSxMcm8sNDMyMDMzODEs

**Comment by fkk-cz** [comment]
This is probably related to the update that fixed vehicle resonating. Trailers, unlike normal vehicles, are created via RPC and shouldn't be persistent entities, i.e. auto deleted once there are no players in network range. Are these trailers staying here all day?

**Comment by kelliott33** [comment]
Yes they’re staying there all day, I went there to do a gas run yesterday and a trailer was where my gas truck spawns so I left and came back later in the day but the same trailer was still there along with multiple other trailers around the station

**Comment by fkk-cz** [comment]
Added a possible fix in https://github.com/fkk-cz/noire/commit/997227992acad44d8341328920b9f8b7d66ea1a8. Going to check a few job sites tomorrow to confirm this.

**Comment by fkk-cz** [comment]
Only found one truck & trailer abandoned at that location. Marking this as fixed.
