### ISSUE TITLE
Roulette tables not paying out

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#1131]
Just wanted to see if we could get a fix to the roulette tables not paying out have had 4 occasions now where it didn’t pay out that total $350,000. I enjoy being a degenerate gambler sometimes and spending hours at the casino. It would be nice if this could be fixed as it’s happening often enough that it’s not a one off thing. I’ll include some clips of it in the comments.

**Comment by Mynameisnotlenny** [comment]
https://medal.tv/games/gta-v/clips/x79zUwixN4uij

**Comment by fkk-cz** [comment]
Have you noticed any correlation or patterns to this? Without repro steps this is going to be hard -- if not impossible -- to fix.

**Comment by Mynameisnotlenny** [comment]
> Have you noticed any correlation or patterns to this? Without repro steps this is going to be hard -- if not impossible -- to fix.

Haven’t noticed anything specific yet besides it only occurring in the clips I submitted on the first 12 numbers on the table. If it happens to anyone else hopefully they have a clip they can add here to help us find any patterns to figure out what causes this to occur.

**Comment by cxerq** [comment]
It looks like its just happening with the first 9 numbers i havent had it happen to me on anything higher! could be wrong and could just be lucky for it not to happen!

**Comment by Mynameisnotlenny** [comment]
> It looks like its just happening with the first 9 numbers i havent had it happen to me on anything higher! could be wrong and could just be lucky for it not to happen!

Could be right just had it occur again on number 9 I’ll post that clip soon, that’s another 87500 gone RIP

**Comment by Mynameisnotlenny** [comment]
Excuse the coughing I was ripping dabs but here is the clip of it occurring again on the number 9 

https://medal.tv/games/gta-v/clips/xTYCY93XJuqhd

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/290c16acf077ce407906cdb7f61c6a35978e856b fixes this issue.

**Comment by cxerq** [comment]
Tested this seems like it work! thanks for fixing!
