### ISSUE TITLE
getting priority when you crash or leave 

### ISSUE THREAD

**Issue by 22reece** [fkk-cz/noire-public#1133]
Ok i think there should be a priority thing implemented so if the player left the game less than five minutes ago they should get a priority pass so they can just fly back in straight away instead of them having to wait in a queue for trying to fix a bug by flying out and flying back in. this should also be the same for people who crash they should get instant priority back into the city as there game crashed causing them to lose there spot in the game i think this would be a great addition to the server.

**Comment by PeanutTheCop** [comment]
around a year ago this use to be a thing when you crashed

**Comment by fkk-cz** [comment]
There is already a grace period/timer that exists, which includes position saving for people who timeout in queue.
