### ISSUE TITLE
[Suggestion] Right-Click while driving unarmed causes forced 1st-person middle-finger emote that changes your perspective until you change it back manually

### ISSUE THREAD

**Issue by smokinate** [fkk-cz/noire-public#1143]
When driving a vehicle unarmed, the right-click default is to show the middle finger, which is fine, but it changes the perspective to first person, which is an issue, and also annoying when just driving. Often I find myself accidentally clicking right-click and messing up my perspective. The current fix is to try and not crash, then hit "V" (whatever your key-bind is) 3 times to reset your perspective back to what it originally was. I understand the purpose of this functionality is for drive-by accuracy when firing a weapon, but if it is easily done, then it should be done.

**Comment by smokinate** [comment]
### **Additional:**

When you use a phone as a passenger in a vehicle, this issue is repeated with the middle-finger showing up every time you click on something on the phone.

**Comment by fkk-cz** [comment]
Agreed, this is quite annoying when unarmed. I'll look into this.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/dc4e403798e90061668eafc68c601c5dd500e789 fixes this.
