### ISSUE TITLE
Vehicles in the water 

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire-public#1149]
so I died and the guy took my trailer and put it in the water now I have to wait for tsunami I was finna mine all day ik its a me problem but say if it goes in the water you can get it back from insurance right away ik if its used in a pursuit and they drove it into the water its a issue but if that's not the case then we should be able to get it back right away

**Comment by fkk-cz** [comment]
Vehicles that are (un)intentionally driven into the water by another player, or otherwise as a result of a bug, cannot and will not be recoverable. It's impossible to tell whether a vehicle is in water from server script, `IS_ENTITY_IN_WATER` is client-only for obvious reasons.

**Comment by IIBurntLuisII** [comment]
i see now it makes alot of sense from that stand point
