### ISSUE TITLE
White shirt blue pants "gang"

### ISSUE THREAD

**Issue by rustigibbons** [fkk-cz/noire-public#1159]
Something has to be done about this group, I and many others are running into these guys nonstop and they are constantly breaking rp, and acting like complete idiots committing KOS, amongst breaking other rules.  The one with the man bun consistently tells everyone he is "CLIPPING" moments so he has evidence and talks about how he is streaming it. I know i can not be the only one having these horrible rp interactions.

**Comment by TheBottomFragger** [comment]
> Something has to be done about this group, I and many others are running into these guys nonstop and they are constantly breaking rp, and acting like complete idiots committing KOS, amongst breaking other rules. The one with the man bun consistently tells everyone he is "CLIPPING" moments so he has evidence and talks about how he is streaming it. I know i can not be the only one having these horrible rp interactions.

Are you at least reporting this? Nothing will get done if people aren’t reporting it. Seems like you have met them several times, so hopefully you reported every time it happened

**Comment by fkk-cz** [comment]
GitHub issues are for reporting bugs, not for making player reports. Use the reporting channel in Discord.

**Comment by rustigibbons** [comment]
understood I apologize
