### ISSUE TITLE
125 and below

### ISSUE THREAD

**Issue by Rakeem21** [fkk-cz/noire-public#1160]
this area should be KOS for people that have flags and possibly just have a indicator at the top left saying High Crime Area or something like that.

**Comment by tythetanman** [comment]
125 and below… so the courthouse too… soooo realistic…

**Comment by Rakeem21** [comment]
MY BAD MAN i meant the 125 store and like the ghetto areas. apologies.

**Comment by Mynameisnotlenny** [comment]
> this area should be KOS for people that have flags and possibly just have a indicator at the top left saying High Crime Area or something like that.

Haven’t been flagged in a while but pretty sure that area is already KOS for gangs when the gangs decided on rules. This doesn’t apply to people with armbands though only to whitelisted gangs.
