### ISSUE TITLE
Slow phones

### ISSUE THREAD

**Issue by Buymefourlokos** [fkk-cz/noire-public#1165]
I’ve played a lot in this server, hundreds of hours and I know I’m not the highest in the server nor will I be but I would like to suggest a new phone script as this one is super slow/laggy and doesn’t have manny features, it would be nice to have a phone with investing/banking apps and runs smoothly.

**Comment by GoldBlockGames** [comment]
You can fix it by turning on fix UI lag in the fivem menu

**Comment by fkk-cz** [comment]
Try enabling this setting.

![image](https://user-images.githubusercontent.com/74131024/188127312-9cf9c67f-4b69-4423-86f6-476f94b8f48c.png)
