### ISSUE TITLE
UCL Safezone 

### ISSUE THREAD

**Issue by IIcey77** [fkk-cz/noire-public#1169]
So I left for a few months for work and when I got back I found UCL in a new place with no safezone, last I had played was 4 months ago when UCL was in Sandy with a safezone, was always super chill and if people had issues they took it elsewhere. 

I came back to the new one and it has no safezone. I’m not sure the reasoning behind that, but can we get one added back?

If EMS isn’t going to go to UCL then I think we can all agree (with UCL being a hotspot for players) it should have a safezone. It seems every time I go the past few weeks I witness several people getting killed, or I’ll roll up and find bodies on the ground, and if EMS is on you’re stuck waiting 10-15m to respawn.

**Comment by kinkybearcat** [comment]
I second this. I understand the abuse of a safe zone, but that goes for any safe zone not just UCL. Everyone knows no cops or EMS even go up north and that it is basically the wild west. Hunters are rarely lucky enough to get EMS to fly out there after being mauled by a mountain lion.

RDM/VDM, random shootouts, being robbed or even gang violence always finding its way up there. People will even set cars on fire while for sale with jerry cans. The same things happen just outside of PDM, but they at least have a safe zone along with active cops and EMS just around the corner. 

With a safezone, we can at least guarantee a safer transaction, and possible car meets where it makes the most sense and safety without the need for EMS or cops to arrive on scene.

**Comment by fkk-cz** [comment]
There are no plans to return the safezone back to UCL. This caused a ton of other issues when the location was Sandy Shores, and was responsible for a disproportionate amount of reports.

> People will even set cars on fire while for sale with jerry cans. The same things happen just outside of PDM, but they at least have a safe zone along with active cops and EMS just around the corner.

Setting vehicles on fire will not be stopped with an active safezone. The police do not conduct regular patrols at PDM specifically either.
