### ISSUE TITLE
Shooting out of a car while sending a text

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#1170]
So I was sitting in the passenger seat of a car, while I was sending a text my gun just start shooting!

**Comment by Ryannn5** [comment]
Same thing happened to me scared the crap out of me lol

**Comment by fkk-cz** [comment]
This will be fixed when the phone is updated.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/npwd/commit/35aaf9c6055eadb670e22bcf5b0fc0b1afdbe880 fixes this issue.
