### ISSUE TITLE
Clock in/ clock out Taxi

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire-public#1174]
I know this has been mentioned before, but would it be possible to add a clock in/clock out area at the taxi place?

**Comment by TheBottomFragger** [comment]
Also maybe remove the ability to call for taxi when you’re still in jail?

**Comment by jeanndabeann** [comment]
idk if me commenting on this reopens it but taxi doesnt have an actual off duty role so the clock out circle doesnt work :(((
