### ISSUE TITLE
Photo getting stuck on screen

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire-public#1177]
ik this feature was just added but when u click on pictures sometimes it gets stuck on your screen and you will have to fly out

**Comment by IIBurntLuisII** [comment]
when u make a picture larger on twitter i mean it has a high chance of getting stuck maybe there is a button to fix it idk

**Comment by fkk-cz** [comment]
This happens when clicking on an 'oversized' (close to, or larger than, your screen's native resolution) image. Shouldn't be an issue if you click on the phone behind the enlarged image?

**Comment by IIBurntLuisII** [comment]
would you be down to test it im not trying to fly out again

**Comment by IIBurntLuisII** [comment]
if you click on the picture on the phone yes it does close it
thx
