### ISSUE TITLE
Phone Camera Not Saving Photos

### ISSUE THREAD

**Issue by YeagerGTA** [fkk-cz/noire-public#1179]
Have cleared out most of the existing photos, when I go to take a new one it says unable to process request in a red popup.

**Comment by Buymefourlokos** [comment]
Same issue here

**Comment by fkk-cz** [comment]
Seems like a problem caused by https://github.com/project-error/npwd/commit/b437d5342564e4f299f425c4d2975e2d1cdf8d05. Looking into this.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/screenshot-basic/commit/9e30f97db609074891bb03287c6eff0616371066 and https://github.com/fkk-cz/npwd/commit/6fbdb92a3c40030d965e2a241a32cee978ea14c0 fixes this issue.
