### ISSUE TITLE
there is a issue with people stealing trailers

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire-public#1182]
if you lock your gooseneck and the keys and you lock it only you can connect to it even tho it has gotten rare it is still a issue because then i have to worry abt chasing them down and having a clip im just trying to mine and it gets yoinked

**Comment by fkk-cz** [comment]
Not a bug -- there is no way to prevent a vehicle from being attached to another trailer, regardless of whether you have keys or not.
