### ISSUE TITLE
Can we please get radio’s in the city 

### ISSUE THREAD

**Issue by Danny123372** [fkk-cz/noire-public#1187]
We need radio’s so you can talk to your friends all the time and plus it stops people from meta gaming and it is in every other city I’ve been in that why y’all should add it because it doesn’t hurt anyone it just makes it easier to talk to people so if you can add radios I would really appreciate it.

**Comment by TheBottomFragger** [comment]
Just gonna comment here since there’s already a lot of GitHub posts about this. They already mentioned that they won’t bring radios in 😢

**Comment by fkk-cz** [comment]
GitHub issues are for reporting bugs, not feature requests. Use the discussions channel on Discord instead.
