### ISSUE TITLE
Clothing! 

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#1188]
Is it possible when you add new clothing it doesnt remove the clothing item that was in the slot already! A new Sheriff clothing item was added yesterday and it removed a jumper that i know alot of people in the city used (including myself)

**Comment by fkk-cz** [comment]
GitHub issues are for reporting game bugs or issues, this doesn't appear to be either.

Clothing items are added by name and override an existing model or texture, or both. There is a spreadsheet of add-on clothing items by name and corresponding variation index, and attempts are already made at avoiding replacing clothing items that are currently added or in use. Unfortunately this happens from time to time and nothing can be done to completely eliminate this problem.
