### ISSUE TITLE
Radio Bug for AMR + Possibly LEO

### ISSUE THREAD

**Issue by RangerThrawn** [fkk-cz/noire-public#1192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently , if you choose to change your job at job center rather than clock out ( because you plan to go from AMR to Up -N -Atom for instance, like my case,  then the radio is removed from your inventory but it is still a love function - 

### Expected Behavior

The radio should no longer be linked to me once my role changes.  Currently I can continue to hear AMR radio traffic despite not being in the role ( technically I could abuse this to hear people/supervisors talk about me etc) 

### Steps To Reproduce

Clock into AMR , go to job center , change job  then attempt to use radio   ( 

### Anything else?

Thank you

**Comment by fkk-cz** [comment]
> Currently , if you choose to change your job at job center rather than clock out ( because you plan to go from AMR to Up -N -Atom for instance, like my case, then the radio is removed from your inventory **but it is still a love function** -

What?

**Comment by Ell34** [comment]
> > Currently , if you choose to change your job at job center rather than clock out ( because you plan to go from AMR to Up -N -Atom for instance, like my case, then the radio is removed from your inventory **but it is still a love function** -
> 
> What?

Pretty sure they're saying if you switch whitelists at job center instead of clocking out and then switching, you can still access the radio with the shift + f3 command. It's also and issue with VU.

**Comment by RangerThrawn** [comment]
Yes exactly , that was meant to read “live function”   But yes , if you
change jobs instead of clock out THEN change jobs , the radio (despite
physically being removed)  is very much still working , at receiving audio
and speaking audio into

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/9be2e194661ae2c7c20599a7d99714e76e11d3f6 fixes this issue.
