### ISSUE TITLE
[BUG]: <You cant search people>

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire-public#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

you cant search people when you frisk them it stops the animation then you get stuck you have to press x to un get stuck

### Expected Behavior

im guessing it would show the gun they have on them

### Steps To Reproduce

go to search someone

### Anything else?

hopefully it can get fixed before next tsunami bc if not you cant rob people for the whole day

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/3cb23e0aaeacfec2ca870624aeeebb475898b123 fixes this issue.
