### ISSUE TITLE
[BUG]: Vanilla Unicorn Whitelist issues 

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During our 2 day anniversary event (in June), we noticed an issue with the whitelists. On Wednesday the 29th, bartenders were able to see the prompt to dance on the pole, where those with the strippers were not. Strippers were able to use the bar, and bartenders were not. The bouncer whitelist was working fine that day. On the 30th, Bouncers were not able to see the prompt to get radios. Only one out of the 2 bartenders working were able to see the prompt for the bar. Those with the stripper whitelist were able to see the radio prompt, and bouncers were able to use the pole.

I also noticed and issue with the CEO menu where I wasn't able to see the prompt to open it unless I flew out.

### Expected Behavior

all that shit above to work lol

### Steps To Reproduce

idfk

### Anything else?

no

**Comment by Ell34** [comment]
I also cant access the CEO at all anymore, even if I've relogged.

**Comment by Ell34** [comment]
Bumping this as I would like to get VU up and running again

**Comment by fkk-cz** [comment]
Most job-related markers and actions have been fixed. Need to make a map edit to add metal detectors in front for security purposes. https://github.com/fkk-cz/noire/commit/e17575c43552e6073799d28972a98792460edb00
