### ISSUE TITLE
Yacht no longer functional 

### ISSUE THREAD

**Issue by RangerThrawn** [fkk-cz/noire-public#1201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I suspect this is undintended as it happened with the drug re-work, but wasn’t mentioned as far as I can find…. 

### Expected Behavior

Normally the yacht has some small-medium loot spots - which attracts occasional
Traffic to the yacht (hostile zone)   This creates great criminal Rp moments / conflicts / scavenging that I truly and deeply miss … can we get it back ? 

### Steps To Reproduce

Visit the yacht, it's a ghost town now :/ 

### Anything else?

I put this under bugs because I really didn’t think it was intentional that it stopped…. Sorry if it’s intended , but I still would love for this to come back :-)  thanks

**Comment by RangerThrawn** [comment]
Anybody??

**Comment by fkk-cz** [comment]
This was intentional, not a bug. The yacht caused issues and was a large source of player reports, people seemed to complain a lot about getting shot and killed there -- despite it being a hostile area.

**Comment by RangerThrawn** [comment]
Major bummer…

Thanks for your time
