### ISSUE TITLE
[BUG]: "Standing Dead" Becoming more frequent

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire-public#1202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On AMR we have seen an increase in what are called "Standing Dead" bodies when we arrive on the scene of a distress signal. The only way we are able to take care of the patient is to either put in an assist and hope a staff member is able to respond or kick them so they "are dead" and we are able to pick them up and transport them. While "standing Dead" the affected person appears if they are just standing there in their head which also makes it impossible to determine if they are the dead person or not unless they /me and tell us that way. 

### Expected Behavior

A dead person should be a flopping body on the floor that AMR can attach to a stretcher. Unsure how else to describe the expected behavior..

### Steps To Reproduce

Unsure ways to reproduce this. We arrive on scenes to this daily and I know some of the staff who respond to assists have seen this as well.

### Anything else?

If this is an issue purely from people flying out and back in dead just let me know and I will adjust AMR policy to reflect such. fly in dead used to spawn at specific areas of the city and we were able to identify them at the time. If these standing dead are also fly in dead people it would be good to know.

**Comment by fkk-cz** [comment]
> While "standing Dead" the affected person appears if they are just standing there in their head which also makes it impossible to determine if they are the dead person or not unless they /me and tell us that way.

If a player is dead, they are unable to use /me. I suspect most of these issues happen when players spawn in dead, maybe caused by fall damage?

**Comment by fkk-cz** [comment]
This appears to be fixed -- there seem to be no more assists for this issue.
