### ISSUE TITLE
[BUG]: PDM Menu gets stuck if you don't have a drivers license.

### ISSUE THREAD

**Issue by No-Yes1** [fkk-cz/noire-public#1204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you don't have a drivers license and attempt to test drive a vehicle, the PDM menu gets stuck and the only way to fix it is to fly out and fly back in.

### Expected Behavior

Menu shouldn't get stuck

### Steps To Reproduce

1. Don't have a driver's license.
2. Go to PDM and find any vehicle
3. Attempt to test drive and wait for the notification to state you must have a driver's license to test drive
4. Menu gets stuck, and you can't open/buy/test drive any vehicles until you fly in and out.

### Anything else?

Clip: https://streamable.com/xrt6et
Photo: 
![image](https://user-images.githubusercontent.com/79383480/196034727-319ae642-898a-4f0e-b28b-f113235be9d9.png)

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/1dd01923b134b3212ad147c01352fc182ae41ed7.
