### ISSUE TITLE
[BUG]: not being able to interact/see inventory.

### ISSUE THREAD

**Issue by Buymefourlokos** [fkk-cz/noire-public#1205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have no idea if this is a fivem/pc or server issue. Most of the time I’d have to leave and join back multiple times due to my 3rd eye/inventory/house inventory/any kind of menus like garage or house/or anything of that sort not working.
I can navigate through it and still use the options but I’d have to do it blindly because I can’t see the menus as I said. To be honest I have no idea if I described correctly but I will definitely try to get a video if the person handling this issue doesn’t understand it.

### Expected Behavior

I just expected everything to work how it used to work a few days ago

### Steps To Reproduce

-have to write here

### Anything else?

-have to write here

**Comment by fkk-cz** [comment]
This doesn't seem like a server-specific issue, no one else has reported this and without any further information, nothing can be done. Try reinstalling a clean copy of GTA and FiveM, probably a client issue.
