### ISSUE TITLE
[BUG]: <Custom title here>

### ISSUE THREAD

**Issue by Gmoney7** [fkk-cz/noire-public#1207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

trailer glitched and detaches but follows you around. here is a clip: https://streamable.com/yjivd9

### Expected Behavior

im expecting it not do that

### Steps To Reproduce

Idk it happens sometimes, idk how it happens tho.

### Anything else?

no

**Comment by fkk-cz** [comment]
This is a GTA/FiveM issue related to attached trailer syncing, not a server-specific issue. There is no fix for this at the moment, others have reported this issue in the past.
