### ISSUE TITLE
Cars getting stolen because of auto theft while in mines or safezone 

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire-public#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was mining and the guy ran up and took my titan even though I'm in the mines you shouldn't be able to do that my friend thinks its bc the car gets pinged while your outside the safezone 

### Expected Behavior

you shouldn't be able to hotwire in a safezone 

### Steps To Reproduce

get a auto theft and if it gives you a car outside of a safezone and they go into one it still allows you to hotwire it

### Anything else?

.

**Comment by fkk-cz** [comment]
There is no way to test whether a point is in a safezone server-side, as safezones are entirely a client script. This could be partially mitigated by excluding vehicles from the available pool if the driver enters a safezone. Not a perfect solution though as vehicles could still be rammed out, or parked in inaccessible areas (behind locked gates) which cannot be determined from server script either.
