### ISSUE TITLE
trailers getting stolen from the mines 

### ISSUE THREAD

**Issue by IIBurntLuisII** [fkk-cz/noire-public#1212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

people will just drive up and take your trailer there is zero ways to get it back they basically get it for free and there stealing your stuff

### Expected Behavior

maybe make it to where if they dont have keys to the trailer they cant connect to it that would be the best way i could think of it working

### Steps To Reproduce

just go to the mines and steal someones stuff watch how easy it is 
it shouldnt really work like that

### Anything else?

please mr fkk

**Comment by rich1212122222222222** [comment]
hi

**Comment by fkk-cz** [comment]
You created the same issue https://github.com/fkk-cz/noire-public/issues/1182 a month ago. Stop bringing up trailer or mining-related issues -- both are planned to be discontinued and removed when suitable replacement jobs are thought of and completed.
