### ISSUE TITLE
[BUG]: AMR Distress working for some people when AMR is clocked in.

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire-public#1215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As AMR I have seen an increase in people informing me when they died that they did not get a prompt to hit their G muscle to call for EMS. 

### Expected Behavior

Anyone who has died (Minus Comserv Beach or currently in a Jail Sentence) Should be able to prompt their Distress signal for an AMR unit to be dispatched. 

### Steps To Reproduce

Unsure. 

### Anything else?

If the current system is broken or too glitchy maybe we could look into a new version.

**Comment by Bountyrogger** [comment]
If the current Hit G muscle doesnt work maybe we could look at a /callEMS to be used (Only allowed when dead maybe)

**Comment by fkk-cz** [comment]
Distress signal prompts are only available 30 seconds after dying, this was done to help prevent excessive call spam and to make it easier for AMR to locate bodies. No issues as far as I'm concerned.
