### ISSUE TITLE
[BUG]: <scammed at casino>

### ISSUE THREAD

**Issue by zbjw521** [fkk-cz/noire-public#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i went to gamble at the casino and the dealer took my chips but didnt give me cards

### Expected Behavior

give me cards

### Steps To Reproduce

go in casino 
play blackjack

### Anything else?

https://streamable.com/xvyql1

**Comment by fkk-cz** [comment]
Looks like you bet too close to the round being closed out. Not worth fixing, as that could be explained by network delay or latency. Also, refer to our policies re: casino issues - https://github.com/fkk-cz/noire-public/discussions/985.
