### ISSUE TITLE
[BUG]: Stretcher Issues

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire-public#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So there are currently 2 stretcher issues happening for AMR.

1.  sometimes when we pull our stretcher out of the garage we are teleported under the map around Postal 540 for whatever reason (Can happen at Pillbox or Zonah and I will link a clip below)

2. we are still having issues where the stretchers will eventually break causing us not be be able to pick it up (The only fix being to fly out and back in which is an issue during peak hours for any of our staff without a ticket). this was an issue from before and your temp fix was to attach at the hip at all times until a fix could be made. Unsure if a fix was ever made or if stretchers were just reverted to be able to be picked up again.

### Expected Behavior

1. When pulling our stretcher out at a Hospital we should be found at the Vehicle Garage Spawn point and not be stuck under the map. 

2. Stretchers shouldn't be bugging out causing them to be unable to be repicked up again (It doesn't happen every time and some Staff report it happening more than others.)

### Steps To Reproduce

Issue 1.

1. Spawn a stretcher in the garage and there is a chance of being spawned under the map (Not every time but will link a clip below)

Issue 2.
1. Spawn a Stretcher and pick it up and stage it either in your Ambulance or near your Tahoe/Explorer.
2. Seems to be from reports if you leave it alone for an extended period of time (No calls so just waiting at the Hospital) There is a chance of bugging out and the legs will extend into the ground and be unable to be picked up.

Both of these issues are infrequent cases so its hard to force it to replicate.

### Anything else?

This is the link for Issue 1.

https://medal.tv/games/gta-v/clips/GvYEWGl-DQKRf/d1337Go7g75z?invite=cr-MSx4WlUsOTI5OTk5NTIs

**Comment by fkk-cz** [comment]
I was unable to recreate the stretcher spawning issue. Can you try spawning a job vehicle at the same time as another player? Coordinate it via radio or something.
