### ISSUE TITLE
3030 Trailer spawn point

### ISSUE THREAD

**Issue by Daniiel35** [fkk-cz/noire-public#1218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i attempt to complete a gas run, the trailer spawns in & flips over on its side & can't be moved or flipped back over, this has only been in issue for about a week, unsure why this is happening now

### Expected Behavior

Move spawn location of trailer to another location so it doesnt flip

### Steps To Reproduce

starting a gas run, the trailer will spawn on its side 

### Anything else?

![Screenshot 2022-10-31 151615](https://user-images.githubusercontent.com/95129567/198952423-220ee4b9-cda4-42aa-aff1-58b991afd6db.png)

**Comment by mackenzzie** [comment]
This happens to me almost everytime as well at other stations. Also noticed a couple days ago this started but when I attach the Tesla truck to the tank it doesn't move, almost like it's bricked but when I unattach it's completely normal.  Not sure if other people are having this same issue as well

**Comment by fkk-cz** [comment]
This was introduced when trailer spawning was switched to server-side. Probably the client unable to set the vehicle correctly on all legs. Worth looking into whether it's possible to spawn both vehicles already attached.

**Comment by Daniel9935** [comment]
This could fix the issue as the trailer isn't needed to complete the gas runs, it would just help when finishing the job to help it disappear

**Comment by LactatingWalrus** [comment]
Would that not make it worse as the truck can't pull the trailer forward? I have the same issue going on but i also can't pull the trailer when attached. It can be reversed but it blocks access to the gas station either way.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/ec09c57df9aa7fcab40789e4f76d58b9b0ca30a6 fixes this issue, reverted back to RPC trailer creation which spawns the vehicle on the ground properly.
