### ISSUE TITLE
[BUG]: <Custom title here> not able to die

### ISSUE THREAD

**Issue by Gmoney7** [fkk-cz/noire-public#1220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

so what happened was i was walking up mount chiliad just out of curiousity and when i wanted to get back down i fell and when i fell i just couldnt die, it said i had 0 health but there wasnt any black screen and when i flew out and in to see if it would solve the issue i just respawned without losing my stuff

### Expected Behavior

i expect me to die or fully fatal from that with a black screen

### Steps To Reproduce

not sure since this came out of the blue 

### Anything else?

https://streamable.com/ld9nsi clip of what happens when i "die"

**Comment by fkk-cz** [comment]
A few people are reporting this issue, probably caused by the changes to the death handler module. Reverted https://github.com/fkk-cz/noire/commit/79de354d364da3a99bf7d7d834d553491fe5b7fb for now.
