### ISSUE TITLE
[BUG]: TV Issue (2 tvs displaying two different pieces of content)

### ISSUE THREAD

**Issue by mehvexitry** [fkk-cz/noire-public#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried out the channel that was already on the /tv.. which was cops. It worked great. I got excited and headed to my other room, played a unique YouTube link. It worked too. Shortly after, both screens shut off, no longer showing “no signal” either. 

### Expected Behavior

I expected both televisions to display the content. In retrospect, I know I was asking too much of the young plug-in. 

### Steps To Reproduce

1. Within an enclosed area, fairly close together, have two TVs (listed as “flatscreen TV” in “FURNITURE UI.” 2. On one screen display the “COPS” channel. 3. On another screen, (nearby of course) display a YouTube link of your choice, 4. Walk back and forth, watching both of the screens. 5. Observe the results. 

### Anything else?

N/A

**Comment by fkk-cz** [comment]
I don't understand what the issue here is? Why would two separate TVs play the same video?
