### ISSUE TITLE
Cannot pull Toyota Supra GR out of garage

### ISSUE THREAD

**Issue by ChirpyMedusa** [fkk-cz/noire-public#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the last few days, I have not been able to pull my Toyota Supra GR out of my garage. Whenever I try and do it, nothing happens and it disappears from my garage. I believe someone had a similar issue a few days ago with another vehicle that was resolved but I could not find it. This only started happening in the last week. 

### Expected Behavior

Cannot pull this vehicle out from any garage at all. 

### Steps To Reproduce

1. Go to garage
2. Select Toyota Supra GR
3. It then disappears from garage and is sent to insurance

### Anything else?

No

**Comment by woody67890** [comment]
Same issue here. Tried twice in 2 days. Tried getting it from my personal garage. When selecting it says something like ‘vehicle stored’ and then if I go into my list of vehicles again, it’s no longer listed

**Comment by fkk-cz** [comment]
Stream files were removed because the vehicle's liveries are oversized. Should be working now.
