### ISSUE TITLE
[BUG]: <The Door to galaxy club Doesnt work any more>

### ISSUE THREAD

**Issue by Ge0rge122** [fkk-cz/noire-public#1223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the door doesnt work anymore and is acting like there is a wall there

### Expected Behavior

the door to work normaly

### Steps To Reproduce

when you try to walk through the door it doesn't work!

### Anything else?

https://medal.tv/games/gta-v/clips/HONpO9lhCjOQN/d1337aZhoZsZ?invite=cr-MSxqd2QsMTI4MDM5OTcxLA
This is an example of the bug.

**Comment by fkk-cz** [comment]
Duplicate/conflicting .#bn files from the cinema caused issues. Removed the newer files and seems to be fixed.
