### ISSUE TITLE
[Suggestion]: Add a safezone to sanitiation job site

### ISSUE THREAD

**Issue by a-oliveira7** [fkk-cz/noire-public#1228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You go to sanitation job site, and there is no safezone, so your car ends up not being there when you come back 99% of the time. Truck driver + Mining have their job sites as safezones

### Expected Behavior

To have a safezone at sanitation job site, even a parking lot if not the entire thing

### Steps To Reproduce

1. Go to Sanitation
2. Walk in
3. Leave your car locked
4. Go do a job run
5. Come back, and do another job run
6. 99% of the time you car will be stole or despawn after that 2nd one

### Anything else?

A few people have also expressed interest

**Comment by residentalyeti1** [comment]
its possible that vehicles are just despawning when at sanitation

**Comment by a-oliveira7** [comment]
> its possible that vehicles are just despawning when at sanitation

Yeah I definitely agree. It's not like it's 100% needed but still, I just think it would stay consistent with other job sites and be helpful. Safezone helps with more than just cars getting stolen

**Comment by fkk-cz** [comment]
Safezones have nothing to do with your vehicle despawning. Sanitation is also no longer a job.
