### ISSUE TITLE
Porsche GT RSR

### ISSUE THREAD

**Issue by xLoMein** [fkk-cz/noire-public#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vehicle has an average acceleration with an unkown top speed because when Im driving on freeways, The car cant kick into 6th gear, and so the car hasnt gone over 170

### Expected Behavior

I was really hoping that there would be a way to either increase its acceleration or top speed by a noticeable amount, or maybe even increase both slightly 

### Steps To Reproduce

.

### Anything else?

.

**Comment by fkk-cz** [comment]
Use the [vehicle repo](https://github.com/fkk-cz/noire_vehicles) for this.
