### ISSUE TITLE
[BUG]: Stuck in trunk animation

### ISSUE THREAD

**Issue by aytexii** [fkk-cz/noire-public#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I enter my trunk it will sometimes not load my trunk inventory. Whenever this happens and I try again to open my trunk, my game will get bugged. I cannot move, go into settings, talk, anything.. unless I hold down the alt button. But even then I cannot sprint, sell mined items, etc..

### Expected Behavior

Enter the trunk and retrieve items from the trunk with no issues or bugs.

### Steps To Reproduce

1. Enter the trunk (preferably with a trailer or a vehicle on a trailer)
2. Re-enter the trunk if it doesn't load
3. Game stuck with alt bug

### Anything else?

Nope

**Comment by fkk-cz** [comment]
> Whenever I enter my trunk it will sometimes not load my trunk inventory. Whenever this happens and **I try again to open my trunk**, my game will get bugged. 

Sounds like this issue is occurring when players in an active animation of opening a trunk attempt to open the trunk again, causing the tasks to get stuck. Adding a timeout for the two tasks involved should help.
