### ISSUE TITLE
[BUG]: GoPostal drop off bug

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#1232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the house at postal 718 doesnt have a mailbox, resulting in you not being able to finish your run and get paid. 

### Expected Behavior

To have a mailbox

### Steps To Reproduce

Do the GoPostal Job

### Anything else?

n/a

**Comment by jeanndabeann** [comment]
this is my house and honestly if we could just remove it from the route that would be even better. There is not physical mailbox outside of it which is what i think is causing the issue. Ive now run into 2 people on 2 separate days trying to do the job, who have told me it doesnt work. This then is causing them to have to fly out and in to reset themself or switch jobs(not sure if this one works) so they can get a new job which results in them losing the money cause you dont get paid till the end.

**Comment by fkk-cz** [comment]
Is the mailbox under the ground or does it just not exist?

**Comment by Ell34** [comment]
> Is the mailbox under the ground or does it just not exist?

Does not exist

**Comment by fkk-cz** [comment]
The postal you provided has a mailbox that is underground, along with others. Rockstar included these props in the world but failed to bring them above ground for some reason.

**Comment by fkk-cz** [comment]
Removed two locations where the mailbox was underground. Leaving this open for the time being in case others are discovered.

**Comment by LUCCI23** [comment]
3 known locations i have experienced in game for Go Postal
1st location is in sandy shores at the tattoo parlor the mail box dosen't appear but gps location marker shows tattoo parlor
2nd location is in Paleto Bay block 1025 2nd house in no indicator on top of the mailbox but gps location shows that house
3rd location 700 SW Normandy Dr mailbox is there but no indicator gps shows that house

will continue to update upon finding anymore locations

**Comment by fkk-cz** [comment]
Please provide screenshots in addition to postal codes, it's hard to tell which house you're referring to based on a description alone.

**Comment by LUCCI23** [comment]
I am not home or on at the moment, but i will gather that for you asap

**Comment by Ell34** [comment]
> Please provide screenshots in addition to postal codes, it's hard to tell which house you're referring to based on a description alone.

![Screenshot 2022-11-30 192018](https://user-images.githubusercontent.com/92474477/204936081-ee44fa38-3769-4faf-bd34-91117eb45bac.png)
![Screenshot 2022-11-30 192037](https://user-images.githubusercontent.com/92474477/204936101-84fae860-1b42-4184-b391-9fdaf07a026c.png)

Just discovered this one

**Comment by Ell34** [comment]
> 

![Screenshot 2022-11-30 211216](https://user-images.githubusercontent.com/92474477/204949414-046cc0cb-895b-459d-9b81-3baec166673a.png)
![Screenshot 2022-11-30 211240](https://user-images.githubusercontent.com/92474477/204949424-882ee266-3493-4250-8161-39ac7da4e2f6.png)

**Comment by fkk-cz** [comment]
Job locations that do not have a valid mailbox for whatever reason will automatically be skipped once a player drives within a fixed range. Mailboxes that are underground will now be usable even if the prop itself is not visible.

Also increased pay per stop (PPS) by approximately 8%.
