### ISSUE TITLE
Cockatoos + Other Clubs

### ISSUE THREAD

**Issue by jeanndabeann** [fkk-cz/noire-public#1233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have briefly talked about things that the clubs need to help them run a tad smoother, I'm sure other owners will have some input as well. I wanted to make a issue about this so we have it all in one place everything we need. Other owners feel free to add below in bullet form.

### Expected Behavior

- Security the option to Grab people.
- Cockatoos: Lighting inside, not sure if its something that can be fixed but it is VERY bright
- Cockatoos: If someone jumps over the bar, the register tazes people and about 90% of the time kills them. If we could get a barrier around it that would stop the plus stop the issue of people being trolls and jumping over where the bartenders are.
- Radios for Workers, locked to one channel, only works in the surrounding area of the club? Maybe they disappear from your pockets once you leave the area.
- Bartenders/CEO's invoicing
- Storage for drinks that have already been made, Currently there is a storage system that holds the ingredients, but if you take the ingredients out, you cant put them back. If you accidentally take something out or make extra drinks there is no where to store them. This would just help for being more prepared as well

### Steps To Reproduce

N/A

### Anything else?

I can get a clip of the register tasing and killing if needed.

**Comment by tythetanman** [comment]
Being able to put drinks or ingredients in the storage would be beautiful instead of having to go to another location like your house to store what you pull out or make.
