### ISSUE TITLE
flipped vehicles 

### ISSUE THREAD

**Issue by Jakebeastt** [fkk-cz/noire-public#1234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when you flip your car should should be able to peek at it and flip it back . Just a suggestion. 

### Expected Behavior

maybe having an option to flip it?

### Steps To Reproduce

none

### Anything else?

none

**Comment by Hesh77** [comment]
You think a normal sized person should be able to just flip a 1300 kilogram vehicle?

**Comment by ImDead48** [comment]
Can any normal person in the wood be able to lift 1300 kilograms? (2880 pounds)
