### ISSUE TITLE
Metal Detector Bug After Update

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the medal detector was fixed, I've noticed an issue and others have with the metal detector randomly beeping out of the metal detecting zones and when you don't have one on you. I'm currently driving around and I constantly hear it. 

### Expected Behavior

Not to randomly beep

### Steps To Reproduce

Just listen

### Anything else?

no

**Comment by tshives26** [comment]
Same. I was noticing it still when I threw my metal detector on the ground and left it as well. The beep that haunts for eternity!

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/db6fb24250f96b3ad6c820379371710fac151fef fixes this issue.

**Comment by MrThrawn** [comment]
Yes. At first I noticed it happening when you would enter and exit the spawn radius of the chests , but then it would periodically happen down south in the city as well  it's the same beep that emits when a signal is found and the blue bars begin guiding you in the detector , also the same beep as when you pull out and out away the detector , or enter a vehicle while equipping a detector
