### ISSUE TITLE
[BUG]: <VPN or Proxy connection not allowed>

### ISSUE THREAD

**Issue by helloqueygs** [fkk-cz/noire-public#1237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I load into the server and get stopped telling me I have a VPN or proxy connection enabled when thats not the case. I'm assuming   it's a false positive with your checker service.

### Expected Behavior

Load in fine like the other times

### Steps To Reproduce

1. Make sure you aren't using a proxy connection or vpn
2. launch Fivem
3. Load into the server
4. wont load (vpn error)

### Anything else?

![VPN Error](https://user-images.githubusercontent.com/65980728/207654305-7a13aeaa-e9e1-4f21-ae15-18231433754d.png)

**Comment by fkk-cz** [comment]
Temporarily disabled the service for now -- a few people recently have been encountering this false positive issue.
