### ISSUE TITLE
[BUG]: You can fall thro one of the hospitals walls at 507

### ISSUE THREAD

**Issue by Plasre** [fkk-cz/noire-public#1242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you run into one of the outside walls of the 507 hospital you will fall thro it into the underground garage
![image](https://user-images.githubusercontent.com/121388147/209470001-c0e28fbb-727a-42db-9c4a-845725461eb0.png)

### Expected Behavior

IF you ran thro that wall you will fall into the garage bellow and youll need to go into first person to see where you are.

### Steps To Reproduce

1. Get to the hospital.
2. run to the wall in the picture 
3. Run at the wall
4. Boom your in the garage.

### Anything else?

You must go into first person to escape as if you in the third person you wont be able to see and it will look like your under the map

**Comment by fkk-cz** [comment]
Fixing this will require a complete replacement of Zonah hospital, which is not planned at this time.
