### ISSUE TITLE
[BUG]: Dog Walking Job Bug

### ISSUE THREAD

**Issue by Ctolding69** [fkk-cz/noire-public#1243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you get to the house, as soon as the dog comes out of the house it says You have lost track of the dog... and cancels mission. 

### Expected Behavior

Just to be fixed, was working a day ago. 

### Steps To Reproduce

I'm not sure what this means lol

### Anything else?

No just letting y'all know abt the bug and hopefully you guys can get to it soon! Merry Christmas

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/d1ba5096939d070f22549ef53ba9dcdca4343b08 fixes this.
