### ISSUE TITLE
New Courthouse at 506

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#1246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Gabz | Townhall](https://fivem.gabzv.com/package/5127312[](https://fivem.gabzv.com/package/5127312) )

I’ve also purchased the MLO to make it easier.

  Looking to properly suggest a new location for 142 and 211 courthouses:  142 court is connected to the sheriffs department that is a pro whenever it does come to the location, but probably the only pro.  With this courthouse located at 506 you can basically completely eliminate the need for 211 courthouse and have that brought to this location, and it’s in the middle of a major PD location and a major hospital. 
  
But the biggest perk about moving and going to this location there are more than five private rooms that can be utilized for different things from meetings to attorney speaking with clients to the building also having holding cells, like the last two court locations.   Possibly also put it to where you can have the ability to be able to get your gun and hunting licenses here as well and boating in one location while not eliminating the other current locations to obtain those licenses (at the entrance podium)

Then put the boss menu for myself in a designated office that is just locked for judge only so there is a private office like 585 had.

https://youtu.be/q_b3C290taE

### Expected Behavior

An active department that’s in close proximity of the courthouse with a active medical center that is nearby for realistic needs and in a area of the city that could be populated more than just medical needs. 

### Steps To Reproduce

Moving property from one building that does not have private meeting rooms in areas for clients to speak with attorneys to an area that has the adequate LEO staff in area. 

### Anything else?

Can provide the purchased MLO asap.

**Comment by MrThrawn** [comment]
Golden idea!

**Comment by cxerq** [comment]
Like Another thing that would be useful along with this new Court House, Would be a way for court staff to move people from a cell to a room when no cops are around so they can talk to there lawyers without people talking over there conversations!

**Comment by tythetanman** [comment]
I believe that’s definitely a massive need. Especially whenever I open court at random times in those random times there’s a very high percentage that there’s no cops online.

**Comment by fkk-cz** [comment]
Courthouse is added, thanks for finding & suggesting this.
