### ISSUE TITLE
[BUG]: <Not getting paid as promoter>

### ISSUE THREAD

**Issue by Jakobsen2008** [fkk-cz/noire-public#1247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I placed like 30 posts and I got paid like 5k and every 30 posts I’m getting paid and yesterday I got paid for every post that I placed.

### Expected Behavior

I expected that I got paid for every post I made like yesterday.

### Steps To Reproduce

Idk

### Anything else?

Nope

**Comment by noyeahsure** [comment]
this is not a bug. this was implemented alongside promoter being direct bank payment now, it no longer gives money every job, but after a certain number of jobs done.
