### ISSUE TITLE
[BUG]: Dog Walking Bug again

### ISSUE THREAD

**Issue by Ctolding69** [fkk-cz/noire-public#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The job is no longer broken in the sense that it cancels as soon as it starts, but sometimes the dog will be frozen @ the start and you have no way of getting him to move. I have figured out sometimes hitting them w a snowball fixes it. Also randomly during the walk sometimes the dog will freeze like that.

### Expected Behavior

Just a fix

### Steps To Reproduce

?

### Anything else?

Just need it fixed thx

**Comment by fkk-cz** [comment]
Not sure what causes this. I've seen the dog freeze in the middle of the assigned task, usually walking around should unfreeze the ped. Marking this until it can be fixed.

**Comment by PsychoticCore** [comment]
If you kick him once he'll start walking again, only fix I've found so far

**Comment by Ell34** [comment]
> If you kick him once he'll start walking again, only fix I've found so far

also works for me

**Comment by Raynebowkitty** [comment]
now being unable to square up or hit outside how will people get the dogs out of being frozen without killing it or causing it to attack

**Comment by noyeahsure** [comment]
i am 90% sure that unable to hit thing was an accident that was implemented with tweak(cl): disable targeting in gunstores - fkk-cz with the problem being it technically thought everywhere, even outside was the gunstore, think it might be fixed on reset w this in repo updates. fix(cl): interior check for disabled targeting - fkk-cz
