### ISSUE TITLE
[BUG]: GUN STORE SALES CLERK IS KILLING

### ISSUE THREAD

**Issue by CjSSB13** [fkk-cz/noire-public#1250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

THIS NEEDS TO BE FIXED, EVEN IF YOU DONT HAVE A GUN IF TOUCH HIM BY ACCIDENT U AUTOMATICALLY DIE, THIS NEED TO BE FIXED WE HAVE LOST GUNS TO THIS BUG!

### Expected Behavior

MAKE IT WHERE WE DONT GET SHOT OUT OR DIE FOR NOTHING

### Steps To Reproduce

dsadsadasdsad

### Anything else?

NOTHING ELSE

**Comment by fkk-cz** [comment]
Gunstore clerk behavior now uses the same logic as the guards, which was adjusted and only shoots at people attacking or locked on to other peds. Victims of random people punching will no longer be killed.
