### ISSUE TITLE
THE NEW GUN STORE CLERK IS KILLING FOR LITTLE TO NO REASON

### ISSUE THREAD

**Issue by Latlepod** [fkk-cz/noire-public#1251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

THE CLERK IS WAY WAY TO SENSATIVE TO ANY ACTIONS PLAYERS DO. HE KILLS YOU FOR LITTLE TO NO REASON LIKE EVEN ACIDENTALY RIGHTCLICKING NEAR HIM WILL CAUSE HIM TO SHOOT YOU.

I HAVE LOST GUNS AND TIME BY THIS AND I THINK THE CLERK IS A GOOD ADDITON BUT WHEN IT IS THIS SENSATIVE ITS BETTER WITHOUT HIM.

### Expected Behavior

THE WAY IT SHOULD BE IS THE ONLY TIME HE SHOOTS YOU IS WHEN YOU HAVE A WEAPON OUT. AND THERE SHOULD BE A TIMER FOR WHEN HE STARTS SHOOTING LIKE 5 SEC WARNING TIME.

### Steps To Reproduce

1. WALK IN THE STORE
2. ACIDENTALY PULL OUT GUN 
3. DIE

### Anything else?

THIS IS A CLIP THAT HAPPEND TO ME THAT SHOWS THE EXTREMLY SENSATIVE NATURE OF THE CLERK.

https://medal.tv/games/gta-v/clips/OqIi2ct9HG89J/d1337LkZrv0G?invite=cr-MSx4Q2YsMTU5ODkwMzEwLA

**Comment by noyeahsure** [comment]
there is already an issue open for this and there is no need to have caps of for all of this

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/1250
