### ISSUE TITLE
New Jail MLO

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#1252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A attempt to update the jail system for the city. 
includes a visitation section and different areas on top of the current prison system, but more interiors to expand options for further role-play in the prison system.

### Expected Behavior

Expanded role-play, and it comes from the same type of company that brought the new courthouse and pillbox

### Steps To Reproduce

https://fivem.gabzv.com/package/4724793

### Anything else?

Hopefully this does help the prison system

**Comment by styxh** [comment]
if we're getting a new jail i think we need one with a new interior and exterior entirely.

**Comment by jeanndabeann** [comment]
https://www.youtube.com/watch?v=IaBDsc_Yrik

This is a script for prison work and stuff with a new interior as well it seems like. But i agree with Styx, we need a new interior completely for more to do

**Comment by jeanndabeann** [comment]
https://www.youtube.com/watch?v=Bog1moLythc
This one looks cool too, unsure if its the one used for he video above but i like it
