### ISSUE TITLE
New furniture UI

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Furniture is good in the city, but this is for a update to part of the city that has not been updated in more than a year and small housing adjustments. 

### Expected Behavior

Currently small errors whenever you’re placing furniture and the total type of furniture. Improvements to go along with the use of the television in homes as well.

### Steps To Reproduce

Just put down furniture

### Anything else?

[ModFreakz: Furni v3 - FiveM Scripts | Modit.store](https://modit.store/products/mf-furni-v3)

[ModFreakz: Housing v3 - FiveM Scripts | Modit.store](https://modit.store/products/mf-housing-v3)

**Comment by simsomsim22** [comment]
![image](https://user-images.githubusercontent.com/122949991/213064956-5a6b8219-324e-4414-a5e9-3289da4bc7ff.png)

Funny. [https://github.com/fkk-cz/noire_vehicles/blob/master/DATA/f250dot_data/vehicles.meta#L7](url)
![image](https://user-images.githubusercontent.com/122949991/213065076-40b9a63a-82b0-49b9-8c1d-2c3136990aaa.png)

Proof is also in his own vehicle data repo.

**Comment by simsomsim22** [comment]
My question is, a man with that many supporters. I sometimes wonder where the server money goes? Upvotes seems be the only thing, that **if** they are **real**.

**Comment by simsomsim22** [comment]
So before you delete this, because you definitely will to hide yourself. 

We will come back 100 times stronger to show your community what you do Mr. FKK, while you may know how to code and the way around, but the latest copy of your server shows leaked resources. 

Don't also try to play victim stating your server is out there, why do u do it when you have the money?

**Comment by cxerq** [comment]
LOOOOL

**Comment by simsomsim22** [comment]
![image](https://user-images.githubusercontent.com/122949991/213066330-b6d3b4e4-6fb3-4f26-848f-b67f796c8435.png)

The housing script is 2 years old, and leaked. 
The hospital map is leaked, which is inadvertently why there is a fall-through issue.
Lockpick script is a leaked script.
Trucking script is leaked.

**Comment by cxerq** [comment]
> 

where is your proof that any of the stuff he uses is leaked other than you just saying it is, also who tf cares if it is leaked, Not a single person who supports the server is required to, not a single person who plays here is forced to, Everyone who plays/supports does it cause they wont to! You are shit talking on a github on an account that was made 20 minutes ago go touch grass or something

**Comment by simsomsim22** [comment]
He agreed to the terms of service himself. I'm sorry but last I checked, man is using leaked resource, which creators made and just supporting leaking?

**Comment by simsomsim22** [comment]
![image](https://user-images.githubusercontent.com/122949991/213067747-61f3a167-afa6-43b5-bc34-ef0ec4b48de5.png)

**Comment by simsomsim22** [comment]
"See patreon.com/noirerp for more information"

**Comment by cxerq** [comment]
Like ive stated go outside and touch some grass for a little bit, you seem angry where you banned or something?

**Comment by simsomsim22** [comment]
Oh no, I haven't been banned, never played actually. I hunt servers that use leaked resources.

**Comment by cxerq** [comment]
honestly smells like cap but you do you! I would recommend talking to someone about your feelings tho ;)
