### ISSUE TITLE
[BUG]: <Electrition box not spawning>

### ISSUE THREAD

**Issue by Unwashedarc** [fkk-cz/noire-public#1282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The box on the bridge near gokart rental doesn't spawn in, meaning that you cannot complete the job and also have to relog.

### Expected Behavior

For the box to spawn in

### Steps To Reproduce

1.Do electrition
2.Get the location near gokart rentals 
3.See that it doesn't spawn in

### Anything else?

It is only this location, all the others work fine.

**Comment by fkk-cz** [comment]
Does anyone have a screenshot of this specific location?

**Comment by Poochthebozz** [comment]
https://medal.tv/games/gta-v/clips/Rf8KNSgUhd3jo/d1337asx6nIu?invite=cr-MSxRRDAsMTI4MDM5OTcxLA

**Comment by Poochthebozz** [comment]
https://medal.tv/games/gta-v/clips/RfNY7yfjWCnIN/d1337WNxtjT1?invite=cr-MSxRV1csMTI4MDM5OTcxLA

Heres another one that didnt spawn

**Comment by Unwashedarc** [comment]
I now notice that some of the boxes on the signal street bridge near postal 20 also don't spawn

**Comment by Poochthebozz** [comment]
Got another one
https://medal.tv/games/gta-v/clips/RWzzVlZgUl3A3/d1337L4VhrIi?invite=cr-MSxCTmYsMTI4MDM5OTcxLA
