### ISSUE TITLE
Player owned businesses 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#1284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bean machine that would work near Legion Square for potential player owned 

https://fivem.gabzv.com/package/4976870

The beachfront would give further expansion to player, owned businesses while using a MLO that works with little to no issue

Gives a large amount of shops that can be custom on which one can be set that accommodate the city

https://fivem.gabzv.com/package/5275729

Recording studio for West Coast convicts in the city, giving them an actual location so they’re not part of the news

https://fivem.gabzv.com/package/4724719

### Expected Behavior

Simple expansion on player owned businesses for the future

### Steps To Reproduce

Future growth

### Anything else?

Great to have. I love how the city has been growing with things that look like they are not causing that much trouble with headaches.

**Comment by Bountyrogger** [comment]
Gives a large amount of shops that can be custom on which one can be set that accommodate the city

https://fivem.gabzv.com/package/5275729

With these shops options you could have individual shops for different items/services. For example I know one of them is a Bike shop. Could move the Bicycles out of PDM and put them there

**Comment by tythetanman** [comment]
Beach front could have something as simple as a bike store for that MLO and sell the bikes. Instead of add PDM put them there. (Joey-my dad/AMR medical Director)

**Comment by tythetanman** [comment]
Also gives WCC that was part of the news it’s own place (as it was requested them being their own part of the city by big boss)
