### ISSUE TITLE
[BUG]: Auto thief mission is bugging out 

### ISSUE THREAD

**Issue by MerkTitty** [fkk-cz/noire-public#1286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is not showing the full numbers for the Decoder. and when you fail the mission, it spams the screen with an error message over and over again until you fly out. 

https://medal.tv/games/gta-v/clips/RSyBHDecJFoKu/d1337pLeGpx2?invite=cr-MSxyaXIsODMzMTY0NDIs

### Expected Behavior

Too work like it use too 

### Steps To Reproduce

As soon as you pull the key fob it was only show 3 out of the 4 numbers 

### Anything else?

I think auto thief's should pay a little more. sense you are having to rob players of their car (who could have gun) and worry about the police.

**Comment by fkk-cz** [comment]
There have been no changes to the relevant minigame. Also video link doesn't work.

> I think auto thief's should pay a little more. sense you are having to rob players of their car (who could have gun) and worry about the police.

Payment was dropped when safecracking was reintroduced to encourage people to try different crimes. There are no plans to revert this change at this time.
