### ISSUE TITLE
[BUG]: Electrical Box at 369

### ISSUE THREAD

**Issue by Fallinglol** [fkk-cz/noire-public#1289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The electrical box at postal 369 doesn't spawn.
https://medal.tv/games/gta-v/clips/TeJC9Kes2KsSf/d1337mcXOX8s?invite=cr-MSxjNFIsMTU0MzI3ODks

### Expected Behavior

Make the electrical box spawn so you can complete your job.

### Steps To Reproduce

^^^

### Anything else?

nope

**Comment by Fallinglol** [comment]
Also could possibly add a feature to quit the job if you third-eye the guy again at electrical.

**Comment by Fallinglol** [comment]
could also make a feature where you can turn it in early to combat this problem if it cant 100% be fixed

**Comment by fkk-cz** [comment]
This *should* be fixed now, elec boxes should be automatically recreated if they are deleted or removed for whatever reason. Can you verify this? @Fallinglol

**Comment by Fallinglol** [comment]
> This _should_ be fixed now, elec boxes should be automatically recreated if they are deleted or removed for whatever reason. Can you verify this? @Fallinglol

Yes it is 100% fixed now. thank you!
