### ISSUE TITLE
Push to talk becomes stuck

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#129]
Notice an issue thats been persisting for the past couple of weeks. Push to talk becomes stuck and your voicebox that says your volume is stuck on orange, resulting in open mic.

**Comment by byu26** [comment]
I think this happens sometimes when alt+tabbing, Setting a secondary keybind for voice chat and toggling on and off afterwards should fix it.

**Comment by ItzHunterrrrr** [comment]
IF you have a Play button on your keyboard that stops it most of the time aswell
