### ISSUE TITLE
[BUG]: Twitter auto suspension

### ISSUE THREAD

**Issue by noyeahsure** [fkk-cz/noire-public#1291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

as of now twitter suspends random things, not even anything ooc. i can tweet ooc all day, but get suspended when i say someones in game name, or say raffle, we should really check this out because its annoying getting suspended for doing absolutely nothing wrong

### Expected Behavior

have an actual system that suspends things that should actually be suspended... 

### Steps To Reproduce

1. tweet pooch, or raffle.
2. get suspended

### Anything else?

find a way to make actual ooc get suspended and not random words that dont pertain to OOC

**Comment by fkk-cz** [comment]
Neither one of those words you provided matches any patterns on the prohibited words list. This isn't a bug, you must be saying *something* that falls under one of these categories.
