### ISSUE TITLE
shared carry emotes can force carry anyone dead and alive

### ISSUE THREAD

**Issue by DarkFan5** [fkk-cz/noire-public#1295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I hate to be the ruiner of fun but with the new shared carry emotes you can force carry anyone as they are set to nearby players instead of bound to the requester, dead or alive it doesnt matter. As amr this is really annoying as people will just start hiding bodies or check them in themselves at hospital making us irrelevant as a whitelist. Ive already had this happen to me just now where i arrived on scene and saw the car driving away with the bodies

### Expected Behavior

I think a good solution would be that just like /carry the shared carry emotes through /nearby will be disabled when amr is clocked in. I would hate to see the emotes go away as they are cute and fun

### Steps To Reproduce

Have one player do /nearby carry2 (any carry works if its being carried)
Person who got the invite walks up to any stranger dead or alive and then flex their y muscle
The nearest person will then be attached to you doesnt matter if they are alive or dead and the only way to get out of it is by either person flexing their x muscle

### Anything else?

Again id really hate to see the emotes get taken away so i hope disabling them when amr is on is a good and possible solution.

**Comment by fkk-cz** [comment]
This was fixed in https://github.com/fkk-cz/rpemotes/commit/6b5ad2c87de181cc538d1647d2e364d1419117a1.
