### ISSUE TITLE
[BUG]: Electrical Boxes at 719 Auto Fail

### ISSUE THREAD

**Issue by Poochthebozz** [fkk-cz/noire-public#1296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes when there are multiple boxes at 719, after doing the first one ill auto fail the next ones. 

### Expected Behavior

Allow you to complete every box individually. 

### Steps To Reproduce

Have multiple boxes at 719, attempt to do them. It should auto fail some after the first one. 

### Anything else?

https://medal.tv/games/gta-v/clips/WrqOo_8aslf_m/d1337sruVonn?invite=cr-MSxJVFksMTI4MDM5OTcxLA Heres a clip to show you how it happens.

**Comment by fkk-cz** [comment]
That clip does not exist.
