### ISSUE TITLE
[BUG]: Character spinning upon flying in

### ISSUE THREAD

**Issue by Fallinglol** [fkk-cz/noire-public#1299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This has been going on for quite some time now and is just a tad bit irritating to deal with. Upon flying your character just spins like you are in the clothing store menu changing clothes. You then have to fly out and back in for the glitch to not take place. This happens to me at least once a day and many others say it happens to them as well. 

### Expected Behavior

Fix the bug so you don't have to fly out and back in.

### Steps To Reproduce

Its honestly quite random when it happens and its usually the first time you fly in after server restart, so you will have to take your chances on getting the bug to reoccur.

### Anything else?

https://medal.tv/games/gta-v/clips/YG3cBZnDksPaK/d1337pBFYbV9?invite=cr-MSxONjgsMTU0MzI3ODks

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/eef3d6099324f781d92f1ec5d351975fd688f606 should fix this issue.
