### ISSUE TITLE
[BUG]: SSB flax texture issue

### ISSUE THREAD

**Issue by Unwashedarc** [fkk-cz/noire-public#1303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The SSB flag has a purple glow when you are wearing no shoes. This is actually a big problem because from far away it looks like BGBs flag.

### Expected Behavior

The flag to remain blue without shoes on.

### Steps To Reproduce

1. put on flag
2. take off shoes

### Anything else?

With shoes 
![Screenshot (96)](https://user-images.githubusercontent.com/120619736/227392928-51ef3d81-0f7e-4879-9835-b9c85da3b9f2.png)

Without shoes 
![Screenshot (97)](https://user-images.githubusercontent.com/120619736/227392861-acad16db-f82a-4d05-a77a-b87efeb52c79.png)

**Comment by fkk-cz** [comment]
This issue needs to be resolved in tickets, not here.
