### ISSUE TITLE
F4 Menu Moods Glitch

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#1305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you switch your facial expression to any of the ones in the menu and you try to reset it back to normal, it doesn't work leaving you still doing the facial expression you chose. I did the angry one 2 days ago, and I can't go back to normal. 

### Expected Behavior

Be able to reset expressions when you click the 'Normal - (reset)' option

### Steps To Reproduce

change your expression to angry
to try reset it
bam youre permanently angry

### Anything else?

no

**Comment by fkk-cz** [comment]
Just tested and I'm able to clear my expression fine after trying a few different ones. Not sure how this can even be an issue when looking at [what reset does](https://github.com/fkk-cz/rpemotes/blob/adc7e308cd6cfdb29e13d5ad8ba58e456b6366f3/client/EmoteMenu.lua#L471).

Closing this as it seems like inconsistent behavior.
