### ISSUE TITLE
[BUG]: <Drunk effect when flying in>

### ISSUE THREAD

**Issue by Dandenal** [fkk-cz/noire-public#1306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I fly into the city my eyes are weird. It looks like a drunk effect.

### Expected Behavior

´That it just looks normal

### Steps To Reproduce

nope I don't

### Anything else?

https://medal.tv/games/gta-v/clips/12lq6W9jBgNUYa/d1337kvNctU2?invite=cr-MSxSYnMsMTU3MDMyMDQ1LA

**Comment by fkk-cz** [comment]
You'll have to wait this one out - there was an issue a few days ago where people were incorrectly receiving a drunk status despite not consuming anything with their character.
