### ISSUE TITLE
Sandy aircraft size

### ISSUE THREAD

**Issue by MrThrawn** [fkk-cz/noire-public#1307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some aircraft’s cannot fit into or out of the deploy hanger -nimbus wingspan keeps it from being useable 

I recommend the deploy location be at the head of the north runway, and the return location to be the head of the south runway (for the large aircraft’s at least) 

### Expected Behavior

Expect all charters to be able to take off and return 

### Steps To Reproduce

Charter a nimbus 

### Anything else?

Godspeed

**Comment by radoncombe** [comment]
![image](https://user-images.githubusercontent.com/77242832/229570594-d2eba0e9-70e8-4dcc-ac80-852c78728508.png)
wingspan is stuck within the hangar, and vert stabilizer is stuck behind roof beams

**Comment by radoncombe** [comment]
the tailfin will get past the first roofbeam, but pretty much from there you are stuck and unable to move any further.
