### ISSUE TITLE
*AMR* bodies not being dead in our eyes

### ISSUE THREAD

**Issue by DarkFan5** [fkk-cz/noire-public#1308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Over the past few weeks weve had multiple instances of bodies being allowed to send a distress signal when flying dead. They will be dead in their eyes but not in ours. Due to this there is NO way to pick them up as they arent really dead.

https://medal.tv/games/gta-v/clips/12LMyU2rhQDJQR/d1337iyR5YTv?invite=cr-MSxBRlksNDI0MjIzODEs
Clip from one of our employees. This isnt the only instance and again has happened multiple times over the past few weeks.

We hate to have to explain certain situation to the dead person or when people around dont understand what we're trying to explain having to go ooc just so we dont get any issues. it ruins the rp.

### Expected Behavior

Either the bodies would need to become actually dead for everyone not just them or when flying in dead you should. not be allowed to send a distress signal

### Steps To Reproduce

Due to me never having experienced this problem as user i dont know the steps to reproduce but my assumption would be.

Get killed, fly out, fly in, be allowed to send signal(if amr is on), see if youre actually dead for others

### Anything else?

I heard that this was once an issue(cant confirm if it has) and that they then got told to just kill them so they're actually dead for us but i dont think this is something amr should ever do(save lives dont take em) ot would create a weird and twisted image of the department as a whole regardless of explaining the situation. Gangs would get mad when we have to kill their friend and would start blaming us for them being fatal etc.

**Comment by fkk-cz** [comment]
This has been a known issue for a while, no idea what causes it though. Added a contextual menu option for AMR which effectively force slays the player to avoid AMR having to shoot or punch them.
