### ISSUE TITLE
Platinum map Edit request #1 

### ISSUE THREAD

**Issue by MrThrawn** [fkk-cz/noire-public#1310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Per Fkk, This ticket is to request a helipad be placed at postal 641 - to enable Rp enrichment on citizen Thrawn Sharp, AMR Ace Pilot , and Flight Director of WNN Air. 

### Expected Behavior

Please see two attached photos , 1 is a hopefully example of a pad to be used (Sandy shores AMR pad)   And the 2nd photo is of the location to place the helipad (should it not fit, there is a tree circled in red, I hope can be removed- if it still can’t fit, perhaps a smaller simpler pad?) 
![52FD01F2-4CF0-489B-8134-5D029C48BA79](https://user-images.githubusercontent.com/112103078/232966384-e2d1f7a3-b568-4c9c-9ffd-5d52b420c410.jpeg)
![460F69F5-FB8F-46B9-AF27-2533F3E2FE0A](https://user-images.githubusercontent.com/112103078/232966388-656eeac5-09a6-4d0c-a764-0db39adb617b.png)

### Steps To Reproduce

Postal 641 front lawn    

(Having the stairs overlap alittle on the drive way would be fine, if needed to fit) 

### Anything else?

Thank you

**Comment by LPLips7** [comment]
"I Own a Lamborghini", 
"Oh I Own a Ferrari"
"Yea well I Own a Bugatti"

"I Own my own Helipad"  😭😭

**Comment by fkk-cz** [comment]
![image](https://user-images.githubusercontent.com/74131024/233490261-9d80b821-cf69-4f27-b72d-aae0863ec12f.png)

Tried multiple helipads, all of them are too big for the location you are suggesting. Removing the tree won't help either, the edge is already clipping into the hedges and extending over the driveway.

**Comment by MrThrawn** [comment]
Can you rotate to put stairs on driveway, my garage is in culdesac anywhere so the drive way can be treated as a landing pad access road sticking into the path will actually help make it flow nicely

**Comment by fkk-cz** [comment]
Your driveway will be partially obstructed by the staircase, but if that's what you want it's fine. Will be available next reset.
