### ISSUE TITLE
[BUG]: Sunset Bleach Destinations

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire-public#1311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the sunset bleach destination markers don't disappear after you finish the job. The issue that some people run into is the fact that if you change the waypoint to another postal then you can't go back and see where your current job is. The numbers in the location lost (A-Z) for e.g. "Destination 2/7" can be your current job and this is misleading because you'd think it be either 1 or 7 as the most recent. 

### Expected Behavior

I do not know if there is a fix to this, but it would work like the old landscaping job. After cleaning a house the previous destination marker should disappear and only 1 active one (for the next job) should appear.

### Steps To Reproduce

If there is a way to fix the script to where the destination markers don't stay on your map that would be optimal.

### Anything else?

Nothing else. Thanks!

**Comment by RichieRockefeller** [comment]
One more thing to add would be the ability to press "F6" to look for a job while in the car. This would be similar to looking for a job in the van when there was landscaping.

**Comment by fkk-cz** [comment]
This was fixed last week, forgot to close this. https://github.com/fkk-cz/noire/commit/3686fe8a7187afae3610ecee78093ed5daf2173f
