### ISSUE TITLE
[BUG]: Fix for vehicles disappearing [Sunset bleach workers]

### ISSUE THREAD

**Issue by KnightUS99** [fkk-cz/noire-public#1312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vehicles disappear sometimes while I'm working, my theory is this has to do with how fivem manages vehicles once no player is in render distance. I have proposed a working solution below.

### Expected Behavior

Vehicles should stay as long as needed.

### Steps To Reproduce

1.) Leave your vehicle outside a sunset bleach job
2.) If there is nobody close, then the server most likely disposes of the entity

### Anything else?

i have tested a fix for this issue on my private FiveM server and found that FiveM's **[SetEntityAsMissionEntity](https://docs.fivem.net/natives/?_0xAD738C3085FE7E11)** function will indeed keep the vehicle rendered even if you leave to the other side of the map, i understand this can be abused or have undesired effects such as people abandoning vehicles, you can always just trigger the function for sunset bleach workers only, or store the vehicles with the property in an array and check for inactivity time, thank you.

Example usage of the function:

`
SetEntityAsMissionEntity(GetVehiclePedIsIn(GetPlayerPed(-1), false), false, true)
`

**Comment by fkk-cz** [comment]
> i have tested a fix for this issue on my private FiveM server and found that FiveM's [SetEntityAsMissionEntity](https://docs.fivem.net/natives/?_0xAD738C3085FE7E11) function will indeed keep the vehicle rendered even if you leave to the other side of the map

You must not be running onesync (infinity) mode. All created vehicles are considered mission/script-owned entities.

This was actually fixed a while back but the change had to be backed out when it was causing server crashes. https://github.com/citizenfx/fivem/issues/1565
