### ISSUE TITLE
[BUG]: <CAN'T CHANGE TWITTER NAME OR PROFILE PIC>

### ISSUE THREAD

**Issue by EmilyNicole1** [fkk-cz/noire-public#1314]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

"For over a week now I have been trying to change my Twitter username and profile picture but I cannot change it no matter what I do. I have cleared cache and everything just nothing seems to work. I see that the same thing has happened to others, but no one is able to help me fix it. My name is stuck to a gang's name that I no longer represent, I cannot tweet until I am able to change it."

### Expected Behavior

1. Pull out phone and go to profile
2. Edit name with no spaces, symbols 
3. Profile Successfully Updated

### Steps To Reproduce

1. Pull out phone and go to profile
2. Edit name with no spaces, symbols 
3. Says failed to update profile 

### Anything else?

![twiternameerror](https://user-images.githubusercontent.com/132686482/236558148-9bf98cd3-68ae-4cfa-b0de-02ff6d91d46f.PNG)

**Comment by fkk-cz** [comment]
`
{"level":"error","message":"Failed to update twitter profile: Duplicate entry 'Emily' for key 'profile_name_UNIQUE'","module":"twitter","source":1094,"timestamp":"2023-05-05T20:01:01.232Z"}
`

Looks like the username is already taken, this is not a bug. Profile names must be unique, but a player is (somehow) allowed to have multiple profiles.This should probably be fixed so people can't registered a bunch of fake accounts, or the error message should be updated to indicate the name is already taken.
