### ISSUE TITLE
[BUG]: Sunset Bleach Finding Job

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire-public#1315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You must be outside of a vehicle to find a cleaning job.

### Expected Behavior

Similar to the old landscaping job, you should be able to press F6 to find a cleaning job while in the vehicle.

### Steps To Reproduce

1. Get in any vehicle.
2. Press F6 to find a job.

### Anything else?

Was it intended from the beginning to be required to be outside of a vehicle to find a job? I know this issue is very minimal but it would make things easier overall. If possible, I would also recommend having a tutorial guide pop up when a new player chooses a job. This will make legal jobs a lot more user-friendly for newcomers. There should be an option to, "Never show this again." for those who do not want to see the guide after reading it. Just a few thoughts I thought I'd share. Thanks a lot for your hard work!

**Comment by fkk-cz** [comment]
This is intentional, players are required to get out of the vehicle when searching for a job.

Agreed on the tutorial idea, it's not a high priority though.
