### ISSUE TITLE
[BUG]: Auto Theft Issues

### ISSUE THREAD

**Issue by LinXCS** [fkk-cz/noire-public#1316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Robbing player for car keys bugs mission. (Stuck on hotwire the vehicle) 

Auto theft will bug (sometimes) and not allow the player to turn in the car after 25-30 min ( "Deliver the vehicle" yellow circle will appear but when you drive over it nothing happens)

Auto thefts being inside locked places (Hospital, PD, Nightclub) 

More vehicles to steal. The cars are very specific that are picked for auto thefts 

The public garage stops players from putting their cars away. Personal garages do not stop the player from putting the car away. This causes the mission to Bug 

Cars in the water get picked, and Mission won't go away either (get the same submerged car over and over)

When having a mission you are able to hotwire any vehicle (Basically having an invisible keyfob)

Bait cars are too common (Cops camping the cars before criminals even attempt to steal)

Change the no repairing system to cant repair once the vehicle is hotwired (Cant repair your own vehicle as soon as the mission starts)

Double lock pick bug, where once you lock pick it, it won't unlock and you have to re-lock pick it (sometimes you'll even get in the car hotwire it then get kicked out and it'll relock)

Potentially Add high-Class auto thefts which allow for supercars to be stolen (Pay dirty to a mechanic for information on where the vehicle is)

Motorcycle theft?

### Expected Behavior

N/A

### Steps To Reproduce

auto theft missions

### Anything else?

n/a

**Comment by fkk-cz** [comment]
> Robbing player for car keys bugs mission. (Stuck on hotwire the vehicle)

Wasn't able to recreate this.

> Auto theft will bug (sometimes) and not allow the player to turn in the car after 25-30 min ( "Deliver the vehicle" yellow circle will appear but when you drive over it nothing happens)

This is a rare occurrence, do you have any further information as to what might cause the mission to break?

> Auto thefts being inside locked places (Hospital, PD, Nightclub)

This cannot be fixed, most of these places have lockpickable doors. Can also be handled in RP by trying to deceive your way inside.

> More vehicles to steal. The cars are very specific that are picked for auto thefts

Increased the max value of stealable vehicles -- this should improve the vehicle variety.

> The public garage stops players from putting their cars away. Personal garages do not stop the player from putting the car away. This causes the mission to Bug

Fixed.

> Cars in the water get picked, and Mission won't go away either (get the same submerged car over and over)

Fixed. Vehicles that are in the water will be marked as disqualified and not included in subsequent searches.

> When having a mission you are able to hotwire any vehicle (Basically having an invisible keyfob)

Fixed.

> Bait cars are too common (Cops camping the cars before criminals even attempt to steal)

Added a timeout interval/delay for police notifications.

> Change the no repairing system to cant repair once the vehicle is hotwired (Cant repair your own vehicle as soon as the mission starts)

Not sure what this means.

> Double lock pick bug, where once you lock pick it, it won't unlock and you have to re-lock pick it (sometimes you'll even get in the car hotwire it then get kicked out and it'll relock)

Wasn't able to recreate this.

> Potentially Add high-Class auto thefts which allow for supercars to be stolen (Pay dirty to a mechanic for information on where the vehicle is)

This doesn't make much sense and would effectively make missions supercar exclusive -- not the original intent behind this.

> Motorcycle theft?

Bikes are generally valued much lower than cars and the payout wouldn't be worth it.

**Comment by LinXCS** [comment]
Robbing player for car keys bugs mission. (Stuck on hotwire the vehicle)

Wasn't able to recreate this.

If you have an auto theft mission and you rob the player for the car keys (they get them back with insurance) you will step inside of the car and you will be able to drive it. The problem while driving the car it won't say "wait for instructions" it will say "Hotwire the vehicle" The only workaround i've found is driving off giving another player the keys. getting back into the car and hotwiring it.
---------------------------------------------------------------------------------------------------------------------------------------
Change the no repairing system to cant repair once the vehicle is hotwired (Cant repair your own vehicle as soon as the mission starts)

Not sure what this means.

poorly explained my apologies, Once you start the auto theft (third eye the mechanic) you are no longer able to repair vehicles whether it's the auto theft vehicle, your own personal car, or a PED car. The change I was hoping for is to allow the player to repair any car until the player starts hot-wiring the car.
------------------------------------------------------------------------------------------------------------------------------

Double lock pick bug, where once you lock pick it, it won't unlock and you have to re-lock pick it (sometimes you'll even get in the car hotwire it then get kicked out and it'll relock)

Wasn't able to recreate this.

This is a bug My friends and I run into pretty often, This happens lock-picking cars in general not only on missions. Will get a clip of it.

----------------------------------------------------------------------------------------------------------------------------------------
Auto theft will bug (sometimes) and not allow the player to turn in the car after 25-30 min ( "Deliver the vehicle" yellow circle will appear but when you drive over it nothing happens)

This is a rare occurrence, do you have any further information as to what might cause the mission to break?

Not entirely sure, I'll keep playing around with it. I run into this problem a majority of the time after I spot the vehicle but don't take it for an extended period of time  
--------------------------------------------------------------------------------------------------------------------------------------
Really wanna thank you for addressing these issues.

**Comment by LinXCS** [comment]
After testing today. You can still get cars Submerged in water. got a car in the ocean this morning

**Comment by fkk-cz** [comment]
Cars submerged in the water should be marked as disqualified after the *first* time you receive that mission. On subsequent missions, that vehicle should no longer appear.
