### ISSUE TITLE
[BUG]: Not beeing able to purchase weapons license

### ISSUE THREAD

**Issue by Goofygoob0** [fkk-cz/noire-public#1317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pressing buy weapons license and it shows "constructing background check" and then nothing happens from there

### Expected Behavior

To be able to see if you can or can not purchase a weapons license

### Steps To Reproduce

1. Press buy weapons license
2. Conducting background check
3. Get the pop up to show if you are able to purchase a weapons license

### Anything else?

https://medal.tv/games/gta-v/clips/1bpFPzCW_JJ65e/d1337kSK8x9c?invite=cr-MSxiVFAsMzY5NzMyMDIs

**Comment by fkk-cz** [comment]
This should be fixed - made a typo in the new felony status calcuations.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/1323 fixes the remaining issues.
