### ISSUE TITLE
[BUG]: Spraypaint Remover not working

### ISSUE THREAD

**Issue by No-Yes1** [fkk-cz/noire-public#1318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever you drag the spraypaint remover to use, it does not work or gives any errors as to why it does not work. Spraypaint remains there.

### Expected Behavior

Spraypaint should remove.

### Steps To Reproduce

1. Get spraypaint Remover
2. Go up to any spraypaint
3. drag the spraypaint remover to use
4. watch it not work

### Anything else?

Clip provided: https://medal.tv/games/gta-v/clips/1bpHnIGe8JyvUS/d1337EoRoeoW?invite=cr-MSwzVW8sMTgxNDAzODUs

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/266b723bbb6c4283573edd39d8d145a88148ab21.
