### ISSUE TITLE
[BUG]: <SPRAYPAINT DISSAPEARING>

### ISSUE THREAD

**Issue by andrxsf** [fkk-cz/noire-public#1319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We just spent around 100k on spraypaint and out of nowhere they all dissappeared

### Expected Behavior

Spray paint stays for a month like u guys made it, makes no sense why out of nowhere it dissapeared

### Steps To Reproduce

1.Spraypaint
2.Wait a couple of hours i think it was the change in the weather, it was raining while we spray painted it stopped raining and they all dissapeared

### Anything else?

https://prnt.sc/k69QL9qRarFP
an hour after they're all gone
https://prnt.sc/z773hFQymwXG

**Comment by fkk-cz** [comment]
Not a bug - this change was [backed out](https://github.com/fkk-cz/noire/commit/f109a13a808b00e256dcb8e4cfb5e47f84c50e32) a while ago and reverted back to 7 days. If it disappears in a couple of hours, that most likely means someone cleaned it up.
