### ISSUE TITLE
[BUG]: Unable to Unsuspend Licences

### ISSUE THREAD

**Issue by residentalyeti1** [fkk-cz/noire-public#1321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to unsuspend licences. I believe its taking the money for unsuspending the licence (i could be wrong, only going off what ive been told in city). This results in people getting charged and going to jail SO MANY times for driving suspended but being unable to unsuspend the licence

### Expected Behavior

Be able to unsuspend drivers/CDL/Motorcycle licences

### Steps To Reproduce

Have a suspended licence
Attempt to unsuspend

### Anything else?

nothing else

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/ebff967674b5eba8b62ea6493ac0c56e4c66f3df. Timestamps were recorded in milliseconds, which needs to be converted to properly display the earliest reinstatement date.
