### ISSUE TITLE
[BUG]: Cant 'Press [G] to change vehicle

### ISSUE THREAD

**Issue by jeanndabeann** [fkk-cz/noire-public#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So it might only be me but i'm hoping someone has some type of fix.

This has been happening for around a week now i think, when i go to PDM to look through vehicles i press G and nothing happens, ive relogged multiple times, my packet loss is normal around 5, my ping is normal for me as well 50-60. It is just not working, ive tried seeing if there is a bind for it in key binds to change it for me but i havent found anything.

### Expected Behavior

when i press G i should see the list of cars

### Steps To Reproduce

Literally just go to PDM and press G
I havent heard of anyone else having the problem though

### Anything else?

In this clip i was pressing G over and over again in the beginning before i pressed https://medal.tv/games/gta-v/clips/1bVsk9o8oElZnN/d1337wpVWPt5?invite=cr-MSxiNHgsMjYzMzA4MzYs

**Comment by fkk-cz** [comment]
You most likely have a changed keybind. Check whatever is bound to INPUT_DETONATE in your controls.

**Comment by jeanndabeann** [comment]
Is there a way to fast search like a keyword or do i just have to scroll though bind and look for it

**Comment by jeanndabeann** [comment]
i just went through all the binds and i dont see it so im assuming its unbinded completely
