### ISSUE TITLE
[BUG]: Background check stuck loading

### ISSUE THREAD

**Issue by cheesyponyy** [fkk-cz/noire-public#1327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No matter how many times I relog, I am not able to buy a weapons license. I've played the 24hr needed, and I have no charges waited to be expunged, so it can't be either of those. When I open the menu to access the ammunation clerk, it gives me the option to buy a weapons license or not. When I click the option to buy it, I get a message saying something like "performing background check...", but nothing happens after the message disappears. The menu to buy the license or not is still up as well.

### Expected Behavior

I'd assume the menu would close and the license would be given to you as soon as you click the option.

### Steps To Reproduce

Any and all ammunation stores seem to be affected for me, i've tried at least 3-4 stores.

### Anything else?

There is also a blue circle available that did not used to exist until the first time I attempted to buy the license, but I can only buy weapon magazines, lockpicks, and multi-picks.

**Comment by fkk-cz** [comment]
Fixed in 92ec32cbd263b02dbc71efd7a75a335d8f8f0bda.
