### ISSUE TITLE
Tattoo Removal Issue

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire-public#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When taking off tattoos at the tattoo shop they stay off only until I fly out. I even saved an outfit at the clothing store with no tattoos and loaded that player model at my house wardrobe to test. I then flew out and flew back in and the tattoos reappeared.

### Expected Behavior

The ability to remove tattoos that will stay off when a player logs off and comes back into the server. 

### Steps To Reproduce

1. Go to a tattoo shop
2. Remove tattoos that are already saved 
3. Save changes and save outfit
4. Disconnect from the server
5. Connect to the server 
6. Look at tattoos on body that reappear from last save 

### Anything else?

I really do think the change from the previous tattoo behavior has resulted in positive feedback. There was a time when people used to be required to ink themselves every time they flew in and now that’s changed. The issue now is the fact that the tattoos stay on the player model and can’t be taken off every time a player flies into the city.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/a4540653143816e78ec162aebb5299adef311455 fixes this issue.
