### ISSUE TITLE
[BUG]: 3030 Gas trailer spawning on its side

### ISSUE THREAD

**Issue by residentalyeti1** [fkk-cz/noire-public#1332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The gas trailer at 3030 keeps spawning on its side. have to hit it with the truck to upright it

### Expected Behavior

spawn on its wheels

### Steps To Reproduce

start a gas run at 3030

### Anything else?

have had this issue before but it got fixed. something got changed at it caused the issue again

**Comment by zoiczombie** [comment]
I've had the same things happen to my stations. It's been like this since one of the weekend resets. The tankers are spawning in on their side and are occasionally bricking making them hard to move.

**Comment by LactatingWalrus** [comment]
This is happening at 375 too.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/b3a56715d622de204c326d3f2681cd7679333fb9 fixes this issue -- gas station trailers should now be set on the ground properly when spawned.

Also added logic to auto delete trailers when job is complete or if the player drops in the middle of an active mission.
