### ISSUE TITLE
Game crash on Gas station truck and trailer spawn

### ISSUE THREAD

**Issue by Daniiel35** [fkk-cz/noire-public#1338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have had 2 people attempt to fill gas for 3030 within the last few hours and both times when they have created the job for the station their game has crashed.

### Expected Behavior

When the job for the gas station is created & the truck and trailer spawn in there is an instant crash of our games

### Steps To Reproduce

Start gas refill job and when the truck and trailer spawn in the game crashes

### Anything else?

Hopefully this can be fixed asap, as the station is currently empty as there is a 7 day timer on empty stations.

**Comment by RichieRockefeller** [comment]
https://streamable.com/uvq22f

**Comment by LactatingWalrus** [comment]
375 was working fine this morning but this just happened there as well.

**Comment by fkk-cz** [comment]
The fix for https://github.com/fkk-cz/noire-public/issues/1332 caused this. Turns out you can't set trailers on ground properly.
