### ISSUE TITLE
Open Interior House Lock Fix

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire-public#1339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently my open interior house door lock is linked to my steam hex and I am the only person able to open it. 

### Expected Behavior

Would like it set up with a Pin style so I can allow people with key access to be able to get access to the house inventory

### Steps To Reproduce

Change lock over to pin style lock

### Anything else?

Thank you for any assistance

**Comment by fkk-cz** [comment]
Door has been set to PIN code only.
