### ISSUE TITLE
[Change request]: <Move metal detecting back to Mainland>

### ISSUE THREAD

**Issue by Dandenal** [fkk-cz/noire-public#1340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

That metal detecting is on the island where all the drug stuff is. Everytime you go there you get killed.

### Expected Behavior

Move the metal detection sites back to the beaches.

### Steps To Reproduce

Move spots back to beaches.

### Anything else?

N/A

**Comment by fkk-cz** [comment]
Metal detecting will not be moved back to a non-hostile area. Previously this caused too many issues where people would shoot/kill/run over other players and it's not worth dealing with the reports or issuing punishments.
