### ISSUE TITLE
La Puerta’s Unrealistic Jump on overpass/elevated area. 

### ISSUE THREAD

**Issue by notJudgeTy** [fkk-cz/noire-public#1343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With now two Audi’s (Audi RS7 and an Audi R8) taken from this jump I wanted to ask if it’s possible to block it off to avoid cops even having to deal with this unrealistic jump
![IMG_4818](https://github.com/fkk-cz/noire-public/assets/137250294/50427cfc-304b-42ae-8b96-afeb997ec249)
![IMG_4817](https://github.com/fkk-cz/noire-public/assets/137250294/612eec3e-c9e9-4291-b849-49dd6570c8c6)

### Expected Behavior

Unrealistic jumps that takes away from fun chases. 

### Steps To Reproduce

https://clipchamp.com/watch/1kJ0fHyECkE?utm_source=share&utm_medium=social&utm_campaign=watch

### Anything else?

Hopefully it’s blocked off if possible.

**Comment by fkk-cz** [comment]
This has been blocked off.
