### ISSUE TITLE
[BUG]: GoPostal trucks not having keys and anyone can steal

### ISSUE THREAD

**Issue by Blurrr5** [fkk-cz/noire-public#1347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you start a GoPostal job you are not given the keys to the truck/van and you can not lock your vehicle and anyone can jump in the truck and instantly steal it. This makes it extremely difficult to get runs done especially for professional drivers as people like to steal the vans. 

### Expected Behavior

GoPostal vans to have keys and given to player upon starting job

### Steps To Reproduce

1. start a GoPostal job
2. be given keys to truck/van

### Anything else?

Also had an idea to add to GoPostal where all of the mail boxes were marked on the map and the player got to choose what route they want to take to get to all of the mailboxes.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/36694a25cdb7e8af5e48ddc5bfa3178394bbb5e6.
