### ISSUE TITLE
suggestion: lot of damn things

### ISSUE THREAD

**Issue by CheapMelon** [fkk-cz/noire-public#1349]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

1:Make texts oval and up in the left corner.
2:Make a realistic speedometer in the right corner you can fit the fuel level and speed limit there.
3:Make the icons in map all same size.
4:Make a seatbelt system.
Heres a pic of a speedometer.
![d392e07815031de12bba4ffb28ab09cee162002b](https://github.com/fkk-cz/noire-public/assets/129112803/5e785e74-06da-4a44-92e4-9839fbc9e266)

### Expected Behavior

idk?

### Steps To Reproduce

This is a suggestion

### Anything else?

Nope

**Comment by fkk-cz** [comment]
> 1:Make texts oval and up in the left corner.

This would conflict with help text notifications.

> 2:Make a realistic speedometer in the right corner you can fit the fuel level and speed limit there.

Doing so would obstruct the street, vehicle make/model, and zone name. This also isn't a racing simulator, any large speedometer would just be an eyesore.

> 3:Make the icons in map all same size.

Blip scale is used to emphasis points of interest. Having all blips the same size wouldn't make sense -- why should a player see a house blip owned by another player as the same size of the hospital?

> 4:Make a seatbelt system.

...Why?
