### ISSUE TITLE
Dinghy Gas Backfire when at 0%

### ISSUE THREAD

**Issue by sighzybtw** [fkk-cz/noire-public#1350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when you use the dinghy boat it always has gas backfire on it when at 0% fuel and since all boats are at 0% fuel you cant really do anything about it and putting fuel into the boat doesn't take the backfire off either.

### Expected Behavior

The gas backfire on the Dinghy boat should be taken off to clean up the look of it since boats are gonna be a regular thing now.

### Steps To Reproduce

...

### Anything else?

no

**Comment by fkk-cz** [comment]
The 'no gas backfiring' you are referring to is a GTA mechanic, not something done purposefully by us. Boats currently don't even use fuel, not sure how this is an issue?
