### ISSUE TITLE
[BUG]: When you are doing Sunset bleach and someone kills you the destination will be bugged and you cant enter it

### ISSUE THREAD

**Issue by YazanLol1** [fkk-cz/noire-public#1353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Everytime I do sunset bleach and someone kills me the destination and the house is bugged and you cant enter the house. You cant request a new one it will stay the same and still cant enter it and to fix it you need to fly out and fly back in which Is very annoying because everytime we get killed while doing Sunset we have to fly out and fly back in to fix it.

### Expected Behavior

Whenever you get killed/die while going to the destination of the house/warehouse the current destination disappears and you have to request a new one.

### Steps To Reproduce

1. When killed the destination disappears
2. Request a new house

### Anything else?

N/A

**Comment by fkk-cz** [comment]
Fixed - cleaning job state wasn't being reset on player death. Also disabled entering houses after recently committing crime.
