### ISSUE TITLE
Suggestion: Make it so that you get the gopostal locations like the electrical job locations

### ISSUE THREAD

**Issue by fluffyfool** [fkk-cz/noire-public#1354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now in gopostal you're just driving from A to B constantly when there's 2 miles in between them even though there are 5 packages at A and 5 at B.

### Expected Behavior

Make it so that you can see the locations like you see the electrical job locations so you can choose your own route and order.

### Steps To Reproduce

This is a suggestion

### Anything else?

I couldn't find the discusion tab so i just did the suggestion like this

**Comment by fkk-cz** [comment]
There are no plans to change the electrician job routing at this time.
