### ISSUE TITLE
[BUG]: PDM Doesn't Sell Price

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#1355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So when you go to sell a supporter car back to PDM it doesn't tell you how much you can sell it back for. (This could also be because I'm not gold yet but I am unsure), Just trying to see how much I can sell it for before buying gold so I know if I need more money for a new car or not.

### Expected Behavior

It should tell you how much you can get for it if you sell it back. (I believe it used to tell you?)

### Steps To Reproduce

Go to PDM with a supporter car 
Try and sell it back

### Anything else?

Hopefully if this is an issue it can be fixed.

**Comment by Artificial-IQ** [comment]
When you sell supporter vehicles at PDM, you receive 70% of the vehicle's original value. You just need to do some quick math and you'll know how much it'll come out to.

**Comment by cxerq** [comment]
> When you sell supporter vehicles at PDM, you receive 70% of the vehicle's original value. You just need to do some quick math and you'll know how much it'll come out to.

But when the car has miles on it doesn’t that effect the price?

**Comment by Ell34** [comment]
> > When you sell supporter vehicles at PDM, you receive 70% of the vehicle's original value. You just need to do some quick math and you'll know how much it'll come out to.
> 
> But when the car has miles on it doesn’t that effect the price?

Not yet
