### ISSUE TITLE
[BUG]: Greyed out impounded vehicles, can't pay even with no fines, enough money. 

### ISSUE THREAD

**Issue by Lauretta-Dior** [fkk-cz/noire-public#1358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

People told me it's due to recent changes, but please fix this issue as i'm not the only one. People have vehicles that were impounded before the recent changes to inventory etc. and can't pay for their car to be un-impounded. even with updated driver's licence, enough money and expiry date way past the release date.

### Expected Behavior

Greyed out "pay" button's. 

### Steps To Reproduce

1. enter impound
2. check impound list
3. try to un-impound vehicle way past the expiry date
4. unable to pay even with enough funds and no charges (New valid licence included) 

### Anything else?

I hope there's a fix soon. Alot of people spend alot of time grinding for their cars.

**Comment by Jerry122345** [comment]
For real man it’s a major problem it’s been like this for weeks as well I herd fuck this shit man all this grinding to get nice cars just to get fucked over

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/1359
