### ISSUE TITLE
[BUG]: impound greyed out 

### ISSUE THREAD

**Issue by Jerry122345** [fkk-cz/noire-public#1359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I’m on strike once this issue gets fixed I start playing the sever again how the hell u gonna grind fuck ton of hours for a car and role play with it to get taken away permanently it seems like no one talks about the problem but it a major deal in the sever and it seems like y’all don’t care once this issue is fixed I’ll be back but for now what’s the point in playing the sever for real 

### Expected Behavior

!

### Steps To Reproduce

!

### Anything else?

?

**Comment by Jerry122345** [comment]
Fix impound

**Comment by fkk-cz** [comment]
Calm down - there's no need for the hostility. https://github.com/fkk-cz/noire/commit/b25bff2ef7d2c8b876b99b85d5a3a5306022a061 fixes this issue.
