### ISSUE TITLE
[BUG]: <please fix the impound>

### ISSUE THREAD

**Issue by Jerry122345** [fkk-cz/noire-public#1360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

? 

### Expected Behavior

?

### Steps To Reproduce

?

### Anything else?

?

**Comment by Idk-maybe** [comment]
This is a dupe issue, on top of the first one you opened there's another issue that was opened previously on this, be patient and this will be fixed soon
