### ISSUE TITLE
[BUG]: <Please Fix Fuel>

### ISSUE THREAD

**Issue by pxlATK** [fkk-cz/noire-public#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i was doing go postal this morning and went to get a gas can i spent 1000 dollars and filled my truck from 0% to 39% and it ran out 3 more times so i spent 4000 dollars to fill my truck from 0% to 39% 4 times in total.

### Expected Behavior

i used to be able to fill from 0% to 100% multiple times for a fraction of the cost

### Steps To Reproduce

1. Buy a gas can
2. fill up an empty go postal truck
3. everytime i filled it it would only get to 39%
4. cost around 1000 dollars each time you fill it and it doesnt even go up past 39%

### Anything else?

no

**Comment by Idk-maybe** [comment]
This issue has already been fixed and an announcement was put out in the bulletin channel of the discord. This fix will be live at server restart 7/20
