### ISSUE TITLE
Gas Station doesn’t receive money 

### ISSUE THREAD

**Issue by Casidrew** [fkk-cz/noire-public#1362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I currently own 817 station and it’s does not collect the money when I pay for gas.  As well it does no deplete the gas I have at the station. Just stuck at 99%.

### Expected Behavior

Collect money at station 

### Steps To Reproduce

N/a

### Anything else?

N/a

**Comment by Casidrew** [comment]
Gas Station do know receive money but it is not the full amount, I just spent $350 on the pump but when I check in the station it shows only a purchase of $221 was made.

**Comment by fkk-cz** [comment]
Gas stations are now taxed a proportion of their earnings. This is intentional and not a bug.
