### ISSUE TITLE
[BUG]: DOT service calls

### ISSUE THREAD

**Issue by spliff808** [fkk-cz/noire-public#1363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As of now when someone does the t/calldot command it sends us a ping that we can accept in f6 menu. However if their is more than 1 call and or someone spams it trying to get our attention it’s break the system and we cannot open the call log to accept ANY calls. Not only is this inconvenient for the public by not being able to get help whether is gas or repair, it really limits the potential roleplay that DOT can provide and enjoy.   

### Expected Behavior

When numerous calls come in they all pop up similar to Amr and doesn’t brake our system.

### Steps To Reproduce

Clock in to dot
Have some one call dot multiple times
Notice how it won’t let you open service call menu in f6

### Anything else?

Idk how difficult it would be to route through the mdt but I feel that would be very handy and reliable. Thank you

**Comment by fkk-cz** [comment]
@okxeon was this change ever implemented?

**Comment by Tayytayyy** [comment]
> @okxeon was this change ever implemented?

no

**Comment by fkk-cz** [comment]
DOT service calls from `/calldot` should now be routed to the MDT.
