### ISSUE TITLE
[BUG]: <Gas Prices Formula Needs Altering>

### ISSUE THREAD

**Issue by Akumaaaa** [fkk-cz/noire-public#1367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The new gas system, great, don't need cash, love that. But you seriously can't make us believe that paying upwards of $1000 just to fill up a vehicle makes sense. 

Here in this photo, I fill up the Ninja H2 from 12%, up to 98%, which costs me $980. $98, sure, but $980 is absolutely insane.  

https://cdn.discordapp.com/attachments/1121565423033389206/1134334597849694339/image.png

### Expected Behavior

Alter the formula to be more realistic, since that's the path you seem to want to follow. It's unrealistic for players to be paying this much in-game money for each fill. Unless you're trying to increase wages, it only makes sense to fix this formula and make it more realistic at $100-200 a fill, depending on your vehicle.

### Steps To Reproduce

1. Work hard for your money
2. Drive around until you need to fill your vehicle up
3. Visit a gas station to purchase gasoline
4. Pull up to a stall, and flex that E muscle
5. Start filling up your gas tank
6. Nearly shit yourself seeing how much you just paid for 17 GOD DAMN LITRES OF GASOLINE. Yes, that is how much goes into that bike.

### Anything else?

https://cdn.discordapp.com/attachments/1121565423033389206/1134334597849694339/image.png

**Comment by fkk-cz** [comment]
The fuel cost per tick has been reduced & the fill rate has been increased. This should bring prices at the pump similar to what they were before.
