### ISSUE TITLE
[BUG]: RED CIRCLE NOT SHOWING ON SCREEN

### ISSUE THREAD

**Issue by Godlyah** [fkk-cz/noire-public#1371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The red circle wasnt on my screen but still died to it after it was gone for 6 HOURS was rolling with mayans and then went to meth and i died but had no red circle 

### Expected Behavior

A consistent red circle that shows ups and doesnt hide after 6 hours

### Steps To Reproduce

1. Wait for the recircle to goaway 
2. Relog
3.if its gone check if not didnt work 

What i did was wait for it to go away then i relogged at like 5 then i got off then got back on wasnt there and i came back and just died  i even went into where it was originally (i remember what it looked liked) and didnt die but when i went closer it killed me

### Anything else?

I dont have my bodycam it been buggin

**Comment by fkk-cz** [comment]
> Expected Behavior

A consistent red circle that shows ups and doesnt hide after 6 hours

That's not how the NLR enforcement works. The red circle you are referring to is a blip that should disappear when the zone expires.

There have been reported cases where players will die to an 'invisible' circle, usually after reconnecting. Added some validity checks to ensure NLR enforcement after relogging will only start after any forced deaths from combat logging. This *should* fix it, but without further information it is hard to determine the exact cause.
