### ISSUE TITLE
[BUG]: <Lighting at Coke tables Cayo Perico>

### ISSUE THREAD

**Issue by Leed55** [fkk-cz/noire-public#1374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Light is positioned at the wrong spot and hovers on top of the table. Blocks off vision at night time and makes it hard to see.

### Expected Behavior

The floating orb/light should be positioned where the light hangs from the ceiling and not in front of our eyes when making coke.

### Steps To Reproduce

Wait for night time and for the lights to turn on and watch how it blocks sight.

### Anything else?

no

**Comment by Poochthebozz** [comment]
Even the weed tables does it too, kinda hurts my eyes
