### ISSUE TITLE
[BUG]: Spary paint bot working 

### ISSUE THREAD

**Issue by Poochthebozz** [fkk-cz/noire-public#1376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ive bought spray cans over the past couple days just a couple nothing major. Everytime I put one up its not visible.  

### Expected Behavior

Able to spray a wall and actually see the spray painted message.

### Steps To Reproduce

1. Buy a spray paint
2. Spray "Big OTF" on the wall
3. Spray the wall 

### Anything else?

https://medal.tv/games/gta-v/clips/1nP66Rduado2ns/d1337MFKVmtr?invite=cr-MSx5WHgsMTI4MDM5OTcxLA

**Comment by fkk-cz** [comment]
Works fine for me?

**Comment by Poochthebozz** [comment]
So it looks like they disappear or are not being visible  https://medal.tv/games/gta-v/clips/1nZW92kfbk_jcM/d13379uWUczu?invite=cr-MSxSdkYsMTI4MDM5OTcxLA

**Comment by fkk-cz** [comment]
If the spray is flickering or disappearing, there are most likely too many sprays in the area. This is intentional for performance reasons.
