### ISSUE TITLE
[BUG]: No ID's showing in the hood

### ISSUE THREAD

**Issue by Fallinglol** [fkk-cz/noire-public#1377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whilst in certain areas of the hood, ID's are inconsistently showing. Even when dead you cant even see the id's of the players around you.

### Expected Behavior

Have id's show again

### Steps To Reproduce

Attempt to F3 someone in the hood, get VDM'd or die in the hood in an attempt to see the players id.

### Anything else?

Here is an example of the IDs not showing.
https://medal.tv/games/gta-v/clips/1nYDz0DIxpMqre/d1337gTYSbrr?invite=cr-MSxtbm8sMTU0MzI3ODks

**Comment by fkk-cz** [comment]
Inconsistent overhead IDs are caused by the player being in a 'recently fired' state -- this was initially done because people were complaining about 'getting F3' in a bush while playing an emote.

Adjusted the restrictions to always show IDs in a ragdoll or dead state.
