### ISSUE TITLE
[BUG]: <Casino Searching Not Working>

### ISSUE THREAD

**Issue by Tayytayyy** [fkk-cz/noire-public#1378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we open the casino, someone stands at the front door to search people's pockets to ensure no one is allowed in with a weapon. unfortunately, when the new inventory update was made, our search only shows the first 5 slots. when a weapon is placed in a lower slot it doesn't show up. Our solution at the moment is having people step through the metal detector and if it beeps we don't allow them in, but bullets don't ring _(if they win a gun off the wheel they now have amo for it)_ and sometimes melee doesn't either _(even when it's seen on their back)_.

### Expected Behavior

clocking in for the whitelist should give us access to seeing their entire inventory.

### Steps To Reproduce

n/a

### Anything else?

a lot of people are addicted to the casino and like it when it's open and this issue is making it a bit unsafe for the workers and civs inside. 
thumbs up

**Comment by fkk-cz** [comment]
This *should* be fixed now. Can someone confirm?
