### ISSUE TITLE
[BUG]: DOT MDT Service call

### ISSUE THREAD

**Issue by Poochthebozz** [fkk-cz/noire-public#1381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When getting service calls on the MDT it seems like the Recent Notifications arent self deleting or expiring, so when new calls come in they aren't able to populate. Also on the F6 menu the calls arent showing as well. 

### Expected Behavior

Expect after service call are accepted or when newer service request come in to delete the oldest notification.  

### Steps To Reproduce

1. Get five service calls 
2. Get a 6th call and youll see the 6th call wont show 

### Anything else?

No

**Comment by okxeon** [comment]
Fixed this issue here https://github.com/fkk-cz/noire-mdt/commit/67916ab893c6c87ab77d225f79d7750b454fbcd3. Changes will take effect immediately - thanks for reporting this.
