### ISSUE TITLE
[BUG]: <Custom title here>

### ISSUE THREAD

**Issue by MissKittyVT** [fkk-cz/noire-public#1382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When going to insurance to see where my vehicle is, it shows its at postal 570. with no way to retrieve the vehicle. please fix

### Expected Behavior

fix thisss

### Steps To Reproduce

?

### Anything else?

.

**Comment by fkk-cz** [comment]
This was a typo oversight and is fixed.
