### ISSUE TITLE
[BUG]: Local cars despawning to emergency 

### ISSUE THREAD

**Issue by Poochthebozz** [fkk-cz/noire-public#1383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ive noticed that local cars despawn when the emergency lights are on. The issue is when players are driving said vehicles and pass emergency vehicles, the vehicle despawns. If theres a player in the vehicle the vehicle shouldnt despawn. 

### Expected Behavior

Not despawn local cars when players operating it

### Steps To Reproduce

Have a player drive by when an emergency vehicle is near by.

### Anything else?

No

**Comment by fkk-cz** [comment]
This was fixed a few days ago, vehicles that are hotwired or stolen (lockpicked) should no longer be deleted.
