### ISSUE TITLE
[BUG]: Wholesaler Not Working For BurgerShot

### ISSUE THREAD

**Issue by Chill3rKiller** [fkk-cz/noire-public#1384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Wholesaler is not working, It will not let us interact with him so we are unable to buy meat and we have to resort to other options to obtain meat just so we can be open. 

### Expected Behavior

For the Wholesaler to actually be interactable with and sell us meat. 

### Steps To Reproduce

.

### Anything else?

No

**Comment by fkk-cz** [comment]
I tried this last night and it worked for me, can you provide any further specific information here?
