### ISSUE TITLE
suggestion. REAL LIFE TRUCKS AT TRUCKING

### ISSUE THREAD

**Issue by dinmamma100** [fkk-cz/noire-public#1385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

right now when you do a trucking job you spawn in with the regular old gta truck. 

### Expected Behavior

i think there should be a real life truck like this one https://www.gta5-mods.com/vehicles/scania-r730-streamline-4x2 instead of the normal one 

### Steps To Reproduce

1. add the mod i linked (or something similar)
2. make it spawn when choosing trucking job instead of normal truck

### Anything else?

https://www.gta5-mods.com/vehicles/scania-r730-streamline-4x2

**Comment by fkk-cz** [comment]
Add-on trucks generally tend to be oversized and there are no plans on replacing the `phantom` models at this time.
