### ISSUE TITLE
[BUG]: <Be able to do Hunting with CD>

### ISSUE THREAD

**Issue by BigShane0** [fkk-cz/noire-public#1386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unsure but I doubt you could do hunting with CD

### Expected Behavior

Should do hunting with combat disabled but if you try to kill other players it won’t allow you to do damage to them 

### Steps To Reproduce

Change so you can hunt with CD 
No damage to other players in hunting 

### Anything else?

N/A

**Comment by fkk-cz** [comment]
Not sure if this is a good idea. If you are combat disabled, you probably should not be using any weapons in the first place.
