### ISSUE TITLE
[BUG]: dowgalking glitch

### ISSUE THREAD

**Issue by Lenny128** [fkk-cz/noire-public#1389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://medal.tv/games/gta-v/clips/1qqylJdJA9U3oO/d1337ekl25c3?invite=cr-MSxsRzIsMTM2NTAzMzkzLA 
Randomly i dont get paid for my dogwalks

### Expected Behavior

glitch fixed

### Steps To Reproduce

fix the issue

### Anything else?

https://medal.tv/games/gta-v/clips/1qqylJdJA9U3oO/d1337ekl25c3?invite=cr-MSxsRzIsMTM2NTAzMzkzLA

**Comment by fkk-cz** [comment]
> Steps To Reproduce

fix the issue

It would be **great** if actual steps were provided, or at least any specific information as to what might actually cause this.
