### ISSUE TITLE
Small Gas Run at 374 Bug

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The small gas run that takes you to 371 does not show the red truck indicator for you to press E
![Screenshot 2023-09-03 030343](https://github.com/fkk-cz/noire-public/assets/92474477/b23395d6-9a01-43fa-abd0-a1621580f94a)

### Expected Behavior

For it to work

### Steps To Reproduce

n/a

### Anything else?

n/a

**Comment by cxerq** [comment]
Ma’am that is because you don’t have the trailer on the back! If a run is too close to the station you need the trailer.

**Comment by Ell34** [comment]
> Ma’am that is because you don’t have the trailer on the back! If a run is too close to the station you need the trailer.

Bruh
