### ISSUE TITLE
[BUG]: Dog walking job at 229 Not working correctly

### ISSUE THREAD

**Issue by FilipRusiecki** [fkk-cz/noire-public#1401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dog is unable to go on the ledge, which causes player to be unable to finish the job

### Expected Behavior

player should be able to finish the job

### Steps To Reproduce

Get the dog job to be spawned at 229.

### Anything else?

n/a

**Comment by fkk-cz** [comment]
Dogwalking jobs are house-specific, this isn't a job issue.
