### ISSUE TITLE
[BUG]: Felons still able to buy guns 

### ISSUE THREAD

**Issue by Poochthebozz** [fkk-cz/noire-public#1405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently felons are still able to buy legal guns to buy legal guns. After you are convicted you can just buy your license again.

### Expected Behavior

If you are a felon, it should not allow you to buy a gun. 

### Steps To Reproduce

Get convicted a felony
Go to the store 
Purchase your license
Buy any gun

### Anything else?

No

**Comment by fkk-cz** [comment]
This has apparently been an issue since the new MDT was first rolled out. Surprised no one reported this until now, thanks.
