### ISSUE TITLE
[BUG]: <clothing disappears when logging back in >

### ISSUE THREAD

**Issue by ItzJB1** [fkk-cz/noire-public#1411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i log out and log back into the game my shirt and mask come off of me. then they are invisible and and cant be re put on at the clothing store i have to goto a wardrobe and pick the saved clothes. when i do that my tattoos come off and i have to go to the tattoo shop put them back on and sometimes the left arm sleeve that i use doesnt show up so i have to use something different for the day.

### Expected Behavior

for my clothes to not disappear everytime i log in 

### Steps To Reproduce

n/a

### Anything else?

no

**Comment by fkk-cz** [comment]
This seems like a client-specific issue -- try creating a general support ticket.
