### ISSUE TITLE
[BUG]: <Custom title here>

### ISSUE THREAD

**Issue by Slothami** [fkk-cz/noire-public#1414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the rebalance of cars and every civilian car that seem "too good" getting nerfed i think it's not fair that cops are still able to just de-spawn/ get rid of groups of NPC cars during chases. This is completely unrealistic and not close to real life at all, let alone a huge advantage to cops and disadvantage for criminals as they need to swerve around and avoid NPC cars with huge consequence if they hit one while cops can simply speed through the middle of them and they will all disappear out of their way just off of their lights proximity.

### Expected Behavior

This feature should be removed. Cops should have to avoid all obstacles the same as criminals and do not need this huge advantage along with all their other ones.

### Steps To Reproduce

Cops in a high speed chase for any reason
Criminal swerves around a single or group of NPC cars as to not crash and break their car
Cops drive through the middle of the group of NPC's as fast as they can and all of the NPC cars disappear
Criminal hits one NPC car and their car breaks down then jail

### Anything else?

No

**Comment by spliff808** [comment]
That feature you are talking about will not get rid of cars at high speeds more less even the locals in front, I believe it’s simply to prevent a build up of traffic during traffic stops as “locals” don’t have the intelligence to yield to them. Police need to yield to the same obstacle as civilians during a chase.

**Comment by Slothami** [comment]
That might have been the original intention but its definitely getting used/abused during chases now. I can compile a bunch of clips of this getting used in chases if your really interested.

**Comment by spliff808** [comment]
Idk, from personal experience and from my team experience I’ve never seen it happen to me nor them, we find locals be spawning in front front of us and we have to swerve etc but not to worried about your clips, was just providing my perspective

**Comment by Slothami** [comment]
Yea im not saying your one of the people who abuses it but there definitely are people who do and like i said if you need evidence just lmk.

**Comment by Plasre** [comment]
The thing your talking about, i do not think is an intended feature, its just simply that now if cops turn their lights and sirens on, for some reason it makes local vehicles despawn, cops literally cant cardel vehicles while going above 10miles an hour (dont quote me on the speed as i dont know the exact speed but above a certain speed which isint high cardel becomes disabled.)

**Comment by DarkFan5** [comment]
As someone who drives emergency vehicles(amr) the despawning isnt giving them an advantage during chaces, ive been hit by or hit locals multiple times. Another thing with the emergency lights/sirens is that it freaks locals out, they swerve into you for no reason. 

The lowering of the speed is to make chases more fun and realistic. Get witty with your escapes, try to break some ankles. Dont just shoot it down one street. take corners, learn cop behaviors during the chase. If a cop is on your ass all chase take a last sec turn and you'll break his ankle

**Comment by fkk-cz** [comment]
The purpose of this 'feature' is to prevent ambient vehicle traffic buildup when police are on traffic stops, which allows for scenes to run a lot more smoothly. There is a maximum speed where vehicles get deleted -- this isn't something designed to delete vehicles to make it easier in pursuits.
