### ISSUE TITLE
[BUG]: Courthouse doors getting locked after reset 

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire-public#1416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the doors to the main hall in the courthouse keep getting locked after every restart. This wasn’t a thing before, and someone needs to go unlock the doors after restart aka tsunami or else no one can get in and pay their fines.

### Expected Behavior

The doors should not automatically get locked after tsunami. There’s no way for a normal civ to unlock the doors and pay their fines if the doors are locked.

### Steps To Reproduce

Go to courthouse.. try to go inside right after tsunami..

### Anything else?

No

**Comment by fkk-cz** [comment]
Front doorlock was removed.
