### ISSUE TITLE
[Weazel News Request]: <Weazel News Helicopter Camera Request>

### ISSUE THREAD

**Issue by danielwippo** [fkk-cz/noire-public#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At the Moment the Weazel News Helicopter doesn't have a working news camera.
This makes it harder to record news for the city.

### Expected Behavior

To get a Camera similar to the one that Air1 has.
That you can fly the Helicopter and just have to press a key and that opens up the camera view and you can move it free around.
And if possible don't have any overlay over the screen, so we are able to put your own custom ones over it. depending on what we need.

### Steps To Reproduce

Not sure how the code for the camera works.
But I believe in you guys that you can make it.

### Anything else?

This would be a great addition and improvement for Weazel News, and we can make some cool stuff for the City.

**Comment by fkk-cz** [comment]
Helicam has been updated, the `newsfrog` has a camera now.
