### ISSUE TITLE
[BUG]: <gas station 402 >

### ISSUE THREAD

**Issue by SNIFFDEBUSSY** [fkk-cz/noire-public#1422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on 11/22 i withdraw money from gas station 402 $93,072 I don't know if it went through, and I know for a fact that $ 1,666  was also not deposit into my account. 

### Expected Behavior

withdraw money should go into my account 

### Steps To Reproduce

press withdraw

### Anything else?

no and thank you.

**Comment by fkk-cz** [comment]
This seems like an individual issue -- create a general support ticket instead.
