### ISSUE TITLE
[BUG]: A new snowball pull animation

### ISSUE THREAD

**Issue by fisheeeee** [fkk-cz/noire-public#1426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when you pull a snowball out you do the same animation of pulling a weapon out, this can be a problem for people just pulling out a snowball and someone shooting or police shooting thinking you are pulling a weapon out, its also unrealistic pulling a snowball out of your back pocket.

### Expected Behavior

pull out the same way you pull another melee out or something that doesnt seem like you are pulling a weapon

### Steps To Reproduce

1. pick up a snowball
2. pull out snowball
3. get shot because a cop thinks you are pulling a gun

### Anything else?

no

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/497bbebf798d00674a86a8d7912f827e468725d7.
