### ISSUE TITLE
[BUG]: <AMR MedEvac Helicopter pull out broken>

### ISSUE THREAD

**Issue by danielwippo** [fkk-cz/noire-public#1428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When getting a Helicopter to take north calls, the Helicopter is stuck into the Ground and it is not letting you take of.
This is for all three Hospitals. [Zonah, Pillbox, Sandy]

Videos are in support-4768

### Expected Behavior

That if you pull out a Helicopter that you just can fly away.

### Steps To Reproduce

N/A

### Anything else?

Already opened a ticket as well.
support-4768

**Comment by fkk-cz** [comment]
Nothing was changed for job vehicle spawning. Only related change was adjustments to the heli handling, which has been reverted in https://github.com/fkk-cz/noire_vehicles/commit/4a86478d851a9f499d08a371b5cc867a7c432c5e.

**Comment by danielwippo** [comment]
Helicopters are still broken. When taking out a Heli, the Landing gear is still stuck inside the ground.

**Comment by fkk-cz** [comment]
Spawning the exact same `amrheli` works in a local server. Have you tried buying a new one?

**Comment by danielwippo** [comment]
Just tried it, but it didn't help.
Same issue. Also tried to pull out the new Helicopter at all Hospitals and I had the same problems.
https://medal.tv/games/gta-v/clips/1IlrHV8p-_ypht/d13374XxaOus?invite=cr-MSw2dnUsMTU3MDMyMDQ1LA

**Comment by danielwippo** [comment]
Checked again today and it is fixed now. Thank you very much.
