### ISSUE TITLE
[BUG]: <Taxi keeps breaking down when i pull it out the taxi depot>

### ISSUE THREAD

**Issue by Kaykanjester** [fkk-cz/noire-public#1430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It’s annoying that i always have to buy a repair kit to repair my taxi or to have to buy a new taxi and find it in the big list of taxis i have.

### Expected Behavior

Can’t you add a repair zone in the taxi depot or just make it so it doesn’t break down?

### Steps To Reproduce

Can’t you add a repair zone in the taxi depot or just make it so it doesn’t break down?

### Anything else?

Nothing else

**Comment by fkk-cz** [comment]
I can't recreate this issue, have others experienced this?

**Comment by highfkyo** [comment]
i will vouch that myself and basiclly every taxi driver experience this issue resulting is some indiviuals just buying multiple taxis it does happen often

**Comment by BunghaGTA** [comment]
> I can't recreate this issue, have others experienced this?

Everytime I pull out a taxi its breaks down in less than 15 seconds.

**Comment by TheBottomFragger** [comment]
> I can't recreate this issue, have others experienced this?

I have already reported this issue before, with a clip and it couldn’t be recreated back then either. Can confirm that it still happens, sadly. It’s either that the taxi spawns in broken/smoking or that the meter doesn’t spawn inside, but on top of the car.

**Comment by fkk-cz** [comment]
Issued a change on 12/20 to address this, are people still experiencing this issue?

**Comment by TheBottomFragger** [comment]
> Issued a change on 12/20 to address this, are people still experiencing this issue?

Ppl are still having issues
