### ISSUE TITLE
Body armor protecting against headshots

### ISSUE THREAD

**Issue by Plasre** [fkk-cz/noire-public#1431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This wasn't the case a few months ago, but now for some reason body armor has started to protect against headshots, mainly the pd armor, now to kill officers it takes 2 headshots, the death animation is played once you headshot a cop 1 time, then they will magically respawn and if you headshot them again they will die. This mainly happens with pistols, dont know if its the same for larger calibers.

### Expected Behavior

1 headshot should kill anyone under any circumstance, and body armor should not be protecting against headshots.

### Steps To Reproduce

1. Get a cop to put on body armor.
2. Headshot them with a pistol.
3. See what happens.

### Anything else?

https://medal.tv/games/gta-v/clips/1vYqzE8eKjYDmi/d1337NX1fg0u?invite=cr-MSxvc0UsMTMxMDU0MTMs This is a pretty old clip, but it displays the issue very well.

**Comment by fkk-cz** [comment]
Armor will now only protect the torso, gunshots to any other part of the body will now inflict health and armor damage. Headshot damage has been fixed as well.
