### ISSUE TITLE
[BUG]: Attorney Pay DOJ

### ISSUE THREAD

**Issue by notJudgeTy** [fkk-cz/noire-public#1435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attorney not currently paid hourly and you start to slowly not want to keep your very high hours with that being in place, which results in attorney is not staying on longer than six weeks.  

### Expected Behavior

For attorneys either be able to have a invoice system like the clubs that goes as high as charging $10,000 and the person to be able to accept the charge because we can’t just say everyone can’t pay an attorney whenever there’s a very high percentage that actually can.  

### Steps To Reproduce

Add the ability for attorneys to be able to use the card reader to charge. 

Or

attorneys go back to getting paid so we can retain attorneys with their only issue them having is that they’re working hours on end but not getting paid whenever it’s a more demanding job than any of the restaurants that do currently get paid $1000 an hour or they have some form of way they can get paid. 

### Anything else?

Thank you anything to be able to keep attorneys happy so we can retain them they’re all great. Good gift for them for the holiday season.

**Comment by fkk-cz** [comment]
Defense attorney is more of a RP job and does not exist as a moneymaking whitelist, all payments will be handled privately between the client and the attorney.
