### ISSUE TITLE
DMV guard 

### ISSUE THREAD

**Issue by highfkyo** [fkk-cz/noire-public#1438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

can we get the guard infront of the dmv taken out because its down in the hood people sell all around there i just lost weapons and drugs because i was across the street in the parking lot and a local tried fighting me so when i went to defend myself the guard shot me down from super far away and i lost all my stuff

### Expected Behavior

get rid of this dmv guard do to it being down in the hood 

### Steps To Reproduce

be around the guard
defend yourself
get shot down by guard

### Anything else?

it just dosent make sense to have this guy down there when that place is considered the hood

**Comment by fkk-cz** [comment]
This is not a bug, the guard was placed to protect new players from getting robbed or killed at the DMV and will not be removed.
