### ISSUE TITLE
make a job that dosent need a drivers license

### ISSUE THREAD

**Issue by dinmamma100** [fkk-cz/noire-public#1439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

right now all the jobs technically needs a drivers license and when its suspended you cant really work. 

### Expected Behavior

add a job that you dont need a car for like construction, office job or like a finance idk 

### Steps To Reproduce

go to job center
look at the jobs 
add new job

### Anything else?

thank you for looking at this

**Comment by fkk-cz** [comment]
This isn't a bug or issue -- getting your driver license suspended is part of the game. Drive better and avoid getting tickets if you don't want your license suspended.
