### ISSUE TITLE
Taxi as a legal job

### ISSUE THREAD

**Issue by DeannaReign** [fkk-cz/noire-public#1444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently Taxi is a whitelist and doesn't have many people clocking in throughout the day and people are forced to run across the city or rely on friends 

### Expected Behavior

Id like to see taxi be a legal job so anyone can clock in and give rides that way there's a very increased chance of finding a ride when you get stranded

### Steps To Reproduce

Remove the taxi whitelist then make its a legal job

### Anything else?

N/A

**Comment by TheBottomFragger** [comment]
We all know how it went last time taxi wasn’t a WL job.. lol

**Comment by notJudgeTy** [comment]
Bad idea… I’ll just clock in and have hostages.. I mean slaves.. I mean…… current taxi is great as it is..

**Comment by DeannaReign** [comment]
I wasn't here when taxi wasn't a WL so i'm not sure how it went and as far as saying current taxi is great I wouldn't say so since they are rarely clocked in and even when they are they only accept certain rides and they usually aren't the ones that really need it like up in sandy or paleto

**Comment by TheBottomFragger** [comment]
We have a clock in and clock out bot that shows when people are clocking in. I personally think that people are active considering they have other WL jobs, are in gangs or actually got a life outside of the game. 

The reason for the calls up north not getting accepted is that they have been told that they don’t have to accept the calls when it’s busy in city. We can’t accept people to be able to take all the calls if it’s busy. 

Another problem is that people like to move around after calling for a taxi, so when we do end up getting to the location, they’re not there. Nothing that can get done with this.

**Comment by fkk-cz** [comment]
Taxi will not be moved into a public job for reasons stated above.
