### ISSUE TITLE
Field of View on the Heavy revolver

### ISSUE THREAD

**Issue by crewerobin** [fkk-cz/noire-public#1449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Field of view on the heavy revolver is very zoomed out and can kind of see around you alot more dont really know if this is a bug or not though

### Expected Behavior

not to be as zoomed out and just be like normal guns when aimed in

### Steps To Reproduce

Fix the gun if this is an issue

### Anything else?

https://medal.tv/games/gta-v/clips/1R0h39OJLBtRor/d1337AwQMsIz?invite=cr-MSxDZXQsMTQ5OTIxNzI0LA

**Comment by Kaykanjester** [comment]
You can just press V while zommed in and its fixed and it doesn’t change much the fact the FOV is higher when you aim it actually makes it harder

**Comment by notJudgeTy** [comment]
Also, what about removing the baby sig completely and replacing it with the heavy revolver? People would be more inclined to purchase the heavy revolver. 
Additionally, on the casino wheel, could offer the worst gun prize possible, the Beretta vs the current baby sig.

**Comment by DoubleCHINjohnny** [comment]
adding the heavy revolver back to the gun shop would be a great idea since there arent really any good guns besides the ar 15 fn 1911 and the P226. The heavy revolver isnt really hard to obtain either might aswell make it easier by adding it to the gun store
