### ISSUE TITLE
Metal detecting not receiving the money.

### ISSUE THREAD

**Issue by bigbhaii** [fkk-cz/noire-public#1451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i go search the box and metal detecting it does not let me get the money

### Expected Behavior

To obtain the cash given to me when I search the bost

### Steps To Reproduce

When at metal detecting to fix the issue when you hold your tab muscle it should only be the metal detector in there nothing else. This includes your id and phone. Put it all in the other pockets clicking your f2 muscle.

### Anything else?

Nope

**Comment by fkk-cz** [comment]
> When at metal detecting to fix the issue when you hold your tab muscle it should only be the metal detector in there nothing else. This includes your id and phone. Put it all in the other pockets clicking your f2 muscle.

The ability to open the inventory, or use any hotkeys, is not related at all to what you are describing.
