### ISSUE TITLE
[BUG]: Valet Allows for the Same Vehicle (Same Plate) to be in two different locations results in false impounds

### ISSUE THREAD

**Issue by xDelays** [fkk-cz/noire-public#1452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Valet'ing a vehicle allows for you to get a vehicle without it actually physically being taken out of garage list, leading to the ability to have two of the same vehicle out at once. This results in false impounds alwell considering one vehicle can get bricked during the valet while the other vehicle is perfectly fine somewhere else.

### Expected Behavior

Valet'ing a vehicle would actually take the vehicle out of the garage preventing the ability to have two of the same vehicle out and about. 

### Steps To Reproduce

Valet said vehicle, wait for it, recieve keys. drive to garage it was located/stored. Pull the same vehicle from garage. now you have two of the same vehicle same plate. 

### Anything else?

https://streamable.com/6ffq0g

Clip to demonstrate known issues.

**Comment by fkk-cz** [comment]
Fixed, thanks for pointing this out. All vehicles are accessible now at every public garage -- regardless of where it was last stored.
