### ISSUE TITLE
[BUG]: <Towtuck Not towing>

### ISSUE THREAD

**Issue by SurgeMMO** [fkk-cz/noire-public#1453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Towtruck is either not hooking or dropping the cars after connecting. I've tested this with City Cars and Player cars. Both player-owned cars where I don't have the keys or do have the keys. The Longest towed car before it dropped was a Mission Gopostal van.

![TOWTRUCK](https://github.com/fkk-cz/noire-public/assets/158855672/fb1c5a80-ca8f-42f9-813f-02baa6ac070f)

### Expected Behavior

Being able to connect and tow an open vehicle 

### Steps To Reproduce

Get the "Towtruck"
Lower the hook (Ctrl)
Connect (snap)
Raise the hook (Shift)
Vehicle will drop off the hook or not connect

### Anything else?

Fixing this will allow players to tow vehicles with broken wheels to despawn points went DOT isn't available

**Comment by fkk-cz** [comment]
The vanilla `towtruck` or `towtruck2` is not good at towing vehicles. This is a known issue even in SP and cannot really be fixed.
