### ISSUE TITLE
[REQUEST]: Make Hotwiring Easier, its IMPOSSIBLE!

### ISSUE THREAD

**Issue by g3kooner** [fkk-cz/noire-public#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The speed of the red tick is way too fast towards the final few rounds of picking, additionally, the blue area to get it correct becomes so small. Not only this, but the spot on the circle where the blue area spawns while lockpicking is random and I truly think sometimes no human could react fast enough due to the fact that the key you had to press (W, A, S or D) is also random. I have a good amount of hours in the city and trust me when I say I frustratingly bought 10 multipicks and couldn't get 1 successfull.

### Expected Behavior

We are humans, not aliens and for a human to react fast enough, press the right key and that within the correct blue spot on the circle is near to impossible. Don't forget that you only have 1 try as well, otherwise the pick breaks (once red tick passes blue area your done). I request this made a bit easier to the point where a human with an average reaction time can hotwire cars at a 50% rate at least, please.

### Steps To Reproduce

1. Grab 5 Multipicks
2. Get inside an unlocked conventionally hotwireable car
3. Try to play the game to wire the car, I bet you can't get 2/5 attempts successful

### Anything else?

N/A

**Comment by BunghaGTA** [comment]
just get good LMAO

**Comment by g3kooner** [comment]
> just get good LMAO

Looks like someone gets their car stolen often...
Be fair, if you can take out 4 multipicks and get at least 2 successful on video I'll close the issue. Let me know how many tries it takes.

**Comment by fkk-cz** [comment]
The difficulty factor is set to easy-medium for all key presses. This really can't get much easier and isn't a bug or an unintentional change.

**Comment by Kaykanjester** [comment]
Changing it was just dumb bring back the old ways
