### ISSUE TITLE
Panic button at Bean Machine & Clubs

### ISSUE THREAD

**Issue by notJudgeTy** [fkk-cz/noire-public#1457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Only VU and the Casino have panic buttons. 

### Expected Behavior

For Bean Machine (only city restaurant that doesn’t have one)  and all clubs to have working panic buttons like VU and the casino, BS and Atom

### Steps To Reproduce

Adding panic button to the high crime bean machine as of recent and the clubs having that ability as well. 

### Anything else?

Thank you. Mentioning things to help the city out.

**Comment by Fqper** [comment]
I own bean machine and we do not want or need this. Thank you.
