### ISSUE TITLE
Motorcycle tweaks 

### ISSUE THREAD

**Issue by MAYAN-MARK** [fkk-cz/noire-public#162]
Fix the collision issues with a few of the Harleys.

Add storage to the bikes that have saddle bags.

Buff the speed on virtually all the Harleys as most top out ar 90-100

Atm there is no reason to buy anything but the LCC KRUST as it out performs every other Harley Davidson style bike by a very long shot. 

Motorcycle are light and powerful vehicles and shouldn't be out ran by eco cars.

**Comment by fkk-cz** [comment]
open an issue https://github.com/fkk-cz/noire_vehicles/issues
