### ISSUE TITLE
Hide HUD Issue

### ISSUE THREAD

**Issue by AnassaHecate** [fkk-cz/noire-public#173]
/hidehud in the chat only hides part of the hud. The "Worker" text in the top right goes away but the rest of the HUD stays.
Edit: The HUD also does not stay hidden, it eventually comes back on by itself. 

Unless this was intended and not a bug I think it should hide the whole thing, would be nice for cinematic views.

**Comment by fkk-cz** [comment]
No idea why `/hidehud` didn't remove the postal, location, and time. Thanks for pointing this out.

Fixed in https://github.com/fkk-cz/noire/commit/0d207ad39cf8a0777a0452044aa30c7a9e3d3c30.
