### ISSUE TITLE
PDM NOT LETTING SELL CARS BACK 

### ISSUE THREAD

**Issue by GoofyMofo** [fkk-cz/noire-public#188]
Went to sale one of my supporter cars back to PDM and it says the vehicle dosent own to me and only supporter cars can be sold here. I clearly own the car and it’s a supporter. Tried restarting my game and putting it in garage etc

**Comment by fkk-cz** [comment]
This is usually a client issue related to:
- FiveM not being an authorized app in Discord
- Not having Discord open when launching FiveM
