### ISSUE TITLE
Sanitation

### ISSUE THREAD

**Issue by Zoraketh** [fkk-cz/noire-public#194]
The stops that have no trash to pick up seem to not register that fact and does not give you the next location. Having to go and pull out a new trashmaster
![Landscaping207](https://user-images.githubusercontent.com/92574732/141048629-bd86e2ec-5b18-41b6-95c9-5215b74091e2.png)

**Comment by fkk-cz** [comment]
The title of the issue is **Landscaping**, but you are showing a screenshot of the ...sanitation job?

**Comment by Zoraketh** [comment]
![image](https://user-images.githubusercontent.com/92574732/141411703-5bac19c1-6870-44b9-9c1a-3974b8af3263.png)
Yes I put the wrong name

**Comment by Zoraketh** [comment]
Same problem again. One of the stop that has no trash, is broken. It did not tell me there was no trash and give me another stop.

**Comment by Zoraketh** [comment]
Someone else just pulled up and it progressed to the next stop.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/208
