### ISSUE TITLE
Sasquatch Popping Heads

### ISSUE THREAD

**Issue by wetweebs** [fkk-cz/noire-public#195]
Something about the Sasquatch, or something that can be done while being a Sasquatch causes anyone near that player to instantly crash. Happened to multiple EMS and another time to someone on PD. I believe someone going by Rated R would know the cause, but the Sasquatch should be disabled until the issue can be identified and fixed

**Comment by fkk-cz** [comment]
Do you have crash dumps?

**Comment by wetweebs** [comment]
> 
> 
> Do you have crash dumps?

A memory dump file? i think so

**Comment by fkk-cz** [comment]
Upload it.

Can you reproduce this issue? I'm not going to start blacklisting things based on speculation

**Comment by wetweebs** [comment]
dump file is apparently isn't supported. I believe it was caused by pulling out a gun? the dude definitely knew it was going to happen, so should be able to reproduce it. I can't do it myself b/c I can't be Sasquatch. He was also changing colors at the time, not sure if it was related. here is a screenshot of the dump, not sure it will be helpful. 
![Screenshot 2021-11-11 000756](https://user-images.githubusercontent.com/90438751/141261445-795a81ea-572a-42d8-9bb2-7321a36e1a8c.png)
ed

**Comment by fkk-cz** [comment]
Coming back to this - I doubt this is caused by a vanilla ped model, most likely some add-on weapon model that was exported with a lot of errors (empty buffers?)
