### ISSUE TITLE
Drug Sells

### ISSUE THREAD

**Issue by KCurt420** [fkk-cz/noire-public#205]
I think we need to have HP count towards city drug sells, half the time they in the city anyways and show up to drug calls quite often actually! And late night usually there’s no pd on but there’s hp and there in the city so it makes since to have them count towards it! Also all of PD just be getting off all at the same time which makes selling even harder to do! Idk of HP is gonna be in the city so much they need to count towards the city things!

**Comment by KCurt420** [comment]
Or at least make an area in sandy or paleto where we can sell out there again! We use to be able too idk why it was taken out

**Comment by fkk-cz** [comment]
Drug sales are being reworked, along with the gathering/production process for all drugs, except meth. https://github.com/fkk-cz/noire-public/issues/297
