### ISSUE TITLE
Trash Job Issues!

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire-public#208]
I've seen it brought up in the discord quite a few times that trash has a few broken locations so I clocked in and went to find them!

This one I wouldn't really count as "broken" but the poles scrap the side of the trash master often when you are pulling in so there are ALWAYS broken down trashmsters left inside the little area. Removing the poles might help!
![image](https://user-images.githubusercontent.com/83321790/141923162-bb2f0e25-f462-4cb3-a8f8-5937e7b69b7f.png)

This one is also not super broken but when the boxes topple over it makes it hard to get into the dumpster, and once upon a time, it sent me through the map...
![image](https://user-images.githubusercontent.com/83321790/141923361-15308491-ff98-4212-9f46-7146fdd809c6.png)

This job is behind the bus station, the yellow circle appears right in front of the big dumpster that you can see in the photo, and then the red circle just never appears anywhere!
![image](https://user-images.githubusercontent.com/83321790/141923240-99d0b1f8-cca2-4dba-a538-216a7cd0afa1.png)

This is the last one that I know of, but my route never took me there so Cortez assisted. But when you pull up into the circle it says "No trash available for pickup at this location" (as you can see in the picture) and then sends you to the next pickup location.
![image](https://user-images.githubusercontent.com/83321790/141923418-b6843eaf-1a62-4627-b30b-faab2558919d.png)

**Comment by EveEnchooli** [comment]
![image](https://user-images.githubusercontent.com/83321790/142348007-a7fa316c-60d8-4374-b5be-6949ff2b654e.png)
Found one more after making this originally this has the same issue as the one behind the bus station

**Comment by byu26** [comment]
The trash location in the 3rd picture is in the alley behind and to the right of the truck.

**Comment by EveEnchooli** [comment]
> The trash location in the 3rd picture is in the alley behind and to the right of the truck.

Interesting I ran all around! Someone was saying that it only shows up sometimes? and that it depends on the dumpster lol

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/66aef06c2b2c726beec083ccd183ff424f737993.
