### ISSUE TITLE
Car Customization issue (1967 Shelby GT500 Eleanor)

### ISSUE THREAD

**Issue by Arcabian** [fkk-cz/noire-public#212]
I've purchased the 1967 Shelby GT500 Eleanor and there is no customization apart from the color and turbo, the turbo modification also  gets removed when the car is stored, there are updated versions of this car and i was wondering if they could be added so the car doesn't feel so disappointing.

**Comment by fkk-cz** [comment]
Vehicle related issues need to be posted to the vehicle repo: https://github.com/fkk-cz/noire_vehicles/issues
