### ISSUE TITLE
Cant Purchase cars at used car lot after pleaing not guilty 

### ISSUE THREAD

**Issue by BingusX** [fkk-cz/noire-public#238]
Hey so the issue is that i cant buy cars at used car lot but you have fixed the issue where people can buy vehicles when they plea not guilty but only buy cars at pdm not used car lot and evey time I tried to buy one at used it would say that i have outstanding charges even tho i dont have any bills to pay and i cant reclaim my car too so i hoping if you can fix it.

**Comment by fkk-cz** [comment]
Removed restrictions on purchasing used vehicles with outstanding charges.

https://github.com/fkk-cz/noire/commit/7d0d88e6aa7414f00f9ad63244e7185949ec21c5
