### ISSUE TITLE
Hotwiring Cars in Safezones

### ISSUE THREAD

**Issue by Stagonium** [fkk-cz/noire-public#241]
The implementation of cars not being able to be lockpicked in safezones was incredibly helpful, but if you are at a safe zone, such as mining, or the mining sell zone, and you unlock your car to get your supplies, someone can sit in the driver seat and use the multipick to hotwire it despite being in the safezone. Since it is a safezone you are unable to shoot them or threaten them to leave your property alone.

Fix would be to limit multipicks in safezones the same way that lockpicks are :)

**Comment by ZacLuxton** [comment]
This is fixed in a recent update
