### ISSUE TITLE
Disappear gun

### ISSUE THREAD

**Issue by Yaboytony7** [fkk-cz/noire-public#256]
https://medal.tv/games/gta-v/clips/73601964/d1337rlpTceE?invite=cr-MSxHTU0sMjI2NTI1ODks this happened to me and now I lost that forever which is just annoying, other people told me it's from picking it up and dropping it fast, lost so much on that for a dumb glitch

**Comment by fkk-cz** [comment]
This video doesn't show anything except people using the clothing store for unintended use (to reset their health). Nowhere in the video does it show a weapon in your inventory before resetting your ped
