### ISSUE TITLE
Electric Vehicles

### ISSUE THREAD

**Issue by Minority9999** [fkk-cz/noire-public#269]
2020 Mercedes Benz EQC400 breaks once using a repair kit. Doesn't allow me to drive vehicle.

**Comment by fkk-cz** [comment]
Make an issue on the [vehicle repo](https://github.com/fkk-cz/noire_vehicles/issues)

**Comment by viigyD** [comment]
Your vehicle needs to have fuel in it, I know it sounds counterintuitive for an electric car, but if your fuel is 0 and your vehicle breaks down you will not be able to start it back up once it's repaired. I had the same issue with my tesla roadster, just had to add some gas to it.
