### ISSUE TITLE
Truck bug

### ISSUE THREAD

**Issue by AustinM0527** [fkk-cz/noire-public#284]
![93038375-992A-4C5C-B3F4-C591397DF5BC](https://user-images.githubusercontent.com/95545758/144722108-9d9f5f86-b902-4031-9e38-8e6795612a36.jpeg)
I tried to customize my truck, when I put a cage in, it took my wheels and doors off and I fell through the map and died

**Comment by fkk-cz** [comment]
What is the exact name of this vehicle? That cage upgrade needs to be removed.

**Comment by AustinM0527** [comment]
2006 GMC Sierra

**Comment by AustinM0527** [comment]
When the cage is removed, will it fix my truck or will it be stuck like this?
