### ISSUE TITLE
Mountain Lion pelt

### ISSUE THREAD

**Issue by MrUnlife** [fkk-cz/noire-public#296]
are we gonna be able to sell mountain lion leather at all soon? there seems to be little to no value going hunting at this point. it all sells for so little and you can't carry much either

**Comment by Pro2gy** [comment]
i thought u can. its just exotic so u have to sell it to a certain buyer

**Comment by ZacLuxton** [comment]
see above, its exotic so u have to find the other guy. im not going to say where it is but it's near the main sell point

**Comment by MrUnlife** [comment]
I found it in the city but forgot to reply to this, I appreciate it!
