### ISSUE TITLE
Selling meth on F-block 

### ISSUE THREAD

**Issue by Proudcat1** [fkk-cz/noire-public#297]
Not sure if it's intentional but the new meth can't be sold over on f block only on the beach. I didn't know if this was something that was a mistake or factored in the cause for the longest you couldn't sell coke at the beach. To which we thought was intentional but it was just the fact you didn't know that, that was an issue.

**Comment by GoofyMofo** [comment]
from my understanding you always could only be able to sell meth and coke at the beach. f block is only to sale weed

**Comment by Proudcat1** [comment]
No you can sell coke and old meth at f block, just not new meth

**Comment by fkk-cz** [comment]
Drug sale zones, along with the whole gathering/processing system, will be changed soon.
