### ISSUE TITLE
Slots at the casino still don't pay out correctly

### ISSUE THREAD

**Issue by LethalTrade** [fkk-cz/noire-public#301]
https://medal.tv/games/gta-v/clips/74606099/d1337LUu9WGF?invite=cr-MSxxQjEsMzM0MzM3NTMs

For some reason every time I try slots sometimes it gives payouts and sometimes it doesn't.

**Comment by fkk-cz** [comment]
What specifically is not paying out correctly?

**Comment by LibexiL** [comment]
Yeah im missing like 280k+ 

https://www.youtube.com/watch?v=rSfQgt62F7w

This is from when the were "originally" broken

**Comment by LethalTrade** [comment]
> What specifically is not paying out correctly?

i will hit a single diamond and get my 250 back like its supposed to then 2 spins later I hit a single diamond again and get nothing. Also sometimes I hit 2 diamonds and get 2500 like normal and then sometimes I hit 2 diamonds and get 250 or nothing.

**Comment by fkk-cz** [comment]
That's because the ordering of the diamonds matter. Refer to the low quality image below, showing the payouts for that particular slot machine.


![image](https://user-images.githubusercontent.com/74131024/145344898-55576e90-3d0e-4e20-8591-ee84a6a2c636.png)

**Comment by LethalTrade** [comment]
> 

ok I was unaware that's who it worked. I was basing it off of how the slots work in GTA online. Thank you for clearing that up
