### ISSUE TITLE
Car has no upgrades

### ISSUE THREAD

**Issue by mk3ext** [fkk-cz/noire-public#309]
The 2017 Dodge Charger from PDM in the Dodge section has no upgrades in Los Santos Customs apart from Turbo?

Not sure if this is intended, but would be great to have as the car breaks if you hit a lamp-post whereas others don't

**Comment by fkk-cz** [comment]
Make an [issue](https://github.com/fkk-cz/noire_vehicles/issues) on the vehicle repo
