### ISSUE TITLE
Carry glitch

### ISSUE THREAD

**Issue by Lucid2001** [fkk-cz/noire-public#332]
Compensation Log
Lucid_19 died.
Server ID: 22
Steam ID: steam:110000146428ccc
Cash: $95
Dirty: $0
Inventory: Phone x1 Repair Kit x1
Loadout: Bat Double-Action Revolver Katana Musket
Typed up by Wop

**Comment by fkk-cz** [comment]
This repo is for **bug reports** or server-related issues.
