### ISSUE TITLE
Rolling a joint breaks the weed table

### ISSUE THREAD

**Issue by Al0kazam** [fkk-cz/noire-public#333]
Using the weed table and selecting the roll joint option no longer allows you to use the table afterward, either to roll joints or package weed, and requires you to relog to continue using it. The table doesn't respond to you selecting the options anymore, even if you don't have the product, it won't tell you what you require.

**Comment by fkk-cz** [comment]
Thanks for pointing this out. Fixed in https://github.com/fkk-cz/noire/commit/bc4f87c3f8904c16668ed31f01ee833d081fd5f2.
