### ISSUE TITLE
New weed setup! 

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#334]
I know who if this is a bug or intended! But you need to gather 20 Untrimmed Cannabis in order to make 1 pack of weed! I believe it should be 10 or even 5 due to the 3 steps required! Also Ped spawning in F block seems to be broken, As I waited for like 20 minutes to try and sell and Zero peds showed up I tired at Day and night and I left and came back too nothing!

**Comment by fkk-cz** [comment]
> As I waited for like 20 minutes to try and sell and Zero peds showed up I tired at Day and night and I left and came back too nothing!

All scenario peds that exist on this whole block are allowed to spawn. Seems like a **you** problem, as other people were able to sell $30K+ worth of drugs in that area _alone_ yesterday.

![image](https://user-images.githubusercontent.com/74131024/146072835-3ec97939-2627-4bda-9dfb-6d6905bc3f8f.png)
