### ISSUE TITLE
Trunk not working on trailers and certain cars

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#339]
Trunks are no longer opening on trailers or some cars - just says "you have to stand near the vehicles trunk". I've tried positioning myself in different spots and it will not work

**Comment by somedudenamedrush** [comment]
yeah its pretty bad for alot of cars atm gunna assume the (open trunk without vehicle nearby) change in the repo might have messed up alot of trunks

**Comment by Ell34** [comment]
yeah I can only think that'd would be the cause for the bug

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/389
