### ISSUE TITLE
Felony Charges

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#340]
### Felony Conviction Confusion

A few individuals seem to be reporting an issue where felony convictions are not wiped +14 days after the charge. Upon further investigation, it seems that people are having a misunderstanding on _when_ the clock actually starts running.

Example of a common situation: Player receives felony charges from the police today (12/15). After waiting 3 days - and receiving a bench warrant - the player then pleads guilty. The +14 days timer starts **after** the conviction and/or guilty plea, in this case, on 12/18. This means the charge _should_ be expunged on 1/1/2021, which is +14 days after 12/18.

### Possible solution

Felony charges result in an immediate conviction and the timer starts on the same day. 

**Pros**: This would prevent confusion where players who do not plead guilty on the same day they receive charges will have a delayed expungement date.
**Cons**: Players who are falsely charged (officer error, innocence, etc.) will face immediate restrictions such as not being able to purchase weapons from the gun store, and may not be able to seek immediate relief if a judge is not available.

Of course, this can be complete avoided if people simply check their criminal record at the courthouse:

![image](https://user-images.githubusercontent.com/74131024/146288396-4608435c-7931-43b1-8f5f-75f5b0434c90.png)

### Refusing to pay or plead

Another related issue is people running around with tens or hundreds of thousands of dollars in charges, refusing to pay them, and having friends buy them weapons. If arrested, a judge is not always available to force charge the individual.

### Possible solution

Automatically remove firearms licenses upon death, and prevent players from being able to unimpound vehicles with outstanding charges. Basically, make it very restrictive for players who choose to go down this path.

**Pros**: Players can no longer act as if the justice system does not apply to them.
**Cons**: Players who are falsely charged have no recourse if a judge is not available.

**Comment by RockemRobotics** [comment]
At least for the second point, I fully support your possible solution. The con of potentially not having a judge available shouldn't be a long-term problem since there are going to be additional judges in the city in the future.

**Comment by RockemRobotics** [comment]
For the first point about the felon status timer, I'm not sure how I feel about the proposed solution. I don't hate it, but I also can't immediately think of a better solution. For a similar reason as point 2's solution, getting charged with a felony should have some immediate impact so that people don't feel like they can simply ignore the Justice System, but perhaps not the full swath of restrictions until after they plead. This one will take some more thought.

**Comment by RockiBurns** [comment]
I think of being released & being able to plead guilty or not guilty as being released on personal recognizance bond. People with outstanding charges or even repeated charges don't get out on PR bonds.

I think the timer should start once a plead is entered for those who plead guilty. For those who don't pay fines, seize their assets to pay them. Meaning a bolo is put out for their vehicles, which can be impounded to pay their fines.
We could even do auctions for them.
For people who don't enter a plea or plead not guilty & don't show up for court, give them a reasonable server vacation for the charges & auction their assets to pay their fines. The count for having these records expunged begins once they've been caught.

A functional justice system on the server is a double edged sword.

Additionally, I think felons should be able to purchase crow bars & bats at the store where fishing poles can be purchased. I think katanas should be purchasable as well. I'm just not sure where.

It sits strangely with me that police who are felons can still protect themselves on the job, but others can't. I'm not trying to take anything away from officers & their ability to fully enjoy the city. I'm try to come up with a reasonable, non-gamebreaking way for others to stay safe as well.

**Comment by woebud** [comment]
Struggling to come up with a fair solution overall but this is the best I got, maybe something could help:

Felony charge w/intent to harm such as attempted murder, assault with a deadly, etc. = immediate firearms license removal while awaiting potential trial. It would be the same as if someone was charged, sent to jail, released on bond awaiting trial, conditions being they cannot own a firearm as they are deemed dangerous. If pleading not guilty and found not guilty, they receive their license back + the cost of the weapon(s) they lost, etc.

On the flip side, a non-dangerous felony charge would operate as the current state.

Keep the 3 + 14 days until the charge is expunged, but add an automatic UI info box when you are sent to prison explaining your options so there is no confusion on how the process works. (could also add a UI info box at the courthouse that a player could click to read more information about how the process works)

After the hypothetical 3+14 days expires, if there are still outstanding charges to be paid, then implement the system where they cannot unimpound their vehicles, etc. and maybe another 14 days after that, freeze their bank account.

**Comment by RockemRobotics** [comment]
> I think the timer should start once a plead is entered for those who plead guilty. For those who don't pay fines, seize their assets to pay them. Meaning a bolo is put out for their vehicles, which can be impounded to pay their fines.
> We could even do auctions for them.
> For people who don't enter a plea or plead not guilty & don't show up for court, give them a reasonable server vacation for the charges & auction their assets to pay their fines. The count for having these records expunged begins once they've been caught.

I don't know that auctions or impounding to pay fines is needed - though it could be done in the future. The judge's role includes the ability to "force fine" people, which CAN put them into debt. Then the person can choose how to deal with that debt, whether it be selling their assets or working for the money.

**Comment by fkk-cz** [comment]
Based on your feedback and after hearing some ideas, the following changes have been made:

### Jail

Players who go to jail will be forced to go through a series of notification prompts which (better) explains the criminal justice system. After reading the prompts, players are required to enter a plea for any outstanding criminal charges. The jail timer will not start until all charges have received a plea of guilty or not guilty.

Example of a prompt: 
![image](https://user-images.githubusercontent.com/74131024/146331845-ecad2c7c-55ec-4d81-874a-a77dd64b7e28.png)

**If a player pleads guilty to ALL outstanding charges:** Jail sentence timer will start, no further action is needed. Player will become a convicted felon immediately and the 14 day expungement timer will start immediately.

**If a player pleads not guilty to one or more charge(s):** If any whitelisted attorneys or judges are online (indicated by the scales in F10 menu), the player will be teleported immediately to one of the holding cells in the courthouse and the court will be notified. If court is unavailable, i.e. no attorneys or judges are online, the system will fallback on the old process -- the charges will be entered as a not guilty plea and the player will have **72 hours** to request a hearing.

### Fines

As mentioned above, the three primary issues with the fine system was:
- People refusing to pay and letting charges rack up on their account
- People failing to appear and enter a plea within 24 hours, leading to disproportionately high amount of bench warrants
- Not guilty pleas would not automatically convert into convictions after 7 days

The first two issues have been solved, as anyone who is sent to jail on felony charges will be forced to enter a plea to start their sentence. Disconnecting will not work, so don't try it. There should be a **lot** less bench warrants being issued for failure to appear/enter a plea, and should only really apply for traffic citations/infractions. Maybe bringing back automatic BOLOs for bench warrants if they will only be issued for individuals who don't respond to traffic citations? Should be much more managable now. Will need to monitor new bench warrant volume before considering this.

The third issue is also fixed -- the time was also lowered from 7 days to 3 days to prevent people from racking up unreasonable amounts of outstanding charges.

### Misc Fixes and Improvements
- Added box props for prison work locations and extra spots
- Fixed issue where respawning could speed up jail time by _n_ times
- `/unjail` command fixed output

As always, these changes will take effect on next reset and will probably need to be adjusted with time.

**Comment by RockemRobotics** [comment]
> **If a player pleads not guilty to one or more charge(s):** If any whitelisted attorneys or judges are online (indicated by the scales in F10 menu), the player will be teleported immediately to one of the holding cells in the courthouse and the court will be notified

I had a chance to test this system a little bit ago, and have a few minor suggested changes to the system that would help a lot.

1 - Add a capability to automatically transport the person from the holding cell to the front of the courthouse once the person has either been found guilty on charges or had them dismissed. Right now the only way to let them out of the courthouse is to escort them (without handcuffs) through the locked doors, or to leave every door unlocked and trust that they will leave on their own. Automatic transport also solves the issue of dealing with unruly civilians once they are let out of their cells.

1a - I didn't test this, but if someone pleads not guilty for several jailable felonies, what happens I click guilty for one of them - are they immediately sent to prison or does the system wait until I'm done with all of their charges?

2 - Something that will be a big problem if the holding cells get crowded - there is no way to see the name associated with each of the charges on the menu to find guilty or dismiss. Back and forth has to happen between the MDT and the charges menu, or to have a second person there to assist. Adding names/birthdates to the charges menu would simplify this process a lot.

3 - This may just be something I overlooked, but if I were to miss the pop up notification that someone pled not guilty and was transported to the cells, is there a way to pull that information back up or see if I missed something? Like a notification history?

**Comment by RockemRobotics** [comment]
4 - Another thing I didn't test - so I'll learn as I go. If someone pleads guilty to one charge and not guilty to another, they get sent to the courthouse cells. If the second charge is dismissed, when does the person go to prison for their remaining (guilty) charge? The answer to this may already be in the system, but I wanted to at least bring it up here in anticipation of finding out this evening.

**Comment by fkk-cz** [comment]
> 2 - Something that will be a big problem if the holding cells get crowded - there is no way to see the name associated with each of the charges on the menu to find guilty or dismiss. Back and forth has to happen between the MDT and the charges menu, or to have a second person there to assist. Adding names/birthdates to the charges menu would simplify this process a lot.

This is unfortunately not surprising, a possible solution would have a list of names of people who were teleported to court in the F6 menu, sorted by most recent in descending order.

> 3 - This may just be something I overlooked, but if I were to miss the pop up notification that someone pled not guilty and was transported to the cells, is there a way to pull that information back up or see if I missed something? Like a notification history?

There is a way to check notification history in the pause menu under the **game** tab. The list menu would solve this issue.

> 4 - Another thing I didn't test - so I'll learn as I go. If someone pleads guilty to one charge and not guilty to another, they get sent to the courthouse cells. If the second charge is dismissed, when does the person go to prison for their remaining (guilty) charge? The answer to this may already be in the system, but I wanted to at least bring it up here in anticipation of finding out this evening.

Will probably need to bring back a way to manually sentence someone to jail. If someone pleads not guilty to one charge and not guilty to another, they will have to be sent back to prison (most likely on a reduced sentence, depending on whether they were acquitted or not).

**Comment by RockemRobotics** [comment]
> There is a way to check notification history in the pause menu under the **game** tab. The list menu would solve this issue.

You're right - I found it under the pause menu under Info -> Notifications.

Another issue that may need addressing - The few people that have gone to the courthouse cells after pleading not guilty seem to have no idea where they are or if anyone is coming for them. One waited patiently but the other flew out. He'll have fun if he flies back in while no DOJ members are on duty.

**Comment by RockemRobotics** [comment]
An additional potential bug, though this may be intentional. People cannot plead guilty if the fine associated with the charge is greater than their bank balance. One prisoner was forced to plead not guilty for several of his outstanding charges, even though he was more than okay with putting his account in the red.

**Comment by fkk-cz** [comment]
> The few people that have gone to the courthouse cells after pleading not guilty seem to have no idea where they are or if anyone is coming for them.

![image](https://user-images.githubusercontent.com/74131024/146466643-ab6b888f-670f-4fa9-b608-4c6d384f3831.png)

Can't fix people who don't pay attention or read.

Reworked the F6 menu to allow state attorneys and higher to hire (whitelist) law clerks and licensed attorneys, should make the process much easier for everyone to get their job title in game.

Also included the ability to jail players in proximity, and a court docket list that brings up the mugshot and other relevant information for the player in the holding cells.

**Comment by fkk-cz** [comment]
There's been a noticable improvement in the number of bench warrants issued every day. As an example, yesterday there were only a total of 14 warrants issued. Out of the 14, only 10 of them seem to be for regular players, the other 4 players either aren't in the Discord or don't have FiveM authorized. Contrast this with a few days ago, when the average number of warrants issued was around 30.
