### ISSUE TITLE
Targetting system gets stuck

### ISSUE THREAD

**Issue by noyeahsure** [fkk-cz/noire-public#341]
not sure if aware, but when gathering untrimmed, your alt muscle will stay on screen not allowing you to gather anymore forcing you to relog.

**Comment by fkk-cz** [comment]
This isn't a weed-specific issue, I've seen the targeting system remain open after interacting with the mouse, further investigation is needed.

**Comment by CapitalOG** [comment]
i've found it happens if you attempt to do it too quickly afterwards.. also if you try to Alt-Tab during the time you are picking.. Found if you tab back in before the count down and click the option again, it goes away.

**Comment by fkk-cz** [comment]
Decided to replace the targeting system entirely. Let's hope this fixes all related problems.

https://github.com/fkk-cz/noire/commit/565f9f6a7ac58f0e8b884e19d6db4cc79a7c7947

**Comment by tythetanman** [comment]
Third eye is not able to be used in Burger shot at all right now. Been like that since reset.

**Comment by fkk-cz** [comment]
The new targeting system will not work if `INPUT_ATTACK` is disabled. Safezones currently disable player shooting, which means the targeting system is unavailable a lot of areas.

Given that it makes sense (probably to prevent NUI 'stuck bug' or other related issues) to disallow targeting if the player's attack control is disabled, I'll leave that check in place and instead modify the safezone logic to allow shooting. Note that players will still be unable to inflict damage on other players in safezones, the only difference is people can shoot when entering a safezone -- regardless of whether they recently shot or not. This isn't anything new, people have been shooting and entering safezones for quite a while now.
