### ISSUE TITLE
Glitch Punching

### ISSUE THREAD

**Issue by AnassaHecate** [fkk-cz/noire-public#348]
Something needs to be done about this stupid glitch. You can't fight back or anything when someone is punching you 50 times within 5 seconds.

**Comment by D4LPebble** [comment]
its fine bro just dont get flipped

**Comment by DizzyPoy** [comment]
Yup

**Comment by D4LSpidey** [comment]
people can punch that fast in real life. just cause you're getting flipped by someone can fight doesnt mean it needs to be fixed 🥴

**Comment by fkk-cz** [comment]
How is this done?

**Comment by AnassaHecate** [comment]
> How is this done?

I have zero idea because I refuse to ask anyone so I don't abuse it myself. If I find out I can DM maybe?

**Comment by AnassaHecate** [comment]
> 

I know how to do it now but idk if I should post it here.

**Comment by fkk-cz** [comment]
Not sure why this was closed, will be fixing this hopefully soon.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/5a7c7b0b56bf32ff575af42adf4b616f400a3ad8.
