### ISSUE TITLE
Trailer issue continued.

### ISSUE THREAD

**Issue by tomswayer123** [fkk-cz/noire-public#356]
Here is what I mean by the trailer driving beside me. I got a bunch of pictures to show you. When the trailer is in this state you can't detach it. I was lucky enough to make it to a public garage to store it. It isn't the trucks. It's the trailer unfortunately. A video would be better, but the pictures do just fine. It shows that I am moving(the speedometer is above zero). It's weird XD.

![20211218175820_1](https://user-images.githubusercontent.com/95537227/146658873-1f024bed-8e4a-4777-acb0-505b05d3e67d.jpg)
![20211218175823_1](https://user-images.githubusercontent.com/95537227/146658874-459c0210-6892-4293-ae8e-9774e3dced99.jpg)
![20211218175914_1](https://user-images.githubusercontent.com/95537227/146658875-bc5ab38f-1e21-4f90-8483-5bd87d528ae1.jpg)
![20211218175915_1](https://user-images.githubusercontent.com/95537227/146658876-4ef5807b-1c71-4f6f-99f4-2d2e0b0f9ba5.jpg)
![20211218175917_1](https://user-images.githubusercontent.com/95537227/146658879-ab83501c-5b30-46f6-8647-627195e48bdf.jpg)
![20211218175923_1](https://user-images.githubusercontent.com/95537227/146658880-610643f9-667f-48f2-bd8e-7225be07fe58.jpg)
![20211218180007_1](https://user-images.githubusercontent.com/95537227/146658881-84bf6b86-cf9c-4ad7-8f94-22e4c6eab759.jpg)
![20211218180015_1](https://user-images.githubusercontent.com/95537227/146658882-dbe10799-cd15-4aa0-beb4-dbcb81be0871.jpg)
![20211218180016_1](https://user-images.githubusercontent.com/95537227/146658884-9fd34f22-0082-4e84-9f7a-dca9d3c46ab6.jpg)

**Comment by fkk-cz** [comment]
This, unfortunately, isn't very helpful as it doesn't give me any ideas or even a hint on what the issue _could_ be. Trailers are attached without any native functions, i.e. the way vanilla trailers are attached to vehicles.
