### ISSUE TITLE
Hunting: Unable to harvest if attempted without required weapon

### ISSUE THREAD

**Issue by tomswayer123** [fkk-cz/noire-public#360]
I got my license, rented my gear. I killed 1 deer, got its meat and leather. I got to kill another animal, which was a mountain lion. I see that I am able to harvest, but it will not let me harvest the animal. I then killed another deer. Same thing won't let me harvest the animal. My knife is out, and I tried the katana. I have relogged and the issue still persists. I have also gone to the original hunting area and the issue is the same. I have talked to two other hunters, and they said to make sure that your knife is out before pressing E, otherwise you won't be able to harvest at all. 
![20211219091647_1](https://user-images.githubusercontent.com/95537227/146680504-19f39b95-4377-4161-912b-4dc7138d601a.jpg)
![20211219091812_1](https://user-images.githubusercontent.com/95537227/146680514-7d3563d7-1019-469f-8912-43a30fcdc09d.jpg)
![20211219091959_1](https://user-images.githubusercontent.com/95537227/146680521-99821477-db66-4fd9-8211-3149e9f0e763.jpg)
Im spamming my "E" key to try and harvest, but it will not let me. Like I said I was able to harvest one of the animals and then after that one animal I wasn't able to harvest again. 

I have even tried hunting in the original area:
![20211219095244_1](https://user-images.githubusercontent.com/95537227/146681501-3d89c7bc-0584-4141-927c-7cf6ec5447d4.jpg)
![20211219095245_1](https://user-images.githubusercontent.com/95537227/146681503-88ae7960-6bba-4cb8-aec9-f3bc8dc566f6.jpg)

**Comment by tomswayer123** [comment]
I am trying to fly out and fly back in to see if it is on my end only.

**Comment by tomswayer123** [comment]
Yup I was able to kill one deer and was able to harvest it. Then I killed another animal and wasn't able to harvest it.

**Comment by fkk-cz** [comment]
>  Im spamming my "E" key to try and harvest, but it will not let me. Like I said I was able to harvest one of the animals and then after that one animal I wasn't able to harvest again.

Does it play the animation or show the progress bar at all?

**Comment by tomswayer123** [comment]
> > Im spamming my "E" key to try and harvest, but it will not let me. Like I said I was able to harvest one of the animals and then after that one animal I wasn't able to harvest again.
> 
> Does it play the animation or show the progress bar at all?

It does the first time. The second time there is no reaction at all. Just says "Press E to Harvest". Only way to fix it right now is to fly out and fly back in. Make sure your knife is out completely before you press E. If you press E before your knife is out, you will not be able to harvest.

**Comment by byu26** [comment]
With this new hunting update, I think this may still be a bug? Rented the knife from the lodge and kill using the hunting rifle you get when entering the hunting zone, but there's no prompt to harvest after getting the kill.

**Comment by fkk-cz** [comment]
Moving to https://github.com/fkk-cz/noire-public/issues/369
