### ISSUE TITLE
Hunting Rental Issue

### ISSUE THREAD

**Issue by tomswayer123** [fkk-cz/noire-public#363]
I hope i'm not bugging you about all these small things, but here is another one.

If you rent the knife and musket, then die. The lodge still thinks you own it. Or if you get robbed and give another player that item, it still thinks you own it.

For example: I rent the musket and knife. I go hunting, then I get killed by a mountain lion. I "respawn" at the hospital with nothing in my inventory. I go back to the lodge, and it says I am not able to rent the knife or musket because I already own it. 

I tried relogging, I tried dying, I also tried picking up another musket and dropping it. I assume its ID related in the database, so whatever musket I rented it has its own unique ID. Which is associated with my character, and the server still thinks it's out there, which it is. BUT I don't have it because I got robbed/killed.

The FIX: I found a musket on the ground dropped by a previous player, took it to the lodge, and was able to "return the musket".

Pictures:
![20211219150108_1](https://user-images.githubusercontent.com/95537227/146690603-8fa72e13-e2ad-4b10-acdf-1885f02cec20.jpg)
Here I do not have the musket or the knife.

![20211219150057_1](https://user-images.githubusercontent.com/95537227/146690613-edb6f1df-707e-4e1d-bf80-7f5c4664e93f.jpg)
It shows the price in red meaning I'm still renting the item, but I don't have that item.

![20211219150100_1](https://user-images.githubusercontent.com/95537227/146690635-cb74de73-427b-4252-89db-11eb69d193b6.jpg)
I tried renting the knife, but it says I still own it.

![20211219150106_1](https://user-images.githubusercontent.com/95537227/146690640-a03fe90d-5453-495b-bcd8-e37fa0558616.jpg)
I tried renting the musket, but it says I still own it.

**Comment by fkk-cz** [comment]
This was designed to prevent people from using the Hunting Lodge as a gunstore, the idea being most people wouldn't die or get robbed and lose their weapons after renting one.

If we decide to reset the rentals on death, people could rent weapons, put the weapon into a house or give it to a friend, and purposely die to buy a new one.

Not sure how to fix this, as it seems primarily caused by user behavior.

**Comment by cxerq** [comment]
Maybe what you could do is, make the all the animals 1hp and make the hunting rifle do only 1 dmg! Then it would stop people from taking them and if they do well its pointless! And then you can reset on death!

**Comment by balesduckman** [comment]
> Maybe what you could do is, make the all the animals 1hp and make the hunting rifle do only 1 dmg! Then it would stop people from taking them and if they do well its pointless! And then you can reset on death!

That could work. Right assert?

**Comment by balesduckman** [comment]
Make it to where the musket(or whatever rifle if you intend to add a scope)and any hunting gear is permanently attached to you. Meaning you can’t lose it, you can’t give it away, and it won’t go away in your inventory. Basically if you die you’ll still have it. Prevent it from being able to give to other players. But you’re still allowed to return it to the lodge. I like the damage idea to where you make the animal have 1hp and the musket does 1hp. Only reason why people buy it is for that accuracy and long range shot. If you take that away, then they won’t use it. The musket would be worthless. But not for us hunters. Then you can add the scoped rifle and do the same thing with the damage and the permanent rental weapon. No one could abuse it.

**Comment by byu26** [comment]
Not sure if hunting is still not working? Rented the knife at the lodge and kill using the hunting rifle you get when entering the zone but still cannot harvest with the rental knife. It doesn't give the option to press E to harvest.
