### ISSUE TITLE
Clothes menu

### ISSUE THREAD

**Issue by Daniel9935** [fkk-cz/noire-public#364]
When i am trying to take off clothes using the comma menu. This doesn't work for me as its all greyed out. I have reset keybinds,  changed setting and reset keybinds again this still doesn't work. I've spoken to a few people and they are having issues as well.

**Comment by fkk-cz** [comment]
Any more information on this? When does this occur, is it grayed out all the time? Do you have a screenshot?

**Comment by Daniel9935** [comment]
This occurs all the time I've never been able to use this menu as its just completely greyed out. I have submitted reports about this before and they told me to reset keybinds and change setting but it still doesn't work and i have no idea why. I have 10 different outfits and even in my eup for dot the comma menu doesn't work
![20211221093733_1](https://user-images.githubusercontent.com/95129567/146856253-d389dd06-455a-45a9-91cb-a998d77334db.jpg)

**Comment by Daniel9935** [comment]
I am still having issues with this is there any update ?

**Comment by No-Yes1** [comment]
Seems like enabling raw input fixes this, same with the contextual menu
