### ISSUE TITLE
Hunting - cannot harvest

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#369]
Tried hunting today after the bug updates for hunting was implemented and I cannot harvest an animal. I don't even get the prompt to press E to harvest. I am in the hunting zone as well.

**Comment by whitefeatherr** [comment]
https://github.com/fkk-cz/noire-public/issues/360

Look through the issues before creating the same one. :)

**Comment by whitefeatherr** [comment]
You must press E after the knife is out. If you press E before it is fully out, that bug will happen. Otherwise you have to fly out and fly back in to fix it.

**Comment by Ell34** [comment]
> #360
> 
> Look through the issues before creating the same one. :)

Thanks for your comment. I did, and another hunter I met on the trail was also experiencing the same issue as me. I also know about the glitch where you have to press E after the knife is out.

**Comment by whitefeatherr** [comment]
Ahhhh he did update the hunting zone. Idk if he made it smaller. Where are you guys hunting? Send some pictures.

**Comment by Ell34** [comment]
https://medal.tv/games/gta-v/clips/5AmK76NdonCt-/d1337YnocjMZ?invite=cr-MSw4VVcsMjI4NTg2Njcs 

> here is video evidence showing the bug

**Comment by fkk-cz** [comment]
> https://medal.tv/games/gta-v/clips/5AmK76NdonCt-/d1337YnocjMZ?invite=cr-MSw4VVcsMjI4NTg2Njcs
> 
> > here is video evidence showing the bug

Are you sure you are attempting to harvest the correct animal? You need to hit **G** and locate the animal with the whistle.

**Comment by Ell34** [comment]
> > https://medal.tv/games/gta-v/clips/5AmK76NdonCt-/d1337YnocjMZ?invite=cr-MSw4VVcsMjI4NTg2Njcs
> > > here is video evidence showing the bug
> 
> Are you sure you are attempting to harvest the correct animal? You need to hit **G** and locate the animal with the whistle.

SINCE WHEN

**Comment by Ell34** [comment]
Ok had no idea you need to press G, it's working. Does this work with all animals? I typically like going for cougars..

**Comment by fkk-cz** [comment]
Here's another list of changes from last night:
- Switched back to the Hunting zone system. Hunting everywhere in Blaine County had too many issues, mainly being too easy where people could kill the same scenario peds over and over. The zone is currently located around old coke
- Spawned animals are no longer marked, the whistle is required to locate animals with a radius blip
- Certain animals (deer, coyote, etc.) will respond to your whistle, listen carefully for the sound
- Ambient/scenario peds will not be harvestable, players need to kill the "correct" ped
- Players with the hunting job entering the hunting zone will automatically receive a hunting rifle, musket was removed from the hunting lodge
- The hunting store will reset every 30 minutes, allowing people to rebuy a knife if needed
- Minimap is now displayed while on foot
- Increased meat price

**Comment by Ell34** [comment]
I suggest you come up north and try hunting. This new update with the zone and whistle aint it.

**Comment by whitefeatherr** [comment]
> I suggest you come up north and try hunting. This new update with the zone and whistle aint it. @fkk-cz

I havent tried it yet. Is it that bad? Maybe add more zones? Or go back to the original zones, but this time with the new updates? Like the hunting rifle spawning when entering the zone, the knife, the lodge, etc.

**Comment by fkk-cz** [comment]
I already did for over an hour and didn't run into any issues?

**Comment by Ell34** [comment]
> I already did for over an hour and didn't run into any issues?

I'm noticing issues when the blip for the animal comes up and I go there, there's no animal, or the blip appears so far away by the time you get there it's despawned

**Comment by Ell34** [comment]
> I already did for over an hour and didn't run into any issues?

i also noticed yesterday the payment for 2 perfect deer pelts went from 1.5k-2.3k to $700. Why was it cut back? With this new update all I'm getting is deer so I feel like there's no point now. Haven't gotten a single cougar yet.

**Comment by whitefeatherr** [comment]
> > I already did for over an hour and didn't run into any issues?
> 
> i also noticed yesterday the payment for 2 perfect deer pelts went from 1.5k-2.3k to $700. Why was it cut back? With this new update all I'm getting is deer so I feel like there's no point now. Haven't gotten a single cougar yet.

Burgershot relies on us now. So deer is a priority. He raised the meat prices. IDK if he raised the pelt prices.

**Comment by fkk-cz** [comment]
Some of the changes take effect on next reset, namely the one with increased meat prices. Scopes also weren't working correctly -- it should be much easier to find and kill animals with a working variable zoom scope.

https://github.com/fkk-cz/noire/commit/f9d5cfa4b0b0c4a61746414a43effb33232828fe

Also reverted the scenario ped change, removes the confusion in shooting the "wrong" animal.

**Comment by whitefeatherr** [comment]
> Some of the changes take effect on next reset, namely the one with increased meat prices. Scopes also weren't working correctly -- it should be much easier to find and kill animals with a working variable zoom scope. This has also been fixed for next reset.
> 
> [fkk-cz/noire@f9d5cfa](https://github.com/fkk-cz/noire/commit/f9d5cfa4b0b0c4a61746414a43effb33232828fe)
> 
> Another change: reverted the scenario ped change, removes the confusion in shooting the "wrong" animal.

Next reset is tonight im guessing or tomorrow?
