### ISSUE TITLE
2018 Dodge Durango SVT

### ISSUE THREAD

**Issue by CapitalOG** [fkk-cz/noire-public#371]
The Durango is very easily flipped even turning corners at around 35mph. I don't know if this is solution that can be solved or not, but i just thought I'd bring it to attention. Other than being very easily flipped compared to the 2020 tahoe or the 2014 tahoe.

**Comment by fkk-cz** [comment]
Wrong repo. https://github.com/fkk-cz/noire_vehicles/issues
