### ISSUE TITLE
Vehicles have inaccessible trunks

### ISSUE THREAD

**Issue by Sixlett** [fkk-cz/noire-public#389]
Wont let me open the trunk anywhere around the truck. I've went mining with this thing a few times and it will work but today was the first day it wouldn't work.

**Comment by fkk-cz** [comment]
I've seen a few people reporting this issue, which started around when this fix was introduced: https://github.com/fkk-cz/noire/commit/d002e7c24ba996eb38bd59765a9e9ea47ccae6ed.

Probably related to certain vehicle models not having a `boot` vehicle bone, which explains why the trailer (correctly) no longer has accessible storage.
