### ISSUE TITLE
Gas Station Bug/Glitch that is being heavily abused

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#390]
Okay so I've owned a Gas station for the longest time! And for the last few weeks I've been noticing our gas station has been getting a lot of charges for little amounts! Video here to see a bunch of charges in the last few hours! https://medal.tv/games/gta-v/clips/5RfcatzvEo3Pz/d1337nRnmMzM?invite=cr-MSxpY2YsMTg3OTQ2MDQs

Example of how this is done: You pull up and your car is on 20 fuel, you have lets say 100$ on you, you start to fill it up once the charge goes over 100$ it stops filling gives the gas and lets you keep your cash! Then hit you start it again and boom you send up with full tank for less than 50$, The gas station loses a lot of money due to this happening! I'll get more clips of other gas stations transactions and show them here to show how big of a problem this is!

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/715cf1cd7c0713270b94baed146519ce977a1e42.

Not a perfect solution, but should charge the exact amount of cash the player has if the fuel charges exceed their cash on hand.

**Comment by fkk-cz** [comment]
Confirmed fix is working, all gas station owners should see a small to moderate increase in (lost) profits in a week or so.
