### ISSUE TITLE
mining no profit

### ISSUE THREAD

**Issue by MrUnlife** [fkk-cz/noire-public#393]
I went to sell my three truck loads worth of mining goods and didn't get paid at all for it. it said I was getting the cash in the bottom left but when I checked my bank account after it all, I was at the same as before. kinda sucks mining for a whole hour or so and get nothing from it

**Comment by fkk-cz** [comment]
I've never heard of anyone reporting this despite mining being one of the more popular non-whitelisted jobs, seems like an isolated incident. Without any specifics or steps to reproduce this, not much can be done.
