### ISSUE TITLE
Add markers for drug interaction locations

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#399]
Newer players might find it confusing exactly where and what to do in drug locations. Markers should solve this issue.

**Comment by Creloix** [comment]
they want it to be rpd out but like even just a notice saying that

**Comment by cxerq** [comment]
> Newer players might find it confusing exactly where and what to do in drug locations. Markers should solve this issue.

I disagree with adding markers to it, cause it will just cause an influx of RDM and shit at drug places

**Comment by Creloix** [comment]
yeah i feel like that should be said tho like in the rules jus so everyones on the same page that u gotta find your own path

**Comment by CapitalOG** [comment]
I think the current set up is pretty good. Some people stumble upon it by looking, others pay for information. I think the confusing part might be having to use your third eye and where to look.

**Comment by fkk-cz** [comment]
Markers are not the same thing as blips, not sure how that would cause RDM at drug zones?

The issue is people not knowing to use the contextual menu (which has limited use and isn't consistently used for every interaction) at the right spot.
