### ISSUE TITLE
Ped's spawning at F block

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#401]
I've already made one of these but still it seems to be the same thing, Peds just aren't spawning on the drug selling locations on F block, Reason why this is happening I believe its because there is always people at 134 and I believe it is stopping peds from spawning, Also when you only start searching for someone to sell drugs to the cops get alerted even if you don't find a buyer! Maybe to help with this temporarily you could make Vespucci a Drug selling zone again! Cause its hard to sell drugs right now!

**Comment by fkk-cz** [comment]
Already answered in https://github.com/fkk-cz/noire-public/issues/334#issuecomment-993946548.
