### ISSUE TITLE
Keybinds to adjust radio volume without chat command

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#406]
Similar to the ability to switch up/down radio channels with bracket keys, players should be able to turn their radio down instead of switching channels or turning their radio off completely.

Any suggestions for non-conflicting keybinds?

**Comment by FertileSphere** [comment]
plus and minus? technically they are used inside of vehicles for the indicators but outside I don't see why they couldnt be used for the volume adjusters.

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire/commit/81d47c284d8d78ed21eecbaac76b66a84778af6d.

Decided to make it the up/down arrows, only when the radio is open.
