### ISSUE TITLE
Used car sale title paperwork

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#408]
Currently, players in proximity of the used car lot can spam buy near a vehicle, leading to problems where a non-intended recipient could buy a vehicle from two players engaging in a private transaction.

A better system would do the following:
- Eliminate the 3D text above vehicles, improving client performance
- Get rid of the /sellCar command, which is not intuitive
- Require a usable item for players to complete a car transfer or sale
- Only involve the intended buyer and seller of a vehicle
- Support logging for all used car transactions

**Comment by legacyReflex** [comment]
Would it be possible to set up UCL like PDM where there is a spot where you walk up and scroll through available cars. Instead of new cars it would just list the vehicles that people have brought there to sell. Once selecting the vehicle it would show it infront of you with the price and it’s stats.

**Comment by RockiBurns** [comment]
This might be an opportunity for a business & jobs. The employee could make a % commission off of sales. It might even work best if the business negotiates with the owner to purchase the car, & then the business sells the car to the new buyer.

It means the seller would probably make a bit less off selling a car & the buyer would pay a little more. But the used car lot is currently so dangerous & causes such bad headaches, I think many people just avoid it as much as possible.
