### ISSUE TITLE
Phone proximity ring on incoming call

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#413]
Players receiving phone calls should play a networked ringtone from their position so anyone in proximity (<15m) are aware they are being called.

**Comment by Creloix** [comment]
thats a pretty large distance i would say 5 meteres or 15 ft

**Comment by jeanndabeann** [comment]
i like this idea, maybe we could get the option to put it on vibrate so its a little quieter?

**Comment by fkk-cz** [comment]
Setting this aside unless an audio bank with a decent ring sound can be found. Found one a while ago but it seems to be SP only.
