### ISSUE TITLE
Ped in my car and drives off?

### ISSUE THREAD

**Issue by Bergsbrew** [fkk-cz/noire-public#419]
self explanatory 
https://www.twitch.tv/bergsbrew/clip/RelentlessAdventurousArtichokeMoreCowbell-eyvUsyI0cvdxB0xV

**Comment by legacyReflex** [comment]
So this happens when you attempt to get out the car and the area tries to populate with peds simultaneously. A way to prevent this is when you first pull up your vehicle think about the fact that I have no idea what I’m talking about and get wrekt nerd. Love you Phinn <3

**Comment by fkk-cz** [comment]
This seems like a very rare isolated incident, FiveM had this issue a long time ago but was fixed. If this happens repeatedly I'll raise the issue again.
