### ISSUE TITLE
Permanent Tattoos

### ISSUE THREAD

**Issue by jeanndabeann** [fkk-cz/noire-public#422]
I know this was brought up ages ago but gosh its becoming such a pain to have to put my tattoos on everytime i fly in or everytime i change into a saved outfit, and after i clock off PD and get back into my civ clothes, its just such a pain. I know it was added to the dev roadmap but i dont think that exists anymore, so any update on this?

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/765b8f25f4edc727aeca46aecb850b14e3c5ae13 fixes this issue.

**Comment by Bountyrogger** [comment]
So meant to put this in that same day you updated this but. The only thing is it does not save when I switch to another outfit in my houses wardrobe. Even if I delete it and resave it while wearing tattoos. It does save when using /eup and the locker room at AMR to switch back to civilian clothing.

Unless I am doing something wrong
