### ISSUE TITLE
We need more place to get food besides gas stations and burger shot 

### ISSUE THREAD

**Issue by teresgrunt4555** [fkk-cz/noire-public#423]
We need another restaurant in town burger shot it it’s on the other side of town there is nothing close to the casino or even warehouse district. You have the Mexican food place across the street from 134 or even up and Atom at 567 witch could compete with burger shot and it would help everyone from just coming to burger shot in one corner. There are more place it could work these are just a few places off the top of my head

**Comment by Decratic** [comment]
Was thinking the same thing. Maybe a pizza place that also delivers which would create not only another restaurant, but more jobs and definitely spread players throughout the map.

**Comment by teresgrunt4555** [comment]
I would be perfect but it would probably only start out as a carry out only until we get enough people interested in the food.

**Comment by Creloix** [comment]
I would love this, or overall just more jobs that induce rp

**Comment by fkk-cz** [comment]
There will be more whitelisted restaurant/bar or club jobs in the new year.
