### ISSUE TITLE
The suspicious person texts the police get when drug dealing are way too often

### ISSUE THREAD

**Issue by Creloix** [fkk-cz/noire-public#425]
Especially because they’re already camping the only form of criminal activity, if there were more things civs could do to spread the police out I would understand but cops have nothing but drugs to hang around and camp

**Comment by fkk-cz** [comment]
> cops have nothing but drugs to hang around and camp
Not true at all. Ask any of the LSPD/SAHP officers, they are always busy responding to calls or doing traffic / speed enforcement.

The police alert probability is **lower** than it was with the old system. Please do not complain about things like this -- people are still selling over $150k of drugs daily.

**Comment by Pookk** [comment]
Idk why this got closed with no discussion.  Other than ask HP. Of course HP gonna say that don't camp it. How bout ask anyone who's tried to sell at Stab city.  I've taken one (1) pack to sell,  looked for a buyer, and by the time I'm looking for the guy, I hear sirens. On top of air one and 3+ troopers coming,  Stab City is SHOT

**Comment by fkk-cz** [comment]
> I've taken one (1) pack to sell, looked for a buyer, and by the time I'm looking for the guy, I hear sirens. On top of air one and 3+ troopers coming, Stab City is SHOT

Providing anecdotal 'evidence' and making unverifiable claims such as this is not helpful.

Consider the possibility that people are selling over $150,000 worth of drugs every day. Here's an partial example from last night, captured earlier (before checking at the end of the day):
![image](https://user-images.githubusercontent.com/74131024/147791702-579cadfb-2e3c-402e-b8db-b0109dbe0593.png)

Closing this _again_ as all people want to do is complain about the new system and claim it's 'too hard' or 'not worth it' all while solely providing anecdotal evidence that is completely refuted by the data we collect.
