### ISSUE TITLE
Animation for interacting with a vehicle's trunk

### ISSUE THREAD

**Issue by teresgrunt4555** [fkk-cz/noire-public#426]
I don't think I am the only one, but we need to make a safe spot for people to park where people cant steal out of our vehicles I thought I was the only one up there and someone drove up and stole 5 leather from my truck.

**Comment by fkk-cz** [comment]
Having an animation for trunk interaction should solve this issue.

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire/commit/0e316f5d1324eaccb1a89852bb02e5578d56caad.
