### ISSUE TITLE
Carbine rifle has excessive variable damage

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#432]
Shooting people with the carbine rifle will do random amounts of damage, ranging from 33 to 95.

**Comment by somedudenamedrush** [comment]
[https://medal.tv/games/gta-v/clips/6Ahgjhs7_D8fy/d1337jZZdR67?invite=cr-MSxEaHAsNjE1MzMwNyw
](url)
this is what we found earlier today at 134 said id provide the clip

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/19cc9f51075ed96307b784797686664926f5c5d0. Need to test this in a live environment, as it might be caused by server slowdown (?)
