### ISSUE TITLE
3rd eye (left alt) stuck when picking untrimmed weed.

### ISSUE THREAD

**Issue by noyeahsure** [fkk-cz/noire-public#433]
I'm not quite sure what causes this, seems like alt tabbing while picking sometimes will do it, and sometimes it will also just do it on its own when you open the alt menu and click pick without alt tabbing, seems like the only fix for this now is flying out and back in.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/341
