### ISSUE TITLE
Outfit reverts/possible wardrobe issue 

### ISSUE THREAD

**Issue by RockiBurns** [fkk-cz/noire-public#435]
If I use my wardrobe to change into one of my saved outfits then fly out more than 30 minutes later without going to a clothing store, I will be wearing the outfit I was in before using the wardrobe when I fly back in.

**Comment by QuintenM911** [comment]
At this moment in time the only way to save an outfit once changed at a wardrobe is to go to a clothing store and interact and exit and save changes. that will save the outfit upon exiting and re-entering the city

**Comment by RockiBurns** [comment]
Thank you for the info. I didn't realize that was the case.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/dcf279db3dd9fa0740b3e5ff7a910f928281a724.
