### ISSUE TITLE
Speed cameras are inaccurate

### ISSUE THREAD

**Issue by RockemRobotics** [fkk-cz/noire-public#442]
I decided to sacrifice $2000 in the city to check the speed cameras on the bridge on the East side and found they're inaccurate.

In this example, the highest speed my car reaches is 96 (before the cameras - 95 after), but I was clocked by the speed cameras going 106.8 mph: [Video 1](https://streamable.com/bo0x11)

In this example, I used cruise control to make sure the highest speed I hit on my speedometer was 91, but I was clocked going 101.6 mph: [Video 2](https://streamable.com/frby29)

In each case, the system seemed to add about 10mph to my max speed between the cameras. I don't object to getting a ticket for going 90+ mph, but I'd like for the speed reflected by the ticket to reflect the actual speed I was going.

**Comment by viigyD** [comment]
Good call, I'm sure that will be tweaked soon enough. But I'm more curious about how you're getting 70-80 fps at MRPD? Please share your secret sauce.

**Comment by RockemRobotics** [comment]
> But I'm more curious about how you're getting 70-80 fps at MRPD? Please share your secret sauce.

Turn off Anti-Aliasing. It's a GPU-killer.

**Comment by Stagonium** [comment]
I did some testing today as well; 
With cruise control at 100 I got clocked at 120. [Video](https://streamable.com/ul3nmh)
With cruise control at 149 I got clocked at 184. Note I did have a minor headache in this test but it is still wildly off. [Video](https://streamable.com/ejufgx)
