### ISSUE TITLE
Burgershot Resupply not working

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#445]
### Discussed in https://github.com/fkk-cz/noire-public/discussions/444

<div type='discussions-op-text'>

<sup>Originally posted by **tythetanman** January  2, 2022</sup>
This is more of a suggestion or request.

 
At the burger shot, we were given about 1,000 raw meat the day before Christmas, and we have not been restocked at all at the whole seller, and wanted to see if that is going to be restocked and how often?

 
We do participate heavily when it comes to hunting and purchasing meat from Hunter's, but it’s not enough to justify the hours of the burger shot, which has gone from being open anywhere from 18 to 24 hours to anywhere from 5 to 10 hours a day now, and we really do want to be able to feed the city and not have to tell people we are not open because we are out of raw meat and then tell them raw meat from hunting is not coming in fast enough.

 
My personal suggestion is that we get 800 burger patties or even 1000 once or twice a week and then, whenever we do get low on orders or the massive bulk orders, we handle the other 15 to 45% of orders by going hunting ourselves, because if it was considered an IRL restaurant, we would be going to whole seller 82, which is normally 100% of the time.

 
Please, and thank you in advance.</div>

**Comment by fkk-cz** [comment]
Not sure why this isn't working properly, it worked fine on a localhost session.

Changed it to a weekly resupply, currently set every Monday at 11AM. https://github.com/fkk-cz/noire/commit/da4ce4cc5709a62b33d6dbe1d50a1e21a1a1205b

**Comment by tythetanman** [comment]
Thank you, and also, if I may add, 1,000 raw meat with the massive orders, you will run out in about three days. We have no problem with hunting. It’s just that we wanted to see if it was possible if that of 1000 could be raised even a little bit to provide food to the city. The city currently has the only restaurant that’s currently selling.

**Comment by tythetanman** [comment]
I'm not trying to complain, but they did check at 11 a.m. on Monday, Eastern Standard Time, and it was not restocked.

**Comment by fkk-cz** [comment]
Fixed ub https://github.com/fkk-cz/noire/commit/59f263426b5ce83e5d4923ef9dd402fa364ffc08,
