### ISSUE TITLE
purchased a jeyski and it said it wasnt mine.

### ISSUE THREAD

**Issue by hervey872** [fkk-cz/noire-public#450]
i purchased the 85k jet ski and it would not let me insure it or store it in the garage.

https://medal.tv/clips/6Sdw5L64ZCLP6/vpKb8zcWR?invite=cr-MSxld0osNDMyNDM2MDAs

**Comment by fkk-cz** [comment]
Can you check your video playback for the notification that shows the plate of the jet ski?

**Comment by hervey872** [comment]
i wasnt recording the whole time just clipped right there and when i was cruising the ocean

**Comment by fkk-cz** [comment]
Please create a report on the Discord for player-specific issues.
