### ISSUE TITLE
House and Gas station keys

### ISSUE THREAD

**Issue by EveEnchooli** [fkk-cz/noire-public#458]
Hello!
So revoking house and gas station keys just doesn't seem to work, if it does it's about 1 out of 10 attempts. 

With the house you'll select the name and it will say "taking keys from player" but then they are still in the list and still have access to the house.

With the gas stations, it seems to only work if they are online? and even then only sometimes will it actually remove the keys.

**Comment by fkk-cz** [comment]
I wiped a bunch of invalid (null) keys from all houses and gas stations yesterday, is this still an issue?
