### ISSUE TITLE
Casino Taking Bet, Not receiving cards

### ISSUE THREAD

**Issue by zNotAlpha** [fkk-cz/noire-public#459]
I placed down a bet at the casino, took my bet but never gave me the cards to play. Sat there for a few minutes waiting then went to get up and couldn't, was stuck at the table. After watching the clip it looked like the table was frozen before I even sat down, there were cards on the table from previous players.
https://medal.tv/games/gta-v/clips/70nqa1cZqoNLr/d1337Y17qDpW?invite=cr-MSxsdXUsMjgyODM1MDAs

**Comment by fkk-cz** [comment]
Create a report on the Discord for player-specific issues.
