### ISSUE TITLE
Trailer glitch, disappears randomly

### ISSUE THREAD

**Issue by AustinM0527** [fkk-cz/noire-public#462]
Happened 3 times, randomly will disappear then end up attached to the side of the truck. In this clip, youll see where it disappeared and never reappeared.

https://medal.tv/games/gta-v/clips/76G23FbrASLh9/d1337GwkiKMr?invite=cr-MSxram4sMzc0OTQ5MDUs

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/359
