### ISSUE TITLE
Clothing Store

### ISSUE THREAD

**Issue by ImJustBetter420** [fkk-cz/noire-public#463]
i’m also gonna say something along with the clothing store stuff, i’ve got roughly 15-20 outfits saved and yesterday the hairstyle i had was completely removed from the city and replaced with dreadlocks, in saying that those 15-20 outfits that i have saved are now useless, curious on why it was removed.

**Comment by fkk-cz** [comment]
Answered in https://github.com/fkk-cz/noire-public/discussions/461.
