### ISSUE TITLE
Door phase glitch

### ISSUE THREAD

**Issue by slackatk** [fkk-cz/noire-public#465]
There is a glitch with handing your id we found in the cells accidentally which could possibly lead to prison breaks.  Clip to shows what happened 
https://clips.twitch.tv/HelpfulArbitraryPizzaFeelsBadMan-bqLHyDY__SQFpScG

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/be982ed201150b0606e4ef8204c2f976ca55ed91.

Thanks for pointing this out.
