### ISSUE TITLE
Armored Truck Rework

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#487]
Here's a list, in no particular order, of inconveniences and problems with the truck heist:
- ~Cops get alerted when the hacking is complete~
- ~Vehicle spawns are limited to culling radius of the initiating player ped, resulting in more predictable locations~
- ~C4 object does not properly delete after detonation~
- ~Explosion isn't networked properly~
- Civilians have no ability to safely grab the cash, as they are forced into an animation outside the vehicle without cover

**Comment by fkk-cz** [comment]
Fixed three of above issues in https://github.com/fkk-cz/noire/commit/86a8960dcd89df515aba1c96acd7f7a102af6a55.

Armored truck is most likely going to change into a random ambient event where trucks will randomly appear in the city and can be robbed immediately without completing a minigame. This, of course, will require extensive testing but should improve the odds for both sides and make the missions more dynamic and exciting.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/76d6a54d073b2697aafcd873f5b71214029f5f42

Armored truck is now a random world event and will spawn in random locations when there are enough police online. Players will no longer be able to start the mission manually, as that led to a number of complaints about the police 'camping' the area, along with people having issues figuring out the hacking minigame.

- Hacking minigame is eliminated, the mission is started as soon as a player decides to kill the guards
- **Any** player can walk up to the armored truck and kill the driver/passenger, set an explosive charge, and steal from the vehicle. Prior to this change, only the individual who started the hacking minigame was able to interact with the heist.
- Police are only notified when the occupants of the vehicle are killed
- Heist is fully networked and synced between all players

There _might_ be some issues, this update took **many** hours of testing in a local session, however there could be issues when introduced live.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/4927375f8dbdfa1468658343b22f7e8def8d1d15

First issue - the armored truck spawn function wasn't in a `while` or `repeat` statement. That explains why the truck isn't spawning today.

Second, if the individual grabbing the cash is killed, a flag is not properly reset, therefore preventing anyone else from grabbing the cash when the truck has blown up and is not secured.

**Comment by Stagonium** [comment]
Being reported that civilians get the armored truck alerts when the detonation happens. As it is a [911 Emergency Notification](https://i.imgur.com/K2sRzkz.png) I assume that is not intentional. Wanted to bring awareness to it so it could be fixed sooner rather than later.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/3d9934de23fee463caf1771110d20d2ef30ca7fc. Thanks for pointing that out.
