### ISSUE TITLE
Place barriers outside of 585 courthouse

### ISSUE THREAD

**Issue by teresgrunt4555** [fkk-cz/noire-public#490]
It would be nice to have the parking lot at 584 a safe zone again so all the lawyers and DOJ members have somewhere to park where people can’t lock pick or steal our cars

**Comment by MrKennyG** [comment]
This was a HUGE problem area and now with the court house there having this a safe zone would be awful for the city imo. 

Maybe it could be a non safe zone garage so they can park there car there but not have it be a safe haven for people to run to.

**Comment by FertileSphere** [comment]
> This was a HUGE problem area and now with the court house there having this a safe zone would be awful for the city imo.
> 
> Maybe it could be a non safe zone garage so they can park there car there but not have it be a safe haven for people to run to.

yeah, or they could get a DOJ garage similar to PD/HP/EMS?

**Comment by c0mmoncents** [comment]
Hp does not have a garage anywhere near our hq

**Comment by teresgrunt4555** [comment]
But highways got somewhere to park where people cant steal their cars DOJ as to worry about their cars every time we clock in. if its a garage would be a problem because people would just hang out there and we would not be able to do anything there like before when it was a garage.

**Comment by RockiBurns** [comment]
> This was a HUGE problem area and now with the court house there having this a safe zone would be awful for the city imo.
> 
> Maybe it could be a non safe zone garage so they can park there car there but not have it be a safe haven for people to run to.

I don't think garages are safe zones anymore. I know that one of the features of safe zones (maybe being able to return fire from a safe zone under certain circumstances) was recently removed.

The cars of people working at the courthouse & individuals there on legitimate business are regularly stolen, robbed, and hit by traffic driving down the street (generally due to bubbles). Then DOT comes through, legitimately doing their jobs, and impounds cars the owners properly parked. The closest garage is down by LSPD, and it's not safe for the Judges and State's Attorneys to run up from there the way I can.

I think parking just for individuals that work at the courthouse would be best for the overall safety of the city rather than a public garage at that location. The space under the courthouse exists. Many of us have flown into the city and fallen threw the floor into the space. The question becomes how it can be tied into the roadways of the area. Because of the size of the space, it may need to be a garage rather than somewhere we just park our cars.

**Comment by RockiBurns** [comment]
> Hp does not have a garage anywhere near our hq

Correct. You don't have a garage there. You have a huge fence that destroys the flow of traffic on the primary highway leading in/out of the city to protect your personal cars & belongings while you're working

**Comment by fkk-cz** [comment]
> Correct. You don't have a garage there. You have a huge fence **that destroys the flow of traffic** on the primary highway leading in/out of the city to protect your personal cars & belongings while you're working

Not anymore. The checkpoint was edited days ago to open up both lanes and the broken path nodes were fixed. GPS and traffic patterns have been fixed as well.

One idea that might help is having the entire sidewalk outside of the courthouse fenced off, along with barriers to prevent people from ramming vehicles outside. With map changes and a more consistent law enforcement presence at the courthouse, a safezone and/or garage shouldn't be needed.

**Comment by RockiBurns** [comment]
> > Not anymore. The checkpoint was edited days ago to open up both lanes and the broken path nodes were fixed. GPS and traffic patterns have been fixed as well.

Thank you for fixing that. I haven't flown in much in the last week. When I have I've stayed at the courthouse. Every time I used that Highway to get to my house & drive back into the city navigating the locals driving was a nightmare. 

> 
> One idea that might help is having the entire sidewalk outside of the courthouse fenced off, along with barriers to prevent people from ramming vehicles outside. With map changes and a more consistent law enforcement presence at the courthouse, a safezone and/or garage shouldn't be needed.

I think that will result in our vehicles being hit into those fences & barriers, unless our vehicles are inside the fence. But I honestly hope I'm wrong & this resolves the issue.

**Comment by RockemRobotics** [comment]
An additional suggestion is to put a locked gated fence around the parking lot at 584 across from the courthouse. DOJ (on and off duty), LSPD, and SAHP would have keys to that gate.

**Comment by fkk-cz** [comment]
That's a much better idea instead of having safezones.

**Comment by raphquaza** [comment]
That fence then need to be quite high as the back wall of that parking space is just a balcony, unless you put a cage on top too? which could turn that parking space into a bird cage

**Comment by teresgrunt4555** [comment]
We could even have the fence up on the back balcony so it not to high.

**Comment by No-Yes1** [comment]
Can this be closed? You now have the barriers across from the courthouse to park vehicles?

**Comment by tythetanman** [comment]
Definitely Can be closed. I think the only other possible need but don’t know if it’s possible is some type of barricade so vehicles are not able to go up on the steps.

**Comment by No-Yes1** [comment]
Sure, I'll leave this open for that then.
