### ISSUE TITLE
Court sentencing menu closes when performing an action

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#500]
I Get a ton of people asking how much longer am I a felon and wanted to find out of Judge's and SA's can have the ability to say how much longer someone is a felon. 

also wanted to find out if the menu for view outstanding charges can be adjusted: when I press not guilty or guilty it fully exits out and only 20% of the time it does not. 

it stayed on that page till the sentencing is done that would be great. 

Thank You.

**Comment by fkk-cz** [comment]
> I Get a ton of people asking how much longer am I a felon and wanted to find out of Judge's and SA's can have the ability to say how much longer someone is a felon.

That's already possible, players can check their criminal records at the county courthouse. Judges and attorneys shouldn't have to waste their time on administrative/clerical things that civilians can easily check themselves.

> also wanted to find out if the menu for view outstanding charges can be adjusted: when I press not guilty or guilty it fully exits out and only 20% of the time it does not.

Adding this to the list.

**Comment by fkk-cz** [comment]
> also wanted to find out if the menu for view outstanding charges can be adjusted: when I press not guilty or guilty it fully exits out and only 20% of the time it does not.

Fixed in https://github.com/fkk-cz/noire/commit/1c3aa9274f17f5fbfcf27f1e0104e87fa8ae5690.

**Comment by fkk-cz** [comment]
@tythetanman can you confirm, is this fixed?

**Comment by tythetanman** [comment]
Still exits out. Just tested it. Clicked not guilty on a charge and it exited out. Have to F6 to re enter to finished going down the charges list.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/08e5c66f8aea013f7e3aa565c3a2102a2cd2730f.

A server callback wasn't being properly called due to a script error when dismissing charges.
