### ISSUE TITLE
Add "Court in Session" checkmark to F10

### ISSUE THREAD

**Issue by RockemRobotics** [fkk-cz/noire-public#503]
Currently, the bus driver only brings those charged with felonies pleading not guilty into the court cells at 585 if there is any judge or state attorney clocked in ("Court is in session" as we've been describing it). We agree this should stay in place - but what we would request is that since the number of attorneys on the F10 menu includes **all** DOJ members, it is often unclear to people in the city if court is in session or not.

Since this boolean value already exists in determining whether the bus driver brings someone to the courthouse or not, we simply request that it be displayed on the F10 menu along with the status of criminal activities. For example, at the left of "City Drug Sales", there can be another option named "Court In Session" with either a checkmark or an X depending on that boolean value.

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire/commit/2c19bac275d4b157970a4125b2da48829882607d.
