### ISSUE TITLE
Dark Chat…

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#509]
Please give me the ability to leave dark chat..

I'm in the burger shot one, and they won't shut the hell up, lol. It's bing bing bing bing. 

Don't want to just mute my phone. Just the ability to leave dark chats or mute the dark chats.

**Comment by D4LPebble** [comment]
you can leave it... lol

**Comment by RockemRobotics** [comment]
> you can leave it... lol

How?
