### ISSUE TITLE
falling through house/map when flying in

### ISSUE THREAD

**Issue by h0dger** [fkk-cz/noire-public#538]
My current house is a 1016 and everytime i fly in i fall through the map and it take a minute to reset everything. I wanted to swap houses with a house at 959. Please let me know if you have any other questions or concerns. thank you.

**Comment by c0mmoncents** [comment]
I believe this is because the interiors are actually under ground so if you leave in the house you fall through. It's happened to me as well so I just go outside before exiting.

**Comment by h0dger** [comment]
i asked in discord, they said i can request to switch houses due to this.

**Comment by No-Yes1** [comment]
Are you able to get a video of this happening? Just to see whether it's just your house or an interior issue?

**Comment by fkk-cz** [comment]
Post your Discord ID and a screenshot of your new desired location.

**Comment by fkk-cz** [comment]
> i asked in discord, they said i can request to switch houses due to this.

Please create a report in the Discord referencing this issue and it will be fixed.

**Comment by h0dger** [comment]
Eww_itz_seth#2844
![Screenshot (2)](https://user-images.githubusercontent.com/98565787/151678818-cfac86ef-7555-4698-a474-c605024da2e9.png)
