### ISSUE TITLE
Taco truck clear trunk inv when stored 

### ISSUE THREAD

**Issue by c0mmoncents** [fkk-cz/noire-public#545]
I stored my taco truck and when I pulled it back out the trunk inv was empty. I had 49 tacos and 24 waters.

**Comment by fkk-cz** [comment]
This does not meet our requirements for in-game compensation. Only cash losses over $10,000 can be compensated, we cannot spawn in items or weapons. Your claim does not meet those requirements.

In addition, we generally don't accept anecdotal reports like this without evidence -- the items in your vehicle were more than likely stolen by another player.
