### ISSUE TITLE
Add option to DOJ F6 menu to release suspects

### ISSUE THREAD

**Issue by RockemRobotics** [fkk-cz/noire-public#546]
When the courts find someone not guilty, there is no way to get them out of their orange jumpsuit and set up with a new phone short of sending them through the streets in their orange jumpsuit to a clothing store & shop OR sending them to prison for a 1-month sentence.

Adding an option to our F6 menu to "Release Suspect" or something similar would solve this. Have it teleport them to the back of the courthouse but without the jumpsuit and with a phone, just as if they'd just gotten out of prison. An alternative would be that this happens when we "sentence" someone to zero months in prison, but I prefer the idea of having it be an entirely separate menu item entirely.

**Comment by MatticusDaGreat** [comment]
^ I concur with this idea. That'd be a good solution for people that end up having their charges dismissed.

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire/commit/986d2f0b38c88d98683acfb368b9c1c621abad65.

Instead of releasing them in front of the courthouse (enough people are loitering on the steps), it will send them to the jail release location.

Releasing individuals, managing charges, and other court features are now restricted to use at the courthouse only.

**Comment by RockemRobotics** [comment]
> Instead of releasing them in front of the courthouse (enough people are loitering on the steps), it will send them to the jail release location.

We kind of already had that option. By sending them to prison for 1 month, they'd be out of the prison by the time they were done clicking through things. I hate to look a gift horse in the mouth, but we were hoping for a different option, which is why I'd suggested sending them to the back of the courthouse as a possibility. Something distinctly different from being sent to prison for a very short sentence.

> Releasing individuals, managing charges, and other court features are now restricted to use at the courthouse only.

This is a great idea. Thanks for implementing it.
