### ISSUE TITLE
twitter suspension

### ISSUE THREAD

**Issue by prettykiddoe** [fkk-cz/noire-public#548]
I keep having my Twitter auto-suspended for no reason. I never say anything disrespectful or even attempt to say anything harmful/disrespectful and when I try to make another tweet, I'm suspended until reset with no fix. I'm the SOA Melanie account and I'm joking about divorcing my in-city husband when I have my account suspended. 
![Screenshot (51)](https://user-images.githubusercontent.com/98686213/151693390-f8f8dcea-7862-4d8f-9910-17af59b62a7b.png)
![Screenshot (52)](https://user-images.githubusercontent.com/98686213/151693392-4519ae03-03f8-46df-ab2e-e5d24e93e839.png)
![Screenshot (53)](https://user-images.githubusercontent.com/98686213/151693396-887baf31-e6a0-49b3-a9b5-0eec9860f931.png)

This happened to me before where I was responding to a Burgershot employee on Twitter and had my account autosuspended by this new system. What words ping the system to suspend my account cause I'm not able to get it back until reset.

**Comment by fkk-cz** [comment]
I have no idea what's causing people to get their Twitter accounts auto suspended. Also a bit hesitant to release the exact list of words/patterns that will cause a suspension, as people will try to circumvent it.

Do you have the exact tweet that was sent before your account got suspended?

**Comment by prettykiddoe** [comment]
it was “#singleladies” and then after that i attempted to say “lets have a girls night, just soa girls”

**Comment by D4LPebble** [comment]
yeah its nothing you did prior, it bans you on the CURRENT tweet you tried to send. like i found out we cant say "bang." its just an auto ban. i get not releasing a list, but maybe even so just muting twitter for a smaller amount of time would suffice. if an hour passes then most people may have just flown out, or wont even be focus on whatever they were saying.  if it persists throughout that day, like for example i get suspended once its 1 hour, then if i get suspended a 2nd time in the same day its 3 hours, then it just becomes harsher and harsher

**Comment by fkk-cz** [comment]
One of the patterns matched for the word "ban", not checking for any word boundaries. That is the most likely explanation for a lot of the false Twitter mutes recently -- I guess people send a lot of tweets with the word "ban".

Reducing the Twitter suspension to an hour isn't a bad idea, this feature was implemented due to an incident where one disgruntled individual decided to join and send racial slurs.

**Comment by noyeahsure** [comment]
flew in right now and tested the same thing yesterday, tweeted hey guys, then went to tweet this food bangin and got it again, pretty sure I see another word that is also in the list, which i can understand why,
but adding on to pebbles comment, maybe 
1st offense 1 hour
2nd is until restart

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/8dfaf54d1bab3435afcf88708b012f0e2fee4cd5

Automatic suspensions are now one hour, manual suspensions are until restart. Also removed the pattern "ban" from the match list.

**Comment by D4LPebble** [comment]
woooo for constructive conversation!
