### ISSUE TITLE
My house has an invisible wall! 

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#550]
After restart today an invisible wall popped up blocking me from getting into my house! Also while this gets fixed can the locks inside be removed please! 

https://medal.tv/games/gta-v/clips/9yd7v2-1u2bBT/d1337SUSpA1H?invite=cr-MSxWcWksMTg3OTQ2MDQs

**Comment by No-Yes1** [comment]
I'm not sure what the issue is/was? I've just tested it out & works fine for me: https://streamable.com/vjbemy

**Comment by cxerq** [comment]
Yeah it worked for others too! I don't understand it!

**Comment by No-Yes1** [comment]
Since there is no way to reproduce the issue. I'm not sure what your issue is. Maybe take a look at any graphics mods you have installed (i.e NVE) and see if that can possibly assist.
