### ISSUE TITLE
HUD Issues and Improvements

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#554]
Players on non-standard resolutions (apparently people somehow still play on something less than 1920x1080?) have issues where the main HUD elements (player ID, health, armor, etc.) start wrapping into the next line, or are too small to read at higher resolutions.

All of these HUD elements now scale according to screen size. I've tested it in windowed mode and everything seems to look fine, further feedback from players with 4K/"weird" resolutions will be required.

Depending on the feedback, the next step would include fixing some of the positional issues with the postal and street display, along with the car diagnostics text.

**Comment by somedudenamedrush** [comment]
atm the new ui says 0 hp when you know ur 100
![image](https://user-images.githubusercontent.com/40413422/152219346-50511168-d908-4386-8418-965851d4a066.png)

**Comment by fkk-cz** [comment]
Fixed, thanks for reporting. https://github.com/fkk-cz/noire/commit/d07f677b20c95268da0d64bb8191414c16c30e04

**Comment by budmitchell** [comment]
![image](https://user-images.githubusercontent.com/98933860/152279953-0cc24adb-37e4-4fde-b51c-62b0d1a36bae.png) 
i have that issues as well as this issues with the MDT 
![image](https://user-images.githubusercontent.com/98933860/152279980-ad9bff52-52bf-41a2-a58a-3c2aeef836bf.png)

**Comment by RockemRobotics** [comment]
> ![image](https://user-images.githubusercontent.com/98933860/152279953-0cc24adb-37e4-4fde-b51c-62b0d1a36bae.png) i have that issues as well as this issues with the MDT ![image](https://user-images.githubusercontent.com/98933860/152279980-ad9bff52-52bf-41a2-a58a-3c2aeef836bf.png)

For reference, this user has a 1366 by 768 resolution monitor.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/542

MDT issue is not HUD-related, this is for vehicle and the character info HUD only.
