### ISSUE TITLE
third eye cursor glitch 

### ISSUE THREAD

**Issue by AntonioAres** [fkk-cz/noire-public#556]
https://user-images.githubusercontent.com/98921585/152246660-35ca69e4-570f-400e-9e51-1a50a40f4e32.mp4

My third eye glitches my cursor to were I can not select anything or interact with my third eye.

**Comment by RockemRobotics** [comment]
Go to Settings -> Keyboard/Mouse and look at "Mouse Input Method"

Is it on "Windows"? If so, change it to "Raw Input" or "Direct Input". I did some quick Googling and then confirmed for myself in-game that this is an issue in FiveM when using "Windows" as your mouse input method.

**Comment by fkk-cz** [comment]
Raw input is always generally recommended, mainly used to disable any kind of mouse acceleration. Not sure whether that is the cause, but it does look like a input focus problem.

Anyone else having this issue?

**Comment by noyeahsure** [comment]
havent ran into this problem yet in the updated third eye system

**Comment by Daniel9935** [comment]
Changing this to Raw Input fixed this for me and also an issue I was having with my comma clothing menu so thank you 🙂
