### ISSUE TITLE
Mischarged

### ISSUE THREAD

**Issue by Originalwizkid** [fkk-cz/noire-public#557]
I got charged with reckless driving and illegal street racing. I was told I shouldn't be charged as a felon by 2 cops and a judge but unfortunately i was fined 9k sent to jail for a month and now I'm a felon.

**Comment by noyeahsure** [comment]
sir this is what the DOJ system was put in for

**Comment by fkk-cz** [comment]
Github issues are not for roleplay issues. Please handle this in game.
