### ISSUE TITLE
Felony not removed after 14 Days

### ISSUE THREAD

**Issue by BeeezyBCD** [fkk-cz/noire-public#558]
My felony wasn't removed after 14 days. I got arrested for felony possession (Only had 1 Untrimmed weed)
Officer who read me my charges said felony's reset at midnight, which would be 15 days not 14. I would really appreciate  like more incite to the situation so I can get these charges removed. Also My last felony was on Jan 19th. and before today it said they would be removed on the 2nd but now when I look it says the 3rd. Went to court and go no answers from the judge. nobody can give me clear answers

**Comment by No-Yes1** [comment]
Go to the courthouse near MRPD and check the expunge date, that will show you when you are not a felon.

**Comment by BeeezyBCD** [comment]
My last felony was on Jan 19th. and before today it said they would be removed on the 2nd but now when I look it says the 3rd

**Comment by fkk-cz** [comment]
Wait until tomorrow and it will be removed from your record.
