### ISSUE TITLE
FPS since Golf

### ISSUE THREAD

**Issue by Daniel9935** [fkk-cz/noire-public#561]
I have been in the city for about 4 months now and I have all the recommended graphics settings in discordia set for the city. 

Since golf has been added my FPS has gone from 80-100 to 30-40 and I have been unable to find out why as all my hardware is running perfectly with no issues. 

Im mainly just after any tips to improve my FPS as currently, it's been unplayable since golf was added as driving around the city has been a massive issue.

**Comment by noyeahsure** [comment]
That's weird my FPS is almost the same as it was before golf. very confused at how golf would ruin your frames that bad, seeing as golf really isn't that intensive, it's not like, loading in 30 players vehicles etc

**Comment by RockemRobotics** [comment]
If you haven't already, turn off all of the anti-aliasing options in your graphics settings (Everything with an "AA" in it). That should help your frame rate.

**Comment by Daniel9935** [comment]
This has already been turned off since I joined the city
