### ISSUE TITLE
Player owned houses not loading in 

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#563]
I've had this issue for the past few months- happens at least 3 times a week. I'll fly in and everything loads in but the P.O houses. It takes a few times of relogging to resolve the issue.
![Screenshot 2022-02-04 173449](https://user-images.githubusercontent.com/92474477/152612314-3aa82a44-9dca-4867-8aa7-d7d6c24a1526.png)

**Comment by Ell34** [comment]
A few will load in but not all.

**Comment by fkk-cz** [comment]
Are you able to enter any of the houses even without the blips?

**Comment by Ell34** [comment]
> Are you able to enter any of the houses even without the blips?

Nope. Garage doesn't show either.

**Comment by No-Yes1** [comment]
Someone else had this issue before, I can't remember who or the fix

**Comment by fkk-cz** [comment]
Finally had this issue myself -- it's caused by invalid data received from the server when fetching houses on connect. https://github.com/fkk-cz/noire/commit/73e4ea35e5c2a8d1be5761ae3f5f570ec209094f

**Comment by Ell34** [comment]
> Finally had this issue myself -- it's caused by invalid data received from the server when fetching houses on connect. https://github.com/fkk-cz/noire/commit/73e4ea35e5c2a8d1be5761ae3f5f570ec209094f

Just relogged and they aren't loading in. I'm more than positive its a connection based issue with the player.
