### ISSUE TITLE
Landscaping Job at 185/184 Is bugged.

### ISSUE THREAD

**Issue by integrationrachel** [fkk-cz/noire-public#58]
Got assigned the Landscaping job at postal 185/184 and the person you talk to to start the job does not appear. This also happened for other players as well. Since you can not get a new job without finishing this one, we can no longer do any landscaping jobs until we disconnect from the server. The image is the location of the job.

![image](https://user-images.githubusercontent.com/71654490/137638112-e9d61ee8-6657-4598-86a2-cc0f26dc6135.png)

**Comment by byu26** [comment]
Just to add a month later. This issue seems to happen still and at other locations. As well as after completing the job the NPC is just gone and you can't collect the money.
