### ISSUE TITLE
Remove static gates from player owned property

### ISSUE THREAD

**Issue by Trapp1** [fkk-cz/noire-public#598]
The gate at my house won't open and is glitched, so I have to go around and jump just to get into my house. Therefore, I suggest removing the gate of the house or if possible fixing it.

**Comment by No-Yes1** [comment]
Where's your house located/can you provide a clip?

**Comment by Trapp1** [comment]
> Where's your house located/can you provide a clip?

The house is located at postal 855

**Comment by Trapp1** [comment]
And also I’m not sure how to post the clip here so where can I post it instead ?

**Comment by No-Yes1** [comment]
Upload the clip to https://streamable.com/ and then post the link here.

**Comment by Trapp1** [comment]
> Upload the clip to https://streamable.com/ and then post the link here.

yo its been more than a week, any updates ?

**Comment by fkk-cz** [comment]
This would require a map edit to remove the gate. No idea if it will even work, I'll look into this.

**Comment by fkk-cz** [comment]
Added a ymap edit to fix your housing issue. If anyone else has gates blocking their driveway, put the postal and a screenshot of the house here.

**Comment by Noelcorrea** [comment]
https://streamable.com/yoiwte postal 688 my gate wont open at all

**Comment by fkk-cz** [comment]
> https://streamable.com/yoiwte postal 688 my gate wont open at all

Fixed for next reset, removed the gate entirely.

@Bludiam0nds those gates cannot be removed as they are not selectable entities. I'd recommend a house relocation.

**Comment by Bludiam0nds** [comment]
oh wow. i just moved there i didnt know...

**Comment by Noelcorrea** [comment]
is it the coming up reset? cause its still there after last reset

**Comment by Noelcorrea** [comment]
Any update on this? my gate is still there.

**Comment by fkk-cz** [comment]
Not sure why this isn't working -- I made the appropriate map edits and the file does appear to be streamed correctly. I'll look into this tomorrow.

**Comment by Noelcorrea** [comment]
okay thank you (:

**Comment by Trapp1** [comment]
> Added a ymap edit to fix your housing issue. If anyone else has gates blocking their driveway, put the postal and a screenshot of the house here.

I haven't played since we last talked, but I hopped on yesterday and the gate is still there
