### ISSUE TITLE
Stuck on black screen after checking in

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire-public#605]
Hola!
There’s a issue with the whole checking in system atm. When you check in after getting picked by EMS, you get stuck on a black screen and need to relog to get out of the black screen.
When you relog, your stuff won’t be in your inventory anymore.

**Comment by fkk-cz** [comment]
Does this only occur when getting checked in by another player? Or does it apply to self check in as well?

> AND when you try to use the wardrobe in a house, you get stuck and need to relog

No changes were made to the wardrobe system, this sounds like an isolated issue.

**Comment by cxerq** [comment]
> Does this only occur when getting checked in by another player? Or does it apply to self check in as well?
> 
> > AND when you try to use the wardrobe in a house, you get stuck and need to relog
> 
> No changes were made to the wardrobe system, this sounds like an isolated issue.

Its only when checked in by someone!

**Comment by TheBottomFragger** [comment]
> Does this only occur when getting checked in by another player? Or does it apply to self check in as well?
> 
> > AND when you try to use the wardrobe in a house, you get stuck and need to relog
> 
> No changes were made to the wardrobe system, this sounds like an isolated issue.

When ppl are getting dropped in front of the counter, they can’t use the third eye to check in, so EMS need to check them in, but as far as I know, the ppl that got checked in by EMS got that black screen. 

And when it comes to the wardrobe thing, it’s most likely because of the “player loading” or whatever that pops up now

**Comment by fkk-cz** [comment]
The black screen when checked is fixed in https://github.com/fkk-cz/noire/commit/7fc234c512e5060e479495001338f2e361d6540f.

I was unable to recreate the house wardrobe issue, it has nothing to do with the clothing store.
