### ISSUE TITLE
Stuck in wardrobe

### ISSUE THREAD

**Issue by residentalyeti1** [fkk-cz/noire-public#606]
Saw there was someone else who had a wardrobe issue earlier. So i was putting my civilian clothes on at Mt Zonah and got stuck. couldnt use any keys on the keyboard other than to rotate

https://medal.tv/games/gta-v/clips/aXlXcQcy9B0ni/d1337ka5ideM?invite=cr-MSxwZU4sNDMyMDMzODEs

**Comment by ImJustBetter420** [comment]
yeah at station earlier somone was changing back into civ clothes and got stuck and had to relog

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/b18d0ab536d34fd70a5318c357fdb546de4efdb8.
