### ISSUE TITLE
EMS Related Issues

### ISSUE THREAD

**Issue by PresumedDumbass** [fkk-cz/noire-public#607]
Just to start with 2 for now. But the new system with the 3rd eye and having to look at the doctor is a bit scuffed since the doctor moves around and the 3rd eye option has a rare chance of working.  To add on, if the doctor moves places in your eyes its still in the same spot or different spot for other peoples eyes.  Patients also cant use their 3rd eye when dead and with the doctor moving around its hard to check people in as EMS which is their only way of checking in.  The other issue is also that the EMS supervisor ford explorer has broken textures so its constantly changing colors and looks broken. Along with our supervisor SUVS both explorer and tahoe for a while now can no longer place bodies inside them even though we have seen law enforcement throwing dead boddies inside their vehicles.

**Comment by fkk-cz** [comment]
> But the new system with the 3rd eye and having to look at the doctor is a bit scuffed since the doctor moves around and the **3rd eye option has a rare chance of working.**

_What_? What does the ped's movement have to do with the targeting system's reliability?

> Patients also cant use their 3rd eye when dead and with the doctor moving around its hard to check people in as EMS which is their only way of checking in.

That's ..kind of the point? No one should be able to check themselves in when dead.

> The other issue is also that the EMS supervisor ford explorer has broken textures so its constantly changing colors and looks broken. Along with our supervisor SUVS both explorer and tahoe for a while now can no longer place bodies inside them even though we have seen law enforcement throwing dead boddies inside their vehicles.

Both of these issues have been fixed.

**Comment by Stagonium** [comment]
> Patients also cant use their 3rd eye when dead and with the doctor moving around its hard to check people in as EMS which is their only way of checking in.

I think the hard part is the person being carried sometimes being in the way of you using alt to select the doctor. But for PD at least I would just drop the guy and then check them in since it checks for nearby people. I would imagine EMS could do the same thing with a stretcher full of bodies, just set it at the desk and then _Check in Nearby Player_ repeatedly
