### ISSUE TITLE
Mining Layout Suggestion

### ISSUE THREAD

**Issue by gxdsent** [fkk-cz/noire-public#608]
With the addition of the gooseneck trailers and increased volume of players in the city I've noticed the few times I do mining runs. Each time the whole area down there is a mess due to people just not knowing proper etiquette, people being greedy and stealing spots/etc. So when people are trying to navigate down there because there is a mess of trailers/vehicles it makes it much more difficult than it has to be. 

What I was suggesting is maybe relocate mining spots and spread them out to where they can be on the other two levels that are surrounding the original mining area so there is more room to navigate, and it isn't as congested down in the thick of it. Anything to help the flow of that area would be huge for the rigs people are able to use now.

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire/commit/a713682282379fcf559dc39366ba5f9a3eca7d2b.
