### ISSUE TITLE
Taxi company clock in and clock out system at the taxi depot 

### ISSUE THREAD

**Issue by teresgrunt4555** [fkk-cz/noire-public#613]
It would be nice for the taxi members to be able to go on and off duty from the depot so we don’t keep running in to the fact of  people saying they are not paycheck camping but they just forgot to clock out. It would make us like the other places.

**Comment by No-Yes1** [comment]
Merging this issue with the one you made after - https://github.com/fkk-cz/noire-public/issues/656.
