### ISSUE TITLE
EMS Additions

### ISSUE THREAD

**Issue by PresumedDumbass** [fkk-cz/noire-public#623]
Just small things that/ideas to be added in for EMS: 
If we could possibly get the quick change for our radios at least for Sr.EMTs and up with the brackets  [ ] to switch channels since its super awkward changing channels with a stretcher in your hand and we cant see the radio options when doing so.

Lastly, I know the broken vehicle textures are still being worked on, but we were told the 2016 Ford explorer Textures were fixed but they're still broken so if that could hopefully be fixed along the way?

**Comment by No-Yes1** [comment]
> Lastly, I know the broken vehicle textures are still being worked on, but we were told the 2016 Ford explorer Textures were fixed but they're still broken so if that could hopefully be fixed along the way?

Use the noire_vehicles repo issue for that https://github.com/fkk-cz/noire_vehicles/issues/888

**Comment by fkk-cz** [comment]
Cycling the radio is now available for all whitelisted jobs with a usable radio. https://github.com/fkk-cz/noire/commit/b16e9d3474eb95dee33578e3341cbac883faf585
