### ISSUE TITLE
DOT Additions/Updates

### ISSUE THREAD

**Issue by No-Yes1** [fkk-cz/noire-public#624]
I know we spoke about this in a meeting a few months back, but thought i'd put it all into one issue, with some few updated suggestions from DOT Employees.

~-  Allow for DOT Managers/Executives to unimpound vehicles~
~-  Better way to take pictures to put in 》impound-evidence (Already in the making)~
-  A feature for civilians for call dot (either by a favourites on the phone,  how LSPD/SAHP is.)
-  Possibly having the mass re-vamp and change DOT to a mechanics shop, where we would repair/do certain upgrades on vehicles
- Repair kits may only repair up to a certain % (obviously this will cause issues, where people will spam twitter/ become irate with DOT, constantly asking for repairs). Maybe certain vehicle types (i.e. Super/Sports vehicles)??
- Invoicing system similar to how how Cab-Co has, Currently if a civilian flags a DOT employee down, we relay on that the civilian has cash in hand (which most people don't for obvious reasons). An invoicing system for repairs/fuel would make more sense, and the money would go back into the DOT society account.
 - Managers/Executives access to PD frequency's, there's still A LOT of times where PD especially will impound vehicles, even though DOT is on, or they will request PD and just drive off... Leaving DOT confused on what we're impounding the vehicle for/what vehicle we're impounding in general.
 - Another Impound lot up north in the county so that DOT can impound vehicles up north instead of solely patrolling the city.

**Comment by cxerq** [comment]
> * Repair kits may only repair up to a certain % (obviously this will cause issues, where people will spam twitter/ become irate with DOT, constantly asking for repairs). Maybe certain vehicle types (i.e. Super/Sports vehicles)

I think this would be great, maybe could add in Player Owner Mechanic Shops that would allow player to go there and fix there cars if the shop is stocked with the stuff needed, Could tie this in with a new job for salvaging metal and other parts!

**Comment by fkk-cz** [comment]
> Better way to take pictures to put in 》impound-evidence (Already in the making)

Added in https://github.com/fkk-cz/noire/commit/1e3e85d3fd28db323cce90b77d9cde77d2daa51e. All new impounds will require a valid image URL in the impound form before submitting.

**Comment by No-Yes1** [comment]
> > Better way to take pictures to put in 》impound-evidence (Already in the making)
> 
> Added in [fkk-cz/noire@1e3e85d](https://github.com/fkk-cz/noire/commit/1e3e85d3fd28db323cce90b77d9cde77d2daa51e). All new impounds will require a valid image URL in the impound form before submitting.

This is a good feature, however DOT Executives use impound evidence when we are doing the bonus pay. This is due to activity log shows graffiti removals. Plus, if a civilian wanted to complain re: improper parking, Managers+ have no way to see what the image was unless we ask the civilian (which 90% of the time they won't have it). Possibly adding in a webhook in impound-evidence for managers to see, as well as Executives to carry on our process on the society account.

**Comment by No-Yes1** [comment]
> Players will now be able to challenge their impounds at the courthouse. DOJ (State Attorneys and higher) & DOT (Manager and higher) have the authority to release impounded vehicles -- regardless of time remaining -- and waive all impound fees.
> 
> This will be used sparingly as police/DOT are required to document evidence on the form before submitting, mainly to correct errors or release vehicles on acquittal. To qualify for impound relief, the registered owner of the vehicle must prove there was a clear mistake. In other words, the burden of proof is **not** on the impounding officer -- all of the information, including the photo of the car, will be taken on a good faith assumption.

DOT need one at the impound lot as there is currently only one at the courthouse, which means DOT would rely on DOJ to be available to unlock the doors.

**Comment by somedudenamedrush** [comment]
still missing Unimpound blip at the DOT lot

**Comment by No-Yes1** [comment]
Just querying for an update on this -- we are still waiting for an unimpoundment blip @ DOT lot so we don't have to keep relaying on DOJ to be available. 😄

**Comment by No-Yes1** [comment]
Following on from a conversation with LEO, Maybe adding in the name of the LEO who requested DOT's assistance, i.e "LSPD - SGT Jumbi is requesting a DOT service Call".

**Comment by No-Yes1** [comment]
Also - I know we spoke about this, but adding in an un-impoundment log due to recent incidents

**Comment by No-Yes1** [comment]
Can we bump this please, especially the priorities:

Invoicing system similar to how how Cab-Co has, Currently if a civilian flags a DOT employee down, we relay on that the civilian has cash in hand (which most people don't for obvious reasons). An invoicing system for repairs/fuel would make more sense, and the money would go back into the DOT society account.
Managers/Executives access to PD frequency's, there's still A LOT of times where PD especially will impound vehicles, even though DOT is on, or they will request PD and just drive off... Leaving DOT confused on what we're impounding the vehicle for/what vehicle we're impounding in general.
> [somedudenamedrush](https://github.com/somedudenamedrush) commented [on 24 Mar](https://github.com/fkk-cz/noire-public/issues/624#issuecomment-1077310532)
still missing Unimpound blip at the DOT lot

**Comment by No-Yes1** [comment]
Can DOT get a notepad, like the one LEO have, would be useful to note down things at LEO service calls.

**Comment by No-Yes1** [comment]
> Just querying for an update on this -- we are still waiting for an unimpoundment blip @ DOT lot so we don't have to keep relaying on DOJ to be available. 😄

Sorted that one, thank you

**Comment by RockemRobotics** [comment]
> > Just querying for an update on this -- we are still waiting for an unimpoundment blip @ DOT lot so we don't have to keep relaying on DOJ to be available. 😄
> 
> Sorted that one, thank you

Enjoy it!

**Comment by No-Yes1** [comment]
Can we have any sort of update on this/any expected time frame.
