### ISSUE TITLE
weird bug that happened to me

### ISSUE THREAD

**Issue by gnomeking69420** [fkk-cz/noire-public#625]
https://medal.tv/games/gta-v/clips/bMUkGFpcAnxNE/d1337Uqxls9b?invite=cr-MSwzZFcsMTg0ODg2ODYs

**Comment by fkk-cz** [comment]
Were you in the nightclub earlier in the same session?

**Comment by gnomeking69420** [comment]
it just happened to me again at the same gas station and in both sessions i haven't been in the night club

**Comment by fkk-cz** [comment]
Decided to remove the vanilla nightclub entirely -- the teleporter thing was weird anyways. Going to replace it with a walk-in interior.
