### ISSUE TITLE
New Phone Issues and Improvements

### ISSUE THREAD

**Issue by jeanndabeann** [fkk-cz/noire-public#628]
(PLEASE FEEL FREE TO ADD COMMENTS OF SUGGESTIONS)
Phone Stuff
- showing the number of people who favorited your tweet. I think this will cut down with all the Retweeting that floods timelines.
- opening pictures from twitter, you cant open them to screenshot them
- when you are calling someone it is INCREDIBLY loud, like overbearingly loud, and there is no way to lower it
- It says 'NOIRE' in the top right of the phone which probably isnt the best for our streamer friends
- bank app being added (pretty sure i saw this already going to be added but im just adding it here so it doesnt get forgotten)
- snake game app plz
- some more ringtones and text tones would be nice, i do miss our old text tone!
- time stamps for texts so we can tell the time when someone texted you
- for the matchmaking app, idk if its planning on staying but as of now you go through a few people and then it says there are no more matches until you fly out and back in.
- gps location being added back to texts, idk if it was on purpose but it is helpful when you are in the middle of no where hunting or something
- group chats maybe
Overall the phone update is something to get used to but its better in the long run

**Comment by tythetanman** [comment]
The ability to be able to block a number.

**Comment by Ell34** [comment]
- be able to import photos into photo gallery via URL, 

- be able to edit photos that are saved in your gallery

**Comment by Ell34** [comment]
also when you go to upload a URL photo to twitter and its too big theres no way to scroll down to hit "tweet"

**Comment by jeanndabeann** [comment]
- organizing contacts by alphabetical order
- organizing texts by recents and newest at the top

**Comment by No-Yes1** [comment]
> also when you go to upload a URL photo to twitter and its too big theres no way to scroll down to hit "tweet"

Technically, you shouldn't be posting URL's on the twitter feed. If you're cropping a picture you can always use https://imgur.com/. Then paste the photo there to get the link.

![image](https://user-images.githubusercontent.com/79383480/155085440-867fc4ea-0ab0-487f-aaef-e6ac259e2114.png)

Click open image in new tab and then you can copy and paste that in twitter.

**Comment by tythetanman** [comment]
“ for the matchmaking app, idk if its planning on staying but as of now you go through a few people and then it says there are no more matches until you fly out and back in.” i’ve noticed that as well you can’t have it to update with new names or the matches that were made unless you fly out and back in. 

Other than that like I said above be able to block someone from contacting you and group messaging would be a great thing. 

The matchmaking app only has that one single flaw of having to re-log to update.

**Comment by fkk-cz** [comment]
Moving #509 #514 #536 here.

**Comment by RockemRobotics** [comment]
> * organizing contacts by alphabetical order
> * organizing texts by recents and newest at the top

Contacts go back into alphabetical order when you fly back into the city. Until then all new contacts stay at the bottom of your contact list on the order you added them.

**Comment by jeanndabeann** [comment]
just flew back in after yesterday and i noticed i dont have a notification for new texts over the messages app! and new texts dont show up by order of the most recent!
- something to add would be notifications for missed calls and notifications for text messages!
adding to what art added, my contacts are in alphabetical order now after tsunami!

**Comment by fkk-cz** [comment]
Adding https://github.com/fkk-cz/noire-public/issues/634 to this.

**Comment by tythetanman** [comment]
The ability to have to Twitter accounts whenever we all can acknowledge we have a cousin. 

If possible two Twitter accounts per citizen and one name change per account.

**Comment by No-Yes1** [comment]
Following on from that ^ - The possibly to have a government job twitter account, (i.e Casino/Cab.Co/DOT) etc etc.

**Comment by tythetanman** [comment]
Ohhhh I love that

**Comment by Bountyrogger** [comment]
IDK if its still an issue or just me, but when Im not in the city and get texts I get a notification when I fly in but there is no messages to speak of...

**Comment by okxeon** [comment]
Adding an insurance app of sorts to allow players to report their car stolen.  This would be a significant improvement as right now the only way to really report a car stolen is to linger around a PD till you find a cop. The insurance app would let players report only cars they own, and in addition the app could also automatically set a BOLO for the vehicle. Granted this opens the door for the feature to be abused. Friends will give friends cars to do criminal activity, and the owner will report it stolen to avoid impound times & fines. One simple fix is for LEOs to have the ability to ping the vehicles location once every minute. That way if you do crime in a stolen car it becomes more of a risk. Just a thought.

**Comment by somedudenamedrush** [comment]
can we get the ability to zoom into photos in text twitter and marketplace

**Comment by Dezutss** [comment]
When your in a call with someone there way too quiet,I sometimes can even make out what there saying.

**Comment by DeJayRambo** [comment]
Bring back the old ringtones or make it so we can set our own. cause the recent change sounds like a office phone and its kinda icky in my opinion.

**Comment by IIBurntLuisII** [comment]
we need a mobile banking app and be able to send money through the app
