### ISSUE TITLE
Phones not opening then game crashes 

### ISSUE THREAD

**Issue by Dallasknight** [fkk-cz/noire-public#633]
Today I had to fly out three times just for my phone to come back onto my screen. At random times when you press f1 the animation of the phone will show but the phone itself will not appear on the screen. In order to fix that I’ve had to fly out. However several of my friends have had their games crash after this same issue.

**Comment by No-Yes1** [comment]
Enable this option in the FiveM Settings -> 
![image](https://user-images.githubusercontent.com/79383480/155508999-ac1d4aae-8817-4a3b-9405-f0d1c23bf274.png)

Otherwise, you can try pressing f8 and typing in "/rui"

**Comment by Dallasknight** [comment]
I have and done the other thing and it still does it.

**Comment by No-Yes1** [comment]
Have you got a clip of this?

**Comment by Dallasknight** [comment]
Yes. It just happened and I have it clipped

**Comment by Dallasknight** [comment]
https://medal.tv/games/gta-v/clips/cP1RXI1FhwGFu/d1337Wf3YKev?invite=cr-MSxUTTQsNTIwMjAwNjcs

**Comment by fkk-cz** [comment]
> https://medal.tv/games/gta-v/clips/cP1RXI1FhwGFu/d1337Wf3YKev?invite=cr-MSxUTTQsNTIwMjAwNjcs

Are there any obvious error messages in the F8 console when this happens? Could you upload any crash dumps?

**Comment by Dallasknight** [comment]
my game didn't crash, but here is the error message in the F8 menu
https://medal.tv/games/gta-v/clips/d9rklm6pdSvxN/d1337xzvk7Rx?invite=cr-MSxmdDMsNTIwMjAwNjcs

**Comment by fkk-cz** [comment]
Unfortunately these error messages aren't too helpful, the pattern `\bunread\b` doesn't even exist in the /resource subdirectory.

Does this happen _every_ time you try to open the phone?

**Comment by Dallasknight** [comment]
Not all the time. I don't know what My friends and I do that may cause it but it happens at random times.
