### ISSUE TITLE
aventador speed 

### ISSUE THREAD

**Issue by h0dger** [fkk-cz/noire-public#636]
if possible maybe just a tad increase on top speed. everything else is good in my opinion but being a 1.5 million dollar car 240 seems a little low.

**Comment by No-Yes1** [comment]
i think we're more then fair with the 240 top speed on it: 
<img width="758" alt="image" src="https://user-images.githubusercontent.com/79383480/155863628-f2bcfefa-8382-4c0e-af86-56c14eaf3e20.png">

Not all vehicles go 240, so it's not like it's a common thing. Vehicle issues for future reference need to go to https://github.com/fkk-cz/noire_vehicles/issues
