### ISSUE TITLE
Can't drive if passenger is waiting in car

### ISSUE THREAD

**Issue by RockemRobotics** [fkk-cz/noire-public#642]
As of today, there is a bug where if a passenger in a car before the driver gets in, the driver cannot actually drive the car. The passenger exiting and entering seems to fix the problem, but it leads to situations where getting into a car with a waiting friend means you can't actually go anywhere and there's no reason for the person to sit in the passenger seat.

Video demonstrating the bug: https://streamable.com/mp6htx

**Comment by fkk-cz** [comment]
This looks like an isolated incident with you (the driver) not having control of the vehicle. I was unable to recreate this myself, tried multiple vehicles and didn't have this issue.

**Comment by RockemRobotics** [comment]
I tried to show in the video that it happened with different vehicles and different drivers but the same situation. It might be an intermittent issue but it was very repeatable between the two of us that morning.

**Comment by tythetanman** [comment]
Ran into this a 2nd time today. BUT currently it’s happened to me maybe 2 out of over 30 times. 

But did happen.
