### ISSUE TITLE
PDM no longer shows how much your car is worth when selling it back

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#647]
PDM used to tell you how much you would get back from selling your supporter car. I've noticed since the vehicle recall update, when you drive into the green circle it just says "Press E to sell your car back to the dealership". I don't know if this was intentional or if its just a bug.

**Comment by No-Yes1** [comment]
That's intentional as when we were doing the recalled vehicles, it would state how much, but it would sometimes be in-correct. Selling Supporter Vehicles back to PDM gives you 70% back, so you can easily calculate how much it would be.
