### ISSUE TITLE
Addons in the city

### ISSUE THREAD

**Issue by AntonioAres** [fkk-cz/noire-public#655]
Could we impliment a system if you have a tv In your house you can search a Youtube video using the URL and paste it on your tv and you can watch the youtube video on the tv in your house.

**Comment by tythetanman** [comment]
Personally Antonio I did think about that as well whenever I found out about VR Chat. I was not sure if it was possible and did not have the time or remember to think about it outside of court stuff.

**Comment by tythetanman** [comment]
But then we would also have the issue of potentially going AFK more often.

**Comment by cxerq** [comment]
> But then we would also have the issue of potentially going AFK more often.

It would be a great way to show court evidence too!
