### ISSUE TITLE
Upgrades for Downtown cab co.

### ISSUE THREAD

**Issue by teresgrunt4555** [fkk-cz/noire-public#656]
There are some upgrades I think we could use to improve taxi and get more use out of it. 
1st one would be a way to have people tip drivers with out having to go to the bank or their force charge them to and have the available to accept tips and improve time. 
2nd- would be a tracker or some type of way to see invoice to see who is driving when no manager or Executive can be on. One way I could see this is maybe like how DOJ has court activity maybe we ca get something like that so we can see who is active. 
3rd- I would also like to see taxis either get a little it if a pay raise or even bonus. I was think for a pay raise it would go 
Driver- 2,000
Dispatch/ Sr Driver- 2,500
Manager and Owner - 3,000
4th- A new location with a working interior so we have some where to hang out when calls are slow or eve somewhere to do interviews. It would also help us out with SOA across the street and hang wars.

**Comment by Bountyrogger** [comment]
To add onto this. I think the number one thing we need is a way to clock in at the depot. So many times I go and clock in when im driving on my own and I get 3+ calls just trying to get from Job Center to the Depot and same thing when Im clocking out

**Comment by LegendaryBruno22** [comment]
Yes this is brilliant, I was rejected from the Taxi for not writing full sentences 🤣

I do believe this would be more functional and more realistic too.
