### ISSUE TITLE
Ability to dock boats on yachts and aircraft carrier + docks 

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#665]
Me and a friend ran into a problem where our boat flipped in the aircraft carrier boat bay. Adding an ability to dock boats on larger boats and with time to docks would allow a lot more interaction with the activities on the water.

**Comment by fkk-cz** [comment]
Surprised no one brought this up earlier -- having your boat float away when parked in the water has been an annoying issue that's prevented boats from being used more.

Added the ability to drop an anchor on all boats, vehicles that are anchored will no longer drift away (unless someone tampers with your anchor and removes it).

![image](https://user-images.githubusercontent.com/74131024/158305030-72304905-2a5e-4d2e-967c-77808ab657ec.png)
