### ISSUE TITLE
Bug with vehicle missions/suggestion.

### ISSUE THREAD

**Issue by YeetMeAway** [fkk-cz/noire-public#668]
Recently I have seen 2 vehicle missions function properly from beginning until the vehicle has to be dropped off. Once it is properly placed and kicks you from the vehicle, the vehicle does not disappear and takes on characteristics of a standard local car. No payout is given, and you lose all keys and access to the stolen vehicle. Only constant is that it was the Mustang GT, and it was on a trailer at some point. It has functioned properly with the same variables on separate missions. 

Also potential to move vehicle missions to function outside of cooldown similar to drug sales, as last I knew they were tied directly to cooldown. This would allow these to still be accessible when enough officers are online, while cooldown can hinder that for unrelated reasons and it is not a violent crime, unlike the robberies it is currently tied to.

**Comment by YeetMeAway** [comment]
Also potentially change the amount of people who can do it. As of now it seems that there is only one mission per shop per night. bumping it up to 2 or 3 people at each location being able to start a job may help with more people gaining interest in it. So far its basically a sprint to start the job first and after that its just a waiting game for the next night.

**Comment by FertileSphere** [comment]
gotta agree with all stated here.
I know I'll be doing some more today with a crew, will try and replicate conditions to make mission glitch out and not complete, so that we have more substantial evidence on how we are breaking them.

**Comment by fkk-cz** [comment]
> Only constant is that it was the Mustang GT, and it was on a trailer at some point.

Highly doubt it's vehicle specific. Also attached to a **trailer**? How is that even possible?

> Once it is properly placed and kicks you from the vehicle, the vehicle does not disappear and takes on characteristics of a standard local car.

This seems like some issue with the payout in the server script. Should be easily fixable.

> Also potential to move vehicle missions to function outside of cooldown similar to drug sales, as last I knew they were tied directly to cooldown.

It's ..already that way? Auto theft missions are not affected by normal (timer) cooldown. Only a global cooldown issued by staff members can block these missions from starting.

> Also potentially change the amount of people who can do it. As of now it seems that there is only one mission per shop per night. bumping it up to 2 or 3 people at each location being able to start a job may help with more people gaining interest in it. So far its basically a sprint to start the job first and after that its just a waiting game for the next night.

I don't want people grinding these missions like drugs. New and different missions will be added in the near future, once a bunch of other tasks and features are completed first.

**Comment by QuintenM911** [comment]
I was just attempting a vehicle theft and found out the 1999 Honda civic after the theft doesn't give you the next prompt after you are told to keep a low profile and wait 
![image](https://user-images.githubusercontent.com/90533639/158913597-84ca0901-3adf-487f-8e3b-86f8d67f293c.png)
and to cancel the mission I had to destroy the vehicle to fail
![image](https://user-images.githubusercontent.com/90533639/158913672-c6a8e1a3-3eb2-48a4-aa87-cac7d54bc273.png)

**Comment by FertileSphere** [comment]
Conducted some more in city testing today, I have some thoughts;
- Missions don't always pop up at ANY pay'n'spray/benny's
  We had two ENTIRE night cycles that didnt give us any missions, even with "camping" the locations with a team, yet when we started, 2/3 team members got a mission on their first try.
  - Money and how its calculated
    I personally had 2 missions that were both the Volvo XC90 SUV, that paid way different. I got them both from mirror park, yet one was an airport drop and the other a power station drop. My airport got 3K dirty yet my power (which was 2 miles further away) got 2700 dirty. very weird dispersion in results. talking to others, this seems the case with their missions aswell.
 - "grinding"
   Yeah, I know, the unholy word. But seriously, if we cut the payments to under 1500 per car, wouldnt that still only give us time for 2/3 missions a night with an organised crew? I don't see how we couldn't adjust the missions to make it less of a "printer" activity.

**Comment by LethalTrade** [comment]
I have noticed 2 bugs since doing the auto theft missions. The first one is just like one stated above ill get to the point where it says keep a low profile and wait for the handler but never gets past this point and the other is ill be taking the car to the drop-off point and when I park the car over the circle nothing happens. it doesn't kick me out and I get no money and even if I park it and get out I get no money and I can just get right back in and keep driving the car.

**Comment by QuintenM911** [comment]
adding another thing to the auto mission list of problems if you go to the sell point but the vehicle doesn't sell. It locks you out of using repair kits for your vehicles saying you are still on an active mission 
![image](https://user-images.githubusercontent.com/90533639/160470510-ee0cea51-5b06-478b-a768-661dcdea6840.png)

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/8771827fb60520994ce4e7723c442a9de2a6fe5d.
