### ISSUE TITLE
Boat Anchor malfunciton!

### ISSUE THREAD

**Issue by Reefeid** [fkk-cz/noire-public#685]
Hello , 

Every time I anchor my boat and hop off the boat starts sinking . 
Also , I cannot drive or release the anchor . 

I have to go back to insurance to get back my boat . can you please look into this .

**Comment by Mynameisnotlenny** [comment]
Which boat is it, I haven’t personally had any issues anchoring my boat yet.

**Comment by Reefeid** [comment]
its the Squalo ( MSRP $125K) - yeah I had 2 assists earlier today to help me while I was stuck mid-sea fishing XD

**Comment by fkk-cz** [comment]
Any _specific_ steps to reproduce this?

I spawned in the `squalo` and did not experience this issue.
