### ISSUE TITLE
Jerry Cans Not Working

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire-public#687]
Can't refuel my car thats in my garage for 3 days straight now. Put it into the garage at 20 something fuel, pull it out and its got 5. Trying to refill with a jerry can shows "Not enough cash" instead of refuel. 
![Screenshot_29](https://user-images.githubusercontent.com/86823385/159618342-8203d177-f19a-4cf2-886b-4c3aa843a161.png)

**Comment by No-Yes1** [comment]
Get in your vehicle, wait a few seconds, get back out and then it should work

**Comment by fkk-cz** [comment]
Refueling requires a player to be the net owner of the vehicle. Ideally refueling should work without getting in/out of the vehicle, but state awareness policy prevents the non-owner from modifying entity state. This probably isn't worth circumventing either.
