### ISSUE TITLE
Gas stations not allowing import of fuel

### ISSUE THREAD

**Issue by zoiczombie** [fkk-cz/noire-public#690]
Gas stations are allowing us to do gas runs but not registering the runs as complete. Currently, we've run into this issue with 148 and 3025.

**Comment by TheBottomFragger** [comment]
Same problem with 3025, 385 and 120

**Comment by QuintenM911** [comment]
Having the same problem at 230 as well

**Comment by LactatingWalrus** [comment]
Same issue with 375.

**Comment by TheBottomFragger** [comment]
Pretty sure there’s already a fix for this which will take effect after server restart today ☺️

**Comment by No-Yes1** [comment]
Guessing this has been fixed after reset, if someone can confirm?
