### ISSUE TITLE
Vanity Plate Issue. 

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire-public#693]
I have some mixed answers on this but after doing some research I have discovered many players having issues with vanity plates. They aren't working at the DMV. No cars appear when you go to set vanity plate. Wondering if this could be looked into. Is there a new method that hasn't been fully explained or is it now broken.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/e1bc01bd78eedf576a48aa72382c043b7d6ba551.

Was related to the new garage changes.
