### ISSUE TITLE
connection failed error

### ISSUE THREAD

**Issue by fdamusic** [fkk-cz/noire-public#695]
![Screenshot 2022-03-28 115859](https://user-images.githubusercontent.com/67622279/160449632-207f463a-9c20-4db5-9bbf-5d99a14d7ade.png)
hello i keep getting this error, i tried to restart, i eveen waited a day. i can connect to all other fivem servers, except this one.....

**Comment by fkk-cz** [comment]
Did you finish setting up your steam community profile?

**Comment by fdamusic** [comment]
nope,i did now, and  that fixed it, thank you so much! :)
