### ISSUE TITLE
The Galaxy Nightclub Stereo System

### ISSUE THREAD

**Issue by jeanndabeann** [fkk-cz/noire-public#696]
The Galaxy Nightclub stereo thingy doesn't work, you cant actually get to the stereo there is an invisible barrier blocking you from reaching it

**Comment by jeanndabeann** [comment]
https://medal.tv/games/gta-v/clips/fVqV1dAN1UaoP/d1337dDLKL7w?invite=cr-MSxLT2UsMjYzMzA4MzYs

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire/commit/42ff82c9d628bca8ecbaa9fc10e85734678ab618.

Need to fix the collision on that booth as well.
