### ISSUE TITLE
Car duplication

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#703]
Currently if you recover your personal vehicle at insurance if it hasn’t disappeared then it duplicates the vehicle with the same license plate. Was able to duplicate 3 vehicles in a row and assume it could be unlimited 
![image](https://user-images.githubusercontent.com/100061006/161179458-d5e24752-161b-48f6-8261-114670608c2b.jpg)

**Comment by fkk-cz** [comment]
Thanks for pointing that out, was a typo on my part.

Should probably move all vehicle creation (excl. trailers? add-on trailers seem to work) server-side and make the insurance functions server only.

Fixed in https://github.com/fkk-cz/noire/commit/26c268357adfb5796f432a712d665b80db4a830e.
