### ISSUE TITLE
Trailers

### ISSUE THREAD

**Issue by NikeXpert** [fkk-cz/noire-public#706]
Gooseneck is tethering behind by Two Feet the truck pulling it or it's beside the truck as you drive down the road, and sometimes it's disappears or doesn't show up for others.

**Comment by fkk-cz** [comment]
Someone else raised this issue, does this occur _every_ time you attach the trailer? Where are you spawning the trailer (personal vs. public garage)?

Are you detaching the trailer every time you exit the vehicle?
