### ISSUE TITLE
Vanity plates 

### ISSUE THREAD

**Issue by IsaacGucci** [fkk-cz/noire-public#707]
Not all of my cars appear when you go to set vanity plate this was happening to more then just me is there a specific garage we need to put cars into a change the vanity plates or ?

**Comment by fkk-cz** [comment]
This was fixed in https://github.com/fkk-cz/noire/commit/428a0162aa02cb71370247be9f9e7ba1b7aa4657 - after today's normal scheduled restart.

You should be able to change vanity plates on all vehicles that are not out, regardless of the garage.
