### ISSUE TITLE
Cops Locking The Hospital

### ISSUE THREAD

**Issue by zurged** [fkk-cz/noire-public#715]
Cops locking the hospital is not really realistic, people in irl are hurt or dying and they dont lock the hospital that will cost there lives, cops need to stop locking them people are on like low heartbeat or dead if EMS is not on and someone carrys them and they tell them to go to another hospital,i think that cops should put them in hand cuffs it not like they can run

**Comment by ahollis3** [comment]
yu so god damn right its not like real life if they are stopping u - they can put them into cuffs then take them into custody

**Comment by johnvito760** [comment]
Well you should know Zona was added for the civs while the cops use pillbox for suspect situations so you should use Zona more than pillbox

**Comment by fkk-cz** [comment]
> Cops locking the hospital is not really realistic, people in irl are hurt or dying and they dont lock the hospital that will cost there lives

It's also unrealistic to have civilians walking around hospitals open carrying fully automatic weapons. Also your point of no locks is actually not accurate - modern hospitals have a lot of security and keycard controlled access with magnetic door locks.

What is the _real_ issue here? AMR/Cops forgetting to unlock the doors and people getting stuck?
