### ISSUE TITLE
Car won't start; essentially bricked.

### ISSUE THREAD

**Issue by cljames45** [fkk-cz/noire-public#716]
As I'm pulling up to my house, my vehicle dies after smoking and as it's dead, it stops perfectly in my driveway enough for me to put it in my garage, which I do and head inside. I leave, pull my car out, and it will not start. It looks to be in perfect condition but does nothing, regardless of using the /enginestartstop command, repairing it, and locking it and unlocking. It also says this on the outside: anyone got any tips? 
![image](https://user-images.githubusercontent.com/103002947/161639034-fd01f0d8-5a91-445c-b40f-27c235b6bf8f.png)

**Comment by fkk-cz** [comment]
Looks like a netID mixup which falsely led your client into thinking your vehicle was the armored truck. Added a model check to fix this.
