### ISSUE TITLE
Car missing

### ISSUE THREAD

**Issue by RandomSquirrels** [fkk-cz/noire-public#721]
I recently heard about the change of not being able to take cars out of all garages and only being able to take cars out of the garages that you last stored the car in. I have a Focus that I didn't know where I stored it so i spent a bit of time going to all the garages and looking for it. Come to find out, it is not available in any of the public garages and it has not been impounded and is also not recoverable so i'm not sure what I need to do to get my car back.

**Comment by fkk-cz** [comment]
Plate of the vehicle?

**Comment by RandomSquirrels** [comment]
> 

I dont know the plate. I never put a custom one on it or anything. Just used whatever the game gave me when i got it

**Comment by fkk-cz** [comment]
What's your steam ID?

**Comment by RandomSquirrels** [comment]
76561198986961169

**Comment by fkk-cz** [comment]
Here are the vehicles owned by that steam ID. Looks like your Focus is in Sandy.

```
"RJP472"	"SandyShores"	"Ford Focus RS"
"SLOWZ34"	"Paleto"	""
"VXT342"	"Paleto"	"Toyota FJ40"
```

**Comment by RandomSquirrels** [comment]
thank you
