### ISSUE TITLE
Interiors

### ISSUE THREAD

**Issue by B-Cobra** [fkk-cz/noire-public#723]
When i enter by house theres nothing, no walls, no floor just straight void

**Comment by fkk-cz** [comment]
Can you provide a screenshot of what that looks like?

**Comment by B-Cobra** [comment]
![House](https://user-images.githubusercontent.com/103154059/162100991-2919f9eb-2945-499c-acee-a2e1afcf9156.PNG)

**Comment by fkk-cz** [comment]
You might need the location moved.

Open a ticket in Discord.

**Comment by B-Cobra** [comment]
the only tickets they have are for Request clothing, request vehicle, ban appeal, report a player, and report a cop

**Comment by fkk-cz** [comment]
Just open a report a player I'll convert the ticket to the correct category.
