### ISSUE TITLE
Car not appearing in garage

### ISSUE THREAD

**Issue by mynameissailboat** [fkk-cz/noire-public#727]
I frequently use different garages in the city and I often can't access all of my cars in the garages. I often can only take out 1 or 2 cars when I own 5. I then have to go to a separate garage and often the car isn't in that garage either. I've gone to insurance numerous times to try and recover the vehicle but this doesn't make the car seen on the menu in the garage. I would appreciate any help in fixing this.

**Comment by Daniel9935** [comment]
This happened with an Audi R6 i brought from UCL the day before the garage changes. i still haven't found the car after a while of asking i just forgot about it

**Comment by fkk-cz** [comment]
Steam ID?

**Comment by mynameissailboat** [comment]
I remembered that I need to get the car from the garage that I stored it in. This was my problem all along. Thanks again

**Comment by Daniel9935** [comment]
76561199212410461
