### ISSUE TITLE
Fishing 

### ISSUE THREAD

**Issue by Proudcat1** [fkk-cz/noire-public#732]
Fishing is my favorite legal to do I'm not asking for a huge buff but I did a test today on the ratio for the random shit to actual fish and it is horrible. I bought and used 123 bait and got a return of only 26 fish I know that could be the lowest and it could be higher on another run that's how rng works. But that is a really low number for something that sells for not much 9 fish sells for 3k something so in total, I made like 8k for all of that time and money invested into bait in equipment. If I subtract the money invested into the equipment I would have only made close to 5-6k for all that time to get the stuff and sit out there and use all the bait I'm just wondering if one of the 2 can be buffed either the odds of getting a fish or the price they sell for thanks for your time.

**Comment by fkk-cz** [comment]
Fishing needs a rework to make it more of a viable job. A couple ideas to make the activity more interesting:
- Allowing players to fish off a boat instead of standing on land
- Ability to catch crustaceans (fish, lobster, etc.) which can then be sold to some type of fine dining restaurant
- Being able to eat what you catch, provided the appropriate steps are taken

**Comment by Reefeid** [comment]
You can fish off boat- tested :) although when you catch the fish it drowns quickly. So you have to jump off boat and try to get it . You’ll be lucky if you catch one and at times you might drown urself trying XD

**Comment by herkkkk** [comment]
Another feature that could be added with a fishing rework is illegal fish. Such as sharks, stingrays, ells, etc; they could sell for more money but it also adds risk to fishing like the other legal jobs in the city. This could also add more RP to the fishing job as LSPD and Highway would have to check what people are fishing up. I think it would overall be a good change and could add another layer of RP.

**Comment by fkk-cz** [comment]
Not sure about illegal fishing - it's supposed to be a legal job paying clean cash.

**Comment by gxdsent** [comment]
> Fishing needs a rework to make it more of a viable job. A couple ideas to make the activity more interesting:
> 
> * Allowing players to fish off a boat instead of standing on land
> * Ability to catch crustaceans (fish, lobster, etc.) which can then be sold to some type of fine dining restaurant
> * Being able to eat what you catch, provided the appropriate steps are taken

Also, I'm fishing right now and maybe change the fishing mechanics to the contextual menu? Third eye fishing could be much more efficient than using the menu and sometimes it bugging out and not casting

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/1111#issuecomment-1221612781
