### ISSUE TITLE
inventory not working - 

### ISSUE THREAD

**Issue by ahollis3** [fkk-cz/noire-public#738]
![INVENTORY](https://user-images.githubusercontent.com/102285389/163423732-1d56d74e-e4b1-4cc6-8bab-9bbe88fff1b6.PNG)
when i press f2 it says that and i have deleted fivem and downloaded it back and deleted citizen- if anyone knows how to fix please help me

**Comment by No-Yes1** [comment]
Merging into an existing issue #697
