### ISSUE TITLE
1030 tsunami

### ISSUE THREAD

**Issue by glefave0209** [fkk-cz/noire-public#739]
We're getting a second tsunami at 1030 everyday. Should this be happening?

**Comment by TheBottomFragger** [comment]
No, not supposed to happen. I was hoping this was already getting worked on tbh

**Comment by fkk-cz** [comment]
No, logs don't show any restart at 10:30 AM EDT. The only scheduled restart _should_ be at 10:00 AM.

**Comment by TheBottomFragger** [comment]
For the last weeks or so, everyone crashes exactly 30 minutes after restart

**Comment by fkk-cz** [comment]
Turns out this was caused by inconsistent restart schedules - one on the main server and the one of the proxies. Moved the restart back to 10:30 AM EDT, thanks for pointing this out.
