### ISSUE TITLE
gooseneck trailer not lowering ramp and cant store

### ISSUE THREAD

**Issue by diablo1320** [fkk-cz/noire-public#740]
i cant lower the trailer ramp but everyone else can. seems like its just an issue on me end. once pulled out i cant store it any more.

https://user-images.githubusercontent.com/103771688/163601956-849130bb-c318-4b48-8750-4226e4d2a9c7.mp4

https://user-images.githubusercontent.com/103771688/163602068-f2cb389f-746f-4653-ae6e-9b79c8ff6d94.mp4

**Comment by fkk-cz** [comment]
Looks like an isolated incident - did you try storing and pulling the vehicle back out?

**Comment by diablo1320** [comment]
I cant store it only way i make it disappear is storing the ram 3500 while
attached to trailer second clip shows i get no option to store it.

**Comment by fkk-cz** [comment]
Storing a trailer requires you to line up the trailer so the driver's seat is in the red circle. From there, enter the seat and store it like any other vehicle.

**Comment by diablo1320** [comment]
Leaving the city and coming back seems to fix the issue thanks !
