### ISSUE TITLE
Hard Racism During Trucking

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire-public#744]
Hey Bobby, I've been hearing a LOT of racism on trucking radio's in the early morning from tsunami to around 11-12PM CST. So What I was wondering is, could you maybe revert just the trucking radio's back to show people's names on the side of your screen so we can report all these racists and homophobes. That's all I'm hearing for hours on end. Today some guy kept calling a buddy of mine the N word and making stereotypes that he wants to eat fried chicken and watermelon, whilst just repetitively calling him the N-Word with the hard R.

**Comment by No-Yes1** [comment]
Trucking radio never showed player names to my knowledge, I agree that there is a _lot_ of randoms just going on the trucker radio, and saying random shit, either blasting music/being homophobic etc etc.

**Comment by WaywardCanuck** [comment]
> Trucking radio never showed player names to my knowledge, I agree that there is a _lot_ of randoms just going on the trucker radio, and saying random shit, either blasting music/being homophobic etc etc.

You're correct, they never showed player names but the logs will show who was using what name on radio.

**Comment by PreacherDeimos** [comment]
I just would like to see player names, even if it's the starter trucking names like Delta12345 we'd still be able to see when someone clipped it, and logs will show their SteamID and then the issue can be resolved from there, because it's getting quite bad on the trucking radio.

**Comment by Stagonium** [comment]
> Trucking radio never showed player names to my knowledge,

It did used to when the radio showed the list of connected members. That was how LSPD Detectives solved a big case a while back. 

Maybe for trucker radio if it just had their player ID visible on the side that could be a solution.

**Comment by No-Yes1** [comment]
oh yeah, you right, thought it was mentioning marker blips on the map

**Comment by fkk-cz** [comment]
How would having player IDs/names _fix_ this issue? This is a people problem. If players are doing this use `/assist` and someone can switch into the radio to handle it.

One solution could be to restrict new players from using the radio, or giving an easy way to mute/unmute.
