### ISSUE TITLE
Removing vehicle generator at 937 gas station

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#745]
Currently there is a PED vehicle that blocks the spawn point for gas runs majority of the time and only way to do gas run is to ram the car out of the way or to have it cardeld, would be nice if the vehicle generator for the parking spaces beside the spawn point could be turned off or disabled so that gas runs could be done without issue.

**Comment by No-Yes1** [comment]
This is a case at most gas stations, I know 148 has the same issue
