### ISSUE TITLE
Spawning gas station vehicles will not warp ped into driver seat

### ISSUE THREAD

**Issue by kelliott33** [fkk-cz/noire-public#746]
Not sure if it is all gas stations but 402 when i start a gas run it makes me hotwire the truck and it doesnt give me a route afterwards

**Comment by No-Yes1** [comment]
Can you provide a clip?

**Comment by kelliott33** [comment]
don't have a clip but i flew out and back in later on and it let me do a gas run so not sure what might have caused it

**Comment by kelliott33** [comment]
it is supposed to spawn you inside the truck after you start a run but for whatever reason it doesn't. then it makes me hotwire the truck just for it to not give me a route 
https://user-images.githubusercontent.com/86857219/163795796-082d1d37-0e3d-4f84-856e-bcd38f7ed851.mp4

**Comment by YeetMeAway** [comment]
Happening with certain members of 596 gas as well. Truck spawns, gives no prompt to player and truck is spawned in with local plate instead of gas station plate. When you enter, you have to hotwire but have no destination to travel to for the gas, so the truck and trailer are useless with zero gain and losing money

**Comment by kelliott33** [comment]
the issue hasn't happened to me the last couple days, i think it bugs out when you hit cashier first then go to refuel to do a run. when i open up the menu and go straight to refuel i have no problems

**Comment by Mynameisnotlenny** [comment]
Also currently seems to be an issue with exporting too, gives location but no vehicle spawns

**Comment by fkk-cz** [comment]
You shouldn't have to enter the vehicle, it should automatically warp you into the driver's seat. Weird how this is working for _some_ people but not others, probably an unintended side effect of RPC vehicle creation.

**Comment by fkk-cz** [comment]
Apparently `CreateVehicle` was being called on the server with the vehicle _name_ as the first argument. This is a pretty obvious oversight, ouch. Fixed in https://github.com/fkk-cz/noire/commit/d70bced8a34c378fafc2ab0332c38541c5f3d607.

**Comment by Mynameisnotlenny** [comment]
Hey, just tried exporting gas again and still running into the same issue, gives a location on the gps however no vehicle spawns to do the run so it ends up taking the fuel from the station and you receive nothing in return

**Comment by fkk-cz** [comment]
What about _importing_ (regular) gas runs?

**Comment by Mynameisnotlenny** [comment]
Haven’t tried importing for regular runs today but never personally had an issue with that, still as of today still currently having an issue with exporting though. Have given Mr. Amiri keys to 937 if you’d like to try recreate it, I’ve also heard from other owners that they aren’t able to export either.

**Comment by YeetMeAway** [comment]
Import runs are working intermittently. i did 3 runs fine, 1 where the truck spawned but with a ped plate without me in it. The final attempt the station refused to even spawn the truck. When the truck spawns with a ped plate without you in it there is no mission, but it still charges the station for the run that never was able to occur as it miscommunicates somewhere server side in the generation of the route/job

**Comment by Mynameisnotlenny** [comment]
Tried exporting again today and still having issues, here is also a clip of what happens when trying to export https://medal.tv/games/gta-v/clips/j6VOppmAgsyrj

**Comment by hmu4green** [comment]
Can confirm I’m having the same problems as Lenny when it comes to exporting gas. Click export and nothing happens, only a waypoint to the destination. Once you get to the destination nothing happens, no vehicle for you to get in just nothing. It should also be mentioned it in fact takes your gas when you do this and you get nothing in return besides lost profits. Wasted several litres of gas and money trying to solve this on my own and nothing seems to work. A fix would be greatly appreciated
