### ISSUE TITLE
Allow refueling when not netowner of vehicle

### ISSUE THREAD

**Issue by glefave0209** [fkk-cz/noire-public#753]
A few of us ran into issues last night with the Ram 3500 not accepting Jerry Cans.  All my other vehicles worked fine but for some reason the 3500 wouldn't allow a fill with it.  Not sure if it was a Ram specific problem or just all HD's, but the 3 issues were all with Rams

Filling up at a regular station worked fine.

**Comment by hmu4green** [comment]
I fill up my 3500 with a jerrycan no problem

**Comment by PreacherDeimos** [comment]
Have you tried getting into your vehicle and getting out, then trying to fill up? Or going into first person, then trying to fill up? Maybe try these things.

**Comment by glefave0209** [comment]
This can be closed. Seems like a one day issue that self corrected

**Comment by fkk-cz** [comment]
Refueling the vehicle requires the player to be the network owner of the vehicle. This inconvenience should probably be fixed, or at the very least, a help message should appear to notify the player what to do.

**Comment by fkk-cz** [comment]
Additionally, another bug has been identified and fixed - one where players with a gas can cannot refuel their vehicle under these irrelevant conditions:
- Not having enough cash
- Gas station nearby not having enough stock

No idea why these requirements existed for gas can refueling.
