### ISSUE TITLE
ATMS on the wall not working

### ISSUE THREAD

**Issue by jeanndabeann** [fkk-cz/noire-public#756]
Love the third eye with ATM's update but me and a few people have noticed that the ones on the walls dont always work. This is a struggle for the gas stations that have only ATMS on the wall.
For example, yesterday i was able to use the ones outside of the bank but Sunny wasnt. When you third eye it just doesnt give any prompts at all
![image](https://user-images.githubusercontent.com/92621139/164546003-269db64e-82a6-4e36-8a5d-fcb00bf464f7.png)

**Comment by ItsGabble** [comment]
^^ Yesterday I could use the one on the wall at 596 but not TKG gas. Made Colt try and he had the same issue at other locations. So far I have only been able to use the bank ATM by the courthouse, but the one in Legion is inoperable for me. They seem to work sporadically right now.

**Comment by somedudenamedrush** [comment]
if u have the NVE installed remove the atm animation mod from the folder you can use all ATMS after that

**Comment by Mynameisnotlenny** [comment]
New atm system is cool, wanted to also add that the atms inside the banks no longer work which is unfortunate.

**Comment by PreacherDeimos** [comment]
Isa was having the same problem, hopefully you got it fixed.

**Comment by fkk-cz** [comment]
> if u have the NVE installed remove the atm animation mod from the folder you can use all ATMS after that

What ATM animation are you referring to?

**Comment by fkk-cz** [comment]
Is there a white outline around the wall ATM when you attempt to interact with it? @jeanndabeann @ItsGabble

**Comment by ItsGabble** [comment]
@fkk-cz negative. I tried removing the NVE atm animation and it didn’t fix it either. I can only use the standalone machines inside stores and none of the wall ones.

**Comment by jeanndabeann** [comment]
same here with what happened with cortez, once i removed the NVE thing i was able to use the wall atms again and the white border would show up again. Before that they werent showing up

**Comment by lIALEKS** [comment]
![Capture d'écran 2024-11-08 174350](https://github.com/user-attachments/assets/0db78ce2-a677-4c7f-aad6-5b445328e4fd)
Delete this mod ! It work for me now
