### ISSUE TITLE
Cant Start Gas Runs! 

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#760]
So today doing gas runs it keeps glitching out not putting us into the tesla truck and when we climb in, its asking us to hotwire the truck and not giving us the location where we need to go! It happened at 385 and 120 gas stations

**Comment by cxerq** [comment]
Found somewhat of a fix and thats Relogging! Its a GUI lag issue!

**Comment by fkk-cz** [comment]
What? How does 'GUI lag' cause the vehicle to spawn without the keys? Can you provide more information or the steps to recreate this?

**Comment by cxerq** [comment]
> What? How does 'GUI lag' cause the vehicle to spawn without the keys? Can you provide more information or the steps to recreate this?

So to recreate it, I don't know if you can, But whenever We clicked to do a gas run it wouldn't work aka like it was lagging, So after we clicked it a few times of it not working it then spawned in the truck but didn't give us keys, Relogging fixed it, and if I'm not mistaken I believe some others has a similar issue. (This is from another gas station https://user-images.githubusercontent.com/86857219/163795796-082d1d37-0e3d-4f84-856e-bcd38f7ed851.mp4 )

**Comment by fkk-cz** [comment]
Merging this with https://github.com/fkk-cz/noire-public/issues/746.
