### ISSUE TITLE
Vstancer Addon

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire-public#761]
I don't know if this has been mentioned before but is there any way to add this feature. I think it would be nice so fitment with widebody kits for certain vehicles can be adjusted. https://github.com/carmineos/fivem-vstancer

**Comment by PreacherDeimos** [comment]
I actually mentioned this in the Discord yesterday, a lot of cars have widebody kits or they're just JDM/Stancer cars and I'd love to see the addition of the VStancer script in this server.

**Comment by fkk-cz** [comment]
This resource uses decorators to sync vehicle modifications between players. Decorators might as well be considered deprecated at this point as there are better options such as statebag synchronization. As a result, this cannot be used as a plug & play resource, nor should it be introduced as it will only have to be replaced further down the road.

**Comment by PreacherDeimos** [comment]
Understandable, okay thanks anyways Bobby. You can close this bossman.
