### ISSUE TITLE
Car wash removed at 941 gas station

### ISSUE THREAD

**Issue by iGotDank** [fkk-cz/noire-public#764]
I recently purchased the gas station at 941, prior to me purchasing it I noticed a car wash was added at the location which in all honesty was a big motivator in me buying the gas station. It has come to my attention that it has been removed. I think this isn’t a good call simply because there are no existing car washes in sandy shores, only in the city and paleto bay. It’s also annoying that it was implemented after the gas station went up for sale almost to entice someone into buying it, which stated above was a motivator for my purchase. This could be a simple glitch possibly but if it was removed I would kindly ask for it to be re-instated or I would like some sort of partial reimbursement from my purchase of the station.

**Comment by robbieshoff** [comment]
i am pissed they took it out that was the best gas station in sandy because of the car wash all this is causing is for him to lose buisness because people wanted to clean their cars when they got gas
