### ISSUE TITLE
Trucking Issues

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#767]
I don't know what exactly caused this, but for the past 4 days trucking has had a few bugs. Here's a list of what i've noticed:
     -The gas in the trucks is no longer at 100 percent like it was before. I know someone who did a log run and the truck started at 20 fuel. 
     -Not always, but the truck sometimes won't despawn after you return it, causing a whole mess.

These are the only ones I've noticed. Of course, if anyone else has noticed anything, they can add it in the comments

**Comment by Ell34** [comment]
Noticed another bug today doing the oil run, the trailer detached and teleported somewhere in the city. drove to the location and it wasn't there.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/ea96fc52fb2fc73a65a7c862ca83d5e407b50a5a.
