### ISSUE TITLE
Voice Chat problems after attending Comedy Club

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire-public#769]
Unsure if this is an isolated incident or related but last night after attending the Comedy Club for an event, myself Preacher and Isa starting having issues where we couldn't hear one of the others voices but their mouth was moving requiring us to turn the voice chat off and back on in our settings. This happened multiple times in the hour or so I flew out last night. I have never had an issue like this before happen as much as it did last night

**Comment by fkk-cz** [comment]
This is not caused or related to a specific interior/MLO. No idea what's been causing this, other people have reported this issue for months.
