### ISSUE TITLE
Dragging weapon causes trunk to glitch out

### ISSUE THREAD

**Issue by glefave0209** [fkk-cz/noire-public#770]
Not sure if this has been raised before, but if a user accidentally tries to grab their weapon and drag to the trunk of their car, the trunk glitches out and they are no longer able to move inventory to the trunk and the only solution is to take a nap

The obvious solution is to pay closer attention when dragging inventory across, but I'm wondering if this also can be patched?

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/bc3d2f90365758f7c091416c66734432e9b21ec1. Thanks for pointing this out.
