### ISSUE TITLE
New advancement towards weapon technology and potential glove box. 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#772]
Making a suggestion on the RP improvements to the city that discusses the development of the crime and court system at the same time.

Below is a script that includes a serial system for firearms for better locating owners of purchased weaponry and glove box space to make it fair on the criminal side, so it’s not just giving something to the LEO side.

With the potential addition of serial number system to firearms, that would definitely make the RP experience a bit more interesting and exciting. 

Also, potentially weapon accessories and The same inventory we currently have with the same look.

https://esx-scripts.com/shop/premium-inventory-with-ammo-weapons-durability/

**Comment by PreacherDeimos** [comment]
I would also like to add this script is currently %70 off until Monday.

![image](https://user-images.githubusercontent.com/103844484/168403828-2338546a-7b29-4eb1-8148-505611f616ad.png)

**Comment by tythetanman** [comment]
I'm wondering the chances of a glovebox to the city. 

Yes anyone could hide anything in it and restrict the: FAL,SMG,AK and double barrel in it. Maybe also packaged weed. 

But everything else would be great to have to go in there and then officers would have another area. They would have to check when and if they search the vehicle.
