### ISSUE TITLE
Incorrect speed limit signs

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#791]

**Comment by cxerq** [comment]
If you drive under an underpass it changes the limit sign to the highway above speeds

**Comment by fkk-cz** [comment]
> If you drive under an underpass it changes the limit sign to the highway above speeds
> 
> 

This cannot be fixed as street names are based on coords, not roads.

**Comment by Chunky30** [comment]
Senora Road, Speed signs allong the street both North Bound & South Bound posted at 60mph, according to the GPS it is 45mph

![image](https://user-images.githubusercontent.com/96521927/169738062-1525f540-7a62-4249-8176-f1b46052c71b.png)

Issue persist through Joshua road North Bound, Speed sings along the road at 60mph, according to GPS posted at 50mph

![image](https://user-images.githubusercontent.com/96521927/169738248-99c0a7d2-7acb-42a6-a9ea-6e786a5cf057.png)

**Comment by fkk-cz** [comment]
Fixed both of these. https://github.com/fkk-cz/noire/commit/428637f6e416744f6f53fe88931b29fdad4ad6a9
