### ISSUE TITLE
New Trucking Jobs

### ISSUE THREAD

**Issue by AngelofDeathGaming** [fkk-cz/noire-public#795]
THE NEW TRUCKING- The good, the bad, and my opinion.
As we know there has been an update on the trucking jobs. We have had many bugs in the past and this update is supposed to fix that. It not only made changes to the starting fuel, but there are many other changes that you would like to know about. Quite honestly, its more bad than good. Here's why. Starting fuel seems to be fixed. The lowest i started with is 51%. Yeah its not 100% but last week we had problems with fuel starting out at 30%. Yes its more, but not much more. Especially if you have long trips like Paleto bay. Every single trucking job i took, i ended up having to refuel once. Sometimes it was after you drop off a load, but sometimes you werent so lucky and you have to pull into a gas station with a full trailer. sucks monkey balls still doing that. Next lets talk safety. There is no longer a seatbelt function. So if you hit something, good luck! I didnt test this out, but i assume since you cant physically put on a belt anymore, youre going through that front windshield if you hit something hard enough. Speaking of which, they took away our color coding of damage. There is no longer white, orange, or red colors to indicate how damaged your truck is. You cant tell if youre low on fluids or oil and whatnot anymore. TRUCKING JOBS are now paying less. Ive tested this with multiple jobs such as gainseed, logs, heavy equip, ect. Higher paying trips youre earning about $2k less per trip. If you did logs, youll remember the $7.2k average payout. Now thats a thing of the past. Expect an average of $5.8k. Gainseed paid me a whopping $4.2k. So as you can see, all job payouts have been nerfed. I do like the new speed limit that they give you so that you know the speed limit of that road you are currently on. Fuel consumption seems to have improved only when you dont have a load. Ive noticed less fuel being used when you dont have a trailer connected. There is a lot of good and bad but im thinking more bad than good. Im thinking that with this update, people will flood landscaping and sanitation. If those get too full, we might lose some people to other servers. I hope not but thats just my opinion. Thanks for taking the time to read all of this!

**Comment by fkk-cz** [comment]
> Yes its more, but not much more. Especially if you have long trips like Paleto bay. Every single trucking job i took, i ended up having to refuel once. Sometimes it was after you drop off a load, but sometimes you werent so lucky and you have to pull into a gas station with a full trailer. sucks monkey balls still doing that.

That's the same with every other non-whitelisted job? Sanitation, landscaping, and mining workers are all required to purchase fuel for their vehicle.

> There is no longer a seatbelt function. So if you hit something, good luck! I didnt test this out, but i **assume** since you cant physically put on a belt anymore, youre going through that front windshield if you hit something hard enough.

That's a false assumption, ejecting out of windshields hasn't been in for a long time. In other words, the seatbelt function was completely useless and served no purpose other than confuse new players who would then proceed to place assists wondering why they couldn't exit their vehicle.

> TRUCKING JOBS are now paying less.
Job payout was adjusted to prevent people from 'camping' certain jobs - we've been seeing issues recently with people fighting over jobs and killing each other at the job site. Other factors to consider:
- Driving is a lot easier now. Cruise control now holds your speed and eliminates having to control the throttle.
- Players are automatically warped into the truck. This saves time and reduces the risk of getting killed or your job stolen.
- The shorter routes received a pay increase to help balance out the jobs.

In total, trucking has actually become _easier_ -- the only issue I see is the low fuel for the longer runs, this can be solved by making the starting fuel proportional to the route distance.

**Comment by AngelofDeathGaming** [comment]
Yes the seat belt helps a lot! I've accidently hit my G muscle while driving my truck and have fallen out and died. It is still necessary to have in my opinion. Also, I've tried shorter route jobs. You get paid $700 less with those instead of $1k-$2k less.

**Comment by fkk-cz** [comment]
> I've accidently hit my F muscle while driving my truck and have fallen out and died. It is still necessary to have in my opinion.

What you're describing is user error. Why should a seatbelt mechanic exist solely to prevent people from accidentally exiting their vehicle? The obvious solution is to be more careful and have better control over your character when playing.

**Comment by AngelofDeathGaming** [comment]
You haven't gotten anxious and accidently hit the wrong button? I mean irl
in some driving situations you'd get anxious and accidently slam on the
brakes or gas but not accidently open the door and roll out of it. What
your describing is being a smartass. It's not user error to get anxious at
times. It happens irl.

**Comment by fkk-cz** [comment]
> You haven't gotten anxious and accidently hit the wrong button?

Not that I can recall, at least not due to anxiety. Seems like a _you_ problem.

Closing this as it's just turned into you arguing for changes to protect players from user error (i.e. fat fingering) and making false assumptions such as ejecting out of windshields -- something that has been removed for over a year now.

**Comment by AngelofDeathGaming** [comment]
As a disabled veteran, yes I do get anxious. I'm medicated for it. Yes shit like that happens irl and it's not user error. This has nothing to do with flying out of a window. This is my opinion of the update. It has facts lined with it. A seat belt is mandatory irl why shouldn't it be in game? It's the very first thing I do when I get in a vehicle, so why can't it be the same here. Also I've seen a lot of passengers accidently jump out of a moving vehicle. I'm pretty sure you'll get a lot more complaints about it over the weekend.

**Comment by Blumpkin-JC** [comment]
AngelofDeathGaming, first I would like to thank you for creating this discussion of trucking. As a fellow disabled Combat Vet, I have never signed out a humvee to where it was completely filled up with fuel. As a Vet, I am sure your aware of what PMCS is. It is the responsibility of the driver to do a Preventive Maintenance Check Service to make sure you truck is safe for traveling on highways to prevent injuries to yourself and others. Fueling is part of the PMCS, with that said it’s not realistic to start off with a full tank. As for the seatbelt issue your having, it has caused more issues than anything, which is why they were taking out. I myself have occasionally fat finger and jumped out of a moving car. This pretty much our problem as maybe we need to get in a better habit of not flexing your F button along with other players. Also I have never heard of any Vet or Combat Vet getting anxious and jumping out of a car while it was moving. Again thank you for your time! 

Respectfully,

JC
