### ISSUE TITLE
MRPD Sound proofing + parking

### ISSUE THREAD

**Issue by ChugThis** [fkk-cz/noire-public#798]
Not sure if/what changed, but LEOs have noticed that between floors and through rooms we can hear each other again, and if you're in the stairwell you can hear the majority of the department, was hoping to get the soundproofing working again for meetings/bookings.

Going to tack on and ask for the 218 garage to be fenced off for LEO parking as LSPD currently has nowhere to bring/park their personal vehicles.

**Comment by Mynameisnotlenny** [comment]
Is there not parking in front of MRPD and street parking behind MRPD as well as a parking lot right beside MRPD? Just curious how much parking is needed?

**Comment by Stagonium** [comment]
> Is there not parking in front of MRPD and street parking behind MRPD as well as a parking lot right beside MRPD? Just curious how much parking is needed?

Yeah there is parking spaces, but having a secure parking lot for the people who don't just fly in and out at PD is the goal of the request

**Comment by Mynameisnotlenny** [comment]
Is there currently a problem with cars being defaced when parked regularly? I know the fences around the DOJ parking lot were implemented because people would ram the cars in front of the court house causing the cars to need a repair kit as well as causing the cars to be impounded by DOT. Just curious if this is currently a problem or if it’s more just being asked for. I don’t see an issue with cars being parked where the old public garage was beside MRPD not sure why a locked gate would be needed unless there is a consistent issue with cars being impounded by DOT and smashed by other civs. I don’t believe the 218 garage is currently owned by LSPD or is part of the station either so it wouldn't necessarily be logical for that land to go to the LSPD. If anything it would make more sense for someone to purchase the lot and then they could hypothetically pay to build the fences and could charge people to park there. Similar to how most parking lots would cost money to use in the downtown core of most big city’s.

**Comment by ChugThis** [comment]
> Is there currently a problem with cars being defaced when parked regularly? I know the fences around the DOJ parking lot were implemented because people would ram the cars in front of the court house causing the cars to need a repair kit as well as causing the cars to be impounded by DOT. Just curious if this is currently a problem or if it’s more just being asked for. I don’t see an issue with cars being parked where the old public garage was beside MRPD not sure why a locked gate would be needed unless there is a consistent issue with cars being impounded by DOT and smashed by other civs. I don’t believe the 218 garage is currently owned by LSPD or is part of the station either so it wouldn't necessarily be logical for that land to go to the LSPD. If anything it would make more sense for someone to purchase the lot and then they could hypothetically pay to build the fences and could charge people to park there. Similar to how most parking lots would cost money to use in the downtown core of most big city’s.

LEO vehicles that are not parked within our gates get stolen and rammed every single day. We have no room inside our gates so we instruct people to either fly in and out of the building which is limiting, or to park outside where the cars get rammed or stolen. If you want me to buy it I will but it's not for sale.

**Comment by ChugThis** [comment]
SAHP and the court have secure parking for their troopers and employees, just want the same for LSPD.

**Comment by Mynameisnotlenny** [comment]
> SAHP and the court have secure parking for their troopers and employees, just want the same for LSPD.

Understandable, just in terms of the SAHP parking lot it is part of the station and in terms of the courthouse parking lot, that parking lot was always intended for the courthouse, whereas for this it would be taking over an area that currently isn’t part of MRPD.

**Comment by ChugThis** [comment]
There is a garage that is on the other side of the station as well, any suggestions would be great just looking for something really

**Comment by Mynameisnotlenny** [comment]
If possible I’ve seen some MRPD layouts with a underground garage, I’ll see if I can find the file with it. I think an underground garage similar to the one at Zonah might be useful.

**Comment by Stagonium** [comment]
> If possible I’ve seen some MRPD layouts with a underground garage, I’ll see if I can find the file with it. I think an underground garage similar to the one at Zonah might be useful. 

We used to have that MRPD building, but we opted for a bigger building inside with no underground garage, as we had the public garage across the street. Just lookin to get that old unused parking lot reserved for PD

**Comment by Mynameisnotlenny** [comment]
Another option that comes to mind would be a garage within MRPD that can only be accessed by off-duty and on-duty officers so that they can store and retrieve vehicles from within MRPD.

**Comment by Ell34** [comment]
> Is there currently a problem with cars being defaced when parked regularly? I know the fences around the DOJ parking lot were implemented because people would ram the cars in front of the court house causing the cars to need a repair kit as well as causing the cars to be impounded by DOT. Just curious if this is currently a problem or if it’s more just being asked for. I don’t see an issue with cars being parked where the old public garage was beside MRPD not sure why a locked gate would be needed unless there is a consistent issue with cars being impounded by DOT and smashed by other civs. I don’t believe the 218 garage is currently owned by LSPD or is part of the station either so it wouldn't necessarily be logical for that land to go to the LSPD. If anything it would make more sense for someone to purchase the lot and then they could hypothetically pay to build the fences and could charge people to park there. Similar to how most parking lots would cost money to use in the downtown core of most big city’s.

you literally key coded my aventador outside of mrpd.

**Comment by fkk-cz** [comment]
Apparently MRPD never had working audio occlusion, there don't appear to be any .dat or .ymt files for it.

218 is already a garage, adding gates wouldn't be a bad idea.

**Comment by ItsGabble** [comment]
I agree it feels like something changed audio wise. We tested it the other day and could hear a conversation happening upstairs from the street outside the gate.

A garage is definitely necessary. Our cars get stolen constantly when left out front.

**Comment by FertileSphere** [comment]
coul we maybe get 216 rooftop parking area fenced off too/or as an alternative to 218? 216 literally only needs a single gate/fence added to stop access as there isnt anyway to boost into that specific space. arguably could fit as many vehicle as 218 aswell

**Comment by fkk-cz** [comment]
MRPD should have working audio occlusion now.

**Comment by Stagonium** [comment]
It wasnt when I was in earlier.

**Comment by Stagonium** [comment]
The soundproofing is still not working, and is actually worse than when the building was initially put into use.

**Comment by fkk-cz** [comment]
No idea how it somehow got _worse_, there were no occlusion relevant streamed files before. Reverting https://github.com/fkk-cz/noire/commit/abb574fe8cae5c0b288ed41cfa1e472bbaca5371 for now.

**Comment by fkk-cz** [comment]
Looks like the new RHPD has the same issue, even with valid dat15/dat151 files and a streamed ymt.

Adding gates around the garage across MRPD is out of the question -- the eyesore across the old courthouse was bad enough. The new PD building has an underground garage, but no working audio occlusion. Can't have both nice things I guess. I'll look into the audio occlusion issues.
