### ISSUE TITLE
ATM Cursor Bug

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#804]
### Discussed in https://github.com/fkk-cz/noire-public/discussions/803

<div type='discussions-op-text'>

<sup>Originally posted by **PsychoticCore** May  6, 2022</sup>
When exitting an ATM sometimes your cursor gets left on your screen and you cant move or do anything... Just thought i'd let it be known if it wasnt a known bug. Me and a couple of friends have been having this issue lately

Only fix ive found is just relogging.. and that sucks when its a 30 man queue then you have to wait hours just cause of a bug</div>

**Comment by Stagonium** [comment]
l have noticed it was less likely to happen if you click the exit button in the top right corner, as opposed to hitting escape to get out of it.

**Comment by fkk-cz** [comment]
No repro steps? I've never had this issue when using an ATM.

**Comment by PsychoticCore** [comment]
No clue how it happens I can just be using the ATM normally leave it and then bam I have a cursor stuck on my screen and can't move anything

**Comment by PsychoticCore** [comment]
> No repro steps? I've never had this issue when using an ATM.

I've just had the issue again, this time got to get it on video so here it is. For some reason this time my D key is stuck so my guy is just turning in circles...

https://user-images.githubusercontent.com/69283872/167321705-da722756-10fc-4712-b570-01a4aee3af75.mp4

.

**Comment by fkk-cz** [comment]
How are you interacting with the ATM? Contextual menu or pressing a key?

One immediate issue I'm seeing here is your ped not being in the correct position -- I'm assuming the enter ATM animation wasn't played when you first opened the menu?

**Comment by PsychoticCore** [comment]
I can't quite remember if it did pay the animation or not but it doesn't seem like it did since I'm still on the side of the ATM and to access it I used the third eye like you would to interact with most things

**Comment by fkk-cz** [comment]
Added an entity check in the contextual menu that should hopefully fix this issue. Do you have the same problem when pressing a key to access the ATM as well?

**Comment by PsychoticCore** [comment]
I only really use the third eye to access it but I assume using the ATM with E would not cause this issue since you have to be directly Infront of the ATM to do it

**Comment by xFooliee** [comment]
> I only really use the third eye to access it but I assume using the ATM with E would not cause this issue since you have to be directly Infront of the ATM to do it

I waa having the exact same problem, haven’t noticed it while being able to use the E button again but definitely had multiple problems using L Alt

**Comment by fkk-cz** [comment]
Going to assume this is fixed since people haven't been complaining about this since this change was pushed.
