### ISSUE TITLE
New ID's giving the wrong ID

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire-public#808]
So myself and a friend were checking out the new ID's. When I give him my ID it shows his and vis versa. So if PD goes to pull over someone they are going to see their own ID and not the drivers

**Comment by residentalyeti1** [comment]
https://medal.tv/games/gta-v/clips/keIaVZOeCXT6A/d1337BqS2PJj?invite=cr-MSxVNEosNDMyMDMzODEs Heres a video i took with AMR with this issue

**Comment by fkk-cz** [comment]
Mixed up the source/target when fetching user data. Fixed in https://github.com/fkk-cz/noire/commit/e533b51ecf53dc9978b5967a4bf18c22ea058d37.
