### ISSUE TITLE
Auto Theft Changes

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#817]
With the old issue (https://github.com/fkk-cz/noire-public/issues/719) fixed, the following changes have been made as well:
- Target vehicles are no longer spawned when starting a mission. Instead, a random **player spawned** vehicle is used instead.
- Selected vehicles must be server created entities, i.e. population type 6 or 7, with no ped initially occupying the driver seat. Vehicles that are attached to an entity will be excluded, along with vehicles with engine damage exceeding a threshold. Additionally, any vehicle that is marked for sale is also excluded.
- Missions are now available at all LS Customs, including the ones in Sandy Shores and Paleto.
- For city missions, there needs to be sufficient LSPD online, and city-specific cooldown cannot be enabled. The same applies for the county.
- If a player enters the target vehicle after the mission starts, a GPS signal will appear at a fixed interval which will indicate the vehicle's location and heading.
- Mission vehicle variety now includes all vehicles excluding ones in these categories: Bikes, imported vehicles, utility (oversized), and recalled.
- Waiting for destination time has been reduced by 50%.

There will probably be some issues or edge cases that I did not take into account, most likely a vehicle being selected in an inaccessible place (under the map or in the water). Please feel free to report any problems below, along with any related feedback.

**Comment by ChugThis** [comment]
Is there a way to exclude vehicles parked inside locked locations? If a mission is to get a vehicle that's behind a lock that's impossible to get in and out of (courthouse parking lot for example) that wouldn't quite work

**Comment by fkk-cz** [comment]
> Is there a way to exclude vehicles parked inside locked locations?

Not easily. Might have to allow players who are on active missions permissions to open certain gates, regardless of whether they have the authorized job or not. Note that this will not apply to locked doors, to prevent people from entering restricted areas.

**Comment by fkk-cz** [comment]
Small oversight -- the vehicle table was being indexed by model name instead of hash. Explains why no vehicles were available to steal today. Fixed in https://github.com/fkk-cz/noire/commit/14a1f86583a0ed16414cc9fc7fb7da6658cec281.

**Comment by YeetMeAway** [comment]
Currently due to the vehicles being taken from users, any damage to the vehicle prior to the job starting negatively affects your payout. Unsure if it is intentional but a vehicle that took no damage during the theft and delivery was a near four thousand dollar lost profit due to damage that was not done during theft, with a total payout of just under 1800

**Comment by Stagonium** [comment]
Just had one in the PDM parking lot, couldn't lockpick it due to being in a safezone, perhaps adding an exclusion to vehicles in a safezone being selected for stealing.

**Comment by fkk-cz** [comment]
> Just had one in the PDM parking lot, couldn't lockpick it due to being in a safezone, perhaps adding an exclusion to vehicles in a safezone being selected for stealing.

Players on active auto theft missions should be able to lockpick/hotwire anywhere, regardless of safezones.

**Comment by Stagonium** [comment]
I definitely was getting a "you can't lockpick in safe zones" message when I tried.

I know someone said they were able to Hotwire the car in a safe zone, maybe an oversight on the lockpicking? Unsure just spitballing.

**Comment by YeetMeAway** [comment]
Hotwiring is enabled, but lockpicking is still not available per tests I performed last night as well

**Comment by fkk-cz** [comment]
> I know someone said they were able to Hotwire the car in a safe zone, maybe an oversight on the lockpicking? Unsure just spitballing.

Yeah, looks like it. Fixed in https://github.com/fkk-cz/noire/commit/ffd19239ecfdc4fbd95db75e2ede637aa8e41e31.
