### ISSUE TITLE
Cars poofing off trailer

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire-public#820]
Last time I opened a thread like this or whatever these are called I got told that it was user error. Which I now can confirm it isnt because i have not touched anything and I got it on video again, so here Im gonna show both videos here so yall can see that it just randomly poofs into thin air and i didnt do anything. And this second time here 2 disappeared instead of 1

https://user-images.githubusercontent.com/69283872/167698444-406845e8-f6f1-4ddc-98a0-9296db0aa0c7.mp4    Clip #1 
https://youtu.be/omIxd1KF9sc    Clip #2

.

**Comment by glefave0209** [comment]
lmfao.. that second clip with blatant VDM haha

**Comment by PsychoticCore** [comment]
> lmfao.. that second clip with blatant VDM haha
Yeah them people were going mad fighting for a spot, shooting each other and VDM lmao but thats not the issue im tryna point out lmfao

**Comment by glefave0209** [comment]
> 

i know, I'm sorry, that was just funny to me.. No way that guy got away in a 3500 getting chased by a Titan.. LMFAO RIP

**Comment by fkk-cz** [comment]
Again, without steps that can reliably recreate this issue, **nothing can be done** as I wouldn't have any idea on _what_ specifically causes this. Repeatedly submitting videos showing this happening isn't particularly helpful either.
