### ISSUE TITLE
Cars on trailer changing

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire-public#822]
I was just normally accessing my trunk when then i got rammed the piss out of and then the FJ on my trailer changed color and somehow plate got changed too??? and i suddenly dont have the keys to anymore so i cant move it or access the trunk to it anymore?
Idk what type of voodoo magic is going here but this is probably the weirdest bug ive encountered...
Here is the video without any cuts so yall dont think i edited this or anything... You can clearly see the color and plate changing and then me losing access.
https://youtu.be/r27Sj2APwtE

**Comment by Kraezia** [comment]
same thing has happened to me and a few people in my team.... FJs sometimes suddenly turn into a PED vehicle...

**Comment by xFooliee** [comment]
This has definitely been happening for the past few weeks

**Comment by PsychoticCore** [comment]
nice to know this isnt just a me thing

**Comment by fkk-cz** [comment]
Refer to https://github.com/fkk-cz/noire-public/issues/820#issuecomment-1125487643.
