### ISSUE TITLE
Trucking Payout Revert

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#823]
Please revert the trucking payout. There was nothing wrong with the payment before. Now with the new payment, it just boasts mining more. There are currently 55 miners, 39 landscapers and 20 truckers. It was so much more balanced before. I understand your reasoning for the payout changes you stated in a previous github, but I don't see why everyone has to suffer the consequences of delinquents. I also say you said you increased the payment for the shorter routes, but that is not the case. Just did the movie equipment run and only got $1200 for it. You used to get 2800 for it.

**Comment by No-Yes1** [comment]
Please see the below comment from a previous issue raised: https://github.com/fkk-cz/noire-public/issues/795

_TRUCKING JOBS are now paying less.
Job payout was adjusted to prevent people from 'camping' certain jobs - we've been seeing issues recently with people fighting over jobs and killing each other at the job site. Other factors to consider:

Driving is a lot easier now. Cruise control now holds your speed and eliminates having to control the throttle.
Players are automatically warped into the truck. This saves time and reduces the risk of getting killed or your job stolen.
The shorter routes received a pay increase to help balance out the jobs.
In total, trucking has actually become easier -- the only issue I see is the low fuel for the longer runs, this can be solved by making the starting fuel proportional to the route distance._
