### ISSUE TITLE
Can no longer store trailers--urgent

### ISSUE THREAD

**Issue by glefave0209** [fkk-cz/noire-public#825]
Sounds like there was a change that prevents people from "driving" trailers. But that also prevents us from storing them

Once you pull it from a garage, there is no way to put it back without sending it to insurance/poofing

**Comment by PsychoticCore** [comment]
I can "drive" my gooseneck trailer just fine and be able to put it away, im not sure about the small trailer as i dont own one but the gooseneck seems to be working for me

**Comment by glefave0209** [comment]
I think he just fixed it. Lol

**Comment by PsychoticCore** [comment]
ah, well That'd make sense lol

**Comment by fkk-cz** [comment]
This [change](https://github.com/fkk-cz/noire_vehicles/commit/fa4c2623e18f9fdc980663d9ea2e7feba7184606) was introduced last night to prevent people from accidentally entering vehicles that should not have a driver seat, such as the stretcher. Didn't take into account the fact people use it to store trailers.

Fixed for tomorrow's reset.

![image](https://user-images.githubusercontent.com/74131024/167960155-26da3d02-f905-43d9-a2cd-a65ad743516d.png)
