### ISSUE TITLE
Can’t sell drugs

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire-public#826]
Seems like you can’t sell drugs rn. Assuming it’s because the amount of cops you need for auto theft missions got changed..

**Comment by fkk-cz** [comment]
No changes were made to drug sales? Probably not enough cops online.

**Comment by TheBottomFragger** [comment]
> No changes were made to drug sales? Probably not enough cops online.

Then it might just be the F10 that’s bugged

**Comment by fkk-cz** [comment]
Refer to the disclaimer on the scoreboard:
> The crime availability information above is a general approximation of what is possible and may not be
                completely accurate.
