### ISSUE TITLE
Auto Theft Bug

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire-public#827]
Got an auto theft, was given the goal to steal a wheelchair. Couldn't lockpick it or get on it, don't know if that's how the wheelchairs work or what, just figured to throw it in here.

**Comment by fkk-cz** [comment]
That's ..probably a vehicle model that should get removed.

**Comment by fkk-cz** [comment]
Increased the minimum MSRP required for a vehicle to be included in the 'eligible vehicles' list. This should fix the issues with these vehicles that are unintended for auto theft missions.

https://github.com/fkk-cz/noire/commit/6ed238caa60af824b60d5364c6cfb48bc7cd7ace
