### ISSUE TITLE
Fishing Changes

### ISSUE THREAD

**Issue by MKXVIII** [fkk-cz/noire-public#829]
hello today i want to suggest some changes to fishing. For example the catch rate for the fish is between 10% to 40%. i propose that either the catch rate is buffed to 80 to 90% whilst decreasing the price per fish to make stay even with the rest of the legal like mining. 
Although with that being said it takes approximately 1 and a half hours to do a full mining run which can net you somewhere in the range of 30 to 35K. whilst one full gooseneck of fish can take you like 30 hours of fishing and only "GROSS" you like 60K. i say gross because you'll send 2K to get 1000 trunk space of fish bait.

One way fishing could be buff is by increasing the catch rate per the 10 to 20 fish bait being used at one time, like stated above. but when doing that say one person brings a full gooseneck full of fish bait if the catch rate is 80 to 90% they will fill an entire gooseneck before they get to the third trunk. The reason why that would be the case is because the fish bait weights 10 units of inventory whilst the fish weight 25 units of inventory, meaning that you can have 100 fish bait in one 1000 space trunk and only have 40 fish in one 1000 space trunk. to compensate for that issue you could increase the fish bait to weigh 25 units of inventory, so that one full gooseneck of fish bait could equal basically the same amount of trunk space for the fish that one would catch.

another way you could buff fishing is by adding a fishing boat with two trunks of 2000 units of inventory. This could work by increasing to the catch rate for people that use the fishing boats in the open sea, whist the people who don't have boat have the same catch rate as used now for the job. This would provide goals for people to work toward well making and opportunity for another micro economy to open up, which would make fishing on par with mining. This would further diversify the legal jobs allowing for the mines to not be so packed all the time, and allowing limitless space for people to fish.

**Comment by Bountyrogger** [comment]
Gonna be real my man. Barking up the wrong tree. Fishing isn't meant to be like the other jobs in the city. Its more meant for something to do with your pals in your free time.

**Comment by MKXVIII** [comment]
thats why the fishing boat would have 2 trunks

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/732
