### ISSUE TITLE
Auto Theft Bug

### ISSUE THREAD

**Issue by MrGoony** [fkk-cz/noire-public#834]
This problem has happened twice now where I take the car and park it in the yellow orb where the indicator tells me to, only for it to complete the auto theft but not pay me or remove the car marker from my map. Not sure if I'm the only one who's experienced it, figured I'd make it known.

**Comment by MrGoony** [comment]
Would also like to put in that after trying to do my 3rd auto theft, hoping it wouldn't glitch out, it gave me the prompt to go to the area, gave me no area.

**Comment by Jamalcandog** [comment]
SCRIPT ERROR: @es_extended/client/functions.lua"1166: attempt to call a nil value (feild '?') that is what it says when you drop off the car at the auto theft drop off

**Comment by fkk-cz** [comment]
> I take the car and park it in the yellow orb where the indicator tells me to, only for it to complete the auto theft but not pay me or remove the car marker from my map.

Sounds like the same issue in https://github.com/fkk-cz/noire-public/issues/836.
