### ISSUE TITLE
AMR Stretchers

### ISSUE THREAD

**Issue by Bountyrogger** [fkk-cz/noire-public#837]
AMR stretcher need a fix... It is becoming frequently more frequent that when AMR tries to pick one up it glitches out and in our eyes we are not carrying it and we can not pick it up/drop but in others eyes we are carrying the stretcher... Even if we cardel the stretcher we are unable to pick it up. Only fix found so far is to fly out and fly back in. Becoming a lot more frequent that for example in just the last 20 minutes I've had to fly out and back in twice already.

**Comment by Bountyrogger** [comment]
Would like to add. It makes it even worse for anyone on AMR without Priority as if their stretcher breaks during peak they are stuck in a que and will be unable to fly back into the city

**Comment by PreacherDeimos** [comment]
Yeah, stretchers are fucked for me every shift almost. Glad I have priority queue.

**Comment by Bountyrogger** [comment]
Happened twice to me within 20 minutes of each other... and then a third time before an hour even hit..

**Comment by WaywardCanuck** [comment]
Bugged Stretcher
https://medal.tv/games/gta-v/clips/l0EJzYtuzN5_a/d1337OvkejRQ?invite=cr-MSxRaUosNTE5ODUzMjAs

Bugged Ambulance
https://medal.tv/games/gta-v/clips/l0XIx9vyEVWuX/d1337Eft6aic?invite=cr-MSxQbGgsNTE5ODUzMjAs
