### ISSUE TITLE
Auto theft mission hotwire issue

### ISSUE THREAD

**Issue by ChirpyMedusa** [fkk-cz/noire-public#841]
I did two back-to-back missions today and I only had a multi-pick and a lockpick (and a weapon) on my person at the time. On both missions, the key fob decoder screen came up instead of the standard multi-pick scenario. Not sure why this is happening, but these are cars that should not even be lockpicked with a key fob decoder but rather a multi-pick, let alone I don't even have a key fob on my person. 

A separate issue: I got two back-to-back missions with two different vehicles inside the MRPD gates, which is obviously impossible. 

Thanks.

**Comment by FertileSphere** [comment]
the "key fob screen" or , The Matrix, as its more commonly reffered too is standard and supposed to be there. Stealing cars isnt supposed to be easy and its assumed you accepting a boost mission "gives" you the memories to use the key fob and multi pick without them being in your possesion.

As for the "behind locked gates issue" we have had the same scenario multiple times aswell, in fact we had 3 people get the same bike inside PD on the first day the "new" missions were availible.

**Comment by ChirpyMedusa** [comment]
Got it, thanks. Yea so I guess just the issue with the gates is the only problem.

**Comment by fkk-cz** [comment]
> Yea so I guess just the issue with the gates is the only problem.

This isn't a 'problem' -- if an assigned vehicle is behind a locked gate that is something to be roleplayed out. (_Figure out how to convince someone to let you in?_)
