### ISSUE TITLE
House Relocation Issue

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire-public#844]
So I requested a house relocation and got approved for it early this morning. When I got there there was 2 entry points and 2 garages. Eventually, I found out that there was a second person living in the same house. Can I get this fixed please.

**Comment by No-Yes1** [comment]
You or that other player will have to /relocatehouse again then

**Comment by TdotG** [comment]
The other person requested the same house that I requested. I'd appreciate if you can cancel my request and keep me at my current house.
