### ISSUE TITLE
Removing players who are the same rank/higher rank.

### ISSUE THREAD

**Issue by No-Yes1** [fkk-cz/noire-public#845]
This has happened a few times (inc. myself) where I've accidentally fired/demoted someone who is the same rank as myself. Lower Ranks can also demote/fire same/higher ranks. Was wondering if this can be fixed so people with the hiring menu can only demote/fire 1 rank below them.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/e5bfaa275766fba5e0292655650539b98ba5d585.
