### ISSUE TITLE
New drug zones & gang rp

### ISSUE THREAD

**Issue by ghost** [fkk-cz/noire-public#851]
Allow gangs to sell on their block would be a great start to influencing gang rp. It will also open more rp for Leo like them watching a house that has been seeing A lot of activity of people coming in out and could be raided. Forcing gangs to move drugs around .Also allowing people to turn their dirty into 100% cash. I’m sure it gets old to people to get some dirty and just go buy the same guns over and over . Let that dirty turn in to cold hard cash. It really makes no sense to be in a gang and a rough criminal past and just able to clock go mine for like 8 hours and come back rich. That’s for the civ life . As whitelisted gang members. You shouldn’t be able to take your flag off and go do legals. You only means of making should be illegal. I see it as if you chose the gang life then you gotta live the gang life. And i suggest enforced rule changing and war terms. It could be like a wager system. Like your gang has to
Have so much amount of dirty to even be able to go to war. And having a kill count limit to reach to win the war and loser losers the dirty money that was bet.  And there could be a marked war zone in the hood areas. Also hiding  the black market would make things interesting with gangs . And moving it around every so often. If people want to see gang rp which I I’m sure they do that’s why I making this post for them , then you need to tools to make it happen. Enforced rules is most important. People who don’t understand how to rp won’t last in my opinion and that would force good rp within gangs.

**Comment by zoiczombie** [comment]
PD already has a gang unit and watches what houses you go into if you run from them answering a drug call. If we had the ability to sell on our blocks it would benefit us more than LEO since we could easily sell and run into our houses before PD shows up. 

Crims could easily flip dirty to clean since there's a higher demand for it. If you take away jobs from crims you're gonna get a lot of complaints about non-whitelisted people doing crim activity and that's not what we want. It would also cause more tension with gangs and LEO since the ability to get dirty is dictated by the amount of active PD/HP on.

**Comment by dgreengoblin** [comment]
All you have to do is enforce rules of power gaming . And if drug zones are in people hoods then how none whitelisted criminals gonna sell. Shit they gonna have to pay a tax or something. It’s crazy that’s this ain’t possible. When I’ve seen it working perfectly in other places.

**Comment by dgreengoblin** [comment]
And we should  just stop letting our drugs dictate by how many cops online .

**Comment by cxerq** [comment]
> And we should just stop letting our drugs dictate by how many cops online .

Im assuming you mean that we should be able to sell drugs with cops online with this correct?

**Comment by cxerq** [comment]
Having more places to sell drugs would be good! But you need to understand that some crims will abuse the shit out of running into there house before cops show up! Then lets say people get seen going into there house boom they get raided lose all there shit how is that right?

**Comment by dgreengoblin** [comment]
Sell drugs with cops off line . I
Mean ain’t no restrictions on how long someone can sit at mining with like 5
Fjs until they make a million. Why do gangs have to restricted .

**Comment by cxerq** [comment]
> 

This is awful for a few reasons! Value of dirty cash drops completely where an AK would be work less than a Walter p88, Alot of people will only sell when cops arent online which doesnt make sense!

Another idea could be the amount of required cops gets dropped to about 3 cops to sell

**Comment by dgreengoblin** [comment]
Yea that’s right . I
Mean I see detectives in the city but I ain’t really seen no real case building detective work. At the End of the day just enforce rules . Let’s gangs do a drive by  if they rdming and doing it unrealistically then clip it and discipline them. Simple. Let us rob again . It’s more Rdms. Going on now that it was before robbing was taken. Let’s us was our dirty. Every time suggestions are made to get to the way it should be . It alway a response like “oh then they gonna start doing this or that “ ok then enforce the rules. I gave up on the gang banging because shit wasn’t right now I’m forced to be cop just to
Get some good rp. Give the gangs the tools an support they need to rp.

**Comment by dgreengoblin** [comment]
I’d say 2 cops to sell would be fair

**Comment by ChugThis** [comment]
Selling drugs without cops online is not RP. There is RISK involved when selling drugs. How is no risk all reward any fun at all? Crim balance is important but in no way should that be happening. Also, you don’t have the slightest clue what the detective unit does within the LSPD, they have extensive case files that’s part of their RP. 2 cops is not “fair” when people sell in groups of 5+ on bikes that they park 2 feet from them so they can sell, stash, and sell again.

**Comment by dgreengoblin** [comment]
I know exactly about the detective work. I spent over 3000 hrs in a gang in la noire became one of the most recognized gang members. And I never once had a case thrown on me . I get no cops ain’t fair . Honestly I don’t even care about selling with no cops . Just gangs wash they dirty into clean and actually be a real drug hustler. Not cool when i was standing on the block and some dude ask me how I got a car like this I tell him doing garbage runs

**Comment by ChugThis** [comment]
Until you are actually in it, respectfully, you don’t. Maybe just not as well known as you think? There are also a small handful of detectives in a large department. Legals are meant to pay more, and easier. I think we’re all down for balance changes but just to what’s really needed

**Comment by dgreengoblin** [comment]
Bro sit down somewhere. You don’t know shit about about no gang rp.

**Comment by ChugThis** [comment]
I am sitting

**Comment by dgreengoblin** [comment]
I don’t even know why you commenting when I’m sure you biased as fuck. I’ve played my role phenomenally on the gang side . Ima do the same in the Leo side . If you really ain’t been knee deep in the gang side don’t even speak.

**Comment by noyeahsure** [comment]
> Having more places to sell drugs would be good! But you need to understand that some crims will abuse the shit out of running into there house before cops show up! Then lets say people get seen going into there house boom they get raided lose all there shit how is that right?

i know you are not talking about abusing things in game... sir...

**Comment by ChugThis** [comment]
Says the man who knows in depth the whole Leo side whose never done it. Cheers, good luck with that

**Comment by cxerq** [comment]
> > Having more places to sell drugs would be good! But you need to understand that some crims will abuse the shit out of running into there house before cops show up! Then lets say people get seen going into there house boom they get raided lose all there shit how is that right?
> 
> i know you are not talking about abusing things in game... sir...

Im not the only one :( Why you only gotta point out me its fucked up

**Comment by dgreengoblin** [comment]
Bro I’m on fuckn highway now you  j cat.

**Comment by dgreengoblin** [comment]
I just can’t stand who bring problems to problems . Bring solutions .

**Comment by Stagonium** [comment]
> Mean I see detectives in the city but I ain’t really seen no real case building detective work.

There is plenty of case building going on, just because you don't personally see it, doesn't mean it isn't there. It's tough without the tools in place to really do anything with the intelligence collected, as there is no easy or reasonable way to raid a house for its contents as the result of an investigation. We have, in the past had a guy with a half a million dollar warrant that he was fully convicted on, but most of the work is done out of the eye of the public.

**Comment by dgreengoblin** [comment]
This ain’t even case building bro.  This why I don’t come here

**Comment by somedudenamedrush** [comment]
said what i said about this in my opinion here https://github.com/fkk-cz/noire-public/discussions/726

**Comment by dgreengoblin** [comment]
I titles this shit new drug zones and gang rp and y’all bringing up is Leo case building.

**Comment by dgreengoblin** [comment]
> said what i said about this in my opinion here #726

And nobody listened . SMH .

**Comment by Stagonium** [comment]
> I titles this shit new drug zones and gang rp and y’all bringing up is Leo case building.

All I'm saying is if this suggestion is to happen, a lot needs to be implemented all at once to keep it balanced.

I came into the discussion late and replied to a part that I can make a fair response to as it pertains directly to my time in the city. If you didn't want that to be talked about why did you add it to YOUR discussion

**Comment by dgreengoblin** [comment]
> > I titles this shit new drug zones and gang rp and y’all bringing up is Leo case building.
> 
> All I'm saying is if this suggestion is to happen, a lot needs to be implemented all at once to keep it balanced.
> 
> I came into the discussion late and replied to a part that I can make a fair response to as it pertains directly to my time in the city. If you didn't want that to be talked about why did you add it to YOUR discussion

This my first time bring info some things up here. I only spoke up for other people in here as I went back a scrolled through a lot of discussions it just made me think of  the shit we wanted back when I was doing gang shit. But I see it ain’t enough support up here.

**Comment by Stagonium** [comment]
I'm all for new drug zones and methods for things to happen in the city, that ability for things to change is what makes the city fun for all involved, hell, I even have personally suggested [#774](https://github.com/fkk-cz/noire-public/discussions/774) a couple weeks ago to try to spread stuff out in the city and try to widen the area that criminals do their work at and where cops have to respond to.

**Comment by somedudenamedrush** [comment]
anyways now that the LEOs are done arguing lmao 
I do think the school/pills selling would be cool needs work with the selling mechanic cause i dont think theres enough peds up there would have to be something where the peds come to u might be better for the whole city if we're being honest

less cops online (2-3) needed to sell drugs is def needed as of right now the way the city been going cops in the city dont clock on till 7-9pm est (alot of ppl crim or even the randoms dont get the chance to sell/different timezone), but as i stated before a start would be opening it up to the whole lower 125 as i stated before here https://github.com/fkk-cz/noire-public/discussions/726 
theres no lose to this fblock can be used for player houses also now with the whole lower 125 opened yes it will force leos to be creative and catch crims outside of we're gunna pull up to the bridge and camp a few random silos and bushes (ive watched yall operate standing on a roof near st jamestown its sad the randoms selling didnt even get a pack off) also as of rn Fblock is still unusable the peds still shoot

**Comment by YeagerGTA** [comment]
Back to the drug selling by block etc. IMO there should be more areas to sell at other than those currently in place around the city and in the county. It would be cool to work in some way to for gangs to lay claim to them, basically holding them down for periods of time coupled with establishing stash houses that expire, forcing them to move them around. Ideally the white list would  exclude them from storing large quantities at private residences (example say 10 of each) in favor of designated stash houses that are valid for a given amount of time before having to be relocated. Those stash houses would be designated by leadership and would also be raidable by police where stashes would be vulnerable to seizure by police or theft from other gangs. Not full inventory maybe, but some percentage of the stash could be seized or stolen. This would open up RP for both sides on the seizures and add a new interaction with the gangs on each other, other than shooting each other in the streets. Finding each others stash houses, going after them etc. Currently that kind of interaction is limited to processing areas which also impacts non-gang crims.
