### ISSUE TITLE
Society Fire - Can still fire people at same rank:

### ISSUE THREAD

**Issue by No-Yes1** [fkk-cz/noire-public#852]
Following up from https://github.com/fkk-cz/noire-public/issues/845. You can still fire people at the same rank. I had a manager try it out: https://cdn.discordapp.com/attachments/903529430146752572/975948832795930645/MedalTVFiveM20220516221333-tr-edit.mp4

**Comment by RockemRobotics** [comment]
Only a select few people can access the personnel list though right? It's kind of important to keep the ability to fire equal rank at that high of a position, for DOJ at least.

**Comment by No-Yes1** [comment]
it doesn't make sense to fire equal/higher ranks. It should work ad when you are promoting/demoting someone, should only do it to -1 rank to yourself.

**Comment by RockemRobotics** [comment]
It does for DOJ at least. I'm just saying that with this being an ability that very very few people have, you just kick someone off the whitelist if they abuse that power. If it's a mistake it's easily fixed.

**Comment by fkk-cz** [comment]
> Following up from #845. You can still fire people at the same rank. I had a manager try it out: https://cdn.discordapp.com/attachments/903529430146752572/975948832795930645/MedalTVFiveM20220516221333-tr-edit.mp4

There was a missing check for players who were whitelisted but did not currently hold the relevant job. Fixed in https://github.com/fkk-cz/noire/commit/27fea0a11b2bce64f13641e6697123663d2b6fd1.
