### ISSUE TITLE
Matchmaker Notifications

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire-public#856]
I flew in, got a notification I matched with someone, they werent in the matched place. now that im on the app i keep getting a notification "match found" in blue text bubble at the bottom but nothing new in the matched place? Never had this before just started happening. Speaking of the Devil it just happened again as I tabbed back into the game. I feel like I'm getting other peoples notifications cause i dont recognize most of these peoples names 😂

Even after relogging twice I'm still getting these random ass notifications saying ive matched with someone

**Comment by fkk-cz** [comment]
No repro steps or further information was provided. Seems like a client specific issue.

**Comment by Stagonium** [comment]
From my experience with this, if you match with one person, anyone who you dislike that has previously liked you, will say new match found, despite a match not being possible from you disliking them.
