### ISSUE TITLE
Request Trucker mechanic job

### ISSUE THREAD

**Issue by Wickedheadwound** [fkk-cz/noire-public#860]
I am requesting to see if we can get a new job created. The mechanic job only the tuckers, Equipped with a radio that would be on the employee's person that would be able to communicate with the truckers and go out and repair/refuel the Trucks and or trailers for a cost. They would also be able to remove the unattended trailers from the roads to help clear out the roads and to help the server out.

**Comment by Wickedheadwound** [comment]
https://github.com/qbcore-framework/qb-mechanicjob

**Comment by No-Yes1** [comment]
isn't this just DOT? - Request for DOT on twitter if you need this.
