### ISSUE TITLE
Suggestion: Be able to move Death Camera

### ISSUE THREAD

**Issue by smokinate** [fkk-cz/noire-public#863]
If possible, allow the camera to be moveable while dead. I could understand this was maybe implemented to make it so you cannot provide information to others or look around, because realistically, you're dead and shouldn't be able to. However, I think it would be beneficial because:

1) It makes the death wait time less boring, you can at least move the camera and look around rather than stare at a fixed angle for 5-10 minutes.

2) If you're clipping/recording something, it makes it easier to see IDs of players that may have been hacking/RDMing/VDMing/etc. Otherwise, the way it currently is, you only see what is in your POV, which is often a weird angle in which not much is visible.

**Comment by Yush6969** [comment]
I doubt this would be pushed further, Already metagaming is a big problem and if this were to be added in that would make it much worse for everyone as people will be able to give a lot more information to people on calls on the situation. If you do get bored, Most people would just tab out and do something else for the time being.

**Comment by fkk-cz** [comment]
Refer to the statement above -- metagaming is already bad enough.
