### ISSUE TITLE
cars go slower when i drive them

### ISSUE THREAD

**Issue by Vanilla12345** [fkk-cz/noire-public#865]
So I was in PDM and I wanted to see how fast  car was so I was racing my friend in the same car and I go 50mph slower than him
And it’s with all cars I go slower in all cars
And then when he drives it he goes way faster it’s with everyone else like I’m the only one that goes slow

**Comment by PsychoticCore** [comment]
Just curious, are you playing on controller? Because I've had this issue in the past with controllers

**Comment by Vanilla12345** [comment]
im not on controller

**Comment by fkk-cz** [comment]
Did you try validating your GTA game files and/or reinstalling FiveM?
