### ISSUE TITLE
Ways to check your own licenses

### ISSUE THREAD

**Issue by RockemRobotics** [fkk-cz/noire-public#866]
There is currently no way - not without traveling somewhere at least - to see any of your own personal information. I cannot check if I have a CCW without going to an Ammu-Nation and trying to purchase a firearm. I cannot check if I have a valid driver's license without trying to buy a car or going to the driving school. I cannot even check to verify my own in-city birthday without handing my ID to someone and asking them what it says.

Considering that, at least for the CCW, you can get in trouble for not having one, it would sure be great if there were a way to check it without involving law enforcement or a trip to an Ammu-nation. But while we're adding that, it would also be good to include the other licenses to view.

**Comment by fkk-cz** [comment]
Ideally the ID card/drivers license should be an inventory item. That being said, I can already think of a few issues:
- Players (criminals who want to be a smartass and pull the "I have no ID on me you can't figure out who I am" card) dropping the ID/license item on the ground as soon as they respawn
- No real incentive or requirement to carry it around, most people will not carry one and would rather run from the police
- If the item is allowed to be dropped/removed from your inventory, there is no identifier that ties the ID card to a specific person

The last point can only be solved if the entire inventory system was reworked to allow for unique identifiers for each item that exists in the world.

**Comment by RockemRobotics** [comment]
Not knowing how the inventory system works, is it possible to make it a locked item that cannot be removed or dropped and can never leave your inventory?

Otherwise there used to be an F5 menu option that let you view your own license without involving inventory.

**Comment by fkk-cz** [comment]
> Could you not make it like mining minerals or hunting meat where you physically can't drop it?

Then you'll have these smart (dumb) ass criminals who will whine that it's "unrealistic they can't remove their ID" from their inventory when the police search them and find their real name.

That's something they will have to deal with, as it's the only way I can think of to prevent the issues mentioned above.

**Comment by fkk-cz** [comment]
Driver licenses are now a non-removable item, obtainable at the DMV. The first license request is free, subsequent replacements will carry a fee. Players with a valid license are required to carry one while driving, the police will be citing people for driving without carrying their DL. https://github.com/fkk-cz/noire/commit/61aed0aa7da3b65195d6d6a73df4141622df2937

Police are also no longer able to F6 -> Check ID to instantly determine who someone is. The target player must have the item in their inventory. If people start abusing this and dragging out scenes/being extremely stubborn beyond normal limits, this change will be reverted. https://github.com/fkk-cz/noire/commit/4e903d2addcdb3dee7c9e909a081f947bbc0834b

**Comment by ChugThis** [comment]
Clocking out of PD does remove a drivers license as well if that could be adjusted

**Comment by fkk-cz** [comment]
Fixed https://github.com/fkk-cz/noire/commit/38a6fe04bda5753ef838ed56f0cd119a268961a6.
