### ISSUE TITLE
Add an ammunation on sandy shores

### ISSUE THREAD

**Issue by GoldBlockGames** [fkk-cz/noire-public#869]
it would make more sense as peds there have guns and it would be easier for people to access guns and lockpicks

**Comment by Hesh77** [comment]
There already is one unmarked on the map which you can buy lockpicks and weapon mags from.

**Comment by GoldBlockGames** [comment]
> There already is one unmarked on the map which you can buy lockpicks and weapon mags from.

but what about actual guns?

**Comment by fkk-cz** [comment]
The gun store in that location was removed because people would have shootouts -> respawn and run less than a minute down the road -> have another shootout -> place assists/tickets whining about how they got killed after dying etc.

**Comment by Hesh77** [comment]
No it's just the blue circle same as the one near PDM, if it has guns in
it, it's marked on the map.
