### ISSUE TITLE
isn't this just DOT? - Request for DOT on twitter if you need this.

### ISSUE THREAD

**Issue by Wickedheadwound** [fkk-cz/noire-public#872]
isn't this just DOT? - Request for DOT on twitter if you need this.

_Originally posted by @No-Yes1 in https://github.com/fkk-cz/noire-public/issues/860#issuecomment-1133956047_

I would say yes and no, There never is any jobs that are up for tuckers when everything is all going and busy. there is a github already out there for this also DOT in my experince never comes or is on as far as I've seen. Along with that being said there is always trucks just sitting around the lot making everything glitch out.

**Comment by fkk-cz** [comment]
Requesting roadside assistance is planned as an app on the phone. No one should have to manually call (or tweet) for DOT.
