### ISSUE TITLE
Laggy UI

### ISSUE THREAD

**Issue by Metalwrist** [fkk-cz/noire-public#874]
seems that ever since the server switch or whatever happened when it was done for 5 hours the UI has been lagging? Are you aware of this? I have asked multiple people and they have all complained about the same issue. I just don't know if everyone is experiencing this.

**Comment by fkk-cz** [comment]
![image](https://user-images.githubusercontent.com/74131024/169926344-b93a6b60-0235-4c55-821a-06196d91275c.png)
