### ISSUE TITLE
AMR Stretchers

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire-public#883]
I'm aware there is already an issue with this open, but this really really needs to be fixed ASAP. It is completely broken, every single paramedic is having to log out and log back in every shift we take, like almost hourly or sometimes we have to log out and back in 2 or 3 times because our stretchers are just that fucked, yesterday my stretchers fucked up on a call with around 8-10 people and I had to transport them 2 at a time in my Explorer to the hospital because my stretchers were fucked. Please fix this, this is a serious issue. Thank you!

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire-public/issues/837
