### ISSUE TITLE
Auto Theft Bug'ish

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#886]
So i've gotten an auto theft and the owner of the vehicle stored it in his garage and it cancelled the mission after i was chasing him around for like 10 minutes just waiting for my moment to strike and take it! Is it possible to make it so if a car is marked for auto theft it cant be stored away? Or is that just something we will have to deal with?

**Comment by cxerq** [comment]
> You guys can literally lock pick in safezones, unimpeded with no threat of self defense. I think if the owner gets away and stores it, that's a valid trade off you should have to deal with

Thats why its a question! More intented FKK! Thanks for you input tho!

**Comment by fkk-cz** [comment]
This is already the case -- mission vehicles cannot be stored in a public garage until the mission expires or the timeout runs out.
