### ISSUE TITLE
Downtown cab co upgrades

### ISSUE THREAD

**Issue by teresgrunt4555** [fkk-cz/noire-public#891]
I just wanted to post here about some upgrades we talked about.

1- Getting taxi to be purchased like PD/Highway. It would be nice to get this so we can keep upgrades for them with out having to pay every time we get it out.

2- Getting an interior that you saw for taxi co to have somewhere to go inside and interview and do all our business 

3- A gate or some other way to stop people from parking in our lot. We keep getting random cars in our spawn spot for taxis and can’t pull them out

**Comment by fkk-cz** [comment]
Closing #656, marking this for visibility.

**Comment by teresgrunt4555** [comment]
New upgrade for the building https://www.youtube.com/watch?v=MHXA_3A6doQ

**Comment by fkk-cz** [comment]
> 1- Getting taxi to be purchased like PD/Highway. It would be nice to get this so we can keep upgrades for them with out having to pay every time we get it out.

Another option is to make taxi vehicles purchasable at PDM (only with the whitelist, of course). Some taxi companies require the driver to invest in the taxi medallion, and the vehicle.

Added the interior with doorlocks & the audio occlusion override. I'll add a gate in the front as well to prevent people from parking their vehicles in the lot.
