### ISSUE TITLE
Phone very buggy

### ISSUE THREAD

**Issue by Hesh77** [fkk-cz/noire-public#895]
My phone has recently been very slow, especially when I open the marketplace my phone disappears and then in the top right corner of the screen my job and voicebox disappear. This isn't a wifi issue since my router is right next to where I play. I've heard complaints from other players too about this. I hope we can get some update which will resolve this issue.

**Comment by fkk-cz** [comment]
This isn't actionable or helpful at **all**, no repro steps and pointing to irrelevant things such as your network connection, really?

**Comment by Stagonium** [comment]
[Here](https://i.imgur.com/U0xanpt.png) is what I think could be causing it. If you notice the small side scroll bar, it appears as if the marketplace doesn't stop loading posts, so it is likely causing hitching due to the amount of posts being loaded.

**Comment by PsychoticCore** [comment]
That honestly could make sense because the phone does lag until you're a few hours into playing on the server

**Comment by TheBottomFragger** [comment]
I have had the same issue, it only happens when I try to go into the marketplace tbh.. everything else is fine

**Comment by Hesh77** [comment]
> I have had the same issue, it only happens when I try to go into the marketplace tbh.. everything else is fine

same twitter and everything else works fine.
