### ISSUE TITLE
Observations on vehicle despawns

### ISSUE THREAD

**Issue by MinoritySanta** [fkk-cz/noire-public#897]
Just a general question, or maybe a possible solution to the vehicle despawning issues some seem to be facing

One thing I've noticed, is when a vehicle is totaled/bricked, there's nothing that will cause it to despawn.  If it's in the river, or blown up or similar, it will literally stay in the city until Tsunami.  I've even tried flying in and out for a few hours from the opposite side of the city, but it will still stay.. But then we have these random occurrences with trailers or FJs where they will literally poof if you leave the radius for more than 20 seconds

I know specifically in my area (959), If I leave that radius for more than 10 minutes, anything I leave parked there will poof (cars/trucks/trailers etc).  But if I leave something that's damaged, it will stay for the entire day. I rent a lot of vehicles out, and usually the renters bring a vehicle to my place and park it.. By the time I'm back for my next rental, the previous renters vehicle is gonzo

Is there something in the code that won't allow damaged vehicles to despawn?  If so, is it worth looking at a consistent process where either a) everything despawns the same way or b) nothing despawns at all (IE similar to damaged vehicles that don't seem to ever poof)

I can start getting some clips if a visual is needed

**Comment by fkk-cz** [comment]
> Is there something in the code that won't allow damaged vehicles to despawn?
No, server created vehicles will never delete unless a) explicitly done so by a server script, or b) it was created via RPC, to which the normal migration and deletion logic applies.

> If so, is it worth looking at a consistent process where either a) everything despawns the same way or b) nothing despawns at all (IE similar to damaged vehicles that don't seem to ever poof)
No. Any non-automobile (trailer, bike, etc.) will always despawn if there is no player with network range of the entity, as they cannot be created without RPC invocation. If vehicles are being deleted when players **are** in the area, this is a bug that needs to be reported with repro information.
