### ISSUE TITLE
Phone bug 

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire-public#898]
I saw that Hesh already made a github about this, but it got closed not long after he opened it. 
There’s still issues when it comes to the phone and the marketplace. We’re not the only one experiencing this issue and this has been a problem for a few days now.. Is this caused by something that got added to the server? 
Everything else on the phone works perfectly fine, but once you try to go to the marketplace, it just freezes. If you try to put down the phone, the animation goes through when it’s not frozen anymore and everything, but the phone is still on the screen.

Hesh is going to post a clip of this happening if he can get one before this bug makes his game crash. If he can’t get it, I’ll post the clip in a few hours.

**Comment by TheBottomFragger** [comment]
This is from when I basically just loaded in, so it's "better" than it usually is, but here's a little clip of the "lag".
You can see that the animation of me pulling out the phone and putting it away is still working, but the phone is just super laggy.

https://medal.tv/games/gta-v/clips/mRrDQN_lliZ_-/d1337bStUKyH?invite=cr-MSxpaXYsMjEyMDU2NTAs

**Comment by fkk-cz** [comment]
This appears to be caused by a large number of marketplace listings, which leads to NUI slowdown/unresponsiveness. Should be better now, I cleaned up a lot of old listings. Probably need to add some auto cleanup feature to prevent buildup.

**Comment by TheBottomFragger** [comment]
> This appears to be caused by a large number of marketplace listings, which leads to NUI slowdown/unresponsiveness. Should be better now, I cleaned up a lot of old listings. Probably need to add some auto cleanup feature to prevent buildup.

Seems to be better already! Thanks

**Comment by fkk-cz** [comment]
> Probably need to add some auto cleanup feature to prevent buildup.

Added in https://github.com/fkk-cz/noire/commit/e2b0b37b18f2b6ce3dbfeb0bad1b5da16082e559. Marketplace listings that have not been updated for 24 hours will be automatically removed.

Thanks for pointing this out.
