### ISSUE TITLE
Gate at Zonah

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire-public#904]
Every time AMR is on-duty our vehicles are being hotwired and stolen, can we please get a gate at the bottom of our parking lot? Or put some fences and a gate down there? This is unrealistic to go down to our garage and see all our vehicles gone, and we are getting quite frustrated about it. Thank you.

**Comment by cxerq** [comment]
> Every time AMR is on-duty our vehicles are being hotwired and stolen, can we please get a gate at the bottom of our parking lot? Or put some fences and a gate down there? This is unrealistic to go down to our garage and see all our vehicles gone, and we are getting quite frustrated about it. Thank you.

Honestly yall are right next to insurance and a garage around the corner I don't think yall need gates! Plus if miners gotta deal with their shit getting taken I think yall do too!

**Comment by PreacherDeimos** [comment]
> > Every time AMR is on-duty our vehicles are being hotwired and stolen, can we please get a gate at the bottom of our parking lot? Or put some fences and a gate down there? This is unrealistic to go down to our garage and see all our vehicles gone, and we are getting quite frustrated about it. Thank you.
> 
> Honestly yall are right next to insurance and a garage around the corner I don't think yall need gates! Plus if miners gotta deal with their shit getting taken I think yall do too!

There's a lot of difference in a government entity to civilians at a job. I do agree that it shouldn't be happening at the mines, but we should not have to go to insurance to get our cars everyday while we're on duty. This is ridiculous.

**Comment by RockemRobotics** [comment]
I believe you will continue to be told the same thing we were told in DOJ - that sucks but it happens to everyone so get over it.

**Comment by fkk-cz** [comment]
Refer to the last comment.
