### ISSUE TITLE
Import export gas station problem 

### ISSUE THREAD

**Issue by breakpointe** [fkk-cz/noire-public#907]
Import export gas station problem spon  out of the truck and truck ask to be Hotwire and the job does not shown up on the map ending up losing money and all the gas  please fix it

**Comment by fkk-cz** [comment]
Trying this, _again_. If this fix doesn't solve it, I'm marking this as wontfix.

https://github.com/fkk-cz/noire/commit/e46d428fb5bac289e68a31adfe297c33260e83fc

**Comment by breakpointe** [comment]
I hope it's going to be Fix I believe in you

**Comment by fkk-cz** [comment]
Anyone still having issues with not warping into their gas station mission vehicle?

**Comment by breakpointe** [comment]
Yesterday I did

**Comment by MinoritySanta** [comment]
Spoke with you yesterday about this at 960.  As discussed, no problems at this station.  Everything running smooth

**Comment by breakpointe** [comment]
941 is broken I can't do sheat I lose money like hel
