### ISSUE TITLE
Drive-by Adjustments

### ISSUE THREAD

**Issue by ItsGabble** [fkk-cz/noire-public#910]
The new drive-by feature is sick but Sinclair and I were playing around with it a bit and noticed some things that might need to be adjusted. Right-side-drive vehicles show the gun in the wrong hand and make it look like you are shooting your steering wheel. Posting the picture below. Also, you can shoot during a test drive at PDM. Probably shouldn't be able to get your shit rocked on the test drive strip, especially since PDM itself is a safezone. Posting link to clip below. 
![image](https://user-images.githubusercontent.com/102539785/172439656-c7ccdad4-720f-4b43-ae97-8613252c5bec.png)
https://medal.tv/games/gta-v/clips/nEacszOq5zJvC/d1337SEK2oqB?invite=cr-MSw3V3EsNDY3NjAwNzks

**Comment by tythetanman** [comment]
Hahaha I hope that gets fixed but that was funny as shit to watch 😂

**Comment by ItsGabble** [comment]
> Hahaha I hope that gets fixed but that was funny as shit to watch 😂

LMAO it def is

**Comment by somedudenamedrush** [comment]
added note 
add the Mac-10 and Double Barrel to the weapon cycle for drivebys otherwise this shit been dope

**Comment by fkk-cz** [comment]
> Also, you can shoot during a test drive at PDM. Probably shouldn't be able to get your shit rocked on the test drive strip, especially since PDM itself is a safezone.

Yeah, didn't take that one into consideration. Fixed in https://github.com/fkk-cz/noire/commit/96f0ae6c47f9f919cc44f9ae92203880bac836f4.

Unfortunately I don't think the RHD animation can be fixed.

>  add the Mac-10 and Double Barrel to the weapon cycle for drivebys otherwise this shit been dope

No idea how this would be done, would be a nice addition.
