### ISSUE TITLE
Kicking on motorcycles 

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#911]
Just want to bring up that when drive by’s were implemented the kick feature on motorcycles stopped functioning, just wanted to bring this up as I don’t believe it was intended and being able to kick on a motorcycle was a nice feature to have.

**Comment by fkk-cz** [comment]
This was unintentionally disabled but was mostly abused for powergaming purposes. Melee/shooting on bikes will not be making a return, especially with the return of drive-by shootings.
