### ISSUE TITLE
Auto Missions

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire-public#914]
one thing i noticed when doing them i stole a bike didnt crash once but i guess due to the current veh condition which i got it in i got penalized and only got 400 dirty LOL wondering if theres a fix or something for this cause u cant repair the mission car also

**Comment by xFooliee** [comment]
Also the missions are still very glitchy, like 1 out of 5 mission attempts I do usually go through, you'll get to the spot and nothing happens.

**Comment by Hesh77** [comment]
you'll get to the spot and nothing happens. here is an example

https://user-images.githubusercontent.com/77316420/173258517-aa65887f-1071-42ce-8575-40c6c7899215.mp4

.

**Comment by fkk-cz** [comment]
The frequency of this seems to be reduced, however I am still seeing some failed mission data checks. Adding this to the list.
