### ISSUE TITLE
Disable vehicle generators for all gas stations

### ISSUE THREAD

**Issue by Daniel9935** [fkk-cz/noire-public#923]
There is a local car spawn point at 3030 gas that blocks the pumps, i think we have already chatted about the issue. but just wanted to put in here to give a reminder to remove the spawn location if you can

**Comment by fkk-cz** [comment]
This was fixed a while back in https://github.com/fkk-cz/noire/commit/d72ad3d5dbb5710dc78c0fbe83539abc42dc4070.
