### ISSUE TITLE
Gas Station Issue

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#925]
I tried to start a gas run and it only spawned the Trailer not the truck! it took the money for the run also! https://medal.tv/games/gta-v/clips/ovjlmqGuEvlBn/d1337QPQq62i?invite=cr-MSxiUUEsMTg3OTQ2MDQs

**Comment by fkk-cz** [comment]
Duplicate of https://github.com/fkk-cz/noire-public/issues/907.
