### ISSUE TITLE
AMR Keys

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire-public#928]
I feel like I speak for all of AMR when I say not having keys to locked buildings is frustrated, as a first responder I need to get in and out of there, this having been said, I would like that AMR could please get keys to locked buildings. Like the Courthouse and such. Thank you for your time.

**Comment by RichieRockefeller** [comment]
I definitely agree with this as it would help make things easier and more efficient for AMR.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/acee364a4e059aee2dfeaf40fba7f8f71c48db26.
