### ISSUE TITLE
AMR Lockers

### ISSUE THREAD

**Issue by RichieRockefeller** [fkk-cz/noire-public#940]
Would it be possible for AMR to have their own lockers/storage spaces where we can store things before we clock in and then take them out after we clock out? This could also be a thing for other whitelisted jobs to help minimize inconvenience, make it realistic, and help save time.

**Comment by fkk-cz** [comment]
This would probably be misused and could potentially create police corruption issues where people would drop confiscated items, transfer them into the storage, and retrieve them once off-duty. Not worth the trouble, most people working whitelisted jobs know not to bring personal items to work by now.

**Comment by RockemRobotics** [comment]
> This would probably be misused and could potentially create police corruption issues where people would drop confiscated items, transfer them into the storage, and retrieve them once off-duty. Not worth the trouble, most people working whitelisted jobs know not to bring personal items to work by now.

LEOs can already be corrupt doing that with car trunk storage easily enough. I understand if there are other issues preventing it but stopping corruption doesn't track given the systems already available.

**Comment by RichieRockefeller** [comment]
> This would probably be misused and could potentially create police corruption issues where people would drop confiscated items, transfer them into the storage, and retrieve them once off-duty. Not worth the trouble, most people working whitelisted jobs know not to bring personal items to work by now.

Also, a solution would be not being able to access the lockers if on duty. If they just drop it then someone would probably see it. LEOs can technically hand it off to a civilian friend also so maybe the corruption part is already there.
