### ISSUE TITLE
Bug getting in/out of vehicles

### ISSUE THREAD

**Issue by YeagerGTA** [fkk-cz/noire-public#944]
Spotted this last night, don't really know what caused it but will walk you through the observation and effects.

We were rolling the Swat Suburban last night with 3 or 4 of us in it. Two of us went to get into the car, one went into the passenger seat just fine, then when I went to get into the back, I actually yoinked the passenger out of the vehicle, similar animation to pulling a dead body out of a car. From that point on, anyone who did that could not get into the backseat of any vehicle. Drivers side access was fine, as was passenger, but no longer could get into the backseats or extra seats. We tested it on a number of 4-door cars including a cruiser and a 4-door mercedes and could not get into the back seats. 

It was entertaining pulling people out of the car like that, but if the glitch happens too often, we won't be able to fully utilize the other seats in the cars other than the front two.

**Comment by fkk-cz** [comment]
This might be related to the issue where vehicle passengers will sometimes automatically shuffle to the driver seat, even with the flag disabled.

**Comment by YeagerGTA** [comment]
I have seen that too  numerous times.
