### ISSUE TITLE
Invisible Bug

### ISSUE THREAD

**Issue by mystic04** [fkk-cz/noire-public#945]
So a couple of my friends have opened a ticket about this , they haven’t been answered at all . There has been a problem in the city for multiple people . When they kill someone in their eyes they are dead and invisible but for others they are still alive and able to still shoot and kill people that can’t see them . Some suggested desync but this is happening to multiple people and their experience in the city has been smooth they usually don’t have desync pretty often if not any .

**Comment by Diecy** [comment]
I have witnessed this with a officer being killed yet the invisible officer thought he was still alive and attacked people. This ended up coming into the court system as the man was fighting his charges based on invisible cop! We were dumbfounded....

**Comment by FatherRevolution** [comment]
I have the bug and clips of this issue I have had this issue for awhile and done everything that I can to try and fix it

**Comment by KaozGG** [comment]
This bug is also happening to me, switched to Unstable(Canary mode) to try and fix it but nothing has worked. I've made this issue aware to multiple people and nothing was found to fix this. Multiple people have it and we all don't know what to do.

**Comment by Fredydc5** [comment]
I have also had this bug. i made a ticket and they said they could not do nothing about it. its just really annoying dying to this problem.

**Comment by mystic04** [comment]
anything on this yet ? it’s still happening to a handful of people in the city

**Comment by mystic04** [comment]
FIX THIS PLEASE
