### ISSUE TITLE
No Button To Start Rockstar Editor Recording

### ISSUE THREAD

**Issue by ix1ali** [fkk-cz/noire-public#948]
There is no option or a menu to start recording in rockstar editor, We need one to be able to record videos and edits
Please consider adding one

**Comment by fkk-cz** [comment]
Does R* Editor even work with OneSync?

**Comment by ix1ali** [comment]
After research,with rockstar editor, Clip recording, editing, playback and exporting works fine even with OneSync enabled.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ix1ali** [comment]
> Does R* Editor even work with OneSync?

Yes, On rockstar editor, Clip recording, editing, playback and exporting works fine even with onesync enabled

**Comment by ix1ali** [comment]
These video/script might be the best:

https://youtu.be/hXiLfP-lezs

https://forum.cfx.re/t/release-free-rockstar-editor-w-logs-ui/4767335

**Comment by fkk-cz** [comment]
Added a command `/rockstar` to enable recording functionality. https://github.com/fkk-cz/noire/commit/8a41cd935e8b472cf8b34af1d4eb7a8e2754c193

**Comment by ix1ali** [comment]
does not seem to work/open
