### ISSUE TITLE
Gas cans currently bugged

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#952]
Wag1 my drillas noticed that since the repo update regarding jerry cans I haven’t been able to purchase a jerry can from a station. Tried with and without an empty gas can in my inventory. I’ve included 2 clips as well showing the issue. 

https://medal.tv/games/gta-v/clips/pt1TYX7KAZSwl 

https://medal.tv/games/gta-v/clips/pt6mKzZGLfRHW

**Comment by MinoritySanta** [comment]
You can purchase one but if not if station is set to zero$   we had same issue at 960 until we changed price

**Comment by fkk-cz** [comment]
Refer to the answer above -- gas cannot be purchased for $0.
