### ISSUE TITLE
ID Improvements and Changes

### ISSUE THREAD

**Issue by YeagerGTA** [fkk-cz/noire-public#953]
With the new ID's being objects I think the following should be added to various functions within the city itself to make it more realistic and comparable to RL.

Gun Purchases - a valid Drivers License is required to obtain a CCW license at the gun store and any firearm purchase. 
Car Purchases - a valid Drivers License is needed to purchase a vehicle.
Hunting Licenses - a valid Drivers License is needed to purchase.
Boat/JetSki Rentals - a valid Marine License is needed to purchase or rent.
Impound - a valid Drivers License is needed to un-impound a vehicle.

In city Job changes:

Any white listed vehicle operation needs a Valid Drivers License to pull a car/truck or vehicle out.
Sanitation and Trucking need a valid Commerical License
Landscaping needs a valid Drivers License

Something new... in addition to the Drivers License being a carriable object, we should add the CCW license to this as well. Though there are some states that are constitutional carry, most states that issue CCW require you have that permit on you if you are in possession of your firearm. It could the same object with a CCW indicator on the Drivers License or a separate object entirely. 

So law wise:

Felon in Possession - No change (F)
Illegal Possession of a firearm - No valid CCW on record. (F)
*New Charge - Unlicensed Carry  while armed- no valid CCW on person. (M) 

If you want to run wild with this, you can even incorporate it into the new business/nightclubs and casino and have age limits on the purchases of booze, gambling etc (in city age that is). 

That could open up additional RP at these events and businesses. Even could lead to something like bootlegging within the city if you want to have the businesses get booze licenses and purchase the inventory from distributors within the city like the meat market is today with burger shot. People can hijack/steal booze and sell it backdoor as untaxed booze. Perhaps a new crime activity, stills in the county producing booze/beer.

**Comment by fkk-cz** [comment]
A valid, non-expired and non-suspended license (both in the DMV database **and** having the physical item in inventory) is now required to purchase a firearm, rent a jetski, test drive a vehicle, and unimpound a vehicle. After an adjustment period, the physical item requirement will apply for all non-whitelisted jobs that spawn work vehicles as part of the job.

> Something new... in addition to the Drivers License being a carriable object, we should add the CCW license to this as well. Though there are some states that are constitutional carry, most states that issue CCW require you have that permit on you if you are in possession of your firearm. It could the same object with a CCW indicator on the Drivers License or a separate object entirely.

This will be added once more people are carrying their Driver's License on them at all times. The other thing that needs to be done is to bring back license suspensions & force players to apply for renewals after expiration at the DMV, or via their phone.

>  *New Charge - Unlicensed Carry while armed- no valid CCW on person. (M)

Adding this to the list for the next MDT update.
