### ISSUE TITLE
Gas stations aren't actually selling gas! 

### ISSUE THREAD

**Issue by cxerq** [fkk-cz/noire-public#955]
So I've test on 2 gas stations and when people fill up at them the gas stations fuel storge doesn't go down or get the money from the sale! Its like the gas comes from nowhere and money goes nowhere! I've tested at 385 and 120, Each of those gas stations haven't had a single paying customer since todays restart! 

I don't have a clip to prove it cause my medal is fucked up for some reason but feel free to test it out!

**Comment by fkk-cz** [comment]
Forgot to add the gas station ID to the server cache, part of the gas station optimization changes. Ouch. Fixed in https://github.com/fkk-cz/noire/commit/ee3f70f3eb847a792f6131a237741c8399af88ba.

**Comment by RomanianSniper** [comment]
@fkk-cz same issue with the gas station at 366
