### ISSUE TITLE
My F6 

### ISSUE THREAD

**Issue by JustinDuh93** [fkk-cz/noire-public#958]
My F6 menu is bugged out won’t let me manage my member but will let me do everything else

**Comment by Stagonium** [comment]
I noticed this on LSPD, I couldn't access the employee management terminal, the icon was there but nothing would happen when I interacted with it.

**Comment by JustinDuh93** [comment]
Yes needs too be fixed

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/ac536b0e690fa7c4f7b64db79ba88e43ca293b27.
