### ISSUE TITLE
Anti-Lag script

### ISSUE THREAD

**Issue by ix1ali** [fkk-cz/noire-public#959]
Add the anti-lag script to the server.
It would be fun to use with tuned cars and for races etc...

https://forum.cfx.re/t/release-standalone-2-step-als-anti-lag-system/1057327

**Comment by xFooliee** [comment]
As a car enthusiast, I would definitely like to see more things we could do with cars other than just buy and drive. A little more customization, interaction as well. Still think traction control wasn’t any harm tbh, yes im bringing it back up
