### ISSUE TITLE
Renting Cars App

### ISSUE THREAD

**Issue by ix1ali** [fkk-cz/noire-public#960]
Add a renting application to the phones, where players can put any car they own up to rent.
With the option to select a price and maximum rent time

After putting it up for rent they no longer have access to it until they de-list it
And when a player chooses a car to rent he should pay before receiving it, And it should spawn at any random place for him to pick it up.

**Comment by Stagonium** [comment]
Why go through adding a whole app where you have no interaction with the other party? Why not just put it up for rent on the marketplace and let someone text you and meet up and exchange keys for money.

**Comment by ix1ali** [comment]
it would make it easier and people would be able to rent our your car even if you arent in the server, Which would benefit to the renter and car owner

**Comment by xFooliee** [comment]
> Why go through adding a whole app where you have no interaction with the other party? Why not just put it up for rent on the marketplace and let someone text you and meet up and exchange keys for money.

Maybe the person isn’t online, or its more of a pain to give the person the keys. Especially the way how glitchy cars are, on trailers and disappearing or getting impounded, it would be more of a pain on the owner having to go back and forth to help the renter out. The renter should get a time period and from that time period till it ends they have the rights to the car like they are the owner. Would make sense imo.

**Comment by fkk-cz** [comment]
I'm not a big fan of this whole "renting out vehicles to other players" meta. Realistically speaking, no one who owns a super car (or any car, for that matter) would ever rent it out to some random individual on the street for $10-20k "until tsunami". That equivalent amount of money ($500-1000) is pocket change to individuals who could afford such a car, and any normal auto insurance policy would not cover unauthorized drivers.

In addition to what's mentioned above, people have been known to scam new players with such schemes. There are no plans to further encourage and facilitate this kind of behavior.
