### ISSUE TITLE
The 4th of July Purge

### ISSUE THREAD

**Issue by Senni4** [fkk-cz/noire-public#962]
This event would be similar to the Halloween Purge in 2021, anyone can KOS, when you die you respawn with the same stuff you had, but please no MRAP as that would be insanely unfair to the civilians. (and make the weapon mags discounted like you did last time aswell)

**Comment by Bountyrogger** [comment]
Fairly certain I heard they do not plan to do another purge until Halloween due to the impact it causes on the city for the day

**Comment by tythetanman** [comment]
The movie the purge is on Independence Day… 😂

**Comment by tythetanman** [comment]
😂 4th of July Purge…. We all gonna die

**Comment by No-Yes1** [comment]
Maybe if people behaved and acted like it was not KOS every day already, then sure.

**Comment by noyeahsure** [comment]
sir those are the gang rules 😭
