### ISSUE TITLE
Mount Zonah and Pillbox Barriers with locks

### ISSUE THREAD

**Issue by WaywardCanuck** [fkk-cz/noire-public#963]
I would love to see lockable Barriers for Pillbox and Mount Zonah that only AMR and LEO's have access too. 

This is to curb the fuck sticks in the city from clogging up the emergency lanes at the hospitals, blocking AMR from safely transporting the injured to the doctor. The civilians in the city have zero respect for the job and duties of our paramedics.

https://medal.tv/games/gta-v/clips/p8QPO6B9nRvfZ/d1337qHermVJ?invite=cr-MSxPRkgsNzEwMTg0MDMs

The above clip is a daily occurrence. And if AMR does what we're supposed too, cardel/comserv, these idiots come back to harass more and kill EMT’S while out on calls. If these idiots can't behave then I believe that we should put the baby leash on.

**Comment by RichieRockefeller** [comment]
Agreed.

**Comment by elenasalvatore1864** [comment]
agree

**Comment by RockemRobotics** [comment]
Seems like something DOT could help with pretty easily.

**Comment by Bountyrogger** [comment]
> Seems like something DOT could help with pretty easily.

DOT are usually not on when this stuff happens and even if we were to call them the vehicle would be gone before they even showed up

**Comment by WaywardCanuck** [comment]
> Seems like something DOT could help with pretty easily.

You'd think so but it doesn't stop the behaviour,  DOT will still be needed since these same dumbass's will likely clog up the street. At least until all their cars are impounded. 

This is beside the fact that DOT isn't always active when we are.

**Comment by fkk-cz** [comment]
> The above clip is a daily occurrence. And if AMR does what we're supposed too, cardel/comserv, these idiots come back to harass more and kill EMT’S while out on calls. If these idiots can't behave then I believe that we should put the baby leash on.

Any type of added gates would be an extreme eyesore, real hospitals don't have any barriers blocking the emergency lanes. Is deleting vehicles and comserving really _that_ bad?

**Comment by WaywardCanuck** [comment]
> > The above clip is a daily occurrence. And if AMR does what we're supposed too, cardel/comserv, these idiots come back to harass more and kill EMT’S while out on calls. If these idiots can't behave then I believe that we should put the baby leash on.
> 
> Any type of added gates would be an extreme eyesore, real hospitals don't have any barriers blocking the emergency lanes. Is deleting vehicles and comserving really _that_ bad?

I know that it's an eye sore but yes it is that bad. I wouldn't lie to you. My EMT's are being murdered in the streets, gangs come and scream at us constantly,  they keep one person in the car so we can't cardel, and they come back from the beach to keep screaming and blocking emergency lanes. 

Idiots are also using Mt. Zonah as a through street and lead 10-80's through. It's a small miracle that we haven't been killed by at 10-80.

**Comment by WaywardCanuck** [comment]
https://medal.tv/games/gta-v/clips/plgsKovxsXKhi/spok?invite=cr-MSw5YXcsNTE5ODUzMjAs


This is increasingly becoming a problem as well.

**Comment by DarkHourEnt** [comment]
Send their car to insurance

**Comment by WaywardCanuck** [comment]
> Send their car to insurance

We do and get shot for it.

**Comment by TurboFl0w** [comment]
> > The above clip is a daily occurrence. And if AMR does what we're supposed too, cardel/comserv, these idiots come back to harass more and kill EMT’S while out on calls. If these idiots can't behave then I believe that we should put the baby leash on.
> 
> Any type of added gates would be an extreme eyesore, real hospitals don't have any barriers blocking the emergency lanes. Is deleting vehicles and comserving really _that_ bad?

Recently it has been to the point where we need gates. Just over the past few days I have handed out a lot of com servs. I have handed out I think 3 com servs for people that have blatantly VDMed me because they didn’t like how I was doing my job (100 sweeps for each). Also, we have had around 20 to 30 gang members just come and use Zona as a meeting area. We tell them to leave and com serv some when police are not available, but they all refuse to leave until they see a cop car roll up.

**Comment by WyattRamsey33** [comment]
https://medal.tv/games/gta-v/clips/pHfVHVqY2B8rj/d1337960UE3c?invite=cr-MSxvSUcsNzEwMTg0MDMs
Im not sure if a gate like this is even possible to add but it looks so much better and still does the same job.

**Comment by CharlottePett** [comment]
I have also seen the above in other cities and works very well. I have also seen where automatic speeds limits of 20-30mph are put into place in hospital zones to prevent VDM's

**Comment by ix1ali** [comment]
I agree with this one, At least the gates should be at the parking spots not for the hospital itself, A lot of people meet at zonah
it is mostly busy and people harasse emt that are standing there

**Comment by Diecy** [comment]
What about having Walk-ins and drive ups go to different Hospitals? Would this help? It would then leave them no reason to even be at the same place the EMT's work out of and if they are there then you know for a fact they are either up to no good or are dropping someone off/ Picking someone up from work.

**Comment by Bountyrogger** [comment]
> What about having Walk-ins and drive ups go to different Hospitals? Would this help? It would then leave them no reason to even be at the same place the EMT's work out of and if they are there then you know for a fact they are either up to no good or are dropping someone off/ Picking someone up from work.

It would if it worked that easy. AMR uses and transports to every hospital. Whatever the nearest Hospital is used for the patients we pick up. Pillbox is also used for Suspects in Police Custody as their doors lock. 

It won't stop them from still going to whatever hospital anyway. Usually the most problems are gangs using the safe zone at hospitals where I feel the only fix would be removing the safe zones at hospitals but then the EMT's lives will be even more in danger

**Comment by ix1ali** [comment]
something like this would be nice
https://www.gta5-mods.com/maps/mount-zonah-hospital-exterior-modded-rockford-hills-fivem-sp-menyoo-ymap-xml


got ran over today at zonah, so many people, so many cars
lots of gangs fighting
its getting out of hand so barriers would be needed

**Comment by fkk-cz** [comment]
That ymap looks.. rather disgusting and won't stop people from driving/ramming their vehicles through those barriers. The best solution for this issue is to clear out the hospital, regardless of the amount of whining received from the gangs who refuse to leave the area.

**Comment by WaywardCanuck** [comment]
You'd think, but it doesn't stop the behaviour.  DOT will still be needed
because I imagine that these dummies will clog up the streets.
