### ISSUE TITLE
Boat License and non-supporter cars 

### ISSUE THREAD

**Issue by Hesh77** [fkk-cz/noire-public#964]
1. When people are trying to buy a boat license the cost should be there.
2. We need more non-supporter cars, there isn't a single Range Rover, Alfa Romeo, Rolls-Royce, and only 2 motorcycles. I think more should be added to make the game more fun for people who aren't supporters.

**Comment by fkk-cz** [comment]
> When people are trying to buy a boat license the cost should be there.

Agreed. Fixed in https://github.com/fkk-cz/noire/commit/9447970bbbc2ce5e9f56e91a2e1b6f93c24c2e79.

As for the second point, this will be solved when the casino wheel is implemented -- a good way for non-supporters to obtain supporter vehicles.

**Comment by Hesh77** [comment]
This would actually be insane, thanks for the help!
