### ISSUE TITLE
Why was mining nerfed?

### ISSUE THREAD

**Issue by xZedys** [fkk-cz/noire-public#965]
Mining is the only job where you have to invest your own money to make more money. I'm just curious on the reasoning behind nerfing mining? I've been hearing a lot of people don't even want to mine anymore and feel scammed in a way. Thank you in advance!

**Comment by Hesh77** [comment]
It was too good, people we're literally AFK sitting there with an autoclicker, a job would require actual work like landscaping.

**Comment by Chunky30** [comment]
Why are you considering mining nerfed? the only thing that was nerfed was the Toyota FJ 40 Individually, the payouts nor time taken has been change at all, people have been finding different alternative and routes to overcome this little problem, lots of people still mine anyways.

**Comment by fkk-cz** [comment]
> I've been hearing a lot of people don't even want to mine anymore and feel scammed in a way.

The only people who are 'scammed' are the ones who are paying whatever people are charging for those rented vehicles (ugh) that belong to someone else. **One** vehicle's class was changed to reflect the fact it should not have 1000 capacity. If that's how people feel, then tough luck.
