### ISSUE TITLE
Gas station bugged *not receiving sales/money from fill ups* Coordinates*375* 

### ISSUE THREAD

**Issue by RomanianSniper** [fkk-cz/noire-public#969]
Gas station bugged *not receiving sales/money from fill ups* Coordinates*375*, tested it myself and it didn't register the sale when I filled up my car, last registered sale was the 22nd

**Comment by fkk-cz** [comment]
This was fixed in https://github.com/fkk-cz/noire/commit/ee3f70f3eb847a792f6131a237741c8399af88ba.
