### ISSUE TITLE
Buying Guns DL Bug

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire-public#972]
I’ve heard from a good amount of people who are having this issue, but no GitHub has been made on it. Recently, since the update requiring you to have a physical DL on you to test drive cars, when you go and try and buy a gun at the ammunition, it says your drivers license is expired but on the license it says it’s not/in good standing.

**Comment by noyeahsure** [comment]
I think this was just fixed in repo updates. 
![image](https://user-images.githubusercontent.com/93731208/175790384-2621c8af-3476-4569-9acc-da87fc33e175.png)

**Comment by Ell34** [comment]
Oh word, I haven’t checked repo yet today. Hoping that fixes it!
