### ISSUE TITLE
Toyota 4Runner

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#977]
Is there any reason why the 4Runner isn’t in PDM? I had it, i didn’t get a recall notice or anything, and it’s just gone. I can’t get it in PDM either. Also, it still shows up on the lists of cars that can pull small trailers.

**Comment by No-Yes1** [comment]
Vehicle was recalled due to high poly's (over 700K) which is over 3x the amount we allow.

**Comment by CasperBoiRL** [comment]
is there anyway that we can get more SUVS that can pull trailers? The Tahoe already has a hitch, it just cant pull a trailer.

**Comment by No-Yes1** [comment]
Make an issue on the vehicle repo with the Vehiclename. https://github.com/fkk-cz/noire_vehicles
