### ISSUE TITLE
L.A. Noire Entertainment

### ISSUE THREAD

**Issue by ix1ali** [fkk-cz/noire-public#982]
Make an entertainment company/department and hire many employees 

The basic idea of it is that they hold daily or weekly events and contests, Such as:
- Car racing
- Boat racing
- Boxing
- Car meetings
- Bike races
- The purge
- etc..

And there should be money prizes for the winners, For example if a racing event was held the top 3 winners should receive $13,500 or something like that
It would help with reducing the crime RP and get the community together 
And have people something to do other than robbing constantly.

**Comment by okxeon** [comment]
These kind of events with the exception of the purge can be organized by civs. Races can be created and run with the /race command. There is a boxing ring behind 125. Car meetings in the past have been hosted by various racing groups. This does not really need a whitelist.

**Comment by ix1ali** [comment]
People will now show up unless its an organized event and we've seen that before

No one really cares about any event you try and hold, They just want to rob and kill
So if it was something official and announced people will like it and show up

**Comment by Scubaaaaa** [comment]
Plenty of people have held public events and been quite successful in the past. There's really no reason to have a whitelist for any of it. Just go RP in the city and get decently known. From there you can set up events. Either staff or certain ranks within other WL jobs can make an event for you within the discord itself.

**Comment by Stagonium** [comment]
As stated above this doesn't really need a corresponding whitelist to it. If you want it to be a legal business you can go through the DOJ and acquire a business license for it. But most of these events can just be hosted on the fly through advertising on twitter in game and such.

**Comment by CasperBoiRL** [comment]
I wish mr greys never got banned. he was amazing for car meets

**Comment by CasperBoiRL** [comment]
#unbanmrgreys
