### ISSUE TITLE
Up N Atom Ownership. 

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#983]
Originally was interested in another location type restaurant that was Bean machine.

From my understanding, the interior has issues, and it’s not currently something that is opening fairly soon, I believe.

I do have interest in the location of Up N Atom and my reasoning and would be plans:

Providing an additional restaurant support to the city and secondary alternative to Burger Shot restaurant that does not include the pettiness or trash and trashing in each other’s restaurant and competition which would elevate crime whenever the goal at the end of the day for these locations is providing food support and other avenues and potential alternative hours to burger shot without elevating crime to the city.

A hiring process that includes a selection process to minimize potential theft and or wrong doing in the workplace

As far as myself and owning it, that is why you appoint managers under you, so you don’t have to pump 100% of your hours into something. I know that also my track record in the city off of whitelisted jobs.

Court: the most convictions and dismissals by literally more than 10x the next (again, no disrespect, but it is pointing out the ability in my own personal ability to also run a restaurant. With the other jobs, I already have, and with the option of dropping one to two if needed.)

Burger Shot: currently, an assistant manager, and there would be no conflict interest at all and that was already expected that I had interest in another business with the submission of the bean machine back in March.

VU: DJ hours vary based off of events

Other clubs hours vary based off of events

Bahama mama: currently a manager there and head bartender

I’m employed at a large amount of places because I don’t screw over a business, and I have different personalities at each. One job is nowhere near how I act at Burger shot or Court. There is a Cousin system. The city has.

I have a full business proposal for it that includes the selection process of an attorney on retainer for the location.

Projected business license fee that matches all the other businesses that have come (new bars)

**Comment by Client7** [comment]
I'm sorry nothing can be done sir, you can not own everything
