### ISSUE TITLE
Car not appearing in public garage after recovering at insurance. (Bug)

### ISSUE THREAD

**Issue by Yawnsssss** [fkk-cz/noire-public#986]
Hi, last night I purchased a car through the UCL. I left it running (idle), and it de-spawned. 
Next, i went to insurance, recovered the vehicle, and it says it'll be available at any public garage,
and the vehicle was last parked at Rockford Garage.
I went back and forth from insurance to Rockford Public Garage 5x times and no luck. 
I then approached police officers, and they personally took me to each garage and tried to help, still no luck.
They gave me a replacement vehicle for the night, and told me by the time tsunami/reset comes, i should have it back and able to recover from garage.
Its the next day, and i'm still having same issues. 
Its also not at impound lot either. So we can scratch that scenario off.

I've gone to all possible garages in the surrounding area, and have had other players try to help me through screen share, they recommended i post here because it could be a bug. Would appreciate any help, Thanks

**Comment by okxeon** [comment]
What is the plate of the vehicle? Also, did you store it inside the Rockford garage or just left it at the parking lot?

**Comment by Stagonium** [comment]
You may need to just venture to every garage, if you never pulled it out of a public garage it may be based off the one the last owner pulled it from. I would borrow a local car or have a friend drive you around to all of them until you find it, then move it down to the city.

**Comment by Yawnsssss** [comment]
@Stagonium Thanks. I think ill do that now, as i have nothing else to do but wait at this point lol. Will report back

**Comment by CharlottePett** [comment]
If you go to ensure it should tell you what garage it's in?

**Comment by Yawnsssss** [comment]
The car has now appeared at a neighboring garage! Problem solved, appreciate you guys. 
Halfway through  checking every garage just now, i just found it on one of the garages i went to multiple times yesterday. 
Thank you @TheBottomFragger you were a huge help

**Comment by TheBottomFragger** [comment]
> The car has now appeared at a neighboring garage! Problem solved, appreciate you guys.
> Halfway through checking every garage just now, i just found it on one of the garages i went to multiple times yesterday.
> Thank you @TheBottomFragger you were a huge help

Glad you found it!
