### ISSUE TITLE
Armored Truck Bug

### ISSUE THREAD

**Issue by YeagerGTA** [fkk-cz/noire-public#993]
After testing today, we have determined that there is a bug planting the explosives on the truck. The truck drivers are killed the people are unable to attach the explosives to the truck. We had one today that acted like the previous half dozen, a distress and then nothing. We had an officer clock off duty to see if they could plant the explosive and there was not interaction with the truck directly or via the 3rd eye.

**Comment by STKstyx** [comment]
Been this way for a couple weeks now

**Comment by YeagerGTA** [comment]
> Been this way for a couple weeks now

Yeah we had some other issues we thought it was, officer clocking off bring the threshold down while the truck was being hit that kind of thing but it is definitely bugged right now.

**Comment by fkk-cz** [comment]
Checked logs earlier today - there were at least three armored trucks that successfully spawned and returned to destination. This is probably some race condition issue caused by the client somehow 'receiving' or executing the mission event before the global state is synced. Adding a limited wait interval might help, please provide an update next time an armored truck mission occurs. https://github.com/fkk-cz/noire/commit/d3e49c210cf6b37cb75a5f36c287e4fed8b12216

**Comment by YeagerGTA** [comment]
Just an update... the setting of the explosives and unloading of cargo is working now and verified. However, Sinclair also verified that if a truck gets blown/unloaded there are no further respawns despite numbers being there for it. Also a reminder on the unloading timer, need a slight adjustment downward.

**Comment by Stagonium** [comment]
Just performed one myself, the timer reduction for the explosion is good, but I think grabbing the money takes a little too long as you are pretty much guaranteed to be surrounded by LEO leaving the only option as a shootout, where I think a shootout might be better as a secondary option

**Comment by fkk-cz** [comment]
Switched the armored truck client/server logic to use entity state syncing. Confirmed through logs that multiple trucks are in fact spawning.

**Comment by Stagonium** [comment]
Multiple trucks spawn now, but the alerts are messed up. We get a distress alert when the truck spawns, not when the guards are killed. So we only get an alert for an explosion when that happens, not for when people are starting to hit the truck. Also the truck respawns almost immediately after being hit as long as cooldown allows it, which can be seen [here](https://cdn.discordapp.com/attachments/958635731507630111/1007012865607217344/IMG_5289.png?size=4096) should probably still have some baseline time restriction between a truck being hit and being spawned again.

**Comment by STKstyx** [comment]
That's more then plenty of time lol the chance of someone actually getting away is so rare you're gonna catch em almost no matter what. Enjoy the rp and have fun with it no need too make a longer spawn time > again.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/3911167aa55efd2a19dca18869560ed46040a8aa fixes the early alerting.

Not sure what you're referring to about the cooldown between truck spawns, the screenshot you provided shows a ~13 minute gap between missions. Are you suggesting for an increase?

**Comment by Stagonium** [comment]
A player cannot rob the same store within 90 minutes as the "register is empty". I feel like it should be something similar for armored truck considering how much money you can make from it. Plus, if an armored truck just got robbed, realistically they would stop dispatching armored trucks until a safer time?

**Comment by fkk-cz** [comment]
Reverted the last change that attempted to increase the reset interval. https://github.com/fkk-cz/noire/commit/7c4785915e3ea0eb3560e976325f465574e251a7

Going to leave this for now, will adjust if people start abusing and repeatedly hitting it.
