### ISSUE TITLE
Purchasable upgrades for jobs

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#994]
I think it would be cool to have purchasable upgrades, like for mining we could get a jackhammer, we could get the tesla semi for trucking missions, we could get like a super fishing rod or something for fishing. but they all should be purchasable outside of the job itself.

**Comment by xFooliee** [comment]
If this were to happen, I would like for a perk to come with the upgrade, not just for looks

**Comment by CasperBoiRL** [comment]
well yes, thats what i meant. like 1.5x mining speed with the jack hammar, the tesla semi is already way faster than the normal semi, and with the super rod (of some sort) you could catch bigger and more valuable fish that you otherwish couldnt.

**Comment by dukerzzz** [comment]
I have heard that mining and landscaping are possibly being removed from the city sometime in the future. Mining is a brain-dead job. Auto clickers are always present. People always find a way to ruin it for everyone, but I think the city could go for some new jobs. Getting rid of mining would be awesome. As for the upgraded perks go. Not a bad idea. It could be like a progression over time. Will the perk stay with you forever? Or is it whenever you fly back into the city and start that job everything resets?

**Comment by CasperBoiRL** [comment]
It would def me a progression system, but it would have to take a while to unlock. It would stay with you. And i don’t think mining should be removed, as you still have to drive from the mine to the sell.

**Comment by CasperBoiRL** [comment]
Tbh, i feel like all jobs should be as balanced as possible. Most of the time, it’s spread between trucking, landscaping,. and mining. There is always 0-10 people on every other job.
