### ISSUE TITLE
Denied Housing Request

### ISSUE THREAD

**Issue by Jaadoohz** [fkk-cz/noire-public#995]
Hey so A while back I was denied a housing request because I was told the location was a "furniture store and is not a realistic place to live". This seems kinda odd since there's a player owned house that literally says "Furniture store" in the front. The original housing location I had requested was the LS Tuning garage at postal 556. Please see the screenshots below for reference.

**Player owned house at a furniture store:**
![image](https://user-images.githubusercontent.com/107905078/177019614-779cc1fb-0e62-44a8-b8cc-497ca5bf55c6.png)

**The house location I originally requested and was denied:**
![image](https://user-images.githubusercontent.com/107905078/177019655-20a02d91-8c52-46c1-9807-478fa367badc.png)

**The Discord message saying my request was denied:**
![image](https://user-images.githubusercontent.com/107905078/177019665-ef915b5c-c768-4902-87a6-6b00f3fd6378.png)

**Comment by fkk-cz** [comment]
GitHub issues are for reporting bugs or making detailed feature suggestions **only**. If your housing request was denied, submit a new one.
