### ISSUE TITLE
Stock Market

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#996]
I think that there should be some form of stock market added. Whether its on your phone, or it is its own building you have to go too, I feel that it would make things fun and risky.

**Comment by tythetanman** [comment]
….i need..

**Comment by LegendaryBruno22** [comment]
Definitely think it would be a good idea and considering the inflation and all the rest of this city’s money worth I think a stock market would be a great feature and something for the future where you can take risks or become skilled and make a lot of money, I’ve always had this in mind but hey ho.

**Comment by CasperBoiRL** [comment]
https://github.com/JaredScar/BadgerStockMarket

**Comment by RangerThrawn** [comment]
This would be awesome - especially if some of the whitelist businesses had stock that changed with their weekly sales

**Comment by tythetanman** [comment]
They should probably be in discussion, but the smartest thing to do with a stock market would be the big city stock market and not in city restaurants because my ass would get in trouble for insider trading so many fucking times….
