### ISSUE TITLE
Discord Channels

### ISSUE THREAD

**Issue by ix1ali** [fkk-cz/noire-public#999]
Bring back the old events chat so that people can announce about certain events or schedule them
Such as cars meets, races, protests, etc...

It would be easier and help reach many players

Also add a clips chat where people could post clips in the server whether its funny or something else

And most importantly bring back the nsfw chat, It will be useful because no one can share any media (pics/vids) elsewhere

**Comment by fkk-cz** [comment]
Events need to originate from in-game, not Discord. NSFW chat was removed due to people abusing it, _yet again_.
